// ---------------------------------------------------------------------------
//  LOS OCHO DEL CATORCEAVO ENVIO — martes 13 de octubre de 2026.
//  Comprobado en cada web municipal el 7 de septiembre de 2026.
//
//  LO QUE SE APRENDIO PREPARANDO ESTA TANDA, y ahorra tiempo la proxima vez:
//
//  buscar-correo.mjs devolvio "nada" para Rubi, Viladecans, Vic y Mollet, y
//  los cuatro publican su correo de atencion ciudadana perfectamente. El
//  script se descarga la portada y sigue enlaces; estos ayuntamientos montan
//  la web con javascript y ahi no hay nada que leer. Buscarlo a mano en un
//  buscador -"@rubi.cat" oficina atencio ciutadana- los saca a la primera.
//
//  Y al reves: se intentaron los cuatro grandes que quedaban -Gijon, A
//  Coruna, Mostoles, San Sebastian de los Reyes- y ninguno publica un correo
//  de atencion ciudadana. Lo canalizan TODO por el 010 y por formulario web.
//  No es que no se encuentre: es que no existe. Para esos hay que cambiar de
//  via, no insistir con el correo.
//
//  Fuera tambien L'HOSPITALET, el segundo mas grande que quedaba: su seu
//  electronica ya monta un "Assistent Virtual" con un "Tens dubtes?
//  Pregunta'm!". No es un lead de "no teniu assistent".
//
//  Catalan en Rubi, Viladecans, Vic y Mollet; valenciano en Ibi. La Laguna,
//  Puerto Real y Alhaurin el Grande, solo castellano.
// ---------------------------------------------------------------------------

export const MUNICIPIOS_DIA14 = [

// ===========================================================================
{
  slug: 'rubi',
  nombre: 'Rubí',
  articulo: 'de Rubí',
  dominios: 'rubi.cat y seu.rubi.cat',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: "l'OAC", tel: '93 588 70 00', email: 'oac@ajrubi.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'narcis menard',
          'atencio ciutadana', 'adreca', 'horari', 'a quina hora obren', 'telefon'],
      es: { h: "L'<b>Oficina d'Atenció a la Ciutadania (OAC)</b> está en el carrer Narcís Menard, 13-17.",
            l: ['Teléfono: 93 588 70 00. Correo: oac@ajrubi.cat.',
                'Horario: de lunes a jueves de 8:30 a 14:00 y de 16:00 a 18:30.',
                '<b>Las tardes son solo con cita previa.</b>',
                'Viernes y vísperas de festivo: de 8:30 a 14:00.'],
            f: 'La OAC informa de todo lo relativo a la administración local y tramita la mayoría de gestiones municipales de forma integrada.' },
      ca: { h: "L'<b>Oficina d'Atenció a la Ciutadania (OAC)</b> és al carrer Narcís Menard, 13-17.",
            l: ['Telèfon: 93 588 70 00. Correu: oac@ajrubi.cat.',
                'Horari: de dilluns a dijous de 8:30 a 14:00 i de 16:00 a 18:30.',
                '<b>Les tardes són només amb cita prèvia.</b>',
                'Divendres i vigílies de festiu: de 8:30 a 14:00.'],
            f: "L'OAC informa de tot el que fa referència a l'administració local i tramita la majoria de gestions municipals de manera integrada." },
      s: { t: "Oficina d'Atenció a la Ciutadania — rubi.cat", u: 'https://www.rubi.cat/ca/ajuntament/atencio-a-la-ciutadania/oficines-atencio-a-la-ciutadania' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'certificado', 'volante',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me', 'certificat', 'volant'],
      es: { h: 'Los trámites de <b>padró</b> se hacen en la OAC, carrer Narcís Menard, 13-17.',
            l: ['Por la mañana se puede ir de 8:30 a 14:00; por la tarde, solo con cita previa.'],
            f: 'La documentación depende de su caso. Confírmela en el 93 588 70 00 o en oac@ajrubi.cat antes de desplazarse.' },
      ca: { h: "Els tràmits de <b>padró</b> es fan a l'OAC, carrer Narcís Menard, 13-17.",
            l: ['Al matí s\'hi pot anar de 8:30 a 14:00; a la tarda, només amb cita prèvia.'],
            f: 'La documentació depèn del seu cas. Confirmeu-la al 93 588 70 00 o a oac@ajrubi.cat abans de desplaçar-vos.' },
      s: { t: "Atenció a la ciutadania — rubi.cat", u: 'https://www.rubi.cat/es/ayuntamiento/atencion-a-la-ciudadania' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'tarde', 'tardes', 'hace falta cita', 'necesito cita', 'turno',
          'cita previa', 'demanar cita', 'tarda', 'tardes', 'cal cita'],
      es: { h: 'Por la mañana se atiende <b>sin cita</b>; por la <b>tarde, solo con cita previa</b>.',
            l: ['Es la diferencia que más despistes causa: ir a las cinco sin cita no sirve.'],
            f: 'La cita se pide en el 93 588 70 00 o en rubi.cat.' },
      ca: { h: "Al matí s'atén <b>sense cita</b>; a la <b>tarda, només amb cita prèvia</b>.",
            l: ['És la diferència que més despistes causa: anar-hi a les cinc sense cita no serveix.'],
            f: 'La cita es demana al 93 588 70 00 o a rubi.cat.' },
      s: { t: "Oficina d'Atenció a la Ciutadania — rubi.cat", u: 'https://www.rubi.cat/ca/ajuntament/atencio-a-la-ciutadania/oficines-atencio-a-la-ciutadania' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'registro',
          'seu electronica', 'tramit', 'tramits', 'per internet', 'cataleg'],
      es: { h: 'La <b>seu electrònica</b> está en seu.rubi.cat, con el catálogo de trámites.',
            l: ['El Ayuntamiento publica además una carta de servicios de la OAC.'],
            f: 'Dudas: 93 588 70 00 o oac@ajrubi.cat.' },
      ca: { h: 'La <b>seu electrònica</b> és a seu.rubi.cat, amb el catàleg de tràmits.',
            l: ["L'Ajuntament publica a més una carta de serveis de l'OAC."],
            f: 'Dubtes: 93 588 70 00 o oac@ajrubi.cat.' },
      s: { t: 'Seu Electrònica — Ajuntament de Rubí', u: 'https://seu.rubi.cat/catalogoTramites/show/404?lang=ca_ES' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Rubí?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'CA', t: 'Cal cita prèvia a la tarda?' },
    { lang: 'ES', t: '¿Dónde está la OAC y qué horario tiene?' },
  ],
},

// ===========================================================================
{
  slug: 'viladecans',
  nombre: 'Viladecans',
  articulo: 'de Viladecans',
  dominios: 'viladecans.cat y cita.viladecans.cat',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: "l'OAC", tel: '93 635 18 00', email: 'viladecansinfo@viladecans.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'viladecans informacio', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'placa europa',
          'atencio ciutadana', 'adreca', 'horari', 'a quina hora obren', 'telefon'],
      es: { h: "L'<b>Oficina d'Atenció Ciutadana (OAC)</b> está en la plaça Europa, 7.",
            l: ['Teléfono: 93 635 18 00. Correo: viladecansinfo@viladecans.cat.',
                'Horario: de lunes a jueves de 9:00 a 14:15; viernes de 9:00 a 14:00.',
                'Martes y jueves también de 16:15 a 18:00.'],
            f: 'Hay que pedir cita previa en cita.viladecans.cat.' },
      ca: { h: "L'<b>Oficina d'Atenció Ciutadana (OAC)</b> és a la plaça Europa, 7.",
            l: ['Telèfon: 93 635 18 00. Correu: viladecansinfo@viladecans.cat.',
                'Horari: de dilluns a dijous de 9:00 a 14:15; divendres de 9:00 a 14:00.',
                'Dimarts i dijous també de 16:15 a 18:00.'],
            f: 'Cal demanar cita prèvia a cita.viladecans.cat.' },
      s: { t: 'Atenció ciutadana — viladecans.cat', u: 'https://www.viladecans.cat/ca/atenciociutadana' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'certificado', 'volante',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me', 'certificat', 'volant'],
      es: { h: 'Los trámites de <b>padró</b> se hacen en la OAC, plaça Europa, 7, con cita previa.',
            l: ['La cita se pide en cita.viladecans.cat.'],
            f: 'La documentación depende de su caso. Confírmela en el 93 635 18 00 o en viladecansinfo@viladecans.cat antes de desplazarse.' },
      ca: { h: "Els tràmits de <b>padró</b> es fan a l'OAC, plaça Europa, 7, amb cita prèvia.",
            l: ['La cita es demana a cita.viladecans.cat.'],
            f: 'La documentació depèn del seu cas. Confirmeu-la al 93 635 18 00 o a viladecansinfo@viladecans.cat abans de desplaçar-vos.' },
      s: { t: 'Atenció ciutadana — viladecans.cat', u: 'https://www.viladecans.cat/ca/atenciociutadana' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'turno',
          'cita previa', 'demanar cita'],
      es: { h: 'La <b>cita previa</b> se pide en cita.viladecans.cat.',
            l: [],
            f: 'Si el sistema no le da hueco, llame al 93 635 18 00.' },
      ca: { h: 'La <b>cita prèvia</b> es demana a cita.viladecans.cat.',
            l: [],
            f: 'Si el sistema no us dona hora, telefoneu al 93 635 18 00.' },
      s: { t: 'Atenció ciutadana — viladecans.cat', u: 'https://www.viladecans.cat/ca/atenciociutadana' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'omic', 'consumo', 'reclamacion', 'registro',
          'seu electronica', 'tramit', 'tramits', 'per internet', 'consum', 'reclamacio'],
      es: { h: 'Los trámites en línea y el contacto están en viladecans.cat.',
            l: ['El Ayuntamiento tiene además una <b>Oficina Municipal d\'Informació al Consumidor (OMIC)</b>, que es donde van las reclamaciones de consumo, no a la OAC.'],
            f: 'Dudas: 93 635 18 00 o viladecansinfo@viladecans.cat.' },
      ca: { h: 'Els tràmits en línia i el contacte són a viladecans.cat.',
            l: ["L'Ajuntament té a més una <b>Oficina Municipal d'Informació al Consumidor (OMIC)</b>, que és on van les reclamacions de consum, no a l'OAC."],
            f: 'Dubtes: 93 635 18 00 o viladecansinfo@viladecans.cat.' },
      s: { t: "Oficina Municipal d'Informació al Consumidor — viladecans.cat", u: 'https://www.viladecans.cat/ca/omic' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Viladecans?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'CA', t: "On és l'OAC i quin horari té?" },
    { lang: 'ES', t: '¿Cómo pido cita previa?' },
  ],
},

// ===========================================================================
{
  slug: 'vic',
  nombre: 'Vic',
  articulo: 'de Vic',
  dominios: 'vic.cat y demaneuhora.vic.cat',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: "l'OAC", tel: '938 862 100', email: 'atenciociutadana@vic.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'ciutat', 'generalitat',
          'atencio ciutadana', 'adreca', 'horari', 'a quina hora obren', 'telefon'],
      es: { h: "L'<b>Oficina d'Atenció a la Ciutadania (OAC)</b> está en el carrer Ciutat, 1, y en el passeig de la Generalitat, 1.",
            l: ['Teléfono: 938 862 100. Correo: atenciociutadana@vic.cat.',
                'Mañanas: de 9:00 a 14:00. Tardes: de lunes a jueves de 16:00 a 18:00.'],
            f: 'La cita se pide en demaneuhora.vic.cat.' },
      ca: { h: "L'<b>Oficina d'Atenció a la Ciutadania (OAC)</b> és al carrer Ciutat, 1, i al passeig de la Generalitat, 1.",
            l: ['Telèfon: 938 862 100. Correu: atenciociutadana@vic.cat.',
                'Matins: de 9:00 a 14:00. Tardes: de dilluns a dijous de 16:00 a 18:00.'],
            f: 'La cita es demana a demaneuhora.vic.cat.' },
      s: { t: "Oficina d'Atenció a la Ciutadania — vic.cat", u: 'https://www.vic.cat/serveis/atencio-ciutadana/oac' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'certificado', 'volante',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me', 'certificat', 'volant'],
      es: { h: 'Los trámites de <b>padró</b> se hacen en la OAC, carrer Ciutat, 1.',
            l: ['Mañanas de 9:00 a 14:00 y tardes de lunes a jueves de 16:00 a 18:00.',
                'Conviene pedir hora en demaneuhora.vic.cat.'],
            f: 'La documentación depende de su caso. Confírmela en el 938 862 100 o en atenciociutadana@vic.cat antes de desplazarse.' },
      ca: { h: "Els tràmits de <b>padró</b> es fan a l'OAC, carrer Ciutat, 1.",
            l: ['Matins de 9:00 a 14:00 i tardes de dilluns a dijous de 16:00 a 18:00.',
                'Convé demanar hora a demaneuhora.vic.cat.'],
            f: 'La documentació depèn del seu cas. Confirmeu-la al 938 862 100 o a atenciociutadana@vic.cat abans de desplaçar-vos.' },
      s: { t: 'Atenció ciutadana — vic.cat', u: 'https://www.vic.cat/serveis/atencio-ciutadana' },
    },
    {
      k: ['ayuda', 'ayuda con el tramite', 'no se usar', 'certificado digital', 'oac 360', 'soporte', 'biblioteca', 'suport digital', 'pilarin bayes',
          'ajuda', 'suport', 'no se fer servir', 'certificat digital'],
      es: { h: 'Si se atasca haciendo un trámite por internet, hay <b>dos ayudas distintas</b>.',
            l: ['El <b>OAC 360º</b>, que da soporte a la tramitación electrónica, en el 935 954 804.',
                'Y un <b>servicio de soporte digital</b> presencial en la biblioteca Pilarin Bayés, de lunes a viernes de 11:00 a 13:00.'],
            f: 'Para lo demás, la OAC: 938 862 100.' },
      ca: { h: 'Si us encalleu fent un tràmit per internet, hi ha <b>dues ajudes diferents</b>.',
            l: ["L'<b>OAC 360º</b>, que dona suport a la tramitació electrònica, al 935 954 804.",
                'I un <b>servei de suport digital</b> presencial a la biblioteca Pilarin Bayés, de dilluns a divendres d\'11:00 a 13:00.'],
            f: "Per a la resta, l'OAC: 938 862 100." },
      s: { t: "Oficina d'Atenció a la Ciutadania — vic.cat", u: 'https://www.vic.cat/serveis/atencio-ciutadana/oac' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'demanar hora', 'turno', 'sede electronica', 'tramite', 'tramites', 'internet', 'por internet',
          'cita previa', 'demanar cita', 'demanar hora', 'seu electronica', 'tramits', 'per internet'],
      es: { h: 'La <b>hora</b> se pide en demaneuhora.vic.cat.',
            l: ['Los trámites en línea están en vic.cat, en el apartado de atenció ciutadana.'],
            f: 'Dudas: 938 862 100 o atenciociutadana@vic.cat.' },
      ca: { h: "L'<b>hora</b> es demana a demaneuhora.vic.cat.",
            l: ["Els tràmits en línia són a vic.cat, a l'apartat d'atenció ciutadana."],
            f: 'Dubtes: 938 862 100 o atenciociutadana@vic.cat.' },
      s: { t: 'Atenció ciutadana — vic.cat', u: 'https://www.vic.cat/serveis/atencio-ciutadana' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Vic?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'CA', t: 'No sé fer un tràmit per internet, qui m\'ajuda?' },
    { lang: 'ES', t: '¿Dónde está la OAC y qué horario tiene?' },
  ],
},

// ===========================================================================
{
  slug: 'mollet-del-valles',
  nombre: 'Mollet del Vallès',
  articulo: 'de Mollet del Vallès',
  dominios: 'molletvalles.cat y seu.molletvalles.cat',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: "l'OAC", tel: '93 571 95 05', email: 'ajuntament@molletvalles.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'casa de la vila', 'placa major',
          'atencio ciutadana', 'adreca', 'horari', 'a quina hora obren', 'telefon'],
      es: { h: "L'<b>Oficina d'Atenció Ciutadana (OAC)</b> está en la planta baja de la Casa de la Vila, plaça Major, 1.",
            l: ['Teléfonos: 93 571 95 05 (OAC) y 93 571 95 00 (centralita).',
                'Horario: de lunes a jueves de 8:00 a 18:00 <b>ininterrumpido</b>; viernes de 8:00 a 15:00.',
                'En Semana Santa, Navidad y los meses de <b>julio y agosto</b>: de 8:00 a 15:00.'],
            f: 'Las horas de más gente son entre las 10:00 y las 13:00.' },
      ca: { h: "L'<b>Oficina d'Atenció Ciutadana (OAC)</b> és a la planta baixa de la Casa de la Vila, plaça Major, 1.",
            l: ['Telèfons: 93 571 95 05 (OAC) i 93 571 95 00 (centraleta).',
                'Horari: de dilluns a dijous de 8:00 a 18:00 <b>ininterromput</b>; divendres de 8:00 a 15:00.',
                'Per Setmana Santa, Nadal i els mesos de <b>juliol i agost</b>: de 8:00 a 15:00.'],
            f: 'Les hores de més gent són entre les 10:00 i les 13:00.' },
      s: { t: "Oficina d'Atenció Ciutadana (OAC) — molletvalles.cat", u: 'https://www.molletvalles.cat/ca/serveis/atencio-ciutadana' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'tarde', 'tardes', 'hace falta cita', 'necesito cita', 'obligatoria', 'turno',
          'cita previa', 'demanar cita', 'tarda', 'tardes', 'cal cita', 'obligatoria'],
      es: { h: 'La cita se <b>recomienda</b> para la mayoría de trámites, y es <b>obligatoria por la tarde</b>.',
            l: ['Se reserva en molletvalles.simplybook.it, por teléfono en el 93 571 95 05, o en la propia oficina.'],
            f: 'Ir por la tarde sin cita no sirve.' },
      ca: { h: 'La cita es <b>recomana</b> per a la majoria de tràmits, i és <b>obligatòria a la tarda</b>.',
            l: ['Es reserva a molletvalles.simplybook.it, per telèfon al 93 571 95 05, o a la mateixa oficina.'],
            f: 'Anar-hi a la tarda sense cita no serveix.' },
      s: { t: 'Atenció presencial — molletvalles.cat', u: 'https://www.molletvalles.cat/ca/serveis/atencio-ciutadana/atencio-presencial' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'certificado', 'volante',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me', 'certificat', 'volant'],
      es: { h: 'Los trámites de <b>padró</b> se hacen en la OAC, plaça Major, 1.',
            l: ['La OAC tramita la mayoría de gestiones municipales de forma integrada.',
                'Por la tarde hay que llevar cita.'],
            f: 'La documentación depende de su caso. Confírmela en el 93 571 95 05 antes de desplazarse.' },
      ca: { h: "Els tràmits de <b>padró</b> es fan a l'OAC, plaça Major, 1.",
            l: ["L'OAC tramita la majoria de gestions municipals de manera integrada.",
                'A la tarda cal portar cita.'],
            f: 'La documentació depèn del seu cas. Confirmeu-la al 93 571 95 05 abans de desplaçar-vos.' },
      s: { t: "Oficina d'Atenció Ciutadana (OAC) — molletvalles.cat", u: 'https://www.molletvalles.cat/ca/serveis/atencio-ciutadana' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'oficinas electronicas', 'notificacion', 'registro',
          'seu electronica', 'tramit', 'tramits', 'per internet', 'oficines electroniques', 'notificacio'],
      es: { h: 'La <b>seu electrònica</b> está en seu.molletvalles.cat, y los servicios electrónicos en eserveis.molletvalles.cat.',
            l: ['Ahí están la tramitación en línea y las notificaciones electrónicas.',
                'El Ayuntamiento publica además un listado de «oficines electròniques».'],
            f: 'Dudas: 93 571 95 05 o ajuntament@molletvalles.cat.' },
      ca: { h: 'La <b>seu electrònica</b> és a seu.molletvalles.cat, i els serveis electrònics a eserveis.molletvalles.cat.',
            l: ['Hi ha la tramitació en línia i les notificacions electròniques.',
                "L'Ajuntament publica a més un llistat d'«oficines electròniques»."],
            f: 'Dubtes: 93 571 95 05 o ajuntament@molletvalles.cat.' },
      s: { t: 'Tràmits Seu Electrònica — molletvalles.cat', u: 'https://www.molletvalles.cat/ca/serveis/atencio-ciutadana/atencio-telematica' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Mollet?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'CA', t: 'Cal cita prèvia a la tarda?' },
    { lang: 'ES', t: '¿Dónde está la OAC y qué horario tiene?' },
  ],
},

// ===========================================================================
{
  slug: 'la-laguna',
  nombre: 'San Cristóbal de La Laguna',
  articulo: 'de La Laguna',
  dominios: 'aytolalaguna.es y sede.aytolalaguna.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el SAC', tel: '922 601 100', email: 'participacionciudadana@lalaguna.es' },
  idioma2: null,
  kb: [
    {
      k: ['sac', 'oficina', 'oficinas', 'atencion ciudadana', 'atencion presencial', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'san agustin', 'la cuesta', 'taco', 'tejina', 'valle de guerra', 'martes'],
      es: { h: 'El <b>Servicio de Atención Ciudadana (SAC)</b> tiene <b>cinco oficinas</b>, y todas atienden en el mismo teléfono: 922 601 100.',
            l: ['<b>San Agustín</b>: c/ San Agustín, 38 (38201). De lunes a viernes de 9:00 a 13:30, y los <b>martes horario continuo de 9:00 a 17:30</b>.',
                '<b>La Cuesta</b>: plaza El Tranvía (38320). De lunes a viernes de 9:00 a 13:30.',
                '<b>Taco</b>: c/ Los Charcos, s/n, edificio Joy (38108). De lunes a viernes de 9:00 a 13:30.',
                '<b>Tejina</b>: c/ Marina González González, 7 (38260). De lunes a viernes de 9:00 a 13:30.',
                '<b>Valle de Guerra</b>: c/ Calvario, 1, Centro Ciudadano (38270). De lunes a viernes de 9:00 a 13:30.'],
            f: 'La única que abre por la tarde es San Agustín, y solo los martes.' },
      s: { t: 'SAC: Oficinas de Atención Presencial — aytolalaguna.es', u: 'https://www.aytolalaguna.es/servicios/atencion-ciudadana/oficinas-de-atencion-presencial/' },
    },
    {
      k: ['certificado', 'certificado de empadronamiento', 'certificado padron', 'volante', 'carpeta ciudadana', 'usuario y contrasena', 'clave', 'certificado digital', 'certificado electronico'],
      es: { h: 'Ojo con esto: <b>desde el 6 de abril de 2026 ya no se pueden pedir los certificados de padrón con usuario y contraseña</b> en la carpeta ciudadana.',
            l: ['Ahora hace falta identificarse con un <b>sistema oficial de identificación digital</b>, como el certificado digital.'],
            f: 'Si no tiene certificado digital, hay que ir presencialmente al SAC o pedir cita.' },
      s: { t: 'Atención ciudadana — aytolalaguna.es', u: 'https://www.aytolalaguna.es/servicios/atencion-ciudadana/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino'],
      es: { h: 'Los trámites de <b>padrón</b> se atienden en el SAC, calle San Agustín, 38.',
            l: ['Conviene pedir cita previa para no desplazarse en balde.'],
            f: 'La documentación concreta depende de su caso. Confírmela antes de ir en aytolalaguna.es o en el propio SAC.' },
      s: { t: 'Servicios — Atención ciudadana, aytolalaguna.es', u: 'https://www.aytolalaguna.es/servicios/atencion-ciudadana/servicios/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'turno', 'sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet'],
      es: { h: 'La <b>cita previa</b> se pide en aytolalaguna.es/servicios/atencion-ciudadana/cita-previa.',
            l: ['La <b>sede electrónica</b> está en sede.aytolalaguna.es.',
                'El Ayuntamiento explica que la cita existe para evitar desplazamientos innecesarios.'],
            f: 'Los teléfonos y direcciones de cada servicio municipal están publicados en aytolalaguna.es.' },
      s: { t: 'Cita Previa — aytolalaguna.es', u: 'https://www.aytolalaguna.es/servicios/atencion-ciudadana/cita-previa/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en La Laguna?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'ES', t: '¿Puedo sacar el certificado de padrón con usuario y contraseña?' },
    { lang: 'ES', t: '¿Qué horario tiene el SAC?' },
  ],
},

// ===========================================================================
{
  slug: 'ibi',
  nombre: 'Ibi',
  articulo: 'de Ibi',
  dominios: 'ibi.es y sede.ibi.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'la oficina de Estadística', tel: '965 55 24 50', email: 'estadistica@ibi.es' },
  idioma2: { cod: 'VA', clave: 'va', sigla: "a l'oficina d'Estadística", nombre: 'valenciano', sufijo: 'va' },
  kb: [
    {
      k: ['oficina', 'estadistica', 'padron', 'atencion al publico', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'les eres',
          'estadistica', 'adreca', 'horari', 'a quina hora obrin', 'telefon'],
      es: { h: 'La <b>Oficina del Padrón</b> está en la planta baja del Ayuntamiento, calle Les Eres, 48, 03440 Ibi (Alicante).',
            l: ['Teléfono: 965 55 24 50, extensión 120. Correo: estadistica@ibi.es.',
                'Horario: de <b>lunes a jueves de 11:00 a 14:00</b>.'],
            f: 'Es una franja corta: de once a dos y solo de lunes a jueves.' },
      va: { h: "L'<b>Oficina del Padró</b> està a la planta baixa de l'Ajuntament, carrer Les Eres, 48, 03440 Ibi (Alacant).",
            l: ['Telèfon: 965 55 24 50, extensió 120. Correu: estadistica@ibi.es.',
                'Horari: de <b>dilluns a dijous d\'11:00 a 14:00</b>.'],
            f: 'És una franja curta: d\'onze a dos i només de dilluns a dijous.' },
      s: { t: 'Padrón de habitantes — ibi.es', u: 'https://www.ibi.es/ciudadania/padron-de-habitantes/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'menores', 'hijos', 'quien tiene que ir',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me', 'menors'],
      es: { h: 'Para <b>darse de alta</b> en el padrón o cambiar de domicilio hay que ir a la Oficina del Padrón en horario de atención al público.',
            l: ['Tienen que <b>presentarse todos los mayores de edad</b>.',
                'Si se empadrona a un <b>menor</b>, tienen que ir <b>ambos progenitores o tutores</b>.'],
            f: 'Esa condición es la que más viajes en balde provoca: si falta uno de los dos, no se puede hacer.' },
      va: { h: "Per a <b>donar-se d'alta</b> al padró o canviar de domicili cal anar a l'Oficina del Padró en horari d'atenció al públic.",
            l: ["S'hi han de <b>presentar tots els majors d'edat</b>.",
                "Si s'empadrona un <b>menor</b>, hi han d'anar <b>els dos progenitors o tutors</b>."],
            f: 'Eixa condició és la que més viatges en va provoca: si en falta un dels dos, no es pot fer.' },
      s: { t: 'Padrón de habitantes — ibi.es', u: 'https://www.ibi.es/ciudadania/padron-de-habitantes/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'consulta', 'llamar', 'telefono', 'turno',
          'cita previa', 'demanar cita', 'telefonar'],
      es: { h: 'Las consultas, <b>tanto presenciales como por teléfono</b>, se atienden solo con <b>cita previa</b>.',
            l: ['La cita se pide llamando al 965 55 24 50, extensiones 213 o 214.'],
            f: 'También hay información de cita previa en ibi.es/te-interesa/cita-previa.' },
      va: { h: 'Les consultes, <b>tant presencials com per telèfon</b>, s\'atenen només amb <b>cita prèvia</b>.',
            l: ['La cita es demana telefonant al 965 55 24 50, extensions 213 o 214.'],
            f: "També hi ha informació de cita prèvia a ibi.es/te-interesa/cita-previa." },
      s: { t: 'Cita Previa — ibi.es', u: 'https://www.ibi.es/te-interesa/cita-previa/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'dependencias', 'servicios municipales', 'registro',
          'seu electronica', 'tramit', 'tramits', 'per internet', 'dependencies'],
      es: { h: 'La <b>sede electrónica</b> está en sede.ibi.es.',
            l: ['El Ayuntamiento publica los horarios de atención al público y el listado de servicios y dependencias municipales en ibi.es.'],
            f: 'Dudas del padrón: 965 55 24 50 ext. 120 o estadistica@ibi.es.' },
      va: { h: 'La <b>seu electrònica</b> està a sede.ibi.es.',
            l: ["L'Ajuntament publica els horaris d'atenció al públic i el llistat de serveis i dependències municipals a ibi.es."],
            f: 'Dubtes del padró: 965 55 24 50 ext. 120 o estadistica@ibi.es.' },
      s: { t: 'Horarios de atención al público — ibi.es', u: 'https://www.ibi.es/ciudadania/horarios-de-atencion-al-publico/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Ibi?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'ES', t: 'Quiero empadronar a mi hijo, ¿tenemos que ir los dos padres?' },
    { lang: 'VA', t: "Quin horari té l'oficina del padró?" },
  ],
},

// ===========================================================================
{
  slug: 'puerto-real',
  nombre: 'Puerto Real',
  articulo: 'de Puerto Real',
  dominios: 'puertoreal.es y sede.puertoreal.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el SIAC', tel: '956 47 00 00', email: 'ayuntamiento@puertoreal.es' },
  idioma2: null,
  kb: [
    {
      k: ['siac', 'oficina', 'atencion ciudadana', 'informacion', 'direccion', 'telefono', 'contacto', 'rafael alberti', 'ayuntamiento'],
      es: { h: 'El <b>Servicio de Información y Atención a la Ciudadanía (SIAC)</b> está en el Ayuntamiento, plaza Poeta Rafael Alberti, 1, Puerto Real (Cádiz).',
            l: ['Teléfono: 956 47 00 00.',
                'Correo: ayuntamiento@puertoreal.es.'],
            f: 'El Ayuntamiento no publica el horario del SIAC en su web. Confírmelo en el 956 47 00 00.' },
      s: { t: 'Servicio de Información y Atención a la Ciudadanía (SIAC) — puertoreal.es', u: 'https://puertoreal.es/atencion-a-la-ciudadania/servicios-municipales/servicio-de-informacion-y-atencion-a-la-ciudadania-siac/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'hace falta cita', 'necesito cita', 'turno'],
      es: { h: 'La atención presencial es <b>con cita previa</b>.',
            l: ['La cita se pide por teléfono en el 956 47 00 00 o por la sede electrónica municipal.'],
            f: 'Sin cita es probable que no le atiendan.' },
      s: { t: 'Atención a la ciudadanía — puertoreal.es', u: 'https://puertoreal.es/atencion-a-la-ciudadania/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'certificado', 'volante'],
      es: { h: 'Los trámites de <b>padrón</b> se presentan por la sede electrónica, en sede.puertoreal.es, o presencialmente con cita.',
            l: ['A la sede se accede también con <b>Cl@ve</b>, la plataforma de identificación del Estado.'],
            f: 'La documentación concreta no está publicada en la ficha del SIAC: confírmela en el 956 47 00 00 antes de desplazarse.' },
      s: { t: 'Sede Electrónica — Ayuntamiento de Puerto Real', u: 'https://sede.puertoreal.es/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'clave', 'preguntas frecuentes', 'omic', 'consumo', 'reclamacion', 'registro'],
      es: { h: 'La <b>sede electrónica</b> está en sede.puertoreal.es y admite acceso con <b>Cl@ve</b>.',
            l: ['Tiene su propio apartado de preguntas frecuentes.',
                'Las reclamaciones de consumo van a la <b>OMIC</b>, que es un servicio distinto del SIAC.'],
            f: 'Dudas: 956 47 00 00 o ayuntamiento@puertoreal.es.' },
      s: { t: 'Sede Electrónica — Ayuntamiento de Puerto Real', u: 'https://sede.puertoreal.es/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Puerto Real?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente la tasa de basuras?' },
    { lang: 'ES', t: '¿Hace falta cita previa?' },
    { lang: 'ES', t: '¿Dónde está el SIAC?' },
  ],
},

// ===========================================================================
{
  slug: 'alhaurin-el-grande',
  nombre: 'Alhaurín el Grande',
  articulo: 'de Alhaurín el Grande',
  dominios: 'alhaurinelgrande.es y sede.alhaurinelgrande.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el Ayuntamiento', tel: '952 49 00 00', email: 'registro@alhaurinelgrande.es' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'atencion ciudadana', 'ayuntamiento', 'registro', 'direccion', 'telefono', 'contacto', 'plaza del convento', 'oficinas municipales', 'oficinas', 'dependencias'],
      es: { h: 'Las oficinas municipales están en la <b>plaza del Convento</b>, 29120 Alhaurín el Grande (Málaga).',
            l: ['Teléfono: 952 49 00 00.'],
            f: 'El Ayuntamiento no publica el horario de atención al público en su web. Confírmelo en el 952 49 00 00.' },
      s: { t: 'Padrón de Habitantes — alhaurinelgrande.es', u: 'https://alhaurinelgrande.es/padron-de-habitantes/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'cita', 'cita previa', 'pedir cita'],
      es: { h: 'Para las <b>altas y los cambios de domicilio</b> en el padrón hace falta <b>cita previa</b>.',
            l: ['Se pide llamando al 952 49 00 00 o escribiendo a <b>padron2@alhaurinelgrande.es</b>.'],
            f: 'Ojo: la cita es solo para altas y cambios de domicilio. Para los certificados no hace falta.' },
      s: { t: 'Padrón de Habitantes — alhaurinelgrande.es', u: 'https://alhaurinelgrande.es/padron-de-habitantes/' },
    },
    {
      k: ['certificado', 'certificado de empadronamiento', 'certificado padron', 'volante', 'convivencia', 'historico', 'acreditar residencia'],
      es: { h: 'Los <b>certificados</b> —de empadronamiento, de convivencia, históricos— se piden <b>por internet o presencialmente</b>, sin cita.',
            l: ['Presencialmente, en las oficinas municipales de la plaza del Convento.',
                'Por internet, en la sede electrónica: sede.alhaurinelgrande.es.'],
            f: 'Esa es la diferencia con las altas: los certificados no necesitan cita previa.' },
      s: { t: 'Solicitud de certificado de empadronamiento — Sede Electrónica de Alhaurín el Grande', u: 'http://sede.alhaurinelgrande.es/alhauPortal/sede/se_contenedor2.jsp?contenido=6339&nivel=1400&seccion=s_ftra_d4_v1.jsp&tipo=4' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'solicitud general', 'instancia', 'registro de entrada', 'oficina virtual'],
      es: { h: 'La <b>sede electrónica</b> está en sede.alhaurinelgrande.es, con el catálogo de trámites.',
            l: ['Ahí están el registro de entrada y la solicitud general.',
                'Hay además una oficina virtual en ovc.alhaurinelgrande.es.'],
            f: 'Dudas: 952 49 00 00 o registro@alhaurinelgrande.es.' },
      s: { t: 'Catálogo de Trámites — Sede Electrónica de Alhaurín el Grande', u: 'http://sede.alhaurinelgrande.es/alhauPortal/sede/se_contenedor1.jsp?codMenu=846&codMenuPN=820&codResi=1&codbusqueda=669&language=es&layout=se_contenedor1.jsp&numeroPagina=1&seccion=s_ltra_d12_v1.jsp' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Alhaurín el Grande?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'ES', t: '¿Hace falta cita previa para un certificado de empadronamiento?' },
    { lang: 'ES', t: '¿Dónde están las oficinas municipales?' },
  ],
},

];
