// ---------------------------------------------------------------------------
//  LOS OCHO DEL TERCER ENVIO — jueves 10 de septiembre de 2026.
//  Comprobado en cada web municipal el 6 de septiembre de 2026.
//  Misma regla que en municipios.mjs: lo que no se pudo verificar no se pone.
//
//  Dos lenguas ademas del castellano: catalan (Santa Coloma, Sant Cugat) y
//  gallego (Ourense). Torrevieja se deja en castellano a proposito: esta en la
//  Vega Baja, zona de predominio linguistico castellano.
//
//  En `oficina.sigla` el nombre va CON su articulo castellano ("el SAC"),
//  porque la plantilla dice "Consultelo directamente en ${sigla}".
//  En `idioma2.sigla` va con preposicion y articulo YA contraidos en la otra
//  lengua ("a l'OIAC", "na Oficina de Atencion Cidada"), porque alli la
//  plantilla no pone preposicion.
// ---------------------------------------------------------------------------

export const MUNICIPIOS_DIA03 = [

// ===========================================================================
{
  slug: 'algeciras',
  nombre: 'Algeciras',
  articulo: 'de Algeciras',
  dominios: 'algeciras.es y sede.algeciras.es',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'la Oficina de Atención al Ciudadano', tel: '956 67 27 00', email: 'atencionalciudadano@algeciras.es' },
  idioma2: null,
  kb: [
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'estadistica', 'certificado', 'volante', 'cambio de domicilio', 'mudarme', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran'],
      es: { h: 'El <b>padrón</b> lo lleva la <b>Delegación de Estadística</b>, que es quien lo mantiene y lo custodia.',
            l: ['Dirección: Regino Martínez, 16.',
                'Teléfono: 956 672 709.',
                'Horario: de octubre a mayo, de 8:30 a 14:00. De junio a septiembre, de 8:30 a 13:30.',
                'La atención se hace <b>con cita previa</b>.'],
            f: 'El padrón es el registro donde constan todos los vecinos, sus direcciones y las unidades familiares.' },
      s: { t: 'Delegación de Estadística — algeciras.es', u: 'https://www.algeciras.es/es/temas/atencion-al-ciudadano/delegacion-de-estadistica/' },
    },
    {
      k: ['oficina', 'atencion al ciudadano', 'oac', 'direccion', 'telefono', 'contacto', 'regino martinez', 'buzon'],
      es: { h: 'La <b>Oficina de Atención al Ciudadano</b> está en el edificio municipal de la calle Regino Martínez.',
            l: ['Presencialmente, dentro del horario de atención al público.',
                'Por teléfono, en el 956 67 27 00.',
                'Por internet, a través del Buzón del Ciudadano o por correo electrónico.'],
            f: 'Correo: atencionalciudadano@algeciras.es.' },
      s: { t: 'Oficina de Atención al Ciudadano — algeciras.es', u: 'https://www.algeciras.es/es/temas/atencion-al-ciudadano/oficina-de-atencion-al-ciudadano/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita', 'presencial'],
      es: { h: 'La <b>cita previa</b> se pide por internet, desde la sede electrónica.',
            l: ['Dirección directa: sede.algeciras.es/citaprevia/.'],
            f: 'Para los trámites de padrón la cita es obligatoria: la Delegación de Estadística atiende solo con cita.' },
      s: { t: 'Cita previa — sede.algeciras.es', u: 'https://sede.algeciras.es/citaprevia/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo'],
      es: { h: 'La <b>sede electrónica</b> permite hacer trámites sin ir a la oficina.',
            l: ['Ahí está el catálogo de trámites y el sistema de cita previa.'],
            f: 'Si no encuentra su trámite, la Oficina de Atención al Ciudadano lo aclara en el 956 67 27 00.' },
      s: { t: 'Sede Electrónica — Ayuntamiento de Algeciras', u: 'https://sede.algeciras.es/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Dónde se tramita el padrón en Algeciras?' },
    { lang: 'ES', t: '¿Dónde está la oficina de atención ciudadana?' },
    { lang: 'ES', t: '¿Hace falta cita previa para Estadística?' },
    { lang: 'ES', t: '¿Qué horario tiene Estadística en verano?' },
  ],
},

// ===========================================================================
{
  slug: 'santa-coloma-de-gramenet',
  nombre: 'Santa Coloma de Gramenet',
  articulo: 'de Santa Coloma de Gramenet',
  dominios: 'gramenet.cat',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'la OIAC', tel: '934 624 040', email: 'oiac@gramenet.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OIAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oiac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'plaza de la vila', 'miercoles',
          'atencio ciutadana', 'adreca', 'horari', 'telefon', 'placa de la vila', 'dimecres'],
      es: { h: 'La <b>Oficina d\'Informació i Atenció a la Ciutadania (OIAC)</b> es el canal presencial del Ayuntamiento.',
            l: ['Plaça de la Vila, 1 — 08921 Santa Coloma de Gramenet.',
                'Atención telefónica general: 934 624 040. Cita previa: 93 462 40 90.',
                'Horario: de 9:00 a 14:30 los lunes, martes, jueves y viernes.',
                'Los <b>miércoles</b> el horario es más amplio: de 9:00 a 17:30.'],
            f: 'Cada día, de 9:00 a 10:00, se atiende <b>sin cita previa</b> a personas de 65 años o más y a quienes acrediten un grado de discapacidad.' },
      ca: { h: 'L\'<b>Oficina d\'Informació i Atenció a la Ciutadania (OIAC)</b> és el canal presencial de l\'Ajuntament.',
            l: ['Plaça de la Vila, 1 — 08921 Santa Coloma de Gramenet.',
                'Atenció telefònica general: 934 624 040. Cita prèvia: 93 462 40 90.',
                'Horari: de 9:00 a 14:30 els dilluns, dimarts, dijous i divendres.',
                'Els <b>dimecres</b> l\'horari és més ampli: de 9:00 a 17:30.'],
            f: 'Cada dia, de 9:00 a 10:00, s\'atén <b>sense cita prèvia</b> les persones de 65 anys o més i les que acreditin un grau de discapacitat.' },
      s: { t: 'Oficina d\'Informació i Atenció a la Ciutadania — gramenet.cat', u: 'https://www.gramenet.cat/ajuntament/oficina-dinformacio-i-atencio-a-la-ciutadania/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'nacimiento', 'cambio de domicilio', 'certificado', 'copia literal',
          'padro', 'empadronar-me', 'empadronament', 'naixement', 'canvi de domicili', 'certificat'],
      es: { h: 'La OIAC gestiona los trámites del <b>padró municipal d\'habitants</b>.',
            l: ['Alta en el padrón.',
                'Alta por nacimiento.',
                'Cambio de domicilio.',
                'Copia literal del padrón municipal de habitantes y otros certificados.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 934 624 040 antes de pedir la cita.' },
      ca: { h: 'L\'OIAC gestiona els tràmits del <b>padró municipal d\'habitants</b>.',
            l: ['Alta al padró.',
                'Alta per naixement.',
                'Canvi de domicili.',
                'Còpia literal del padró municipal d\'habitants i altres certificats.'],
            f: 'La documentació concreta depèn del seu cas. Confirmi-la al 934 624 040 abans de demanar la cita.' },
      s: { t: 'Carta de serveis de l\'OIAC — gramenet.cat', u: 'https://www.gramenet.cat/es/ayuntamiento/oiac/carta-de-servicios-de-la-oiac/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita', 'sin cita', 'presencial', 'mayores', '65',
          'demanar cita', 'sense cita', 'grans'],
      es: { h: 'La atención es <b>preferentemente con cita previa</b>, pero no de forma exclusiva.',
            l: ['Por teléfono, en el 93 462 40 90.',
                'Por web, en gramenet.cat > seu electrònica > cita prèvia.',
                'De 9:00 a 10:00 se atiende sin cita a mayores de 65 años y a personas con discapacidad acreditada.'],
            f: 'Los miércoles la oficina abre hasta las 17:30, que es el día con más margen si trabaja por la mañana.' },
      ca: { h: 'L\'atenció és <b>preferentment amb cita prèvia</b>, però no de manera exclusiva.',
            l: ['Per telèfon, al 93 462 40 90.',
                'Per web, a gramenet.cat > seu electrònica > cita prèvia.',
                'De 9:00 a 10:00 s\'atén sense cita les persones majors de 65 anys i les que tinguin discapacitat acreditada.'],
            f: 'Els dimecres l\'oficina obre fins a les 17:30, que és el dia amb més marge si treballa al matí.' },
      s: { t: 'Cita prèvia — gramenet.cat', u: 'https://www.gramenet.cat/en/seu-electronica/cita-previa/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet',
          'seu electronica', 'tramit', 'tramits', 'per internet'],
      es: { h: 'La <b>seu electrònica</b> permite hacer trámites y pedir cita sin desplazarse.',
            l: ['Se accede desde gramenet.cat.'],
            f: 'Dudas sobre la sede: 934 624 040.' },
      ca: { h: 'La <b>seu electrònica</b> permet fer tràmits i demanar cita sense desplaçar-se.',
            l: ['S\'hi accedeix des de gramenet.cat.'],
            f: 'Dubtes sobre la seu: 934 624 040.' },
      s: { t: 'Seu electrònica — gramenet.cat', u: 'https://www.gramenet.cat/seu-electronica/suport/contacte/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué horario tiene la OIAC los miércoles?' },
    { lang: 'CA', t: 'Puc anar a l\'OIAC sense cita prèvia?' },
    { lang: 'ES', t: '¿Qué teléfono tienen?' },
    { lang: 'ES', t: '¿Qué trámites de padrón puedo hacer?' },
    { lang: 'ES', t: '¿Dónde está la oficina?' },
  ],
},

// ===========================================================================
{
  slug: 'roquetas-de-mar',
  nombre: 'Roquetas de Mar',
  articulo: 'de Roquetas de Mar',
  dominios: 'aytoroquetas.org y sede.aytoroquetas.org',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'el Ayuntamiento', tel: '950 33 85 85', email: 'atencionciudadana@aytoroquetas.org' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'ayuntamiento', 'plaza de la constitucion', 'sabado', 'sabados'],
      es: { h: 'La atención al ciudadano está en la <b>plaza de la Constitución, 1</b> — 04740 Roquetas de Mar (Almería).',
            l: ['Teléfono: 950 33 85 85.',
                'Horario: de lunes a viernes de <b>8:00 a 21:00</b>, y los sábados de 10:00 a 14:00.'],
            f: 'Es uno de los horarios más amplios de la provincia: abre por la tarde todos los días laborables y también el sábado por la mañana.' },
      s: { t: 'Oficinas del Ayuntamiento de Roquetas de Mar', u: 'https://portaltributario.aytoroquetas.org/oficinas' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'volante', 'certificado', 'cambio de domicilio', 'mudarme'],
      es: { h: 'Los trámites de <b>padrón</b> se pueden hacer enteros por la sede electrónica.',
            l: ['Solicitud del <b>volante</b> de empadronamiento.',
                'Solicitud del <b>certificado</b> de empadronamiento.',
                'Alta de habitantes.',
                'Cambio de domicilio de habitantes.'],
            f: 'Si prefiere hacerlo presencialmente: plaza de la Constitución, 1, de 8:00 a 21:00 de lunes a viernes.' },
      s: { t: 'Sede Electrónica del Ayuntamiento de Roquetas de Mar', u: 'https://sede.aytoroquetas.org/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'carpeta del ciudadano', 'oficina virtual'],
      es: { h: 'La <b>sede electrónica</b> permite hacer actuaciones, procedimientos y servicios públicos del Ayuntamiento de forma segura.',
            l: ['Incluye la Carpeta del Ciudadano, donde consultar el estado de sus expedientes.',
                'Hay además un portal tributario y una oficina virtual separados.'],
            f: 'Dudas: 950 33 85 85.' },
      s: { t: 'Sede Electrónica del Ayuntamiento de Roquetas de Mar', u: 'https://sede.aytoroquetas.org/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Puedo pedir el volante de empadronamiento por internet?' },
    { lang: 'ES', t: '¿Dónde está la oficina?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'ES', t: '¿Qué horario tiene la atención al ciudadano?' },
  ],
},

// ===========================================================================
{
  slug: 'cadiz',
  nombre: 'Cádiz',
  articulo: 'de Cádiz',
  dominios: 'cadiz.es e institucional.cadiz.es',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'el SAC', tel: '956 24 10 00', email: 'atencion.ciudadano@cadiz.es' },
  idioma2: null,
  kb: [
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'sin cita', 'presencial', 'cola', 'colas', 'gestor de colas'],
      es: { h: 'Para el SAC, Estadística y Padrón <b>no hace falta cita previa</b>.',
            l: ['Basta con coger número en el gestor de colas del patio de la Casa Consistorial.',
                'Lo mismo vale para la acreditación del certificado digital.'],
            f: 'Es una diferencia importante respecto a otros ayuntamientos: aquí se puede ir directamente.' },
      s: { t: 'Cita previa en la Oficina del Padrón — transparencia.cadiz.es', u: 'https://transparencia.cadiz.es/el-ayuntamiento-de-cadiz-implanta-el-sistema-de-cita-previa-en-la-oficina-del-padron-para-reducir-a-cero-las-esperas/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'estadistica', 'certificado', 'volante', 'cambio de domicilio', 'mudarme'],
      es: { h: 'La <b>Oficina de Estadística</b> está en la planta baja de la Casa Consistorial, plaza de San Juan de Dios, s/n.',
            l: ['Se pueden solicitar certificados y volantes de empadronamiento.',
                'También comunicar cambios de domicilio.',
                'Por internet: con certificado digital, a través del registro electrónico común de la Administración General del Estado.',
                'Presencialmente: con original y fotocopia de la documentación en vigor y actualizada.'],
            f: 'Teléfono general del Ayuntamiento: 956 24 10 00.' },
      s: { t: 'Volantes y Certificados — institucional.cadiz.es', u: 'https://institucional.cadiz.es/%C3%A1rea-municipal/72' },
    },
    {
      k: ['descargar', 'portal del ciudadano', 'certificado digital', 'dnie', 'clave', 'online', 'internet', 'por internet'],
      es: { h: 'Con <b>certificado digital, DNI electrónico o Clave</b> el certificado de empadronamiento se descarga directamente.',
            l: ['Se hace desde el Portal del Ciudadano del Ayuntamiento.',
                'No hace falta desplazarse a ninguna oficina.'],
            f: 'Si no tiene certificado digital, puede acreditarlo en la Casa Consistorial sin cita previa.' },
      s: { t: 'Portal del Ciudadano — Catálogo de Trámites', u: 'https://portaldelcontribuyente.cadiz.es/portalCiudadano/sede/catalogoTramites.do?opcion=detalle&idApl=3&ent_id=1&idioma=1' },
    },
    {
      k: ['oficina', 'atencion al ciudadano', 'sac', 'direccion', 'telefono', 'contacto', 'casa consistorial', 'san juan de dios'],
      es: { h: 'El Ayuntamiento está en la <b>plaza de San Juan de Dios, s/n</b> — 11005 Cádiz.',
            l: ['Teléfono: 956 24 10 00.',
                'El SAC y la Oficina de Estadística están en la planta baja de la Casa Consistorial.'],
            f: 'Correo de atención al ciudadano: atencion.ciudadano@cadiz.es.' },
      s: { t: 'Atención al Ciudadano — institucional.cadiz.es', u: 'https://institucional.cadiz.es/area/Atenci%C3%B3n-al-Ciudadano/603' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hace falta cita previa para el padrón?' },
    { lang: 'ES', t: '¿Puedo descargar el certificado de empadronamiento?' },
    { lang: 'ES', t: '¿Dónde está la oficina de atención ciudadana?' },
    { lang: 'ES', t: '¿Dónde está la Oficina de Estadística?' },
  ],
},

// ===========================================================================
{
  slug: 'ourense',
  nombre: 'Ourense',
  articulo: 'de Ourense',
  dominios: 'ourense.gal',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'la Oficina de Atención Ciudadana', tel: '988 392 909', email: 'contacto@ourense.gal' },
  idioma2: { cod: 'GL', clave: 'gl', sigla: 'na Oficina de Atención Cidadá', nombre: 'gallego' },
  kb: [
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'habitantes',
          'empadroarme', 'empadroamento'],
      es: { h: 'La Oficina de Atención Ciudadana emite los documentos del <b>padrón de habitantes</b>.',
            l: ['Certificados de empadronamiento.',
                'Volantes de empadronamiento.',
                'Consultas sobre el padrón de habitantes.'],
            f: 'Teléfono: 988 392 909. La oficina está en la planta baja del Concello.' },
      gl: { h: 'A Oficina de Atención Cidadá emite os documentos do <b>padrón de habitantes</b>.',
            l: ['Certificados de empadroamento.',
                'Volantes de empadroamento.',
                'Consultas sobre o padrón de habitantes.'],
            f: 'Teléfono: 988 392 909. A oficina está na planta baixa do Concello.' },
      s: { t: 'Padrón de Habitantes — ourense.gal', u: 'https://www.ourense.gal/es/ayuntamiento/atencion-al-ciudadano/351-padron-de-habitantes-es' },
    },
    {
      k: ['sede electronica', 'internet', 'online', 'por internet', 'descargar', 'registrado', 'usuario', 'rexistrado'],
      es: { h: 'Los usuarios registrados en la <b>sede electrónica municipal</b> pueden descargarse los volantes y certificados individuales.',
            l: ['Evita tener que ir a las oficinas municipales.'],
            f: 'Si no está registrado, la Oficina de Atención Ciudadana le explica cómo hacerlo: 988 392 909.' },
      gl: { h: 'As persoas usuarias rexistradas na <b>sede electrónica municipal</b> poden descargar os volantes e certificados individuais.',
            l: ['Evita ter que ir ás oficinas municipais.'],
            f: 'Se non está rexistrado, a Oficina de Atención Cidadá explícalle como facelo: 988 392 909.' },
      s: { t: 'Rexistro electrónico do Concello — ourense.gal', u: 'https://www.ourense.gal/es/noticias/4637-rexistro-electronico-do-concello' },
    },
    {
      k: ['oficina', 'atencion ciudadana', 'direccion', 'telefono', 'contacto', 'concello', 'registro', 'barreira',
          'atencion cidada', 'enderezo', 'rexistro'],
      es: { h: 'La <b>Oficina de Atención Ciudadana</b> está en la planta baja del Concello.',
            l: ['Teléfono: 988 392 909.',
                'El Registro General se trasladó a la calle Barreira, 2.'],
            f: 'Correo de contacto: contacto@ourense.gal.' },
      gl: { h: 'A <b>Oficina de Atención Cidadá</b> está na planta baixa do Concello.',
            l: ['Teléfono: 988 392 909.',
                'O Rexistro Xeral trasladouse á rúa Barreira, 2.'],
            f: 'Correo de contacto: contacto@ourense.gal.' },
      s: { t: 'Atención á cidadanía — ourense.gal', u: 'https://ourense.gal/es/servizos/atencion-a-la-ciudadania' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Cómo consigo un volante de empadronamiento?' },
    { lang: 'GL', t: 'Onde está a Oficina de Atención Cidadá?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'GL', t: 'Podo descargar o certificado de empadroamento?' },
  ],
},

// ===========================================================================
{
  slug: 'torrevieja',
  nombre: 'Torrevieja',
  articulo: 'de Torrevieja',
  dominios: 'torrevieja.es y torrevieja.sedelectronica.es',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'el PAC', tel: '965 71 01 12', email: 'pac@torrevieja.eu' },
  idioma2: null,
  kb: [
    {
      k: ['pac', 'punto de atencion', 'oficina', 'atencion ciudadana', 'como funciona', 'autoservicio', 'para que sirve'],
      es: { h: 'El <b>Punto de Atención Ciudadano (PAC)</b> ayuda a usar la oficina electrónica de autoservicio.',
            l: ['Da apoyo informativo y asistencia concreta con los trámites.',
                'Identifica qué departamento municipal tiene que intervenir en cada caso.',
                'Y garantiza un canal de contacto efectivo con ese departamento.'],
            f: 'Permite obtener certificados de empadronamiento <b>sin colas y sin cita previa</b>.' },
      s: { t: 'Punto de Atención Ciudadano (PAC) — torrevieja.es', u: 'https://torrevieja.es/en/node/9355' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'censo', 'estadistica'],
      es: { h: 'El <b>certificado de empadronamiento</b> se puede obtener en el PAC sin hacer cola ni pedir cita.',
            l: ['Padrón, censo y estadística son las consultas de mayor volumen que atiende el PAC.',
                'También se puede tramitar por la sede electrónica, sin ir a las oficinas.'],
            f: 'La oficina de Registro/PROP está en la plaza de la Constitución, 5. Recomiendan ir temprano, antes de las 9:00.' },
      s: { t: 'Censo y Estadística — torrevieja.es', u: 'https://torrevieja.es/en/ciudad/census-and-statistics' },
    },
    {
      k: ['registro', 'prop', 'oficina de registro', 'plaza de la constitucion', 'temprano', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran'],
      es: { h: 'La oficina de <b>Registro / PROP</b> está en la plaza de la Constitución, 5.',
            l: ['Recomiendan acudir temprano, antes de las 9:00 de la mañana.'],
            f: 'Muchos trámites se pueden evitar haciéndolos por la sede electrónica, disponible las 24 horas.' },
      s: { t: 'Oficinas de Atención al Ciudadano — gobiernoabierto.torrevieja.es', u: 'https://gobiernoabierto.torrevieja.es/p/1354-oficinas-de-atencion-al-ciudadano' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet'],
      es: { h: 'La <b>sede electrónica</b> del Ayuntamiento está en torrevieja.sedelectronica.es.',
            l: ['Permite hacer trámites y consultas sin acudir presencialmente a las oficinas municipales.'],
            f: 'Si se atasca con la sede, el PAC está precisamente para ayudarle a usarla.' },
      s: { t: 'Sede Electrónica — Ayuntamiento de Torrevieja', u: 'https://torrevieja.es/en/electronic-offices' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Cómo consigo el certificado de empadronamiento?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'ES', t: '¿Para qué sirve el PAC?' },
    { lang: 'ES', t: '¿Dónde está la oficina de Registro?' },
    { lang: 'ES', t: '¿Hasta qué hora abren?' },
  ],
},

// ===========================================================================
{
  slug: 'chiclana-de-la-frontera',
  nombre: 'Chiclana de la Frontera',
  articulo: 'de Chiclana de la Frontera',
  dominios: 'chiclana.es',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'el Ayuntamiento', tel: '956 100 800', email: 'informacion@chiclana.es' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'atencion ciudadania', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'ayuntamiento', 'constitucion', 'sabado', 'sabados'],
      es: { h: 'El Ayuntamiento está en la <b>calle Constitución, 1</b> — 11130 Chiclana de la Frontera (Cádiz).',
            l: ['Teléfono: 956 100 800.',
                'Servicio de atención a la ciudadanía: de lunes a viernes de <b>8:00 a 20:00</b>, y los sábados de 9:00 a 14:00.'],
            f: 'Correo: informacion@chiclana.es.' },
      s: { t: 'Directorio de contacto — chiclana.es', u: 'https://www.chiclana.es/el-ayuntamiento/contacto/directorio-de-contacto' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'sin cita', 'obligatoria', 'necesaria', 'cola', 'colas', 'estadistica'],
      es: { h: 'En el departamento de <b>Estadística</b> la cita previa <b>no es necesaria</b>.',
            l: ['Se puede pedir igualmente si quiere evitar colas.',
                'La cita se solicita en chiclana.es > oficina virtual > cita previa.'],
            f: 'Para el resto del Ayuntamiento la cita previa presencial tampoco es obligatoria.' },
      s: { t: 'Pedir cita previa presencial (no obligatoria) — chiclana.es', u: 'https://www.chiclana.es/gestiones-y-tramites/cita-previa-presencial-ayuntamiento-de-chiclana' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'volante', 'certificado', 'cambio de domicilio', 'mudarme'],
      es: { h: 'Los <b>volantes de empadronamiento</b> se obtienen por la sede electrónica sin desplazarse.',
            l: ['Disponible <b>24 horas al día, los 365 días del año</b>.',
                'Los trámites de padrón los lleva la Delegación de Estadística.',
                'Hay también solicitudes de padrón sin certificado digital, desde la oficina virtual.'],
            f: 'Si prefiere ir en persona: calle Constitución, 1, de 8:00 a 20:00 de lunes a viernes.' },
      s: { t: 'Trámites y procedimientos de Estadística — chiclana.es', u: 'https://www.chiclana.es/delegaciones-y-servicios/estadistica/tramites-y-procedimientos-delegacion-de-estadistica/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'oficina virtual', 'gestiones'],
      es: { h: 'La <b>sede electrónica</b> está disponible las 24 horas, todos los días del año.',
            l: ['Ahí están las gestiones y trámites municipales.',
                'La oficina virtual permite además solicitudes sin certificado digital.'],
            f: 'Dudas: 956 100 800.' },
      s: { t: 'Sede electrónica — chiclana.es', u: 'https://www.chiclana.es/sede-electronica/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hace falta cita previa para Estadística?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'ES', t: '¿Puedo pedir el volante de empadronamiento por internet?' },
    { lang: 'ES', t: '¿Qué horario tiene el registro?' },
  ],
},

// ===========================================================================
{
  slug: 'sant-cugat-del-valles',
  nombre: 'Sant Cugat del Vallès',
  articulo: 'de Sant Cugat del Vallès',
  dominios: 'santcugat.cat',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'la OAC', tel: '010 o 900 104 941', email: 'bustiaciutadana@santcugat.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'plaza de la vila', 'mira-sol', 'mira sol',
          'atencio ciutadana', 'adreca', 'horari', 'telefon', 'placa de la vila'],
      es: { h: 'La <b>Oficina d\'Atenció Ciutadana (OAC)</b> principal está en la plaça de la Vila, 1.',
            l: ['Horario: de lunes a viernes de 10:00 a 14:00.',
                'Hay una segunda OAC en el barrio de Mira-sol: carrer de Mallorca, 42. Teléfono 935 892 018.',
                'La de Mira-sol abre lunes, martes, miércoles y viernes de 10:00 a 14:00.'],
            f: 'Teléfono único: el <b>010</b>, o el 900 104 941 desde móvil o desde fuera del municipio. Es gratuito.' },
      ca: { h: 'L\'<b>Oficina d\'Atenció Ciutadana (OAC)</b> principal és a la plaça de la Vila, 1.',
            l: ['Horari: de dilluns a divendres de 10:00 a 14:00.',
                'Hi ha una segona OAC al barri de Mira-sol: carrer de Mallorca, 42. Telèfon 935 892 018.',
                'La de Mira-sol obre dilluns, dimarts, dimecres i divendres de 10:00 a 14:00.'],
            f: 'Telèfon únic: el <b>010</b>, o el 900 104 941 des de mòbil o des de fora del municipi. És gratuït.' },
      s: { t: 'Oficina d\'Atenció Ciutadana — santcugat.cat', u: 'https://www.santcugat.cat/servei/oficina-datencio-ciutadana' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'sin cita', 'reservar', 'visita concertada',
          'demanar cita', 'sense cita', 'visita concertada'],
      es: { h: 'La OAC <b>combina la cita previa con la atención a quien no la ha pedido</b>.',
            l: ['La cita se pide por internet, desde el formulario de solicitud.',
                'O por teléfono en el 010 (900 104 941 desde móvil o fuera del municipio), que es gratuito.'],
            f: 'Es decir: con cita espera menos, pero sin cita también le atienden.' },
      ca: { h: 'L\'OAC <b>combina la cita prèvia amb l\'atenció a qui no l\'ha demanat</b>.',
            l: ['La cita es demana per internet, des del formulari de sol·licitud.',
                'O per telèfon al 010 (900 104 941 des de mòbil o fora del municipi), que és gratuït.'],
            f: 'És a dir: amb cita esperarà menys, però sense cita també l\'atendran.' },
      s: { t: 'Visites concertades a l\'OAC — santcugat.cat', u: 'https://www.santcugat.cat/servei/visites-concertades-a-loac' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'cambio de domicilio', 'mudarme',
          'padro', 'empadronar-me', 'empadronament', 'certificat', 'volant', 'canvi de domicili'],
      es: { h: 'La OAC gestiona el <b>padró municipal</b> como parte de sus trámites administrativos generales.',
            l: ['Presencialmente en plaça de la Vila, 1, o en la OAC de Mira-sol.',
                'Con cita previa o sin ella.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 010 antes de ir: la llamada es gratuita.' },
      ca: { h: 'L\'OAC gestiona el <b>padró municipal</b> com a part dels seus tràmits administratius generals.',
            l: ['Presencialment a la plaça de la Vila, 1, o a l\'OAC de Mira-sol.',
                'Amb cita prèvia o sense.'],
            f: 'La documentació concreta depèn del seu cas. Confirmi-la al 010 abans d\'anar-hi: la trucada és gratuïta.' },
      s: { t: 'Atenció ciutadana — santcugat.cat', u: 'https://www.santcugat.cat/web/atencio-ciutadana' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', '010',
          'seu electronica', 'tramit', 'tramits', 'per internet'],
      es: { h: 'Para consultas sobre trámites o sobre la ciudad, el teléfono es el <b>010</b>.',
            l: ['Desde móvil o desde fuera del municipio: 900 104 941.',
                'El servicio es gratuito.'],
            f: 'Los trámites en línea están en santcugat.cat.' },
      ca: { h: 'Per a consultes sobre tràmits o sobre la ciutat, el telèfon és el <b>010</b>.',
            l: ['Des de mòbil o des de fora del municipi: 900 104 941.',
                'El servei és gratuït.'],
            f: 'Els tràmits en línia són a santcugat.cat.' },
      s: { t: 'OAC 010 — santcugat.cat', u: 'https://www.santcugat.cat/OAC/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Puedo ir a la OAC sin cita previa?' },
    { lang: 'ES', t: '¿Cuál es el teléfono?' },
    { lang: 'ES', t: '¿Necesito certificado digital?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'CA', t: 'Quin horari té l\'OAC de Mira-sol?' },
  ],
},

];
