// ---------------------------------------------------------------------------
//  LOS OCHO DEL DOCEAVO ENVIO — miercoles 7 de octubre de 2026.
//  Comprobado en cada web municipal el 7 de septiembre de 2026.
//
//  Dos cambios sobre la lista de partida, y los dos por lo mismo: no meter
//  nada que no se haya podido verificar.
//
//  - Ontinyent se cae: su web corta la conexion una y otra vez y no he podido
//    confirmar ni direccion ni horario de su oficina. Entra La Rinconada, que
//    si publica los datos de su SAC.
//  - En Sant Feliu, buscar-correo.mjs proponia el general del Ajuntament. La
//    OAC tiene correo propio publicado, oac@santfeliu.cat, y es mejor destino.
//
//  Catalan en Girona, el Prat y Sant Feliu; valenciano en Alzira. Torrelavega,
//  Ecija, San Fernando de Henares y La Rinconada, solo castellano.
//
//  Lo que un ayuntamiento no publica, aqui no esta: la demo dice que no tiene
//  fuente y da el telefono. Ningun horario inventado.
// ---------------------------------------------------------------------------

export const MUNICIPIOS_DIA12 = [

// ===========================================================================
{
  slug: 'girona',
  nombre: 'Girona',
  articulo: 'de Girona',
  dominios: 'girona.cat y seu.girona.cat',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: "l'OAMR", tel: '972 419 010', email: 'ajuntamentinforma@ajgirona.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAMR", nombre: 'catalán' },
  kb: [
    {
      k: ['oamr', 'oficina', 'atencion ciudadana', 'informacion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'placa del vi', 'sabado',
          'atencio ciutadana', 'adreca', 'horari', 'a quina hora obren', 'telefon', 'dissabte', 'dissabtes', 'sabados', 'obren els dissabtes', 'obriu els dissabtes'],
      es: { h: "L'<b>Oficina d'Assistència en Matèria de Registre (OAMR)</b> está en la plaça del Vi, 1, 17004 Girona.",
            l: ['Teléfono de información ciudadana: 972 419 010. Centralita: 972 419 000.',
                'Horario: de lunes a jueves de 8:30 a 18:00; viernes de 8:30 a 15:00; <b>sábados de 9:00 a 14:00</b>.',
                'Del <b>15 de junio al 15 de septiembre</b>: de lunes a viernes de 8:30 a 15:00 y sábados de 9:00 a 14:00.',
                'Por las tardes, los sábados y en las oficinas de barrio se atiende <b>solo con cita previa</b>.'],
            f: 'La cita se pide en web.girona.cat/citaprevia.' },
      ca: { h: "L'<b>Oficina d'Assistència en Matèria de Registre (OAMR)</b> és a la plaça del Vi, 1, 17004 Girona.",
            l: ['Telèfon d\'informació ciutadana: 972 419 010. Centraleta: 972 419 000.',
                'Horari: de dilluns a dijous de 8:30 a 18:00; divendres de 8:30 a 15:00; <b>dissabtes de 9:00 a 14:00</b>.',
                'Del <b>15 de juny al 15 de setembre</b>: de dilluns a divendres de 8:30 a 15:00 i dissabtes de 9:00 a 14:00.',
                'A les tardes, els dissabtes i a les oficines de barri s\'atén <b>només amb cita prèvia</b>.'],
            f: 'La cita es demana a web.girona.cat/citaprevia.' },
      s: { t: "Horaris d'informació ciutadana — OAMR, girona.cat", u: 'https://web.girona.cat/oamr/mesaprop' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me'],
      es: { h: 'Los trámites del <b>padró municipal d\'habitants</b> se hacen en la OAMR, plaça del Vi, 1.',
            l: ['Para los trámites de padrón se <b>recomienda pedir cita previa</b>: se atiende primero a quien la lleva.',
                'La atención sin cita es limitada.'],
            f: 'La documentación depende de su caso. Confírmela en el 972 419 010 antes de desplazarse.' },
      ca: { h: "Els tràmits del <b>padró municipal d'habitants</b> es fan a l'OAMR, plaça del Vi, 1.",
            l: ['Per als tràmits de padró es <b>recomana demanar cita prèvia</b>: s\'atén primer qui la porta.',
                "L'atenció sense cita és limitada."],
            f: 'La documentació depèn del seu cas. Confirmeu-la al 972 419 010 abans de desplaçar-vos.' },
      s: { t: "Padró municipal d'habitants — girona.cat", u: 'https://web.girona.cat/poblacio/padro' },
    },
    {
      k: ['certificado', 'certificado de empadronamiento', 'volante', 'acreditar residencia', 'preinscripcion', 'colegio', 'escuela', 'curso escolar',
          'certificat', "certificat d empadronament", 'volant', 'preinscripcio', 'escola', 'curs escolar'],
      es: { h: 'Para el <b>volante o certificado de empadronamiento</b> destinado a las <b>preinscripciones del curso escolar</b> <b>no hace falta cita previa</b>.',
            l: ['Para el resto de trámites de padrón, la cita sí es recomendable.',
                'También se pueden consultar en la carpeta ciutadana de seu.girona.cat.'],
            f: 'Dudas: 972 419 010.' },
      ca: { h: "Per al <b>volant o certificat d'empadronament</b> destinat a les <b>preinscripcions del curs escolar</b> <b>no cal demanar cita prèvia</b>.",
            l: ['Per a la resta de tràmits de padró, la cita sí que és recomanable.',
                'També es poden consultar a la carpeta ciutadana de seu.girona.cat.'],
            f: 'Dubtes: 972 419 010.' },
      s: { t: 'No cal cita prèvia per al volant o certificat per a preinscripcions — girona.cat', u: 'https://web.girona.cat/oamr' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'carpeta ciudadana', 'cita', 'cita previa', 'pedir cita', 'registro',
          'seu electronica', 'tramit', 'tramits', 'per internet', 'carpeta ciutadana', 'cita previa', 'demanar cita'],
      es: { h: 'La <b>seu electrònica</b> está en seu.girona.cat y la <b>cita previa</b> en web.girona.cat/citaprevia.',
            l: ['En la carpeta ciutadana de la seu está el apartado de padró d\'habitants.',
                'Los trámites destacados están en web.girona.cat/tramits.'],
            f: 'Dudas: 972 419 010 o ajuntamentinforma@ajgirona.cat.' },
      ca: { h: 'La <b>seu electrònica</b> és a seu.girona.cat i la <b>cita prèvia</b> a web.girona.cat/citaprevia.',
            l: ["A la carpeta ciutadana de la seu hi ha l'apartat de padró d'habitants.",
                'Els tràmits destacats són a web.girona.cat/tramits.'],
            f: 'Dubtes: 972 419 010 o ajuntamentinforma@ajgirona.cat.' },
      s: { t: 'Seu electrònica — Ajuntament de Girona', u: 'https://seu.girona.cat/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Girona?' },
    { lang: 'CA', t: 'Obren els dissabtes?' },
    { lang: 'ES', t: '¿Piden cita?' },
    { lang: 'ES', t: '¿Cómo pido el certificado de empadronamiento?' },
    { lang: 'ES', t: '¿Dónde está la OAMR y qué horario tiene?' },
  ],
},

// ===========================================================================
{
  slug: 'el-prat-de-llobregat',
  nombre: 'El Prat de Llobregat',
  articulo: 'del Prat de Llobregat',
  dominios: 'elprat.cat y seu.elprat.cat',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: "l'OIAC", tel: '93 379 00 50', email: 'oac360@elprat.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OIAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oiac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'placa de la vila',
          'atencio ciutadana', 'adreca', 'horari', 'a quina hora obren', 'telefon'],
      es: { h: "L'<b>Oficina d'Informació i Atenció Ciutadana (OIAC)</b> está en la plaça de la Vila, 1.",
            l: ['Teléfono: 93 379 00 50.',
                'Horario: de lunes a viernes de 9:00 a 13:30, y de lunes a jueves de 16:30 a 19:00.',
                'Del <b>1 de julio al 31 de agosto</b>: de lunes a viernes de 9:00 a 14:00.',
                'Cerrado las tardes de Jueves Santo y los días 24 y 31 de diciembre.'],
            f: 'También existe el <b>OAC 360</b>, atención telefónica en el 93 595 44 14 de lunes a viernes de 8:00 a 20:00.' },
      ca: { h: "L'<b>Oficina d'Informació i Atenció Ciutadana (OIAC)</b> és a la plaça de la Vila, 1.",
            l: ['Telèfon: 93 379 00 50.',
                'Horari: de dilluns a divendres de 9:00 a 13:30, i de dilluns a dijous de 16:30 a 19:00.',
                "De l'<b>1 de juliol al 31 d'agost</b>: de dilluns a divendres de 9:00 a 14:00."],
            f: "També hi ha l'<b>OAC 360</b>, atenció telefònica al 93 595 44 14 de dilluns a divendres de 8:00 a 20:00." },
      s: { t: "Oficina d'Informació i Atenció Ciutadana (OIAC) — elprat.cat", u: 'https://www.elprat.cat/administracio-govern-i-ciutat/atencio-ciutadana/oficina-dinformacio-i-atencio-ciutadana-oiac' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'sin cita', 'hace falta cita', 'necesito cita', 'turno',
          'cita previa', 'demanar cita', 'sense cita', 'cal cita'],
      es: { h: '<b>No hace falta cita</b> para recoger un certificado o volante de empadronamiento, las tarjetas de transporte o cualquier documentación que no lleve un pago asociado.',
            l: ['En esos casos se puede ir directamente a la OIAC y se le atiende.',
                'Para el resto, la cita se pide en elprat.cat/demana-cita-previa.',
                'Hay que pedir <b>una cita por cada trámite distinto</b>.'],
            f: 'Dudas: 93 379 00 50 o el OAC 360 en el 93 595 44 14.' },
      ca: { h: "<b>No cal cita</b> per recollir un certificat o volant d'empadronament, les targetes de transport o qualsevol documentació que no porti un pagament associat.",
            l: ["En aquests casos es pot anar directament a l'OIAC i s'hi atén.",
                'Per a la resta, la cita es demana a elprat.cat/demana-cita-previa.',
                'Cal demanar <b>una cita per cada tràmit diferent</b>.'],
            f: "Dubtes: 93 379 00 50 o l'OAC 360 al 93 595 44 14." },
      s: { t: 'Demana cita prèvia — elprat.cat', u: 'https://www.elprat.cat/demana-cita-previa' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'nacimiento', 'recien nacido',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me', 'naixement'],
      es: { h: 'El <b>padró municipal d\'habitants</b> se tramita en la OIAC o en la seu electrònica.',
            l: ['Tienen ficha propia el alta en el padrón, el <b>alta por nacimiento</b> y el cambio de domicilio.',
                'Cada una está en seu.elprat.cat con su documentación.'],
            f: 'La documentación depende de su caso. Confírmela en el 93 379 00 50 antes de desplazarse.' },
      ca: { h: "El <b>padró municipal d'habitants</b> es tramita a l'OIAC o a la seu electrònica.",
            l: ["Tenen fitxa pròpia l'alta al padró, l'<b>alta per naixement</b> i el canvi de domicili.",
                'Cadascuna és a seu.elprat.cat amb la seva documentació.'],
            f: 'La documentació depèn del seu cas. Confirmeu-la al 93 379 00 50 abans de desplaçar-vos.' },
      s: { t: "Alta en el Padró Municipal d'Habitants — seu.elprat.cat", u: 'https://seu.elprat.cat/siac/ProcedimientoTabs.aspx?tab=1&idProc=29&idnct=206&x=%2FqpB0Jegt4IcXDFg3DsQJw' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'certificado', 'volante', 'registro',
          'seu electronica', 'tramit', 'tramits', 'per internet', 'cataleg', 'certificat', 'volant'],
      es: { h: 'La <b>seu electrònica</b> está en seu.elprat.cat.',
            l: ['Ahí está el catálogo de trámites, incluido el certificado de empadronamiento anterior al 1 de abril de 1986, que va aparte.'],
            f: 'Si se atasca con un trámite en línea, el OAC 360 ayuda: 93 595 44 14 o oac360@elprat.cat.' },
      ca: { h: 'La <b>seu electrònica</b> és a seu.elprat.cat.',
            l: ["Hi ha el catàleg de tràmits, inclòs el certificat d'empadronament anterior a l'1 d'abril de 1986, que va a part."],
            f: "Si us encalleu amb un tràmit en línia, l'OAC 360 ajuda: 93 595 44 14 o oac360@elprat.cat." },
      s: { t: "Seu electrònica de l'Ajuntament del Prat de Llobregat", u: 'https://seu.elprat.cat/siac/Info.aspx?info=Contacte' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en el Prat?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'CA', t: 'Cal cita per recollir un volant?' },
    { lang: 'ES', t: '¿Cuál es el teléfono?' },
    { lang: 'ES', t: '¿Qué horario tiene el registro?' },
  ],
},

// ===========================================================================
{
  slug: 'sant-feliu-de-llobregat',
  nombre: 'Sant Feliu de Llobregat',
  articulo: 'de Sant Feliu de Llobregat',
  dominios: 'santfeliu.cat',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: "l'OAC", tel: '93 685 80 01', email: 'oac@santfeliu.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'placa de la vila', 'laujar',
          'atencio ciutadana', 'adreca', 'horari', 'a quina hora obren', 'telefon'],
      es: { h: "L'<b>Oficina d'Atenció Ciutadana (OAC)</b> tiene dos sedes: la plaça de la Vila, 1, y la plaça de Laujar de Andarax, s/n.",
            l: ['Teléfono: 93 685 80 01. Correo: oac@santfeliu.cat.',
                'Horario: de <b>lunes a viernes no festivos, de 8:00 a 20:00</b>.'],
            f: 'Es un horario largo para una OAC: se puede ir a primera hora o a última sin problema.' },
      ca: { h: "L'<b>Oficina d'Atenció Ciutadana (OAC)</b> té dues seus: la plaça de la Vila, 1, i la plaça de Laujar de Andarax, s/n.",
            l: ['Telèfon: 93 685 80 01. Correu: oac@santfeliu.cat.',
                'Horari: de <b>dilluns a divendres no festius, de 8:00 a 20:00</b>.'],
            f: "És un horari llarg per a una OAC: s'hi pot anar a primera hora o a última sense problema." },
      s: { t: "Oficina d'Atenció Ciutadana (OAC) — santfeliu.cat", u: 'https://www.santfeliu.cat/go.faces?xmid=24374&caseid=sf:10299' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'certificado', 'volante',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me', 'certificat', 'volant'],
      es: { h: 'Los trámites de <b>padró municipal</b> se hacen en la OAC, que es la ventanilla única del Ayuntamiento.',
            l: ['Plaça de la Vila, 1, o plaça de Laujar de Andarax, s/n, de 8:00 a 20:00.'],
            f: 'La documentación depende de su caso. Confírmela en el 93 685 80 01 o en oac@santfeliu.cat antes de desplazarse.' },
      ca: { h: "Els tràmits de <b>padró municipal</b> es fan a l'OAC, que és la finestreta única de l'Ajuntament.",
            l: ['Plaça de la Vila, 1, o plaça de Laujar de Andarax, s/n, de 8:00 a 20:00.'],
            f: 'La documentació depèn del seu cas. Confirmeu-la al 93 685 80 01 o a oac@santfeliu.cat abans de desplaçar-vos.' },
      s: { t: 'Tots els serveis de l\'OAC — santfeliu.cat', u: 'https://santfeliu.cat/oac' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'videollamada', 'videotrucada', 'atencion telematica',
          'cita previa', 'demanar cita'],
      es: { h: 'Para la atención <b>por videollamada</b> hay que pedir cita previa.',
            l: ['La atención presencial en la OAC está publicada como horario abierto, de 8:00 a 20:00.'],
            f: 'Si no le queda claro qué le toca, llame al 93 685 80 01.' },
      ca: { h: "Per a l'atenció <b>per videotrucada</b> cal demanar cita prèvia.",
            l: ["L'atenció presencial a l'OAC està publicada com a horari obert, de 8:00 a 20:00."],
            f: 'Si no us queda clar què us toca, telefoneu al 93 685 80 01.' },
      s: { t: 'Atenció presencial — santfeliu.cat', u: 'https://www.santfeliu.cat/go.faces?xmid=35623' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'registro',
          'seu electronica', 'tramit', 'tramits', 'per internet', 'cataleg'],
      es: { h: 'El <b>catálogo de trámites</b> del Ayuntamiento está publicado en santfeliu.cat.',
            l: [],
            f: 'Dudas: 93 685 80 01 o oac@santfeliu.cat.' },
      ca: { h: "El <b>catàleg de tràmits</b> de l'Ajuntament està publicat a santfeliu.cat.",
            l: [],
            f: 'Dubtes: 93 685 80 01 o oac@santfeliu.cat.' },
      s: { t: "Catàleg de tràmits — Ajuntament de Sant Feliu de Llobregat", u: 'https://www.santfeliu.cat/go.faces?xmid=23240&caseid=sf:9807' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Sant Feliu?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'ES', t: '¿Hace falta cita previa?' },
    { lang: 'CA', t: 'Fins a quina hora obre l\'OAC?' },
    { lang: 'ES', t: '¿Dónde está la OAC?' },
  ],
},

// ===========================================================================
{
  slug: 'alzira',
  nombre: 'Alzira',
  articulo: "d'Alzira",
  dominios: 'alzira.es y sedeelectronica.alzira.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'La Clau', tel: '960 70 43 48', email: 'ajuntament@alzira.es' },
  idioma2: { cod: 'VA', clave: 'va', sigla: 'a La Clau', nombre: 'valenciano', sufijo: 'va' },
  kb: [
    {
      k: ['clau', 'la clau', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'rambla',
          'atencio ciutadana', 'adreca', 'horari', 'a quina hora obrin', 'telefon'],
      es: { h: "La Oficina d'Atenció Ciutadana de Alzira se llama <b>La Clau</b> y está en el carrer Rambla, 23.",
            l: ['Es la planta baja del edificio de Benestar Social, junto a IDEA, enfrente del colegio Purísima.',
                'Teléfono: 960 70 43 48.',
                'Horario: lunes, jueves y viernes de 9:00 a 14:00. <b>Martes y miércoles de 9:00 a 18:00</b>, ininterrumpido.'],
            f: 'La cita previa se pide en citaprevia.alzira.es.' },
      va: { h: "L'Oficina d'Atenció Ciutadana d'Alzira es diu <b>La Clau</b> i està al carrer Rambla, 23.",
            l: ["És la planta baixa de l'edifici de Benestar Social, al costat d'IDEA, enfront del col·legi Puríssima.",
                'Telèfon: 960 70 43 48.',
                'Horari: dilluns, dijous i divendres de 9:00 a 14:00. <b>Dimarts i dimecres de 9:00 a 18:00</b>, ininterromput.'],
            f: 'La cita prèvia es demana a citaprevia.alzira.es.' },
      s: { t: "L'Ajuntament posa en funcionament CLAU, l'Oficina d'Atenció Ciutadana — alzira.es", u: 'http://www.alzira.es/alzira_vpm/index.php/es/noticias/6678-l-ajuntament-d-alzira-posa-en-funcionament-este-dimecres-clau-l-oficina-d-atencio-ciutadana' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'certificado', 'volante', 'historico', 'colectivo',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me', 'certificat', 'volant', 'historic', 'col lectiu'],
      es: { h: 'Los trámites de <b>padró</b> y los certificados <b>histórico y colectivo</b> del Padró Municipal d\'Habitants se hacen en La Clau.',
            l: ['Carrer Rambla, 23, <b>preferentemente con cita previa</b>.',
                'La cita se pide en citaprevia.alzira.es.'],
            f: 'La documentación depende de su caso. Confírmela en el 960 70 43 48 antes de desplazarse.' },
      va: { h: "Els tràmits de <b>padró</b> i els certificats <b>històric i col·lectiu</b> del Padró Municipal d'Habitants es fan a La Clau.",
            l: ['Carrer Rambla, 23, <b>preferentment amb cita prèvia</b>.',
                'La cita es demana a citaprevia.alzira.es.'],
            f: 'La documentació depèn del seu cas. Confirme-la al 960 70 43 48 abans de desplaçar-se.' },
      s: { t: "La Clau amplia el seu servei incloent la cita prèvia — alzira.es", u: 'https://alzira.es/es/la-clau-amplia-el-seu-servei-incloent-la-cita-previa-3/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'turno',
          'cita previa', 'demanar cita'],
      es: { h: 'La <b>cita previa</b> se pide en citaprevia.alzira.es.',
            l: ['Las citas se dan los martes y miércoles de 15:00 a 17:30.'],
            f: 'Si el sistema no le da hueco, llame al 960 70 43 48.' },
      va: { h: 'La <b>cita prèvia</b> es demana a citaprevia.alzira.es.',
            l: ['Les cites es donen els dimarts i dimecres de 15:00 a 17:30.'],
            f: 'Si el sistema no li dona hora, telefone al 960 70 43 48.' },
      s: { t: "Cita Previa — Ajuntament d'Alzira", u: 'https://alzira.es/es/servicios-municipales/cita-previa/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'carpeta ciudadana', 'registro', 'notificaciones', 'factura',
          'seu electronica', 'tramit', 'tramits', 'per internet', 'cataleg', 'carpeta ciutadana', 'notificacions'],
      es: { h: 'La <b>sede electrónica</b> está en sedeelectronica.alzira.es.',
            l: ['Incluye oficina virtual, tributos, factura electrónica, impresos y solicitudes, notificaciones electrónicas, carpeta ciudadana y registro electrónico de entrada.'],
            f: 'Dudas: 960 70 43 48 o ajuntament@alzira.es.' },
      va: { h: 'La <b>seu electrònica</b> està a sedeelectronica.alzira.es.',
            l: ['Inclou oficina virtual, tributs, factura electrònica, impresos i sol·licituds, notificacions electròniques, carpeta ciutadana i registre electrònic d\'entrada.'],
            f: 'Dubtes: 960 70 43 48 o ajuntament@alzira.es.' },
      s: { t: "Sede electrónica — Ajuntament d'Alzira", u: 'https://alzira.es/es/sede-electronica/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Alzira?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'VA', t: 'Quin horari té La Clau?' },
    { lang: 'ES', t: '¿Cómo pido cita previa?' },
    { lang: 'ES', t: '¿Dónde pido el volante?' },
  ],
},

// ===========================================================================
{
  slug: 'torrelavega',
  nombre: 'Torrelavega',
  articulo: 'de Torrelavega',
  dominios: 'torrelavega.es y sede.torrelavega.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el Registro General', tel: '942 81 20 01', email: 'info@aytotorrelavega.es' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'atencion ciudadana', 'registro', 'registro general', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'contacto', 'la llama', 'demetrio herrero'],
      es: { h: 'El <b>Registro General</b> está en el Edificio Municipal La Llama.',
            l: ['Dirección del Ayuntamiento: L. Demetrio Herrero, 4, Torrelavega (Cantabria).',
                'Horario de atención al público: de <b>lunes a viernes de 9:00 a 14:00</b>.',
                'Correo: info@aytotorrelavega.es.'],
            f: 'Antes de ir, conviene mirar en torrelavega.es si esa oficina sigue en La Llama.' },
      s: { t: 'Registro General (Edificio Municipal La Llama) — torrelavega.es', u: 'https://torrelavega.es/servicios-al-ciudadano/oficinas-de-registro-municipal/registro-s/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'sin cita', 'turno', 'cola', 'orden de llegada', 'hace falta cita', 'necesito cita'],
      es: { h: 'En el <b>Registro General y en el Padrón</b> se atiende <b>por orden de llegada</b>, con sistema de cola.',
            l: ['Es decir: para esos dos, no hace falta cita previa.',
                'Para el resto de trámites, el Ayuntamiento tiene servicio de cita previa en torrelavega.es y en sede.torrelavega.es.',
                'Al pedirla se elige día y hora entre los disponibles y llega un correo de confirmación.'],
            f: 'Dudas: info@aytotorrelavega.es.' },
      s: { t: 'Entra en funcionamiento la atención presencial por orden de llegada — torrelavega.es', u: 'https://torrelavega.es/noticia/entra-en-funcionamiento-la-atencion-presencial-por-orden-de-llegada-sistema-de-cola-en-el-registro-general-y-en-el-padron/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'certificado', 'volante', 'instrucciones'],
      es: { h: 'El Ayuntamiento publica unas <b>instrucciones generales de empadronamiento</b> en su web.',
            l: ['La atención presencial del Padrón es <b>por orden de llegada</b>, de 9:00 a 14:00.'],
            f: 'La documentación depende de su caso: mírela en torrelavega.es/instrucciones-generales-de-empadronamiento antes de ir, o pregunte en info@aytotorrelavega.es.' },
      s: { t: 'Instrucciones generales de empadronamiento — torrelavega.es', u: 'https://torrelavega.es/instrucciones-generales-de-empadronamiento/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'oficinas de asistencia'],
      es: { h: 'La <b>sede electrónica</b> está en sede.torrelavega.es.',
            l: ['Ahí están también las oficinas de asistencia en materia de registro y la solicitud de cita previa.'],
            f: 'Dudas: info@aytotorrelavega.es.' },
      s: { t: 'Sede electrónica — Ayuntamiento de Torrelavega', u: 'https://sede.torrelavega.es/sta/CarpetaPublic/doEvent?APP_CODE=STA&PAGE_CODE=PTS2_HOME' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Torrelavega?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'ES', t: '¿Hace falta cita previa para el padrón?' },
    { lang: 'ES', t: '¿Dónde está el Registro General?' },
  ],
},

// ===========================================================================
{
  slug: 'ecija',
  nombre: 'Écija',
  articulo: 'de Écija',
  dominios: 'ecija.es y portal.ecija.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'la oficina del Mercado de Abastos', tel: '95 590 00 00', email: 'participacionciudadana@ecija.es' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'mercado de abastos', 'ayuntamiento'],
      es: { h: 'Las oficinas municipales del <b>Mercado de Abastos</b> abren de <b>lunes a viernes de 9:00 a 14:00</b>.',
            l: ['Teléfono: 95 590 00 00.'],
            f: 'Correo de participación ciudadana: participacionciudadana@ecija.es.' },
      s: { t: 'Gobierno municipal — ecija.es', u: 'https://www.ecija.es/ayuntamiento/gobierno-municipal' },
    },
    {
      k: ['certificado', 'certificado de empadronamiento', 'certificado padron', 'volante', 'acreditar residencia', 'online', 'digital', 'al momento', 'inmediato'],
      es: { h: 'El <b>certificado de empadronamiento digital</b> se saca por internet, al momento y <b>las 24 horas</b>.',
            l: ['Se piden y se obtienen certificados y volantes de forma inmediata desde una aplicación de la web municipal.',
                'También se puede consultar la propia hoja padronal.',
                'En papel existe además un impreso de solicitud de certificado de empadronamiento en ecija.es.'],
            f: 'Si el sistema no le responde, llame al 95 590 00 00.' },
      s: { t: 'Ya está disponible el certificado de empadronamiento digital online — ecija.es', u: 'https://www.ecija.es/noticia/ya_est_disponible_el_certificado_de_empadronamiento_digital_on_line' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'hoja padronal'],
      es: { h: 'El <b>Padrón de Habitantes</b> tiene su propio apartado en la sede electrónica, en portal.ecija.es.',
            l: ['Desde ahí se expiden certificados de empadronamiento y se consultan los datos personales del padrón y la hoja padronal.'],
            f: 'La documentación del alta depende de su caso. Confírmela en el 95 590 00 00 antes de desplazarse.' },
      s: { t: 'Padrón de Habitantes — Sede Electrónica de Écija', u: 'https://portal.ecija.es:10443/portal/pestana.do?pes_cod=-2&ent_id=1&idioma=1' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'anular cita', 'turno', 'sede electronica', 'tramite', 'tramites', 'internet', 'por internet', 'catalogo', 'impresos'],
      es: { h: 'La <b>cita previa</b> se pide en ecija.es/citaprevia.php, donde también se puede anular o consultar.',
            l: ['La <b>sede electrónica</b> está en portal.ecija.es, con el catálogo de trámites.',
                'Los impresos oficiales de solicitud están publicados en ecija.es.'],
            f: 'Dudas: 95 590 00 00.' },
      s: { t: 'Cita Previa — Ayuntamiento de Écija', u: 'https://www.ecija.es/citaprevia.php' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Écija?' },
    { lang: 'ES', t: '¿Dónde está la oficina de atención ciudadana?' },
    { lang: 'ES', t: '¿Cómo consigo un certificado de empadronamiento?' },
    { lang: 'ES', t: '¿Cómo pido cita previa?' },
  ],
},

// ===========================================================================
{
  slug: 'san-fernando-de-henares',
  nombre: 'San Fernando de Henares',
  articulo: 'de San Fernando de Henares',
  dominios: 'ayto-sanfernando.com',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el Ayuntamiento', tel: '91 627 67 00', email: 'informacion@ayto-sanfernando.com' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'atencion ciudadana', 'ayuntamiento', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'plaza de espana'],
      es: { h: 'El Ayuntamiento está en la <b>plaza de España, s/n</b>.',
            l: ['Teléfono: 91 627 67 00. Correo: informacion@ayto-sanfernando.com.',
                'El horario de atención al público del <b>padrón</b> es de <b>lunes a viernes de 9:00 a 14:00</b>.'],
            f: 'Los teléfonos y direcciones de las distintas áreas están publicados en ayto-sanfernando.com.' },
      s: { t: 'Teléfonos y direcciones de interés — ayto-sanfernando.com', u: 'https://www.ayto-sanfernando.com/telefonos-y-direcciones-de-interes/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'baja', 'modificacion'],
      es: { h: 'El <b>padrón municipal de habitantes</b> se atiende de lunes a viernes de 9:00 a 14:00, y con <b>cita previa</b>.',
            l: ['La cita cubre volantes, certificados de empadronamiento y altas, bajas y modificaciones.',
                'Se pide por teléfono en el 91 627 67 00 o en ayto-sanfernando.com, eligiendo día y hora entre los disponibles.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 91 627 67 00 antes de desplazarse.' },
      s: { t: 'Padrón municipal de habitantes — ayto-sanfernando.com', u: 'https://www.ayto-sanfernando.com/padron/' },
    },
    {
      k: ['certificado', 'certificado de empadronamiento', 'volante', 'acreditar residencia', 'historico', 'individual', 'carpeta ciudadana', 'certificado electronico', 'certificado digital'],
      es: { h: 'Con <b>certificado electrónico</b> el padrón se saca sin ir: por la sede electrónica, el registro electrónico o la <b>carpeta ciudadana</b>.',
            l: ['Desde la carpeta ciudadana se accede al <b>padrón histórico</b> y al <b>padrón individual</b>, que es el documento que acredita el empadronamiento.'],
            f: 'Si no tiene certificado electrónico, hay que pedir cita: 91 627 67 00.' },
      s: { t: 'Ya puedes solicitar el padrón online desde la Sede Electrónica — ayto-sanfernando.com', u: 'https://www.ayto-sanfernando.com/ya-puedes-solicitar-el-padron-online-desde-la-sede-electronica-del-ayuntamiento/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'turno', 'sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet'],
      es: { h: 'La <b>cita previa</b> se pide de dos maneras: por teléfono en el <b>91 627 67 00</b> o por internet en ayto-sanfernando.com.',
            l: ['Los trámites están en ayto-sanfernando.com/tramites y la carpeta ciudadana en ayto-sanfernando.com/carpeta-ciudadana.'],
            f: 'Dudas: informacion@ayto-sanfernando.com.' },
      s: { t: 'El Ayuntamiento pone en marcha el servicio de cita previa — ayto-sanfernando.com', u: 'https://www.ayto-sanfernando.com/el-ayuntamiento-de-san-fernando-de-henares-pone-en-marcha-un-nuevo-servicio-de-cita-previa/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en San Fernando de Henares?' },
    { lang: 'ES', t: '¿Cómo pido cita previa?' },
    { lang: 'ES', t: '¿Qué días abren?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'ES', t: '¿Cuál es el teléfono?' },
  ],
},

// ===========================================================================
{
  slug: 'la-rinconada',
  nombre: 'La Rinconada',
  articulo: 'de La Rinconada',
  dominios: 'larinconada.es y larinconada.sedelectronica.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el SAC', tel: '954 79 24 13', email: 'participacion@aytolarinconada.es' },
  idioma2: null,
  kb: [
    {
      k: ['sac', 'oficina', 'atencion al ciudadano', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'pepe iglesias'],
      es: { h: 'El <b>Servicio de Atención al Ciudadano (SAC)</b> está en la calle Alcalde Pepe Iglesias.',
            l: ['Teléfono: 954 79 24 13. Correo: participacion@aytolarinconada.es.',
                'Horario: de <b>lunes a viernes de 10:00 a 14:00</b>, tanto en la oficina como por teléfono.'],
            f: 'El SAC canaliza quejas, sugerencias y peticiones de información, y las traslada a la delegación municipal que corresponda.' },
      s: { t: 'SAC — larinconada.es', u: 'https://www.larinconada.es/es/servicios/sac' },
    },
    {
      k: ['queja', 'quejas', 'sugerencia', 'sugerencias', 'reclamacion', 'reclamar', 'protesta', 'buzon', 'peticion'],
      es: { h: 'Las <b>quejas y sugerencias</b> se presentan en el SAC, que las traslada a la delegación municipal competente.',
            l: ['También canaliza demandas de información o de servicios.'],
            f: 'Calle Alcalde Pepe Iglesias, de 10:00 a 14:00, o en el 954 79 24 13.' },
      s: { t: 'SAC — larinconada.es', u: 'https://www.larinconada.es/es/servicios/sac' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'certificado', 'volante'],
      es: { h: 'Los trámites de <b>padrón</b> se presentan por la sede electrónica, en larinconada.sedelectronica.es, o preguntando en el SAC.',
            l: ['El SAC atiende de lunes a viernes de 10:00 a 14:00 en el 954 79 24 13.'],
            f: 'La documentación concreta no está publicada en la ficha del SAC: confírmela en el 954 79 24 13 antes de desplazarse.' },
      s: { t: 'Sede electrónica — Ayuntamiento de La Rinconada', u: 'https://larinconada.sedelectronica.es/info.2' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'registro', 'instancia'],
      es: { h: 'La <b>sede electrónica</b> está en larinconada.sedelectronica.es.',
            l: ['Desde ahí se presentan instancias y se consulta el estado de los expedientes.'],
            f: 'Dudas: 954 79 24 13 o participacion@aytolarinconada.es.' },
      s: { t: 'Sede electrónica — Ayuntamiento de La Rinconada', u: 'https://larinconada.sedelectronica.es/info.2' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en La Rinconada?' },
    { lang: 'ES', t: '¿Puedo pedir el volante por internet?' },
    { lang: 'ES', t: '¿Dónde está el SAC y qué horario tiene?' },
    { lang: 'ES', t: '¿Cómo pongo una queja o una sugerencia?' },
  ],
},

];
