// ---------------------------------------------------------------------------
//  LOS OCHO DEL NOVENO ENVIO — jueves 24 de septiembre de 2026.
//  Comprobado en cada web municipal el 7 de septiembre de 2026.
//
//  Seis de Bizkaia en euskera, Eivissa en catalan y Granadilla en castellano.
//  Los seis vascos estaban en "revisar": se comprobo con detectar-chatbot.mjs
//  que ninguno tiene widget de chatbot en su portada.
//
//  El euskera de estas fichas se ha dejado a proposito en frases cortas y
//  datos —direcciones, telefonos, horarios—, que es donde el riesgo de sonar
//  a traduccion es menor. Antes de enviar conviene que lo lea alguien que lo
//  hable: un correo a un ayuntamiento vasco con euskera regular hace mas dano
//  que uno solo en castellano.
// ---------------------------------------------------------------------------

export const MUNICIPIOS_DIA09 = [

// ===========================================================================
{
  slug: 'barakaldo',
  nombre: 'Barakaldo',
  articulo: 'de Barakaldo',
  dominios: 'barakaldo.eus',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el SAC', tel: '010 o 944 789 200', email: 'haz-sac@barakaldo.eus' },
  idioma2: { cod: 'EU', clave: 'eu', sigla: 'SAC bulegoa (Herriko Plaza 1)', nombre: 'euskera' },
  kb: [
    {
      k: ['sac', 'haz', 'oficina', 'oficinas', 'atencion ciudadana', 'direccion', 'telefono', 'contacto', 'herriko plaza', 'cruces', 'san vicente',
          'bulegoa', 'telefonoa', 'helbidea'],
      es: { h: 'El <b>Servicio de Atención Ciudadana (SAC)</b> está en Herriko Plaza, 1 — 48901 Barakaldo.',
            l: ['Teléfonos: el <b>010</b> desde Barakaldo, o el 944 789 200.',
                'Hay atención presencial en dos puntos: el centro de Barakaldo, en el barrio de San Vicente, y el barrio de Cruces.'],
            f: 'Antes de ir, en el 010 le dicen qué documentación necesita.' },
      eu: { h: '<b>Herritarrentzako Arreta Zerbitzua (SAC)</b> Herriko Plaza 1ean dago — 48901 Barakaldo.',
            l: ['Telefonoak: <b>010</b> Barakaldotik, edo 944 789 200.',
                'Aurrez aurreko arreta bi puntutan: Barakaldoko erdigunean, San Bizente auzoan, eta Gurutzeta auzoan.'],
            f: 'Joan aurretik, 010 telefonoan esaten dizute zer dokumentazio behar duzun.' },
      s: { t: 'Servicio de Atención Ciudadana (SAC) — barakaldo.eus', u: 'https://www.barakaldo.eus/portal/en/web/el-ayuntamiento/atencion-al-ciudadano' },
    },
    {
      k: ['oficina electronica', 'oficinas electronicas', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'domingo', 'festivo', 'casa consistorial', '22:00',
          'ordutegia', 'igandea', 'jaieguna'],
      es: { h: 'La <b>oficina electrónica</b> de la Casa Consistorial abre <b>todos los días, festivos incluidos, de 8:00 a 22:00</b>.',
            l: ['Está en Herriko Plaza, 1.',
                'Desde ella se emiten certificados de empadronamiento: individuales, históricos y colectivos o familiares.'],
            f: 'Catorce horas al día, siete días a la semana: es el canal más amplio que tiene el Ayuntamiento.' },
      eu: { h: 'Udaletxeko <b>bulego elektronikoa</b> <b>egunero</b> irekitzen da, jaiegunak barne, <b>8:00etatik 22:00etara</b>.',
            l: ['Herriko Plaza 1ean dago.',
                'Bertatik errolda-ziurtagiriak ematen dira: banakakoak, historikoak eta kolektiboak edo familiakoak.'],
            f: 'Hamalau ordu egunean, astean zazpi egunez: Udalak duen kanalik zabalena.' },
      s: { t: 'Oficinas electrónicas — barakaldo.eus', u: 'https://www.barakaldo.eus/portal/en/web/el-ayuntamiento/sac/oficinas-electronicas' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'colectivo', 'historico',
          'errolda', 'erroldatu', 'ziurtagiria'],
      es: { h: 'Los <b>certificados de empadronamiento</b> se pueden sacar en las oficinas electrónicas.',
            l: ['Individuales, históricos y colectivos o familiares.',
                'El SAC tramita además informes de habitabilidad de vivienda para reagrupación familiar e informes de integración social.'],
            f: 'Para saber qué documentación le piden en su caso: 010, o 944 789 200.' },
      eu: { h: '<b>Errolda-ziurtagiriak</b> bulego elektronikoetan atera daitezke.',
            l: ['Banakakoak, historikoak eta kolektiboak edo familiakoak.',
                'SACek etxebizitzaren bizigarritasun-txostenak ere izapidetzen ditu, familia berrelkartzeko, eta gizarteratze-txostenak.'],
            f: 'Zure kasuan zer dokumentazio eskatzen duten jakiteko: 010, edo 944 789 200.' },
      s: { t: 'Oficinas electrónicas — barakaldo.eus', u: 'https://www.barakaldo.eus/portal/en/web/el-ayuntamiento/sac/oficinas-electronicas' },
    },
    {
      k: ['telefono 010', 'atencion telefonica', 'llamar', 'por telefono',
          'telefonoz', 'deitu'],
      es: { h: 'El <b>010</b> es el servicio de atención telefónica del Ayuntamiento.',
            l: ['Desde fuera de Barakaldo: 944 789 200.',
                'Informa sobre servicios municipales, trámites y el estado de los expedientes.'],
            f: 'Es el mismo servicio que atiende presencialmente en San Vicente y en Cruces.' },
      eu: { h: '<b>010</b> Udalaren telefono bidezko arreta zerbitzua da.',
            l: ['Barakaldotik kanpotik: 944 789 200.',
                'Udal zerbitzuei, izapideei eta espedienteen egoerari buruzko informazioa ematen du.'],
            f: 'San Bizenten eta Gurutzetan aurrez aurre artatzen duen zerbitzu bera da.' },
      s: { t: 'Servicio 010 — barakaldo.eus', u: 'https://www.barakaldo.eus/portal/en/web/el-ayuntamiento/servicio-010' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hasta qué hora abre la oficina electrónica?' },
    { lang: 'ES', t: '¿Hay atención telefónica?' },
    { lang: 'EU', t: 'Non dago SAC bulegoa?' },
    { lang: 'ES', t: '¿Cómo consigo un certificado de empadronamiento?' },
  ],
},

// ===========================================================================
{
  slug: 'santurtzi',
  nombre: 'Santurtzi',
  articulo: 'de Santurtzi',
  dominios: 'santurtzi.eus',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el SAC', tel: '010 o 94 420 58 00', email: 'sac@santurtzi.eus' },
  idioma2: { cod: 'EU', clave: 'eu', sigla: 'SAC bulegoa (Murrieta etorbidea 6)', nombre: 'euskera' },
  kb: [
    {
      k: ['sac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'murrieta',
          'bulegoa', 'ordutegia', 'telefonoa', 'helbidea'],
      es: { h: 'El <b>Servicio de Atención Ciudadana (SAC)</b> está en la avenida Murrieta, 6 — 48980 Santurtzi (Bizkaia).',
            l: ['Teléfonos: el <b>010</b> desde Santurtzi, o el 94 420 58 00 desde fuera.',
                'Horario de atención al público: de 9:00 a 14:00.'],
            f: 'Es un espacio contiguo al Ayuntamiento donde se hace cualquier gestión sin ir de un área a otra.' },
      eu: { h: '<b>Herritarrentzako Arreta Zerbitzua (SAC)</b> Murrieta etorbidea 6an dago — 48980 Santurtzi (Bizkaia).',
            l: ['Telefonoak: <b>010</b> Santurtzitik, edo 94 420 58 00 kanpotik.',
                'Jendaurreko ordutegia: 9:00etatik 14:00etara.'],
            f: 'Udaletxearen ondoko gunea da, edozein kudeaketa arlo batetik bestera ibili gabe egiteko.' },
      s: { t: 'Servicio de Atención Ciudadana — santurtzi.eus', u: 'https://santurtzi.eus/es-ES/informacion-ciudadania/SAC' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'anular', 'cancelar', 'reservar',
          'hitzordua', 'eskatu', 'bertan behera'],
      es: { h: 'El SAC permite <b>solicitar y anular citas previas</b>.',
            l: ['Por teléfono: el 010 desde Santurtzi, o el 94 420 58 00.',
                'O desde la web municipal.'],
            f: 'Anularla si no va a poder ir libera el hueco para otra persona.' },
      eu: { h: 'SACek <b>hitzorduak eskatu eta bertan behera uzteko</b> aukera ematen du.',
            l: ['Telefonoz: 010 Santurtzitik, edo 94 420 58 00.',
                'Edo udal webgunetik.'],
            f: 'Joan ezin bazara bertan behera uzteak beste pertsona batentzat uzten du tokia.' },
      s: { t: 'Servicio de Atención Ciudadana — santurtzi.eus', u: 'https://santurtzi.eus/es-ES/informacion-ciudadania/SAC' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'cambio de domicilio', 'gestion',
          'errolda', 'erroldatu', 'ziurtagiria'],
      es: { h: 'El SAC atiende los trámites de <b>padrón</b> junto con el resto de gestiones municipales.',
            l: ['Todo en el mismo sitio: avenida Murrieta, 6, de 9:00 a 14:00.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 010 antes de ir.' },
      eu: { h: 'SACek <b>erroldaren</b> izapideak artatzen ditu, gainerako udal kudeaketekin batera.',
            l: ['Dena leku berean: Murrieta etorbidea 6, 9:00etatik 14:00etara.'],
            f: 'Dokumentazio zehatza zure kasuaren araberakoa da. Berretsi 010 telefonoan joan aurretik.' },
      s: { t: 'Lista de procedimientos — santurtzi.eus', u: 'https://www.santurtzi.eus/es-es/tramites/paginas/lista-procedimientos.aspx' },
    },
    {
      k: ['tramites', 'tramite', 'procedimientos', 'sede electronica', 'online', 'internet', 'por internet',
          'izapideak', 'izapidea'],
      es: { h: 'La lista de <b>procedimientos</b> municipales está publicada en santurtzi.eus.',
            l: ['Desde ahí se ve qué se puede hacer por internet y qué exige ir al SAC.'],
            f: 'Dudas: el 010, o el 94 420 58 00 desde fuera de Santurtzi.' },
      eu: { h: 'Udal <b>prozeduren</b> zerrenda santurtzi.eus webgunean argitaratuta dago.',
            l: ['Handik ikusten da zer egin daitekeen internetez eta zerk eskatzen duen SACera joatea.'],
            f: 'Zalantzak: 010, edo 94 420 58 00 Santurtzitik kanpo.' },
      s: { t: 'Lista de procedimientos — santurtzi.eus', u: 'https://www.santurtzi.eus/es-es/tramites/paginas/lista-procedimientos.aspx' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Dónde está el SAC y qué horario tiene?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'EU', t: 'Nola eskatzen da hitzordua?' },
    { lang: 'ES', t: '¿Puedo hacer el padrón ahí?' },
  ],
},

// ===========================================================================
{
  slug: 'basauri',
  nombre: 'Basauri',
  articulo: 'de Basauri',
  dominios: 'basauri.eus y sede.basauri.eus',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el SAC', tel: '94 466 63 00', email: 'haz@basauri.eus' },
  idioma2: { cod: 'EU', clave: 'eu', sigla: 'SAC bulegoa (Kareaga Goikoa 52)', nombre: 'euskera' },
  kb: [
    {
      k: ['sac', 'haz', 'oficina', 'atencion ciudadana', 'direccion', 'telefono', 'contacto', 'kareaga', 'whatsapp',
          'bulegoa', 'telefonoa', 'helbidea'],
      es: { h: 'El <b>Servicio de Atención Ciudadana (SAC / HAZ)</b> está en la calle Kareaga Goikoa, 52 — 48970 Basauri.',
            l: ['Teléfono principal: 94 466 63 00.',
                'Mensajes 24 horas: 900 840 841.',
                'WhatsApp: 688 737 704.',
                'Correo: haz@basauri.eus.'],
            f: 'Tiene buzón de mensajes las 24 horas, que es raro en un ayuntamiento de este tamaño.' },
      eu: { h: '<b>Herritarrentzako Arreta Zerbitzua (HAZ)</b> Kareaga Goikoa kalea 52an dago — 48970 Basauri.',
            l: ['Telefono nagusia: 94 466 63 00.',
                '24 orduko mezuak: 900 840 841.',
                'WhatsApp: 688 737 704.',
                'Korreoa: haz@basauri.eus.'],
            f: '24 orduko mezu-erantzungailua du, tamaina honetako udal batean ohikoa ez dena.' },
      s: { t: 'Servicio Atención Ciudadana (S.A.C.) — basauri.eus', u: 'https://www.basauri.eus/es/area-de-competencia-departamentos/servicio-atencion-ciudadana-sac' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'obligatoria', 'necesaria', 'reservar', 'sin cita',
          'hitzordua', 'eskatu', 'derrigorrezkoa'],
      es: { h: 'Para cualquier trámite presencial hay que <b>reservar cita previa</b>.',
            l: ['Se pide por internet, en el servicio de solicitud de cita.',
                'Ahí se ven las oficinas y los servicios disponibles y se elige el hueco.'],
            f: 'Muchos trámites se pueden hacer por la sede electrónica <b>sin cita y sin desplazarse</b>.' },
      eu: { h: 'Aurrez aurreko edozein izapidetarako <b>hitzordua hartu behar da</b>.',
            l: ['Internetez eskatzen da, hitzordua eskatzeko zerbitzuan.',
                'Bertan ikusten dira bulegoak eta zerbitzuak, eta ordua aukeratzen da.'],
            f: 'Izapide asko egoitza elektronikotik egin daitezke, <b>hitzordurik gabe eta joan gabe</b>.' },
      s: { t: 'Cita Previa — sede.basauri.eus', u: 'https://sede.basauri.eus/index.php/es/cita-previa' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'cambio de domicilio', 'que tramites',
          'errolda', 'erroldatu', 'ziurtagiria'],
      es: { h: 'El SAC lleva el <b>Padrón Municipal de Habitantes</b> y la expedición de certificados.',
            l: ['También impuestos y pagos municipales, licencias de obra y el cementerio municipal.',
                'Y la participación ciudadana, la protección de datos y las quejas y sugerencias.'],
            f: 'Para el padrón presencial hace falta cita: se reserva en sede.basauri.eus.' },
      eu: { h: 'SACek <b>Biztanleen Udal Errolda</b> eta ziurtagirien jaulkipena kudeatzen ditu.',
            l: ['Udal zerga eta ordainketak, obra-lizentziak eta udal hilerria ere bai.',
                'Eta herritarren partaidetza, datuen babesa eta kexak eta iradokizunak.'],
            f: 'Aurrez aurreko erroldarako hitzordua behar da: sede.basauri.eus webgunean hartzen da.' },
      s: { t: 'Servicio Atención Ciudadana (S.A.C.) — basauri.eus', u: 'https://www.basauri.eus/es/area-de-competencia-departamentos/servicio-atencion-ciudadana-sac' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'sin desplazarse',
          'egoitza elektronikoa', 'izapideak', 'internetez'],
      es: { h: 'La <b>sede electrónica</b> está en sede.basauri.eus.',
            l: ['Muchos trámites se completan ahí sin pedir cita ni ir a las oficinas.'],
            f: 'Si tiene dudas: 94 466 63 00, o el WhatsApp 688 737 704.' },
      eu: { h: '<b>Egoitza elektronikoa</b> sede.basauri.eus da.',
            l: ['Izapide asko bertan osatzen dira, hitzordurik eskatu gabe eta bulegoetara joan gabe.'],
            f: 'Zalantzarik baduzu: 94 466 63 00, edo WhatsApp 688 737 704.' },
      s: { t: 'Sede Electrónica — Basauri', u: 'https://sede.basauri.eus/es/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hace falta cita previa?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'EU', t: 'Non dago SAC bulegoa?' },
    { lang: 'ES', t: '¿Tienen WhatsApp?' },
  ],
},

// ===========================================================================
{
  slug: 'erandio',
  nombre: 'Erandio',
  articulo: 'de Erandio',
  dominios: 'erandio.eus y tramitegunea.erandio.eus',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el HAZ-SAC', tel: '944 89 00 10', email: 'haz-sac@erandio.eus' },
  idioma2: { cod: 'EU', clave: 'eu', sigla: 'HAZ-SAC bulegoa', nombre: 'euskera' },
  kb: [
    {
      k: ['haz', 'sac', 'oficina', 'oficinas', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'altzaga', 'astrabudua',
          'bulegoa', 'ordutegia', 'telefonoa', 'helbidea'],
      es: { h: 'El <b>HAZ-SAC</b> tiene <b>dos sedes</b>.',
            l: ['Altzaga: Antonio Trueba zeharkalea, 2.',
                'Astrabudua: Meso kalea, 20.',
                'Teléfono: 944 89 00 10.',
                'Horario: de lunes a viernes de 8:30 a 14:30.'],
            f: 'Correo: haz-sac@erandio.eus.' },
      eu: { h: '<b>HAZ-SAC</b>ek <b>bi egoitza</b> ditu.',
            l: ['Altzaga: Antonio Trueba zeharkalea, 2.',
                'Astrabudua: Meso kalea, 20.',
                'Telefonoa: 944 89 00 10.',
                'Ordutegia: astelehenetik ostiralera 8:30etik 14:30era.'],
            f: 'Korreoa: haz-sac@erandio.eus.' },
      s: { t: 'Información y orientación a la ciudadanía — tramitegunea.erandio.eus', u: 'https://tramitegunea.erandio.eus/front/procedure/1?lang=es' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'individual', 'colectivo',
          'errolda', 'erroldatu', 'ziurtagiria', 'agiria'],
      es: { h: 'Los trámites de <b>empadronamiento</b> tienen cada uno su ficha en el portal de trámites.',
            l: ['Certificado de empadronamiento.',
                'Volante de empadronamiento individual.',
                'Volante de empadronamiento colectivo.'],
            f: 'Se tramitan en tramitegunea.erandio.eus, o presencialmente en Altzaga o Astrabudua.' },
      eu: { h: '<b>Erroldatze</b> izapide bakoitzak bere fitxa du izapideen atarian.',
            l: ['Errolda-ziurtagiria.',
                'Banakako errolda-agiria.',
                'Errolda-agiri kolektiboa.'],
            f: 'tramitegunea.erandio.eus webgunean izapidetzen dira, edo aurrez aurre Altzagan edo Astrabuduan.' },
      s: { t: 'Certificado de empadronamiento — tramitegunea.erandio.eus', u: 'https://tramitegunea.erandio.eus/front/procedure/43?lang=es' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'alcalde', 'concejalia', 'reservar',
          'hitzordua', 'alkatea', 'eskatu'],
      es: { h: 'Hay un trámite específico para <b>pedir cita con el alcalde o con las concejalías</b>.',
            l: ['Se solicita en tramitegunea.erandio.eus.'],
            f: 'Para las gestiones normales, el HAZ-SAC atiende de 8:30 a 14:30 en sus dos sedes.' },
      eu: { h: 'Izapide zehatz bat dago <b>alkatearekin edo zinegotzigoekin hitzordua eskatzeko</b>.',
            l: ['tramitegunea.erandio.eus webgunean eskatzen da.'],
            f: 'Kudeaketa arruntetarako, HAZ-SACek 8:30etik 14:30era artatzen du bere bi egoitzetan.' },
      s: { t: 'Solicitud de cita previa con alcalde y concejalías — tramitegunea.erandio.eus', u: 'https://tramitegunea.erandio.eus/front/procedure/28?lang=es' },
    },
    {
      k: ['tramites', 'tramite', 'sede electronica', 'online', 'internet', 'por internet', 'tramitegunea',
          'izapideak', 'internetez'],
      es: { h: 'El portal de trámites del Ayuntamiento es <b>tramitegunea.erandio.eus</b>.',
            l: ['Ahí está la ficha de cada procedimiento, con su documentación.'],
            f: 'Dudas: 944 89 00 10 o haz-sac@erandio.eus.' },
      eu: { h: 'Udalaren izapideen ataria <b>tramitegunea.erandio.eus</b> da.',
            l: ['Bertan dago prozedura bakoitzaren fitxa, bere dokumentazioarekin.'],
            f: 'Zalantzak: 944 89 00 10 edo haz-sac@erandio.eus.' },
      s: { t: 'Trámites — Erandioko Udala', u: 'https://tramitegunea.erandio.eus/front/procedure/182?lang=es' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Dónde están las oficinas del HAZ-SAC?' },
    { lang: 'ES', t: '¿Hace falta cita previa?' },
    { lang: 'EU', t: 'Zein da ordutegia?' },
    { lang: 'ES', t: '¿Cómo pido un volante de empadronamiento?' },
  ],
},

// ===========================================================================
{
  slug: 'arrigorriaga',
  nombre: 'Arrigorriaga',
  articulo: 'de Arrigorriaga',
  dominios: 'arrigorriaga.eus',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el HAZ-SAC', tel: '944 020 200', email: 'haz-sac@arrigorriaga.eus' },
  idioma2: { cod: 'EU', clave: 'eu', sigla: 'HAZ-SAC bulegoa (Urgoitia pasealekua 57)', nombre: 'euskera' },
  kb: [
    {
      k: ['haz', 'sac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'urgoitia', 'verano',
          'bulegoa', 'ordutegia', 'telefonoa', 'helbidea', 'uda'],
      es: { h: 'El <b>HAZ-SAC</b> está en Urgoitia pasealekua, 57 — 48480 Arrigorriaga.',
            l: ['Teléfono: 944 020 200.',
                'Horario: de lunes a viernes de 8:00 a 14:45.',
                'En verano: de 8:00 a 13:45.',
                'Correo: haz-sac@arrigorriaga.eus.'],
            f: 'Abre a las 8:00, antes que la mayoría de oficinas municipales.' },
      eu: { h: '<b>HAZ-SAC</b> Urgoitia pasealekua 57an dago — 48480 Arrigorriaga.',
            l: ['Telefonoa: 944 020 200.',
                'Ordutegia: astelehenetik ostiralera 8:00etatik 14:45era.',
                'Udan: 8:00etatik 13:45era.',
                'Korreoa: haz-sac@arrigorriaga.eus.'],
            f: '8:00etan irekitzen du, udal bulego gehienak baino lehenago.' },
      s: { t: 'Servicio de Atención Ciudadana (SAC) — arrigorriaga.eus', u: 'https://www.arrigorriaga.eus/es-ES/Ayuntamiento/AtencionCiudadanaSAC/Paginas/default.aspx' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'cambio de domicilio', 'consultas', 'tramites',
          'errolda', 'erroldatu', 'ziurtagiria', 'izapideak'],
      es: { h: 'El HAZ-SAC es la ventanilla donde se hacen las <b>consultas y trámites</b> con el Ayuntamiento, el padrón incluido.',
            l: ['Urgoitia pasealekua, 57, de 8:00 a 14:45.',
                'Teléfono: 944 020 200.'],
            f: 'La documentación concreta depende de su caso. Confírmela por teléfono antes de ir.' },
      eu: { h: 'HAZ-SAC da Udalarekiko <b>kontsultak eta izapideak</b> egiteko leihatila, errolda barne.',
            l: ['Urgoitia pasealekua, 57, 8:00etatik 14:45era.',
                'Telefonoa: 944 020 200.'],
            f: 'Dokumentazio zehatza zure kasuaren araberakoa da. Berretsi telefonoz joan aurretik.' },
      s: { t: 'El SAC de Arrigorriaga eleva las consultas y trámites de la ciudadanía', u: 'http://www.arrigorriaga.eus/es-ES/Noticias/Paginas/ElSACdeArrigorriaga.aspx' },
    },
    {
      k: ['oficinas administrativas', 'ayuntamiento', 'areas', 'departamentos', 'donde me dirijo',
          'udaletxea', 'sailak'],
      es: { h: 'El Ayuntamiento publica el listado de sus <b>oficinas administrativas</b> y sus horarios.',
            l: ['Está en arrigorriaga.eus, en el apartado del Ayuntamiento.'],
            f: 'Si no sabe qué área lleva su gestión, empiece por el HAZ-SAC: 944 020 200.' },
      eu: { h: 'Udalak bere <b>bulego administratiboen</b> zerrenda eta ordutegiak argitaratzen ditu.',
            l: ['arrigorriaga.eus webgunean dago, Udalaren atalean.'],
            f: 'Zein sailek daraman zure kudeaketa ez badakizu, hasi HAZ-SACetik: 944 020 200.' },
      s: { t: 'Oficinas Administrativas — arrigorriaga.eus', u: 'http://www.arrigorriaga.eus/es-ES/TuAyuntamiento/Oficinas-Administrativas/Paginas/default.aspx' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué horario tiene el HAZ-SAC?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'EU', t: 'Zein da udako ordutegia?' },
    { lang: 'ES', t: '¿Dónde está la oficina?' },
  ],
},

// ===========================================================================
{
  slug: 'etxebarri',
  nombre: 'Etxebarri',
  articulo: 'de Etxebarri',
  dominios: 'etxebarri.eus',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el SAC', tel: '94 426 70 00', email: 'etxebarri@etxebarri.net' },
  idioma2: { cod: 'EU', clave: 'eu', sigla: 'SAC bulegoa (Sabino Arana 1A)', nombre: 'euskera' },
  kb: [
    {
      k: ['sac', 'oficina', 'atencion ciudadana', 'atencion al publico', 'direccion', 'telefono', 'contacto', 'sabino arana',
          'bulegoa', 'telefonoa', 'helbidea'],
      es: { h: 'El <b>Servicio de Atención Ciudadana (SAC)</b> está en la calle Sabino Arana, 1A, 1ª planta — 48450 Etxebarri.',
            l: ['Teléfono: 94 426 70 00.',
                'Correo: sac@etxebarri.eus.'],
            f: 'En la misma planta están Servicios Jurídicos, Personal y Estadística y Padrón de Habitantes.' },
      eu: { h: '<b>Herritarrentzako Arreta Zerbitzua (SAC)</b> Sabino Arana kalea 1A, 1. solairuan dago — 48450 Etxebarri.',
            l: ['Telefonoa: 94 426 70 00.',
                'Korreoa: sac@etxebarri.eus.'],
            f: 'Solairu berean daude Zerbitzu Juridikoak, Langileria eta Estatistika eta Biztanleen Errolda.' },
      s: { t: 'SAC. Servicio de Atención Ciudadana — etxebarri.eus', u: 'http://www.etxebarri.eus/es-ES/tramites/Paginas/SAC.aspx' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'obligatorio', 'seis meses', '6 meses', 'estadistica', 'certificado',
          'errolda', 'erroldatu', 'derrigorrezkoa', 'ziurtagiria'],
      es: { h: 'Empadronarse en Etxebarri es <b>obligatorio</b> si reside allí más de seis meses al año.',
            l: ['Lo lleva el área de Estadística y Padrón de Habitantes.',
                'Está en la misma planta que el SAC: Sabino Arana, 1A, 1ª planta.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 94 426 70 00 antes de ir.' },
      eu: { h: 'Etxebarrin erroldatzea <b>derrigorrezkoa</b> da urtean sei hilabete baino gehiago bertan bizi bazara.',
            l: ['Estatistika eta Biztanleen Errolda arloak darama.',
                'SACen solairu berean dago: Sabino Arana 1A, 1. solairua.'],
            f: 'Dokumentazio zehatza zure kasuaren araberakoa da. Berretsi 94 426 70 00 telefonoan joan aurretik.' },
      s: { t: 'Campaña de empadronamiento — etxebarri.eus', u: 'http://www.etxebarri.eus/es-ES/Noticias/Paginas/20161221-padron.aspx' },
    },
    {
      k: ['tramites', 'tramite', 'sede electronica', 'online', 'internet', 'por internet', 'procedimiento',
          'izapideak', 'internetez'],
      es: { h: 'Los <b>trámites</b> municipales están listados en etxebarri.eus.',
            l: ['Cada uno tiene su ficha con la documentación que hace falta.'],
            f: 'Dudas: 94 426 70 00 o sac@etxebarri.eus.' },
      eu: { h: 'Udal <b>izapideak</b> etxebarri.eus webgunean zerrendatuta daude.',
            l: ['Bakoitzak bere fitxa du, behar den dokumentazioarekin.'],
            f: 'Zalantzak: 94 426 70 00 edo sac@etxebarri.eus.' },
      s: { t: 'Trámites — Ayuntamiento de Etxebarri', u: 'http://www.etxebarri.eus/ES-ES/TRAMITES/Paginas/default.aspx' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Dónde está el SAC?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'EU', t: 'Derrigorrezkoa da erroldatzea?' },
    { lang: 'ES', t: '¿Quién lleva el padrón?' },
  ],
},

// ===========================================================================
{
  slug: 'eivissa',
  nombre: 'Eivissa',
  articulo: 'de Eivissa',
  dominios: 'eivissa.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el SAC', tel: '971 397 600', email: 'sac@eivissa.es' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: 'al SAC', nombre: 'catalán' },
  kb: [
    {
      k: ['sac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'sa colomina', 'canaries',
          'atencio ciutadana', 'adreca', 'horari', 'telefon'],
      es: { h: 'El <b>Servei d\'Atenció a la Ciutadania (SAC)</b> está en el edificio Sa Colomina, carrer de Canàries, 35 — 07800 Eivissa.',
            l: ['Teléfono: 971 397 600.',
                'Correo: sac@eivissa.es.',
                'Horario: de lunes a viernes de 8:30 a 14:00.'],
            f: 'Da información general, registra documentos y lleva los asuntos de población.' },
      ca: { h: 'El <b>Servei d\'Atenció a la Ciutadania (SAC)</b> és a l\'edifici Sa Colomina, carrer de Canàries, 35 — 07800 Eivissa.',
            l: ['Telèfon: 971 397 600.',
                'Correu: sac@eivissa.es.',
                'Horari: de dilluns a divendres de 8:30 a 14:00.'],
            f: 'Dona informació general, registra documents i porta els assumptes de població.' },
      s: { t: 'Servei d\'Atenció a la Ciutadania — eivissa.es', u: 'https://www.eivissa.es/portal/index.php/ca/servei-d-atencio-a-la-ciutadania' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta', 'baja', 'cambio de domicilio', 'certificado', 'viaje',
          'padro', 'empadronar-me', 'empadronament', 'canvi de domicili', 'certificat', 'viatge'],
      es: { h: 'Para inscribirse en el <b>padró municipal</b> hay que ir al SAC, y se atiende <b>exclusivamente con cita previa</b>.',
            l: ['Alta, baja o cambio de domicilio en el padrón municipal.',
                'Certificados de empadronamiento y certificados de viaje.'],
            f: 'Sin cita no se atiende el padrón: no es una recomendación.' },
      ca: { h: 'Per inscriure\'s al <b>padró municipal</b> cal anar al SAC, i s\'atén <b>exclusivament amb cita prèvia</b>.',
            l: ['Alta, baixa o canvi de domicili al padró municipal.',
                'Certificats d\'empadronament i certificats de viatge.'],
            f: 'Sense cita no s\'atén el padró: no és una recomanació.' },
      s: { t: 'Padró Municipal — Ajuntament d\'Eivissa', u: 'https://www.eivissa.es/w/padr%C3%B3-municipal' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'registre d entrada', 'registro de entrada', 'obligatoria',
          'cita previa', 'demanar cita'],
      es: { h: 'La <b>cita previa</b> se pide en eivissa.sedelectronica.es/citaprevia.1.',
            l: ['Hay que seleccionar la opción <b>«Registre d\'Entrada»</b>.'],
            f: 'Esa es la vía para el padrón, que solo se atiende con cita.' },
      ca: { h: 'La <b>cita prèvia</b> es demana a eivissa.sedelectronica.es/citaprevia.1.',
            l: ['Cal seleccionar l\'opció <b>«Registre d\'Entrada»</b>.'],
            f: 'Aquesta és la via per al padró, que només s\'atén amb cita.' },
      s: { t: 'Nou servei de cita prèvia — eivissa.es', u: 'https://www.eivissa.es/portal/index.php/ca/actualitat/noticies/17762-ajuntament-eivissa-posa-en-marxa-cita-previa' },
    },
    {
      k: ['registro', 'documentos', 'quejas', 'sugerencias', 'tramites', 'tramite', 'oficinas municipales',
          'registre', 'documents', 'queixes', 'suggeriments', 'tramits'],
      es: { h: 'El SAC también <b>registra documentos</b> y recoge quejas y sugerencias.',
            l: ['Orienta sobre las relaciones con la administración.',
                'Recibe y tramita las reclamaciones de la ciudadanía.'],
            f: 'Teléfono: 971 397 600.' },
      ca: { h: 'El SAC també <b>registra documents</b> i recull queixes i suggeriments.',
            l: ['Orienta sobre les relacions amb l\'administració.',
                'Rep i tramita les reclamacions de la ciutadania.'],
            f: 'Telèfon: 971 397 600.' },
      s: { t: 'SAC — Ajuntament d\'Eivissa', u: 'https://www.eivissa.es/sac' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hace falta cita previa para el padrón?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'CA', t: 'On és el SAC i quin horari té?' },
    { lang: 'ES', t: '¿Qué opción elijo al pedir la cita?' },
  ],
},

// ===========================================================================
{
  slug: 'granadilla-de-abona',
  nombre: 'Granadilla de Abona',
  articulo: 'de Granadilla de Abona',
  dominios: 'granadilladeabona.org',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el SAC', tel: '010 o 922 759 900', email: '010@granadilladeabona.org' },
  idioma2: null,
  kb: [
    {
      k: ['sac', 'oficina', 'oficinas', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'oficina del medano', 'oficina de san isidro', 'granadilla casco', 'siec'],
      es: { h: 'Hay <b>tres oficinas del SAC</b>, una en cada núcleo.',
            l: ['Granadilla Casco: plaza González Mena, s/n — 38600.',
                'San Isidro: calle Santa María de la Cabeza, 3, edificio SIEC — 38611.',
                'El Médano: plaza de La Ermita, s/n — 38612.',
                'Horario: de lunes a viernes de <b>7:45 a 18:30</b>.'],
            f: 'Teléfonos: el <b>010</b> desde el municipio, o el 922 759 900 desde fuera.' },
      s: { t: 'Oficinas SAC — granadilladeabona.org', u: 'https://www.granadilladeabona.org/servicios/oficinas-sac/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita', 'correo', 'email'],
      es: { h: 'La <b>cita previa</b> se puede pedir de tres formas.',
            l: ['Por correo electrónico: 010@granadilladeabona.org.',
                'Por internet: citas.granadilladeabona.es.',
                'O presencialmente en cualquiera de las tres oficinas SAC.'],
            f: 'El teléfono 010 atiende hasta las 18:30.' },
      s: { t: 'Atención ciudadana — granadilladeabona.org', u: 'https://www.granadilladeabona.org/atencion-ciudadania/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'residencia', 'viaje', 'gratis', 'gratuito'],
      es: { h: 'Los <b>certificados individuales de residencia y de viaje</b> son <b>gratuitos</b> y se obtienen por plataformas digitales.',
            l: ['No hace falta ir a la oficina para conseguirlos.'],
            f: 'Para el resto de trámites del padrón, el SAC atiende de 7:45 a 18:30 en sus tres oficinas.' },
      s: { t: 'SAC — Ayuntamiento de Granadilla de Abona', u: 'https://www.granadilladeabona.org/servicios/atencion-ciudadana/' },
    },
    {
      k: ['telefono 010', 'atencion telefonica', 'llamar', 'por telefono', 'horario ampliado'],
      es: { h: 'El servicio de atención telefónica <b>010</b> atiende hasta las <b>18:30</b>.',
            l: ['Desde fuera del municipio: 922 759 900.'],
            f: 'Es el mismo horario que las oficinas presenciales.' },
      s: { t: 'El Ayuntamiento amplía el horario del 010 hasta las 18:30', u: 'https://www.granadilladeabona.org/el-ayuntamiento-amplia-el-horario-del-servicio-de-atencion-telefonica-010-hasta-las-18-30-horas/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Dónde están las oficinas del SAC?' },
    { lang: 'ES', t: '¿Hace falta cita previa?' },
    { lang: 'ES', t: '¿Hasta qué hora abren?' },
    { lang: 'ES', t: '¿El certificado de residencia es gratis?' },
  ],
},

];
