// ---------------------------------------------------------------------------
//  LOS OCHO DEL TRECEAVO ENVIO — jueves 8 de octubre de 2026.
//  Comprobado en cada web municipal el 7 de septiembre de 2026.
//
//  Tres caidas de la lista de partida, y conviene no repetirlas:
//
//  - CARMONA ya tiene chatbot. La portada de carmona.org monta el widget de
//    Civitphone, con un bot que se llama "Carmo". No es un lead de "no tienen
//    asistente"; hay que escribirle otra cosa o no escribirle.
//  - CAMBRE: su web no responde ni en .gal ni en .org. Igual que Linares, se
//    queda fuera hasta que vuelva.
//  - SALT: la web esta viva pero no publica ni direccion ni horario ni
//    telefono de su oficina. Sin eso la demo no tiene nada que contar.
//
//  En su lugar entran Premia de Mar, Mutxamel y Redondela.
//
//  Y un cambio de destinatario: en Mutxamel, buscar-correo.mjs proponia
//  info@mutxamel.org. La OMAC publica el suyo propio, e-omac@mutxamel.org.
//
//  Catalan en Olot, Sitges, Valls y Premia de Mar; valenciano en Calp y
//  Mutxamel; gallego en Arteixo y Redondela.
// ---------------------------------------------------------------------------

export const MUNICIPIOS_DIA13 = [

// ===========================================================================
{
  slug: 'olot',
  nombre: 'Olot',
  articulo: "d'Olot",
  dominios: 'olot.cat y padro.olot.cat',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: "l'OAC", tel: '972 27 91 00', email: 'atencioalciutada@olot.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'atencion al ciudadano', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'ramon guillamet',
          'atencio ciutadana', 'adreca', 'horari', 'a quina hora obren', 'telefon'],
      es: { h: "L'<b>Oficina d'Atenció Ciutadana (OAC)</b> está en el passeig de Ramon Guillamet, 2.",
            l: ['Teléfonos: 972 27 91 00 y 972 27 91 01. Correo: atencioalciutada@olot.cat.',
                'Horario: de lunes a jueves de 8:00 a 18:00; viernes de 8:00 a 15:00.',
                'En Navidad, verano, Semana Santa y todas las tardes de víspera de festivo: de lunes a viernes de 8:00 a 15:00.',
                'La atención presencial es <b>con cita previa</b>.'],
            f: 'Para consultas que no requieren trámite se puede llamar directamente al 972 27 91 00.' },
      ca: { h: "L'<b>Oficina d'Atenció Ciutadana (OAC)</b> és al passeig de Ramon Guillamet, 2.",
            l: ['Telèfons: 972 27 91 00 i 972 27 91 01. Correu: atencioalciutada@olot.cat.',
                'Horari: de dilluns a dijous de 8:00 a 18:00; divendres de 8:00 a 15:00.',
                'Per Nadal, estiu, Setmana Santa i totes les tardes prèvies a un festiu: de dilluns a divendres de 8:00 a 15:00.',
                "L'atenció presencial és <b>amb cita prèvia</b>."],
            f: 'Per a consultes que no requereixen tràmit es pot telefonar directament al 972 27 91 00.' },
      s: { t: "Horari de l'Oficina d'Atenció Ciutadana (OAC) — olot.cat", u: 'https://www.olot.cat/ca/ajuntament/arees-i-departaments-muncipals/atencio-al-ciutada/pld56/horari-oficina-d-atencio-al-ciutada-oac' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'presencial', 'online', 'por internet',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me', 'per internet'],
      es: { h: 'El <b>alta en el padró municipal d\'habitants</b> se hace <b>solo presencialmente</b>, en la OAC y con cita previa.',
            l: ['No se puede tramitar por internet: hay que presentar la documentación en la oficina.',
                'Passeig de Ramon Guillamet, 2.'],
            f: 'El Ayuntamiento tiene un <b>asistente para los trámites de padrón</b> en padro.olot.cat que ayuda a preparar la documentación antes de ir.' },
      ca: { h: "L'<b>alta al padró municipal d'habitants</b> es fa <b>només presencialment</b>, a l'OAC i amb cita prèvia.",
            l: ['No es pot tramitar per internet: cal presentar la documentació a l\'oficina.',
                'Passeig de Ramon Guillamet, 2.'],
            f: "L'Ajuntament té un <b>assistent per als tràmits de padró</b> a padro.olot.cat que ajuda a preparar la documentació abans d'anar-hi." },
      s: { t: "Alta al padró municipal d'habitants d'Olot — olot.cat", u: 'https://www.olot.cat/pag587/pl221/seu-tramits/id10313/alta-al-padro-municipal-d-habitants-d-olot.htm' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'hace falta cita', 'necesito cita', 'turno',
          'cita previa', 'demanar cita', 'cal cita'],
      es: { h: 'La <b>cita previa</b> es necesaria para la atención presencial y se pide en olot.cat/ca/tramits/cita-previa.',
            l: ['El sistema deja reservar día y hora para que no haya esperas.'],
            f: 'Si el sistema no le da hueco, llame al 972 27 91 00.' },
      ca: { h: "La <b>cita prèvia</b> és necessària per a l'atenció presencial i es demana a olot.cat/ca/tramits/cita-previa.",
            l: ['El sistema permet reservar dia i hora perquè no hi hagi esperes.'],
            f: 'Si el sistema no us dona hora, telefoneu al 972 27 91 00.' },
      s: { t: "Cita prèvia — Ajuntament d'Olot", u: 'https://www.olot.cat/ca/tramits/cita-previa' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'internet', 'catalogo', 'asistente', 'registro',
          'seu electronica', 'tramit', 'tramits', 'cataleg', 'assistent'],
      es: { h: 'Los trámites en línea están en olot.cat, y para el padrón hay un <b>asistente propio</b> en padro.olot.cat.',
            l: ['El asistente guía por las gestiones del padrón antes de pedir la cita.'],
            f: 'Dudas: 972 27 91 00 o atencioalciutada@olot.cat.' },
      ca: { h: "Els tràmits en línia són a olot.cat, i per al padró hi ha un <b>assistent propi</b> a padro.olot.cat.",
            l: ['L’assistent guia per les gestions del padró abans de demanar la cita.'],
            f: 'Dubtes: 972 27 91 00 o atencioalciutada@olot.cat.' },
      s: { t: 'Assistent per als tràmits i gestions de padró — padro.olot.cat', u: 'https://padro.olot.cat/index.php/378687?lang=ca' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Olot?' },
    { lang: 'ES', t: '¿Dónde está la OAC y qué horario tiene?' },
    { lang: 'ES', t: '¿Hace falta cita previa?' },
    { lang: 'CA', t: 'Puc empadronar-me per internet?' },
    { lang: 'ES', t: '¿Qué teléfono tienen?' },
  ],
},

// ===========================================================================
{
  slug: 'sitges',
  nombre: 'Sitges',
  articulo: 'de Sitges',
  dominios: 'sitges.cat y seu.sitges.cat',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: "l'OAC", tel: '938 117 600', email: 'ajuntament@sitges.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'carrer nou', '010', 'les botigues', 'garraf',
          'atencio ciutadana', 'adreca', 'horari', 'a quina hora obren', 'telefon'],
      es: { h: "L'<b>Oficina d'Atenció Ciutadana (OAC)</b> del centro está en el carrer Nou, 12.",
            l: ['Teléfono: 938 117 600. Atención ciudadana: <b>010</b>, o 93 811 48 04 desde fuera del municipio.',
                'Horario: de lunes a viernes de 8:30 a 14:30, y los <b>jueves también de 16:00 a 18:30</b>.',
                'La tarde de los jueves no se hace en verano, Semana Santa ni Navidad.',
                'Hay además OAC en <b>Les Botigues</b> y en <b>Garraf</b>.'],
            f: 'Se recomienda concertar cita previa para ser atendido presencialmente.' },
      ca: { h: "L'<b>Oficina d'Atenció Ciutadana (OAC)</b> del centre és al carrer Nou, 12.",
            l: ['Telèfon: 938 117 600. Atenció ciutadana: <b>010</b>, o 93 811 48 04 des de fora del municipi.',
                'Horari: de dilluns a divendres de 8:30 a 14:30, i els <b>dijous també de 16:00 a 18:30</b>.',
                "La tarda dels dijous no es fa a l'estiu, Setmana Santa ni Nadal.",
                "Hi ha també OAC a <b>Les Botigues</b> i a <b>Garraf</b>."],
            f: 'Es recomana concertar cita prèvia per ser atès presencialment.' },
      s: { t: "Oficina d'Atenció Ciutadana (OAC) - Centre — sitges.cat", u: 'https://www.sitges.cat/vila-de-sitges/guia/marcadors/oficina-datencio-ciutadana-oac-centre' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'al momento', 'inmediato',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me'],
      es: { h: 'El <b>empadronamiento</b> es uno de los trámites que la OAC resuelve <b>en el momento</b>.',
            l: ['Junto con los enterados de obras, las tarjetas de transporte para gente mayor y las propias citas previas.',
                'Carrer Nou, 12, de 8:30 a 14:30.'],
            f: 'La documentación depende de su caso. Confírmela en el 010 o en el 938 117 600 antes de desplazarse.' },
      ca: { h: "L'<b>empadronament</b> és un dels tràmits que l'OAC resol <b>en el moment</b>.",
            l: ['Juntament amb els assabentats d\'obres, les targetes de transport per a la gent gran i les mateixes cites prèvies.',
                'Carrer Nou, 12, de 8:30 a 14:30.'],
            f: 'La documentació depèn del seu cas. Confirmeu-la al 010 o al 938 117 600 abans de desplaçar-vos.' },
      s: { t: 'Atenció a la ciutadania — sitges.cat', u: 'https://www.sitges.cat/ajuntament/atencio-ciutadana' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'turno',
          'cita previa', 'demanar cita'],
      es: { h: 'La <b>cita previa</b> se pide en el portal del Ayuntamiento, en sitges.cat.',
            l: ['Se rellenan los datos y se elige día y hora en el calendario.'],
            f: 'También se puede pedir llamando al 010.' },
      ca: { h: "La <b>cita prèvia</b> es demana al portal de l'Ajuntament, a sitges.cat.",
            l: ['Es omplen les dades i es tria dia i hora al calendari.'],
            f: 'També es pot demanar trucant al 010.' },
      s: { t: 'Cita prèvia — Ajuntament de Sitges', u: 'https://www.sitges.cat/ajuntament/atencio-ciutadana/cita-previa' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'registro',
          'seu electronica', 'tramit', 'tramits', 'per internet', 'cataleg'],
      es: { h: 'La <b>seu electrònica</b> está en seu.sitges.cat.',
            l: [],
            f: 'Dudas: 010, o 93 811 48 04 desde fuera de Sitges.' },
      ca: { h: 'La <b>seu electrònica</b> és a seu.sitges.cat.',
            l: [],
            f: 'Dubtes: 010, o 93 811 48 04 des de fora de Sitges.' },
      s: { t: "Oficina d'Atenció Ciutadana — Seu Electrònica de Sitges", u: 'https://seu.sitges.cat/public/mostrar/info.atencioCiutadana?lang=ca_ES' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Sitges?' },
    { lang: 'ES', t: '¿Puedo presentar un escrito en el registro?' },
    { lang: 'ES', t: '¿Hace falta cita previa?' },
    { lang: 'CA', t: 'Fins a quina hora obre l\'OAC?' },
    { lang: 'ES', t: '¿Dónde está la OAC?' },
  ],
},

// ===========================================================================
{
  slug: 'valls',
  nombre: 'Valls',
  articulo: 'de Valls',
  dominios: 'valls.cat y seu.valls.cat',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: "l'OAC", tel: '977 636 010', email: 'ajuntament@valls.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'atencion al ciudadano', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'placa del blat',
          'atencio ciutadana', 'adreca', 'horari', 'a quina hora obren', 'telefon'],
      es: { h: "L'<b>Oficina d'Atenció a la Ciutadania (OAC)</b> está en la plaça del Blat, 1.",
            l: ['Teléfono: 977 636 010.',
                'Presencial: de lunes a viernes de 9:00 a 13:00, y <b>martes y jueves de 17:00 a 19:30</b>.',
                'En verano, del 15 de junio al 15 de septiembre, <b>solo por la mañana</b>, de 9:00 a 13:00.',
                'Por teléfono: de 9:00 a 14:00, y martes y jueves de 17:00 a 19:30.'],
            f: 'La cita previa <b>no es obligatoria</b>. Si la quiere, está en citaprevia.valls.cat.' },
      ca: { h: "L'<b>Oficina d'Atenció a la Ciutadania (OAC)</b> és a la plaça del Blat, 1.",
            l: ['Telèfon: 977 636 010.',
                'Presencial: de dilluns a divendres de 9:00 a 13:00, i <b>dimarts i dijous de 17:00 a 19:30</b>.',
                "A l'estiu, del 15 de juny al 15 de setembre, <b>només al matí</b>, de 9:00 a 13:00.",
                'Per telèfon: de 9:00 a 14:00, i dimarts i dijous de 17:00 a 19:30.'],
            f: 'La cita prèvia <b>no és obligatòria</b>. Si la voleu, és a citaprevia.valls.cat.' },
      s: { t: "Oficina d'Atenció a la Ciutadania — valls.cat", u: 'https://www.valls.cat/ajuntament/oficina-atencio-al-ciutada' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'baja', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'certificado', 'volante',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me', 'certificat', 'volant'],
      es: { h: 'La OAC gestiona el <b>padró municipal d\'habitants</b>: altas, bajas, cambios de domicilio, certificados y volantes.',
            l: ['Plaça del Blat, 1, de 9:00 a 13:00, y martes y jueves también de 17:00 a 19:30.'],
            f: 'La documentación depende de su caso. Confírmela en el 977 636 010 antes de desplazarse.' },
      ca: { h: "L'OAC gestiona el <b>padró municipal d'habitants</b>: altes, baixes, canvis de domicili, certificats i volants.",
            l: ['Plaça del Blat, 1, de 9:00 a 13:00, i dimarts i dijous també de 17:00 a 19:30.'],
            f: 'La documentació depèn del seu cas. Confirmeu-la al 977 636 010 abans de desplaçar-vos.' },
      s: { t: "Oficina d'Atenció a la Ciutadania — valls.cat", u: 'https://www.valls.cat/ajuntament/oficina-atencio-al-ciutada' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'hace falta cita', 'necesito cita', 'sin cita', 'turno',
          'cita previa', 'demanar cita', 'cal cita', 'sense cita'],
      es: { h: 'En Valls la <b>cita previa no es obligatoria</b>: se puede ir sin ella.',
            l: ['Si la prefiere, se pide en citaprevia.valls.cat.'],
            f: 'Dudas: 977 636 010.' },
      ca: { h: 'A Valls la <b>cita prèvia no és obligatòria</b>: s\'hi pot anar sense.',
            l: ['Si la preferiu, es demana a citaprevia.valls.cat.'],
            f: 'Dubtes: 977 636 010.' },
      s: { t: "Cita prèvia amb l'OAC — valls.cat", u: 'https://www.valls.cat/ajuntament/cita-previa-amb-l-oac' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'registro',
          'seu electronica', 'tramit', 'tramits', 'per internet', 'cataleg'],
      es: { h: 'La <b>seu electrònica</b> está en seu.valls.cat, con su propio apartado de OAC.',
            l: [],
            f: 'Dudas: 977 636 010 o ajuntament@valls.cat.' },
      ca: { h: "La <b>seu electrònica</b> és a seu.valls.cat, amb el seu propi apartat d'OAC.",
            l: [],
            f: 'Dubtes: 977 636 010 o ajuntament@valls.cat.' },
      s: { t: "OAC — Seu Electrònica de l'Ajuntament de Valls", u: 'https://seu.valls.cat/oac' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Valls?' },
    { lang: 'ES', t: '¿Qué diferencia hay entre volante y certificado?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'CA', t: 'Cal demanar cita prèvia?' },
    { lang: 'ES', t: '¿Abren en agosto?' },
  ],
},

// ===========================================================================
{
  slug: 'premia-de-mar',
  nombre: 'Premià de Mar',
  articulo: 'de Premià de Mar',
  dominios: 'premiademar.cat',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: "l'OAC", tel: '93 741 74 00', email: 'info@premiademar.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'carrer del nord',
          'atencio ciutadana', 'adreca', 'horari', 'a quina hora obren', 'telefon'],
      es: { h: "L'<b>Oficina d'Atenció Ciutadana (OAC)</b> está en el carrer del Nord, 60.",
            l: ['Teléfono: 93 741 74 00.',
                'Invierno, del 16 de septiembre al 14 de junio: de lunes a viernes de 8:30 a 14:00, y <b>martes y jueves de 14:00 a 18:30</b>.',
                'Verano, del 15 de junio al 15 de septiembre: de lunes a viernes de 8:30 a 14:00.'],
            f: 'Se atiende preferentemente con cita previa. <b>Durante agosto, solo con cita.</b>' },
      ca: { h: "L'<b>Oficina d'Atenció Ciutadana (OAC)</b> és al carrer del Nord, 60.",
            l: ['Telèfon: 93 741 74 00.',
                "Hivern, del 16 de setembre al 14 de juny: de dilluns a divendres de 8:30 a 14:00, i <b>dimarts i dijous de 14:00 a 18:30</b>.",
                "Estiu, del 15 de juny al 15 de setembre: de dilluns a divendres de 8:30 a 14:00."],
            f: "S'atén preferentment amb cita prèvia. <b>Durant l'agost, només amb cita.</b>" },
      s: { t: "Oficina d'Atenció Ciutadana — premiademar.cat", u: 'https://premiademar.cat/oac' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'modificar datos', 'cambiar datos',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me', 'modificacio dades'],
      es: { h: 'La OAC gestiona la <b>inscripción en el padró municipal d\'habitants</b> y sus modificaciones.',
            l: ['Incluye los cambios de domicilio y la actualización de datos personales.',
                'Carrer del Nord, 60.'],
            f: 'La documentación depende de su caso. Confírmela en el 93 741 74 00 antes de desplazarse.' },
      ca: { h: "L'OAC gestiona la <b>inscripció al padró municipal d'habitants</b> i les seves modificacions.",
            l: ['Inclou els canvis de domicili i l\'actualització de dades personals.',
                'Carrer del Nord, 60.'],
            f: 'La documentació depèn del seu cas. Confirmeu-la al 93 741 74 00 abans de desplaçar-vos.' },
      s: { t: "Oficina d'Atenció Ciutadana — premiademar.cat", u: 'https://premiademar.cat/oac' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'agosto', 'hace falta cita', 'necesito cita', 'turno',
          'cita previa', 'demanar cita', 'agost', 'cal cita'],
      es: { h: 'Se atiende <b>preferentemente con cita previa</b>, y <b>durante el mes de agosto solo con cita</b>.',
            l: ['La cita se pide por internet o llamando al 93 741 74 00.'],
            f: 'Si va en agosto sin cita, es probable que no le atiendan.' },
      ca: { h: "S'atén <b>preferentment amb cita prèvia</b>, i <b>durant el mes d'agost només amb cita</b>.",
            l: ['La cita es demana per internet o trucant al 93 741 74 00.'],
            f: "Si hi aneu a l'agost sense cita, és probable que no us atenguin." },
      s: { t: "Durant el mes d'agost, l'atenció a l'OAC només es farà amb cita prèvia — premiademar.cat", u: 'https://premiademar.cat/document.php?id=11040' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'oac 360', 'catastro', 'catastral', 'registro',
          'seu electronica', 'tramit', 'tramits', 'per internet', 'cadastre'],
      es: { h: 'Los trámites en línea están en premiademar.cat, y hay un servicio <b>OAC 360°</b> en premiademar.cat/oac360.',
            l: ['El Ayuntamiento tiene además un <b>Punt d\'Informació Cadastral</b>.'],
            f: 'Dudas: 93 741 74 00 o info@premiademar.cat.' },
      ca: { h: "Els tràmits en línia són a premiademar.cat, i hi ha un servei <b>OAC 360°</b> a premiademar.cat/oac360.",
            l: ["L'Ajuntament té a més un <b>Punt d'Informació Cadastral</b>."],
            f: 'Dubtes: 93 741 74 00 o info@premiademar.cat.' },
      s: { t: 'OAC 360° — premiademar.cat', u: 'https://premiademar.cat/oac360' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Premià de Mar?' },
    { lang: 'ES', t: '¿Dónde está la OAC y qué horario tiene?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'CA', t: 'Cal cita prèvia a l\'agost?' },
    { lang: 'ES', t: '¿Cuál es el teléfono?' },
  ],
},

// ===========================================================================
{
  slug: 'calp',
  nombre: 'Calp',
  articulo: 'de Calp',
  dominios: 'calp.es y noticias.calp.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'la OAC', tel: '965 833 600', email: 'estadistica@ajcalp.es' },
  idioma2: { cod: 'VA', clave: 'va', sigla: 'a la OAC', nombre: 'valenciano', sufijo: 'va' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'avenida de ifach', 'sabado', 'sabados',
          'atencio ciutadana', 'adreca', 'horari', 'a quina hora obrin', 'telefon', 'dissabte', 'dissabtes'],
      es: { h: 'La <b>Oficina de Atención Ciudadana (OAC)</b> está en la avenida de Ifach, 12, planta baja, 03710 Calp (Alicante).',
            l: ['Teléfono: 965 833 600.',
                'Invierno, del 1 de septiembre al 30 de junio: de lunes a jueves de 8:00 a 14:30; viernes de 8:00 a 14:00; y <b>sábados de 10:00 a 13:00</b>.',
                'Verano, del 1 de julio al 31 de agosto: de lunes a viernes de 8:00 a 14:30.'],
            f: 'La cita previa se pide en calp.es.' },
      va: { h: "L'<b>Oficina d'Atenció Ciutadana (OAC)</b> està a l'avinguda d'Ifach, 12, planta baixa, 03710 Calp (Alacant).",
            l: ['Telèfon: 965 833 600.',
                "Hivern, de l'1 de setembre al 30 de juny: de dilluns a dijous de 8:00 a 14:30; divendres de 8:00 a 14:00; i <b>dissabtes de 10:00 a 13:00</b>.",
                "Estiu, de l'1 de juliol al 31 d'agost: de dilluns a divendres de 8:00 a 14:30."],
            f: 'La cita prèvia es demana a calp.es.' },
      s: { t: 'Padrón de Habitantes — calp.es', u: 'https://www.calp.es/es/padron/info' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'actualizar', 'renovar',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me'],
      es: { h: 'Los trámites del <b>Padrón Municipal de Habitantes</b> se hacen <b>en persona</b> en la OAC, y <b>con cita previa</b>.',
            l: ['Tiene que ir la persona interesada: no vale que vaya otra por ella.',
                'Avenida de Ifach, 12, planta baja.'],
            f: 'Todos los trámites del Padrón Municipal de Habitantes son <b>gratuitos</b>.' },
      va: { h: 'Els tràmits del <b>Padró Municipal d\'Habitants</b> es fan <b>en persona</b> a l\'OAC, i <b>amb cita prèvia</b>.',
            l: ['Hi ha d\'anar la persona interessada: no val que hi vaja una altra per ella.',
                "Avinguda d'Ifach, 12, planta baixa."],
            f: "Tots els tràmits del Padró Municipal d'Habitants són <b>gratuïts</b>." },
      s: { t: 'Empadrónate o actualiza tus datos del padrón — calp.es', u: 'https://www.calp.es/es/padron/empadronate' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'solicitar cita', 'turno',
          'cita previa', 'demanar cita'],
      es: { h: 'La <b>cita previa</b> se solicita en calp.es/es/oac/cita-previa/solicitar.',
            l: ['Es obligatoria para los trámites de padrón.'],
            f: 'Si el sistema no le da hueco, llame al 965 833 600.' },
      va: { h: 'La <b>cita prèvia</b> se sol·licita a calp.es/es/oac/cita-previa/solicitar.',
            l: ['És obligatòria per als tràmits de padró.'],
            f: 'Si el sistema no li dona hora, telefone al 965 833 600.' },
      s: { t: 'Solicitar Cita Previa — Ayuntamiento de Calp', u: 'https://www.calp.es/es/oac/cita-previa/solicitar' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'enlaces', 'direcciones',
          'seu electronica', 'tramit', 'tramits', 'per internet', 'cataleg'],
      es: { h: 'Los trámites del padrón y las direcciones y enlaces de interés están publicados en calp.es.',
            l: ['El apartado de padrón tiene su propia sección de trámites.'],
            f: 'Dudas: 965 833 600.' },
      va: { h: 'Els tràmits del padró i les adreces i enllaços d\'interés estan publicats a calp.es.',
            l: ["L'apartat de padró té la seua pròpia secció de tràmits."],
            f: 'Dubtes: 965 833 600.' },
      s: { t: 'Trámites del Padrón — calp.es', u: 'https://www.calp.es/es/padron/tr%C3%A1mites' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Calp?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'ES', t: '¿Abren los sábados?' },
    { lang: 'VA', t: 'Com demane cita prèvia?' },
    { lang: 'ES', t: '¿Dónde está la oficina?' },
  ],
},

// ===========================================================================
{
  slug: 'mutxamel',
  nombre: 'Mutxamel',
  articulo: 'de Mutxamel',
  dominios: 'ayto.mutxamel.org y sedeelectronica.mutxamel.org',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'la OMAC', tel: '965 95 59 10', email: 'e-omac@mutxamel.org' },
  idioma2: { cod: 'VA', clave: 'va', sigla: 'a la OMAC', nombre: 'valenciano', sufijo: 'va' },
  kb: [
    {
      k: ['omac', 'oficina', 'atencion ciudadana', 'atencion al ciudadano', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'martinez ots',
          'atencio ciutadana', 'adreca', 'horari', 'a quina hora obrin', 'telefon'],
      es: { h: 'La <b>Oficina Municipal d\'Atenció al Ciutadà (OMAC)</b> está en la calle Francisco Martínez Ots, 1, 03110 Mutxamel.',
            l: ['Teléfono: 965 95 59 10. Correo: e-omac@mutxamel.org.',
                'Horario: de lunes a viernes de 8:30 a 14:00.',
                'Verano, del 1 de junio al 30 de septiembre: de 8:30 a 13:30.'],
            f: 'Se puede concertar cita por teléfono o escribiendo a e-omac@mutxamel.org antes de ir.' },
      va: { h: "L'<b>Oficina Municipal d'Atenció al Ciutadà (OMAC)</b> està al carrer Francisco Martínez Ots, 1, 03110 Mutxamel.",
            l: ['Telèfon: 965 95 59 10. Correu: e-omac@mutxamel.org.',
                'Horari: de dilluns a divendres de 8:30 a 14:00.',
                "Estiu, de l'1 de juny al 30 de setembre: de 8:30 a 13:30."],
            f: "Es pot concertar cita per telèfon o escrivint a e-omac@mutxamel.org abans d'anar-hi." },
      s: { t: "Oficina Municipal d'Atenció al Ciutadà — ayto.mutxamel.org", u: 'https://ayto.mutxamel.org/ca/area/omac/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'certificado', 'volante',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me', 'certificat', 'volant'],
      es: { h: 'Los trámites de <b>padró</b> los lleva la OMAC, que tiene su propio apartado de padrón en la web municipal.',
            l: ['Calle Francisco Martínez Ots, 1, de 8:30 a 14:00.'],
            f: 'La documentación depende de su caso. Confírmela en el 965 95 59 10 o en e-omac@mutxamel.org antes de desplazarse.' },
      va: { h: "Els tràmits de <b>padró</b> els porta l'OMAC, que té el seu propi apartat de padró al web municipal.",
            l: ['Carrer Francisco Martínez Ots, 1, de 8:30 a 14:00.'],
            f: 'La documentació depèn del seu cas. Confirme-la al 965 95 59 10 o a e-omac@mutxamel.org abans de desplaçar-se.' },
      s: { t: 'Padró — ayto.mutxamel.org', u: 'https://ayto.mutxamel.org/ca/area/omac/padro/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'turno', 'oficinas', 'pedanias', 'otras oficinas',
          'cita previa', 'demanar cita'],
      es: { h: 'La cita se concierta <b>por teléfono o por correo</b>: 965 95 59 10 o e-omac@mutxamel.org.',
            l: ['Además de la OMAC hay <b>oficinas satélite</b> que abren días concretos, de 9:30 a 13:30.'],
            f: 'Antes de ir a una oficina satélite conviene confirmar que ese día está abierta: hay temporadas en que cierran.' },
      va: { h: 'La cita es concerta <b>per telèfon o per correu</b>: 965 95 59 10 o e-omac@mutxamel.org.',
            l: ["A més de l'OMAC hi ha <b>oficines satèl·lit</b> que obrin dies concrets, de 9:30 a 13:30."],
            f: "Abans d'anar a una oficina satèl·lit convé confirmar que eixe dia està oberta: hi ha temporades en què tanquen." },
      s: { t: "Oficina Municipal d'Atenció al Ciutadà — ayto.mutxamel.org", u: 'https://ayto.mutxamel.org/ca/area/omac/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'un clic', 'registro',
          'seu electronica', 'tramit', 'tramits', 'per internet', 'cataleg'],
      es: { h: 'La <b>sede electrónica</b> está en sedeelectronica.mutxamel.org.',
            l: ['La OMAC publica además una guía llamada «El teu ajuntament en un clic».',
                'La atención se presta por tres canales: presencial, telemático y telefónico.'],
            f: 'Dudas: 965 95 59 10 o e-omac@mutxamel.org.' },
      va: { h: 'La <b>seu electrònica</b> està a sedeelectronica.mutxamel.org.',
            l: ["L'OMAC publica a més una guia que es diu «El teu ajuntament en un clic».",
                "L'atenció es presta per tres canals: presencial, telemàtic i telefònic."],
            f: 'Dubtes: 965 95 59 10 o e-omac@mutxamel.org.' },
      s: { t: 'El teu ajuntament en un clic — ayto.mutxamel.org', u: 'https://ayto.mutxamel.org/ca/area/omac/el-teu-ajuntament-en-un-clic/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Mutxamel?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'VA', t: 'Quin horari té la OMAC?' },
    { lang: 'ES', t: '¿Cómo pido cita previa?' },
    { lang: 'ES', t: '¿Dónde pido el volante?' },
  ],
},

// ===========================================================================
{
  slug: 'arteixo',
  nombre: 'Arteixo',
  articulo: 'de Arteixo',
  dominios: 'arteixo.org',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el Rexistro Xeral', tel: '981 659 000', email: 'rexistro@arteixo.org' },
  idioma2: { cod: 'GL', clave: 'gl', sigla: 'no Rexistro Xeral', nombre: 'gallego' },
  kb: [
    {
      k: ['oficina', 'atencion ciudadana', 'atencion cidada', 'registro', 'rexistro', 'direccion', 'telefono', 'contacto', 'ramon dopico', 'donde presento',
          'enderezo', 'telefono', 'onde presento'],
      es: { h: 'El <b>Rexistro Xeral</b> del Concello está en la praza Ramón Dopico, 1.',
            l: ['Teléfono: 981 659 000. También 981 659 008 (ext. 4008), 981 659 013 (ext. 4013) y 981 659 014 (ext. 4014).',
                'Correo: rexistro@arteixo.org.'],
            f: 'El <b>padrón y estadística</b> tienen teléfonos propios: 981 659 010 (ext. 4010) y 981 659 011 (ext. 4011).' },
      gl: { h: 'O <b>Rexistro Xeral</b> do Concello está na praza Ramón Dopico, 1.',
            l: ['Teléfono: 981 659 000. Tamén 981 659 008 (ext. 4008), 981 659 013 (ext. 4013) e 981 659 014 (ext. 4014).',
                'Correo: rexistro@arteixo.org.'],
            f: 'O <b>padrón e estatística</b> teñen teléfonos propios: 981 659 010 (ext. 4010) e 981 659 011 (ext. 4011).' },
      s: { t: 'Oficinas de rexistro — arteixo.org', u: 'https://arteixo.org/contanos/oficinas-de-rexistro/' },
    },
    {
      k: ['horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'sin cita', 'orden de llegada', 'cola', 'aforo', 'hace falta cita', 'necesito cita',
          'horario', 'ata que hora', 'a que hora abren', 'sen cita', 'orde de chegada'],
      es: { h: 'El horario del registro municipal funciona en <b>dos tramos distintos</b>, y no da igual a cuál vaya.',
            l: ['De <b>9:00 a 11:00</b>: <b>sin cita</b>, por orden de llegada, con límite de aforo.',
                'De <b>11:30 a 14:00</b>: <b>solo con cita previa</b>.',
                'El registro se hace en el mostrador de información general.'],
            f: 'Si va a última hora de la mañana sin cita, es probable que no le atiendan.' },
      gl: { h: 'O horario do rexistro municipal funciona en <b>dous tramos distintos</b>, e non dá igual a cal vaia.',
            l: ['De <b>9:00 a 11:00</b>: <b>sen cita</b>, por orde de chegada, con límite de aforo.',
                'De <b>11:30 a 14:00</b>: <b>só con cita previa</b>.',
                'O rexistro faise no mostrador de información xeral.'],
            f: 'Se vai a última hora da mañá sen cita, é probable que non o atendan.' },
      s: { t: 'Novo horario de atención ao público no rexistro municipal — arteixo.org', u: 'https://arteixo.org/novo-horario-de-atencion-ao-publico-no-rexistro-municipal/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'empadroamento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'certificado', 'volante',
          'empadroarme', 'alta padron', 'cambio de domicilio', 'certificado'],
      es: { h: 'El <b>empadroamento</b> tiene su propia ficha en arteixo.org, dentro del apartado de trámites.',
            l: ['El departamento de padrón y estadística atiende en el 981 659 010 y en el 981 659 011.'],
            f: 'La documentación depende de su caso. Confírmela en esos teléfonos antes de desplazarse.' },
      gl: { h: 'O <b>empadroamento</b> ten a súa propia ficha en arteixo.org, dentro do apartado de trámites.',
            l: ['O departamento de padrón e estatística atende no 981 659 010 e no 981 659 011.'],
            f: 'A documentación depende do seu caso. Confírmea neses teléfonos antes de desprazarse.' },
      s: { t: 'Empadroamento — arteixo.org', u: 'https://arteixo.org/tramites/empadroamento/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'solicitar cita', 'turno', 'sede electronica', 'tramite', 'tramites', 'internet', 'por internet',
          'cita previa', 'pedir cita', 'sede electronica', 'tramites', 'por internet'],
      es: { h: 'La <b>cita previa</b> se pide de tres maneras: por la sede electrónica municipal, escribiendo a citaprevia@arteixo.org, o llamando al <b>981 60 00 09</b>.',
            l: ['El Concello publica además una página con los teléfonos de cita previa de cada servicio.'],
            f: 'Los trámites están en arteixo.org/tramites.' },
      gl: { h: 'A <b>cita previa</b> pídese de tres maneiras: pola sede electrónica municipal, escribindo a citaprevia@arteixo.org, ou chamando ao <b>981 60 00 09</b>.',
            l: ['O Concello publica ademais unha páxina cos teléfonos de cita previa de cada servizo.'],
            f: 'Os trámites están en arteixo.org/tramites.' },
      s: { t: 'Cita previa — arteixo.org', u: 'https://arteixo.org/tramites/cita-previa/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Arteixo?' },
    { lang: 'ES', t: '¿Qué diferencia hay entre volante y certificado?' },
    { lang: 'ES', t: '¿Qué horario tienen?' },
    { lang: 'ES', t: '¿Puedo ir sin cita previa?' },
    { lang: 'GL', t: 'Onde está o Rexistro Xeral?' },
  ],
},

// ===========================================================================
{
  slug: 'redondela',
  nombre: 'Redondela',
  articulo: 'de Redondela',
  dominios: 'redondela.gal',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el Rexistro', tel: '986 400 300', email: 'rexistro@redondela.gal' },
  idioma2: { cod: 'GL', clave: 'gl', sigla: 'no Rexistro', nombre: 'gallego' },
  kb: [
    {
      k: ['oficina', 'atencion ciudadana', 'atencion cidada', 'concello', 'ayuntamiento', 'registro', 'rexistro', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'alfonso xii',
          'enderezo', 'ata que hora', 'telefono'],
      es: { h: 'El Concello está en la rúa Alfonso XII, 2, 36800 Redondela.',
            l: ['Centralita: 986 400 300. Correo general: info@redondela.gal.',
                'El <b>Rexistro</b> atiende los días laborables de <b>9:00 a 14:00</b>, y su correo es rexistro@redondela.gal.'],
            f: 'Atención á Cidadanía en servicios sociales: 986 402 608, laborables de 9:00 a 14:00.' },
      gl: { h: 'O Concello está na rúa Alfonso XII, 2, 36800 Redondela.',
            l: ['Centraliña: 986 400 300. Correo xeral: info@redondela.gal.',
                'O <b>Rexistro</b> atende os días laborables de <b>9:00 a 14:00</b>, e o seu correo é rexistro@redondela.gal.'],
            f: 'Atención á Cidadanía en servizos sociais: 986 402 608, laborables de 9:00 a 14:00.' },
      s: { t: 'Teléfonos e enderezos — redondela.gal', u: 'https://redondela.gal/concello/telefonos-e-enderezos/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'sin cita', 'hace falta cita', 'necesito cita', 'concejal', 'alcalde', 'infraestructuras',
          'cita previa', 'sen cita', 'concelleiro', 'alcalde', 'infraestruturas'],
      es: { h: 'La atención del alcalde y de los concejales se presta <b>sin cita previa</b>.',
            l: ['La excepción es el área de <b>Infraestruturas e Sostibilidade</b>, que sí exige reserva para determinados horarios.'],
            f: 'Para el resto, se puede acudir directamente en horario de atención al público.' },
      gl: { h: 'A atención do alcalde e dos concelleiros préstase <b>sen cita previa</b>.',
            l: ['A excepción é a área de <b>Infraestruturas e Sostibilidade</b>, que si esixe reserva para determinados horarios.'],
            f: 'Para o resto, pódese acudir directamente en horario de atención ao público.' },
      s: { t: 'O goberno local abre as portas do Concello ao veciñanza cun amplo horario de atención ao público — redondela.gal', u: 'https://redondela.gal/atencioonpublicoconcelleiros_noticias2023/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'empadroamento', 'certificado', 'certificado de empadronamiento', 'volante', 'cartafol', 'carpeta ciudadana',
          'empadroarme', 'certificado de empadroamento', 'cartafol cidadan'],
      es: { h: 'Los <b>certificados de empadroamento</b> se piden y se reciben por el <b>Cartafol Cidadán</b>, sin ir al Concello.',
            l: ['Desde ahí se consulta también el estado de los trámites y la situación de deuda tributaria.',
                'Y se presentan solicitudes por el registro electrónico.'],
            f: 'Si prefiere hacerlo presencialmente, el Rexistro atiende de 9:00 a 14:00 en días laborables.' },
      gl: { h: 'Os <b>certificados de empadroamento</b> pídense e recíbense polo <b>Cartafol Cidadán</b>, sen ir ao Concello.',
            l: ['Desde alí consúltase tamén o estado dos trámites e a situación de débeda tributaria.',
                'E preséntanse solicitudes polo rexistro electrónico.'],
            f: 'Se prefire facelo presencialmente, o Rexistro atende de 9:00 a 14:00 en días laborables.' },
      s: { t: 'Sede Electrónica — redondela.gal', u: 'https://redondela.gal/sede-electronica/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'formulario', 'formularios', 'impreso', 'instancia',
          'sede electronica', 'tramites', 'por internet', 'formularios'],
      es: { h: 'La <b>sede electrónica</b> está en redondela.gal/sede-electronica.',
            l: ['El Concello publica además los <b>formularios</b> municipales en redondela.gal/formularios.'],
            f: 'Dudas: 986 400 300 o info@redondela.gal.' },
      gl: { h: 'A <b>sede electrónica</b> está en redondela.gal/sede-electronica.',
            l: ['O Concello publica ademais os <b>formularios</b> municipais en redondela.gal/formularios.'],
            f: 'Dúbidas: 986 400 300 ou info@redondela.gal.' },
      s: { t: 'Formularios — redondela.gal', u: 'https://redondela.gal/formularios/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Redondela?' },
    { lang: 'ES', t: '¿Puedo presentar un escrito en el registro?' },
    { lang: 'ES', t: '¿Hace falta cita previa?' },
    { lang: 'ES', t: '¿Puedo hacerlo por internet?' },
    { lang: 'GL', t: 'Cal é o horario do Rexistro?' },
  ],
},

];
