// ---------------------------------------------------------------------------
//  LOS OCHO DEL DECIMO ENVIO — martes 29 de septiembre de 2026.
//  Comprobado en cada web municipal el 7 de septiembre de 2026.
//
//  Estos ocho estaban parados por falta de correo de contacto, no por otra
//  cosa. Se localizo con _envios/buscar-correo.mjs y se confirmo a mano.
//
//  Un aviso que salio de ahi: en Reus, saic@reus.cat NO es atencion ciudadana
//  sino el Servei d'Atencio i Informacio al CONTRIBUENT, o sea la ventanilla
//  de tributos. La OAC de verdad esta a la placa Mercadal 1 y no publica
//  correo propio, asi que el envio va al general del Ajuntament.
//
//  Catalan en Reus y Vilanova; gallego en Santiago y Lugo.
// ---------------------------------------------------------------------------

export const MUNICIPIOS_DIA10 = [

// ===========================================================================
{
  slug: 'aranjuez',
  nombre: 'Aranjuez',
  articulo: 'de Aranjuez',
  dominios: 'aranjuez.es y sede.aranjuez.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'la OAC', tel: '900 154 900 o 91 809 03 62', email: 'oac@aranjuez.es' },
  idioma2: null,
  kb: [
    {
      k: ['oac', 'oficina', 'atencion al ciudadano', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'stuart'],
      es: { h: 'La <b>Oficina de Atención al Ciudadano (OAC)</b> está en la calle Stuart, 79, planta baja.',
            l: ['Teléfonos: 900 154 900, que es <b>gratuito</b>, y 91 809 03 62.',
                'Horario: de lunes a viernes de 9:00 a 14:00.',
                'Correo: oac@aranjuez.es.'],
            f: 'Informa, normaliza impresos, registra solicitudes y gestiona quejas y sugerencias.' },
      s: { t: 'Atención al Ciudadano — aranjuez.es', u: 'https://www.aranjuez.es/oac/' },
    },
    {
      k: ['cita', 'cita previa', 'sin cita', 'pedir cita', 'turno', 'ticket', 'kiosko', 'fnmt', 'ventanilla unica'],
      es: { h: 'Los trámites <b>municipales</b> se atienden <b>sin cita previa</b>.',
            l: ['Se coge turno en el kiosko de tickets de la entrada del edificio de oficinas.',
                'Los trámites con <b>otras administraciones</b> sí requieren cita: acreditación FNMT para personas físicas y Ventanilla Única.',
                'Esas citas se piden en citaprevia.aranjuez.es.'],
            f: 'La cita previa se suprimió para los trámites municipales precisamente para facilitarlos.' },
      s: { t: 'Se suprime la cita previa en la OAC — aranjuez.es', u: 'https://www.aranjuez.es/se-suprime-la-cita-previa-en-la-oficina-de-atencion-al-ciudadano-para-facilitar-los-tramites-a-los-vecinos/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'cambio de domicilio'],
      es: { h: 'La OAC gestiona los trámites de <b>padrón</b> y los certificados de empadronamiento.',
            l: ['Sin cita previa: turno en el kiosko de la entrada.',
                'Calle Stuart, 79, planta baja, de 9:00 a 14:00.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 900 154 900, que es gratuito.' },
      s: { t: 'Atención al Ciudadano — aranjuez.es', u: 'https://www.aranjuez.es/mp_info_post/oficina-atencion-al-ciudadano/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'impresos', 'solicitudes'],
      es: { h: 'La <b>sede electrónica</b> está en sede.aranjuez.es.',
            l: ['La OAC publica además los impresos de solicitud en aranjuez.es.'],
            f: 'Dudas: 900 154 900 o oac@aranjuez.es.' },
      s: { t: 'Sede Electrónica — Ayuntamiento de Aranjuez', u: 'https://sede.aranjuez.es/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hace falta cita previa en la OAC?' },
    { lang: 'ES', t: '¿Dónde está la OAC?' },
    { lang: 'ES', t: '¿Hay un teléfono gratuito?' },
    { lang: 'ES', t: '¿Hasta qué hora abren?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'ES', t: '¿Qué horario tienen?' },
  ],
},

// ===========================================================================
{
  slug: 'reus',
  nombre: 'Reus',
  articulo: 'de Reus',
  dominios: 'reus.cat y seu.reus.cat',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'la OAC', tel: '010 o 977 010 010', email: 'ajuntament@reus.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'telefono', 'contacto', 'mercadal', 'ayuntamiento',
          'atencio ciutadana', 'adreca', 'telefon', 'ajuntament'],
      es: { h: 'La <b>Oficina d\'Atenció Ciutadana (OAC)</b> está en la plaça Mercadal, 1 — 43201 Reus, en la planta baja del Ayuntamiento.',
            l: ['Teléfonos: el <b>010</b> desde un fijo de Reus, o el 977 010 010 desde fuera o desde móvil.'],
            f: 'Da un servicio integral: información, tramitación directa y canalización de gestiones.' },
      ca: { h: 'L\'<b>Oficina d\'Atenció Ciutadana (OAC)</b> és a la plaça Mercadal, 1 — 43201 Reus, a la planta baixa de l\'Ajuntament.',
            l: ['Telèfons: el <b>010</b> des d\'un fix de Reus, o el 977 010 010 des de fora o des de mòbil.'],
            f: 'Dona un servei integral: informació, tramitació directa i canalització de gestions.' },
      s: { t: 'Oficina d\'Atenció Ciutadana (OAC) — reus.cat', u: 'https://www.reus.cat/oficina-datencio-ciutadana-oac' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'obligatoria', 'sin cita', 'opcion 2', 'reservar',
          'cita previa', 'demanar cita', 'obligatoria', 'opcio 2'],
      es: { h: 'La atención presencial en la OAC es <b>siempre con cita previa</b>.',
            l: ['Hay que llamar al <b>977 010 010</b> y marcar la <b>opción 2</b>.',
                'También se puede pedir en citaprevia.reus.cat.'],
            f: 'Sin cita no se atiende en la oficina presencial.' },
      ca: { h: 'L\'atenció presencial a l\'OAC és <b>sempre amb cita prèvia</b>.',
            l: ['Cal trucar al <b>977 010 010</b> i marcar l\'<b>opció 2</b>.',
                'També es pot demanar a citaprevia.reus.cat.'],
            f: 'Sense cita no s\'atén a l\'oficina presencial.' },
      s: { t: 'Atenció Presencial - OAC — reus.cat', u: 'https://www.reus.cat/atencio-ciutadana/atencio-presencial-oac' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'poblacion', 'certificado', 'cambio de domicilio', 'alta',
          'padro', 'empadronar-me', 'empadronament', 'poblacio', 'certificat', 'canvi de domicili'],
      es: { h: 'Reus tiene una <b>Oficina del Padró i Població</b> propia, además de la OAC.',
            l: ['Los trámites de padrón se gestionan también desde la OAC y desde la Carpeta Ciutadana.',
                'La Carpeta Ciutadana permite consultar trámites y datos personales, fiscales y de empadronamiento.'],
            f: 'Para la atención presencial hace falta cita: 977 010 010, opción 2.' },
      ca: { h: 'Reus té una <b>Oficina del Padró i Població</b> pròpia, a més de l\'OAC.',
            l: ['Els tràmits de padró es gestionen també des de l\'OAC i des de la Carpeta Ciutadana.',
                'La Carpeta Ciutadana permet consultar tràmits i dades personals, fiscals i d\'empadronament.'],
            f: 'Per a l\'atenció presencial cal cita: 977 010 010, opció 2.' },
      s: { t: 'Oficina del Padró i Població — reus.cat', u: 'https://www.reus.cat/oficina-del-padro-i-poblacio' },
    },
    {
      k: ['saic', 'tributos', 'contribuyente', 'impuestos', 'pagar', 'sant llorenc',
          'contribuent', 'tributs', 'impostos', 'pagar'],
      es: { h: 'El <b>SAIC</b> no es la OAC: es el <b>Servei d\'Atenció i Informació al Contribuent</b>, la ventanilla de tributos.',
            l: ['Está en el carrer Sant Llorenç, 25 — 43201 Reus.',
                'Teléfono: 977 010 010. Correo: saic@reus.cat.',
                'Horario: de lunes a viernes de 8:30 a 14:00; martes y miércoles también de 15:30 a 17:30.'],
            f: 'Ahí se informa sobre el pago de tributos y se hace efectivo. Para el resto, la OAC.' },
      ca: { h: 'El <b>SAIC</b> no és l\'OAC: és el <b>Servei d\'Atenció i Informació al Contribuent</b>, la finestreta de tributs.',
            l: ['És al carrer Sant Llorenç, 25 — 43201 Reus.',
                'Telèfon: 977 010 010. Correu: saic@reus.cat.',
                'Horari: de dilluns a divendres de 8:30 a 14:00; dimarts i dimecres també de 15:30 a 17:30.'],
            f: 'Allà s\'informa sobre el pagament de tributs i es fa efectiu. Per a la resta, l\'OAC.' },
      s: { t: 'SAIC Servei d\'Atenció i Informació al Contribuent — reus.cat', u: 'https://www.reus.cat/saic-servei-datencio-i-informacio-al-contribuent' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hace falta cita previa en la OAC?' },
    { lang: 'CA', t: 'On és l\'OAC?' },
    { lang: 'ES', t: '¿Necesito certificado digital?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'ES', t: '¿Qué diferencia hay entre la OAC y el SAIC?' },
  ],
},

// ===========================================================================
{
  slug: 'mijas',
  nombre: 'Mijas',
  articulo: 'de Mijas',
  dominios: 'mijas.es y sede.mijas.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'Atención Ciudadana', tel: '952 485 900', email: 'atencionciudadana@mijas.es' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'atencion ciudadana', 'direccion', 'telefono', 'contacto', 'virgen de la pena'],
      es: { h: '<b>Atención Ciudadana</b> está en la avenida de la Virgen de la Peña, 2.',
            l: ['Teléfono: 952 485 900.',
                'Correo: atencionciudadana@mijas.es.'],
            f: 'Gestiona certificados y volantes de empadronamiento, validación de certificados digitales y los movimientos del padrón.' },
      s: { t: 'Atención Ciudadana — mijas.es', u: 'https://www.mijas.es/portal/en/atencion-ciudadana/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'obligatoria', 'reservar', 'mayores', '65', 'preferente', '24 horas'],
      es: { h: 'La <b>cita previa es necesaria</b> para el padrón y para el certificado digital.',
            l: ['Alta y modificación del padrón de habitantes.',
                'Emisión de volantes y certificados de padrón.',
                'Certificado digital.',
                'Se pide en mijas.sedelectronica.es/citaprevia, o en el 952 485 900.'],
            f: 'Por internet se puede pedir <b>las 24 horas</b>; por teléfono, de 9:00 a 14:00. Los <b>mayores de 65 años</b> tienen horario preferente de 9:00 a 10:00.' },
      s: { t: 'Cita Previa Ayuntamiento de Mijas', u: 'https://www.mijas.es/portal/atencion-ciudadana/cita-previa-atencion-ciudadana/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'cambio de domicilio', 'renovacion', 'como empadronarse'],
      es: { h: 'Atención Ciudadana lleva las <b>altas, cambios de domicilio y renovaciones</b> del padrón municipal.',
            l: ['También la obtención de certificados y volantes de empadronamiento.',
                'Y la validación de certificados digitales.'],
            f: 'Todo con cita previa: mijas.sedelectronica.es/citaprevia o 952 485 900.' },
      s: { t: '¿Cómo empadronarse? — mijas.es', u: 'https://www.mijas.es/portal/atencion-ciudadana/como-empadronarse/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'volante por internet'],
      es: { h: 'La <b>sede electrónica</b> está en sede.mijas.es.',
            l: ['Desde ahí se puede solicitar el volante de empadronamiento sin ir a la oficina.'],
            f: 'Dudas: 952 485 900 o atencionciudadana@mijas.es.' },
      s: { t: 'Volante de empadronamiento — sede.mijas.es', u: 'https://sede.mijas.es/portal/sede/se_gestionar_lateral.jsp?codResi=1&language=es&codAdirecto=131' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hace falta cita previa para el padrón?' },
    { lang: 'ES', t: '¿Dónde está la oficina de atención ciudadana?' },
    { lang: 'ES', t: '¿Los mayores de 65 tienen horario preferente?' },
    { lang: 'ES', t: '¿Cómo me empadrono en Mijas?' },
  ],
},

// ===========================================================================
{
  slug: 'la-linea-de-la-concepcion',
  nombre: 'La Línea de la Concepción',
  articulo: 'de La Línea de la Concepción',
  dominios: 'lalinea.es y sedeelectronica.lalinea.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el Ayuntamiento', tel: '956 696 200', email: '010@lalinea.es' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'ayuntamiento', 'direccion', 'telefono', 'contacto', 'garcia cabreros'],
      es: { h: 'El Ayuntamiento está en la <b>plaza J. García Cabreros, s/n</b> — 11300 La Línea de la Concepción (Cádiz).',
            l: ['Teléfono: 956 696 200.',
                'Correo de atención ciudadana: 010@lalinea.es.'],
            f: 'La delegación de Hacienda está aparte, en la avenida de España.' },
      s: { t: 'Directorio — lalinea.es', u: 'https://lalinea.es/directorio' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita', '24 horas', 'automatico'],
      es: { h: 'La <b>cita previa</b> se pide por internet o por un teléfono automático.',
            l: ['Web: citas.lalinea.es, disponible <b>24 horas al día</b>.',
                'Teléfono automático de citas: 856 564 707.',
                'Sirve tanto para atención presencial como telefónica.'],
            f: 'Cubre la delegación de Hacienda y el resto de departamentos municipales.' },
      s: { t: 'El Ayuntamiento actualiza los contactos del sistema de cita previa', u: 'https://www.lalinea.es/portal/index.php/hoy-es-noticia/12123-el-ayuntamiento-actualiza-los-contactos-del-sistema-de-cita-previa-para-gestiones-ciudadanas' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'cambio de domicilio'],
      es: { h: 'Los trámites del <b>padrón</b> se gestionan en el Ayuntamiento, con cita previa.',
            l: ['La cita se pide en citas.lalinea.es o en el 856 564 707.',
                'También hay sede electrónica y Carpeta Ciudadana.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 956 696 200 antes de reservar.' },
      s: { t: 'El Ayuntamiento actualiza los medios de atención ciudadana — lalinea.es', u: 'https://lalinea.es/el-ayuntamiento-actualiza-los-medios-telefonicos-y-telematicos-de-atencion-ciudadana/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'carpeta ciudadana', 'notificaciones'],
      es: { h: 'La <b>sede electrónica</b> está en sedeelectronica.lalinea.es.',
            l: ['Incluye Carpeta Ciudadana, notificaciones y los procedimientos administrativos.'],
            f: 'Dudas: 956 696 200 o 010@lalinea.es.' },
      s: { t: 'Sede Electrónica de La Línea de la Concepción', u: 'https://www.sedeelectronica.lalinea.es/opencms/opencms/sede' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Cómo pido cita previa?' },
    { lang: 'ES', t: '¿Qué teléfono tienen?' },
    { lang: 'ES', t: '¿Dónde está el ayuntamiento?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'ES', t: '¿Puedo hacer trámites por internet?' },
  ],
},

// ===========================================================================
{
  slug: 'collado-villalba',
  nombre: 'Collado Villalba',
  articulo: 'de Collado Villalba',
  dominios: 'colladovillalba.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el SAC', tel: '91 856 28 50', email: 'sac@ayto-colladovillalba.org' },
  idioma2: null,
  kb: [
    {
      k: ['sac', 'oficina', 'oficinas', 'atencion al ciudadano', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'constitucion', 'batalla de bailen', 'tarde'],
      es: { h: 'El <b>Servicio de Atención al Ciudadano (SAC)</b> tiene <b>dos oficinas</b>.',
            l: ['Plaza de la Constitución, 1 — teléfono 91 856 28 50. De lunes a viernes de 8:30 a 14:00.',
                'Batalla de Bailén, 24 — teléfono 91 856 29 90. De lunes a viernes de 8:30 a 14:00, y <b>martes y jueves de 16:00 a 18:00</b>.',
                'Correo: sac@ayto-colladovillalba.org.'],
            f: 'Si necesita ir por la tarde, la oficina es la de Batalla de Bailén, martes o jueves.' },
      s: { t: 'Atención al Ciudadano y Estadística — colladovillalba.es', u: 'https://www.colladovillalba.es/servicio-de-atenci%C3%B3n-al-ciudadano-sac-y-estad%C3%ADstica' },
    },
    {
      k: ['cita', 'cita previa', 'sin cita', 'pedir cita', 'necesaria', 'obligatoria', 'prioridad', 'disponibilidad'],
      es: { h: 'Hace falta <b>cita previa</b> para el alta o el cambio de domicilio en el Padrón Municipal.',
            l: ['Sin cita se atiende hasta <b>una hora antes del cierre</b>, según disponibilidad.',
                'Quien lleva cita tiene prioridad.',
                'La cita se pide en web.ayto-colladovillalba.org.'],
            f: 'Es decir: sin cita puede que le atiendan, pero después de los que la tienen.' },
      s: { t: 'Atención al Ciudadano. Horarios y cita previa — colladovillalba.es', u: 'https://www.colladovillalba.es/ayuntamiento-y-sac-calle-real.-horarios-y-cita-previa' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'estadistica', 'certificado', 'volante', 'cambio de domicilio'],
      es: { h: 'El SAC lleva también <b>Estadística</b>, que es quien gestiona el Padrón Municipal.',
            l: ['Para el alta y el cambio de domicilio hace falta cita previa.',
                'Las dos oficinas del SAC atienden estos trámites.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 91 856 28 50 antes de reservar.' },
      s: { t: 'Atención al Ciudadano y Estadística — colladovillalba.es', u: 'https://www.colladovillalba.es/servicio-de-atenci%C3%B3n-al-ciudadano-sac-y-estad%C3%ADstica' },
    },
    {
      k: ['telefonos', 'telefonos de interes', 'localizacion', 'como llego'],
      es: { h: 'El Ayuntamiento publica su <b>listado de teléfonos</b> y la localización de sus oficinas.',
            l: ['Están en colladovillalba.es, en el apartado del municipio.'],
            f: 'Para el SAC: 91 856 28 50 (Plaza de la Constitución) o 91 856 29 90 (Batalla de Bailén).' },
      s: { t: 'Teléfonos Ayuntamiento — colladovillalba.es', u: 'https://www.colladovillalba.es/tu-municipio/telefonos-de-interes/ayuntamiento' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué oficina abre por las tardes?' },
    { lang: 'ES', t: '¿Me atienden sin cita?' },
    { lang: 'ES', t: '¿Qué teléfono tienen?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'ES', t: '¿Hace falta cita previa para el padrón?' },
  ],
},

// ===========================================================================
{
  slug: 'santiago-de-compostela',
  nombre: 'Santiago de Compostela',
  articulo: 'de Santiago de Compostela',
  dominios: 'santiagodecompostela.gal',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'Atención á Cidadanía', tel: '981 542 300', email: 'informacion@santiagodecompostela.gal' },
  idioma2: { cod: 'GL', clave: 'gl', sigla: 'na Atención á Cidadanía', nombre: 'gallego' },
  kb: [
    {
      k: ['oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'salvador allende', 'verano',
          'atencion cidada', 'enderezo', 'horario', 'veran'],
      es: { h: '<b>Atención á Cidadanía</b> está en la rúa Presidente Salvador Allende, 4, bajo.',
            l: ['La atención presencial es <b>con cita previa</b>: 881 505 107 o citaprevia.santiagodecompostela.gal.',
                'Horario: de lunes a viernes de 9:00 a 14:00.',
                'Verano, del 15 de junio al 15 de septiembre: de 9:00 a 13:00.',
                'Atención prioritaria por teléfono: 981 542 300 y 981 543 128. Correo: informacion@santiagodecompostela.gal.'],
            f: 'El teléfono y el correo son la vía preferente; la presencial exige cita.' },
      gl: { h: '<b>Atención á Cidadanía</b> está na rúa Presidente Salvador Allende, 4, baixo.',
            l: ['A atención presencial é <b>con cita previa</b>: 881 505 107 ou citaprevia.santiagodecompostela.gal.',
                'Horario: de luns a venres de 9:00 a 14:00.',
                'Verán, do 15 de xuño ao 15 de setembro: de 9:00 a 13:00.',
                'Atención prioritaria por teléfono: 981 542 300 e 981 543 128. Correo: informacion@santiagodecompostela.gal.'],
            f: 'O teléfono e o correo son a vía preferente; a presencial esixe cita.' },
      s: { t: 'Atención á Cidadanía — santiagodecompostela.gal', u: 'http://santiagodecompostela.gal/casa_concello/servizo.php?c=31&lg=cas&txt=ser_aten_cidadan' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'raxoi', 'certificado', 'volante', 'sin cita', 'numero', 'turno',
          'empadroarme', 'empadroamento', 'padron', 'sen cita'],
      es: { h: 'El <b>Padrón Municipal de Habitantes</b> está en los bajos de Raxoi, con entrada por la avenida de Raxoi.',
            l: ['Teléfono: 981 542 318. Correo: padronmh@santiagodecompostela.gal.',
                'Horario: de lunes a viernes de 9:00 a 14:00.',
                'La atención presencial es <b>sin cita previa</b>: solo hay que coger número en la máquina de la entrada.'],
            f: 'Es distinto de Atención á Cidadanía, que sí exige cita.' },
      gl: { h: 'O <b>Padrón Municipal de Habitantes</b> está nos baixos de Raxoi, con entrada pola avenida de Raxoi.',
            l: ['Teléfono: 981 542 318. Correo: padronmh@santiagodecompostela.gal.',
                'Horario: de luns a venres de 9:00 a 14:00.',
                'A atención presencial é <b>sen cita previa</b>: só hai que coller número na máquina da entrada.'],
            f: 'É distinto de Atención á Cidadanía, que si esixe cita.' },
      s: { t: 'Padrón Municipal de Habitantes — santiagodecompostela.gal', u: 'https://santiagodecompostela.gal/es/servicios-municipales/servicios-generales/padron-municipal-de-habitantes' },
    },
    {
      k: ['registro', 'registro general', 'presentar documentos', 'instancia',
          'rexistro', 'rexistro xeral', 'presentar documentos'],
      es: { h: 'El <b>Rexistro Xeral</b> está en la misma dirección: rúa Presidente Salvador Allende, 4, bajo.',
            l: ['Teléfono: 981 543 122.',
                'Horario: de lunes a viernes de 9:00 a 14:00; en verano, de 9:00 a 13:00.',
                'Atiende <b>sin cita previa</b>, con número de la máquina dispensadora.'],
            f: 'Comparte edificio con Atención á Cidadanía, pero no comparte el requisito de cita.' },
      gl: { h: 'O <b>Rexistro Xeral</b> está no mesmo enderezo: rúa Presidente Salvador Allende, 4, baixo.',
            l: ['Teléfono: 981 543 122.',
                'Horario: de luns a venres de 9:00 a 14:00; no verán, de 9:00 a 13:00.',
                'Atende <b>sen cita previa</b>, con número da máquina dispensadora.'],
            f: 'Comparte edificio con Atención á Cidadanía, pero non comparte o requisito de cita.' },
      s: { t: 'Rexistro Xeral — santiagodecompostela.gal', u: 'http://santiagodecompostela.gal/casa_concello/servizo.php?c=31&lg=gal&txt=ser_rexistro_xeral' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo',
          'sede electronica', 'tramites', 'catalogo'],
      es: { h: 'El <b>catálogo de trámites</b> está en la sede electrónica.',
            l: ['sede.santiagodecompostela.gal.',
                'Ahí figuran también las oficinas de registro presenciales.'],
            f: 'Dudas: 981 542 300 o informacion@santiagodecompostela.gal.' },
      gl: { h: 'O <b>catálogo de trámites</b> está na sede electrónica.',
            l: ['sede.santiagodecompostela.gal.',
                'Alí figuran tamén as oficinas de rexistro presenciais.'],
            f: 'Dúbidas: 981 542 300 ou informacion@santiagodecompostela.gal.' },
      s: { t: 'Catálogo de trámites — sede.santiagodecompostela.gal', u: 'https://sede.santiagodecompostela.gal/sta/CarpetaPublic/doEvent?APP_CODE=STA&PAGE_CODE=PTS_CATSERV&lang=ES' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hace falta cita previa para el padrón?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'GL', t: 'Que horario ten no verán?' },
    { lang: 'ES', t: '¿Cuál es el teléfono?' },
    { lang: 'GL', t: 'Onde está o Padrón Municipal?' },
  ],
},

// ===========================================================================
{
  slug: 'lugo',
  nombre: 'Lugo',
  articulo: 'de Lugo',
  dominios: 'concellodelugo.gal y lugo.gal',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el 010', tel: '010 o 982 297 350', email: '010@lugo.gal' },
  idioma2: { cod: 'GL', clave: 'gl', sigla: 'no 010', nombre: 'gallego' },
  kb: [
    {
      k: ['010', 'oficina', 'atencion ciudadana', 'informacion municipal', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'sabado',
          'atencion cidada', 'ordutegia', 'horario', 'sabado', 'telefono'],
      es: { h: 'El <b>Servizo de Información Municipal 010</b> es el canal de atención del Concello.',
            l: ['Marcando el <b>010</b> dentro del término municipal de Lugo; el 982 297 350 desde fuera.',
                'Correo: 010@lugo.gal.',
                'Atención presencial: de lunes a viernes laborables de 9:00 a 14:00.',
                'Atención telefónica: de lunes a viernes laborables de <b>8:30 a 20:30</b>, y los sábados laborables de 9:00 a 14:00.'],
            f: 'El teléfono tiene un horario mucho más amplio que la ventanilla.' },
      gl: { h: 'O <b>Servizo de Información Municipal 010</b> é a canle de atención do Concello.',
            l: ['Marcando o <b>010</b> dentro do termo municipal de Lugo; o 982 297 350 desde fóra.',
                'Correo: 010@lugo.gal.',
                'Atención presencial: de luns a venres laborables de 9:00 a 14:00.',
                'Atención telefónica: de luns a venres laborables de <b>8:30 a 20:30</b>, e os sábados laborables de 9:00 a 14:00.'],
            f: 'O teléfono ten un horario moito máis amplo que a ventanilla.' },
      s: { t: 'Servizo de Información Municipal 010 — concellodelugo.gal', u: 'https://concellodelugo.gal/gl/actuacions/servizo-de-informacion-municipal-010' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'obligatorio', 'cambio de domicilio', 'certificado',
          'empadroarme', 'empadroamento', 'padron', 'obrigatorio'],
      es: { h: 'El <b>Padrón Municipal de Habitantes</b> es el registro donde constan los vecinos del municipio.',
            l: ['Empadronarse es <b>obligatorio</b> para toda persona que viva en España, en el municipio donde resida habitualmente.',
                'Hay que comunicar al Concello cualquier cambio de datos personales o de domicilio.'],
            f: 'Información y trámites: el 010, o el 982 297 350 desde fuera de Lugo.' },
      gl: { h: 'O <b>Padrón Municipal de Habitantes</b> é o rexistro onde constan os veciños do municipio.',
            l: ['Empadroarse é <b>obrigatorio</b> para toda persoa que viva en España, no municipio onde resida habitualmente.',
                'Cómpre comunicar ao Concello calquera cambio de datos persoais ou de domicilio.'],
            f: 'Información e trámites: o 010, ou o 982 297 350 desde fóra de Lugo.' },
      s: { t: 'Servizo de Información Municipal 010 — concellodelugo.gal', u: 'https://concellodelugo.gal/gl/actuacions/servizo-de-informacion-municipal-010' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita',
          'cita previa', 'solicitar cita'],
      es: { h: 'La <b>cita previa</b> se solicita desde la web del Concello.',
            l: ['concellodelugo.gal, en el apartado de solicitar cita previa.',
                'O llamando al 010.'],
            f: 'El 010 atiende hasta las 20:30 entre semana, así que hay margen para llamar después del trabajo.' },
      gl: { h: 'A <b>cita previa</b> solicítase desde a web do Concello.',
            l: ['concellodelugo.gal, no apartado de solicitar cita previa.',
                'Ou chamando ao 010.'],
            f: 'O 010 atende ata as 20:30 entre semana, así que hai marxe para chamar despois do traballo.' },
      s: { t: 'Solicitar Cita Previa — concellodelugo.gal', u: 'https://concellodelugo.gal/gl/solicitar-cita-previa' },
    },
    {
      k: ['registro', 'rexistro xeral', 'presentar documentos', 'carta de servizos', 'sede electronica', 'carpeta',
          'rexistro', 'presentar documentos'],
      es: { h: 'El <b>Rexistro Xeral</b> tiene publicada su carta de servicios.',
            l: ['Está en concellodelugo.gal.',
                'La sede electrónica es lugo.gal/portal y la Carpeta Ciudadana, carpeta.lugo.gal.'],
            f: 'Dudas: el 010, o el 982 297 350.' },
      gl: { h: 'O <b>Rexistro Xeral</b> ten publicada a súa carta de servizos.',
            l: ['Está en concellodelugo.gal.',
                'A sede electrónica é lugo.gal/portal e a Carpeta Cidadá, carpeta.lugo.gal.'],
            f: 'Dúbidas: o 010, ou o 982 297 350.' },
      s: { t: 'Carta de servizos do Negociado Rexistro Xeral — concellodelugo.gal', u: 'https://concellodelugo.gal/gl/carta-de-servizos-do-negociado-rexistro-xeral' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hasta qué hora atiende el 010?' },
    { lang: 'ES', t: '¿Atienden sin cita?' },
    { lang: 'GL', t: 'É obrigatorio empadroarse?' },
    { lang: 'ES', t: '¿Cómo entro en la sede electrónica?' },
    { lang: 'ES', t: '¿Qué diferencia hay entre volante y certificado?' },
  ],
},

// ===========================================================================
{
  slug: 'vilanova-i-la-geltru',
  nombre: 'Vilanova i la Geltrú',
  articulo: 'de Vilanova i la Geltrú',
  dominios: 'vilanova.cat y seuelectronica.vilanova.cat',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'la OAC', tel: '93 814 39 00 o 010', email: 'atencio@vilanova.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'placa de la vila', 'martes', 'tarde',
          'atencio ciutadania', 'adreca', 'horari', 'telefon', 'dimarts', 'tarda'],
      es: { h: 'La <b>Oficina d\'Atenció a la Ciutadania (OAC)</b> está en la plaça de la Vila, 8.',
            l: ['Teléfonos: 93 814 39 00 y el <b>010</b>.',
                'Lunes, miércoles, jueves y viernes: de 8:00 a 15:00.',
                '<b>Martes: de 8:00 a 17:00.</b>',
                'Atención telefónica: de lunes a viernes de 8:00 a 14:00.'],
            f: 'Correo: atencio@vilanova.cat. El martes es el único día con horario largo.' },
      ca: { h: 'L\'<b>Oficina d\'Atenció a la Ciutadania (OAC)</b> és a la plaça de la Vila, 8.',
            l: ['Telèfons: 93 814 39 00 i el <b>010</b>.',
                'Dilluns, dimecres, dijous i divendres: de 8:00 a 15:00.',
                '<b>Dimarts: de 8:00 a 17:00.</b>',
                'Atenció telefònica: de dilluns a divendres de 8:00 a 14:00.'],
            f: 'Correu: atencio@vilanova.cat. El dimarts és l\'únic dia amb horari llarg.' },
      s: { t: 'OAC - Oficina d\'Atenció a la Ciutadania — vilanova.cat', u: 'https://www.vilanova.cat/atencio_ciutadania/oac' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'cambio de domicilio',
          'padro', 'empadronar-me', 'empadronament', 'certificat', 'volant', 'canvi de domicili'],
      es: { h: 'Los servicios de <b>padró</b> se atienden en el mismo horario que la OAC.',
            l: ['Lunes, miércoles, jueves y viernes de 8:00 a 15:00.',
                'Martes de 8:00 a 17:00.',
                'Plaça de la Vila, 8.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 93 814 39 00 antes de ir.' },
      ca: { h: 'Els serveis de <b>padró</b> s\'atenen en el mateix horari que l\'OAC.',
            l: ['Dilluns, dimecres, dijous i divendres de 8:00 a 15:00.',
                'Dimarts de 8:00 a 17:00.',
                'Plaça de la Vila, 8.'],
            f: 'La documentació concreta depèn del seu cas. Confirmi-la al 93 814 39 00 abans d\'anar-hi.' },
      s: { t: 'Oficina d\'Atenció Ciutadana - OAC — vilanova.cat', u: 'https://www.vilanova.cat/directori/detall?id=40607' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'terminal', 'planta baja',
          'cita previa', 'demanar cita', 'terminal', 'planta baixa'],
      es: { h: 'La <b>cita previa</b> se pide de dos formas.',
            l: ['Por el portal municipal, en www.vilanova.cat.',
                'O desde un terminal de tramitación situado en la planta baja del Ayuntamiento.'],
            f: 'El terminal es útil si ya está en el edificio y quiere reservar para otro día.' },
      ca: { h: 'La <b>cita prèvia</b> es demana de dues maneres.',
            l: ['Pel portal municipal, a www.vilanova.cat.',
                'O des d\'un terminal de tramitació situat a la planta baixa de l\'Ajuntament.'],
            f: 'El terminal és útil si ja és a l\'edifici i vol reservar per a un altre dia.' },
      s: { t: 'Atenció a la ciutadania — vilanova.cat', u: 'https://www.vilanova.cat/atencio_ciutadania/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet',
          'seu electronica', 'tramit', 'tramits', 'per internet'],
      es: { h: 'La <b>seu electrònica</b> está en seuelectronica.vilanova.cat.',
            l: ['Ahí se pueden hacer trámites sin ir a la OAC.'],
            f: 'Dudas: 93 814 39 00, el 010, o atencio@vilanova.cat.' },
      ca: { h: 'La <b>seu electrònica</b> és a seuelectronica.vilanova.cat.',
            l: ['Allà es poden fer tràmits sense anar a l\'OAC.'],
            f: 'Dubtes: 93 814 39 00, el 010, o atencio@vilanova.cat.' },
      s: { t: 'Serveis d\'Atenció a la Ciutadania — seuelectronica.vilanova.cat', u: 'https://seuelectronica.vilanova.cat/content/tramits/18_MEM2024_Serveis%20Atenci%C3%B3%20a%20la%20Ciutadania.pdf' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué día abre la OAC por la tarde?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'ES', t: '¿Cómo pido cita previa?' },
    { lang: 'ES', t: '¿Dónde pido el volante?' },
    { lang: 'CA', t: 'Quin horari té l\'OAC els dimarts?' },
  ],
},

];
