// ---------------------------------------------------------------------------
//  LAS SEIS DEL ENVIO 17 — miercoles 7 de octubre.
//  Comprobado en cada web municipal el 10 de septiembre de 2026.
//
//  BURJASSOT ENTRA, y con correo. La tanda 15 lo habia descartado porque el
//  unico correo que se le encontraba era informacionburjassot@atenciontributaria.es,
//  la ventanilla de tributos. La ficha del SAC publica registro@burjassot.es,
//  que si es atencion ciudadana y si es su dominio.
//
//  DOS DOMINIOS QUE HAN CAMBIADO Y CONVIENE APUNTAR:
//   - Santa Eularia ya no es santaeulalia.net: redirige a santaeulariadesriu.com.
//   - La Orotava publica en su ficha del Registro el correo
//     registro.general@villadelaorotva.org — con "orotva", sin la segunda "a".
//     Tiene toda la pinta de ser una errata SUYA, asi que la demo no lo usa:
//     se queda en el telefono. No inventamos el correcto.
//
//  Idiomas: catalan en Santa Eularia, Llucmajor y Marratxi; valenciano en
//  Burjassot. La Orotava y Soria, solo castellano.
// ---------------------------------------------------------------------------

export const MUNICIPIOS_DIA19 = [

// ===========================================================================
{
  slug: 'la-orotava',
  nombre: 'La Orotava',
  articulo: 'de la Villa de La Orotava',
  dominios: 'laorotava.es y su sede electrónica',
  fecha: '10 de septiembre de 2026',
  oficina: { sigla: 'el Registro General', tel: '922 32 44 44', email: '' },
  idioma2: null,
  kb: [
    {
      k: ['registro', 'registro general', 'oficina', 'donde', 'direccion', 'ayuntamiento', 'plaza del ayuntamiento', 'presentar documentos', 'instancia', 'atencion ciudadana', 'telefono', 'llamar', 'contacto', 'extension'],
      es: { h: 'El <b>Registro General</b> está en la plaza del Ayuntamiento, 1, 38300 La Orotava.',
            l: ['Teléfono: 922 32 44 44, extensión 2015.',
                'Es donde se presentan los escritos y las solicitudes dirigidas al Ayuntamiento.'],
            f: 'Ese mismo número es la centralita del Ayuntamiento.' },
      s: { t: 'Registro General — laorotava.es', u: 'http://www.laorotava.es/es/registro-general' },
    },
    {
      k: ['horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'tarde', 'por la tarde', 'verano', 'que dias', 'sabado'],
      es: { h: 'El Registro General atiende <b>de lunes a viernes de 8:00 a 13:30</b>.',
            l: ['La web no publica horario de tarde ni un horario distinto para el verano.'],
            f: 'Si necesita confirmarlo, llame al 922 32 44 44.' },
      s: { t: 'Registro General — laorotava.es', u: 'http://www.laorotava.es/es/registro-general' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'hace falta cita', 'necesito cita', 'reservar', 'turno', 'por telefono'],
      es: { h: 'La <b>cita previa</b> se pide llamando al <b>922 32 44 44</b>.',
            l: ['Al llamar hay que decir con qué servicio se quiere la cita.'],
            f: 'El Ayuntamiento publica el detalle de la cita previa en laorotava.es.' },
      s: { t: 'Cita previa — laorotava.es', u: 'http://www.laorotava.es/es/cita-previa' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'nuevo vecino', 'certificado', 'volante', 'residencia', 'documentacion', 'que necesito', 'que llevar', 'documentos'],
      es: { h: 'Los <b>certificados de residencia y los trámites de padrón</b> se hacen en el Registro General.',
            l: ['Está en la plaza del Ayuntamiento, 1, de 8:00 a 13:30.'],
            f: 'La web no publica la documentación concreta de cada caso. Confírmela en el 922 32 44 44 antes de desplazarse.' },
      s: { t: 'Información y atención al ciudadano — laorotava.es', u: 'http://www.laorotava.es/es/informacion-y-atencion-al-ciudadano' },
    },
    {
      k: ['sede electronica', 'administracion electronica', 'internet', 'por internet', 'online', 'tramite', 'tramites', 'certificado digital', 'identificarse'],
      es: { h: 'El Ayuntamiento tiene <b>administración electrónica</b> y un catálogo de trámites en su web.',
            l: ['Desde ahí se pueden presentar solicitudes sin desplazarse.'],
            f: 'Se abre desde laorotava.es.' },
      s: { t: 'Administración electrónica — laorotava.es', u: 'http://www.laorotava.es/es/areas-municipales/administracion-electronica' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en La Orotava?' },
    { lang: 'ES', t: '¿Qué horario tiene el registro?' },
    { lang: 'ES', t: '¿Cómo pido cita previa?' },
    { lang: 'ES', t: '¿Puedo hacerlo por internet?' },
    { lang: 'ES', t: '¿Dónde pido el volante?' },
  ],
},

// ===========================================================================
{
  slug: 'soria',
  nombre: 'Soria',
  articulo: 'de Soria',
  dominios: 'soria.es y soria.sedelectronica.es',
  fecha: '10 de septiembre de 2026',
  oficina: { sigla: 'el 010', tel: '010 · 975 23 41 00', email: '' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'ayuntamiento', 'donde', 'direccion', 'plaza mayor', 'atencion ciudadana', 'registro', 'estadistica', 'presentar documentos', 'instancia'],
      es: { h: 'El Ayuntamiento está en la <b>plaza Mayor, 1</b>, 42001 Soria.',
            l: ['Ahí están el Registro y Estadística, que es quien lleva el padrón.'],
            f: 'A los dos servicios se va con cita previa.' },
      s: { t: 'Cita previa — Ayuntamiento de Soria', u: 'https://citaprevia.soria.es/citaprevia/' },
    },
    {
      k: ['telefono', 'llamar', 'por telefono', 'contacto', '010', 'atencion telefonica', 'desde fuera', 'horario', 'hasta que hora', 'abren', 'cierran', 'que dias'],
      es: { h: 'El teléfono de información es el <b>010</b>, y el <b>975 23 41 00</b> desde fuera de Soria.',
            l: ['Atiende de lunes a viernes de 9:00 a 14:00.'],
            f: 'Por ese mismo teléfono se puede pedir la cita previa.' },
      s: { t: 'Teléfono 010 — soria.es', u: 'https://www.soria.es/es/servicios/telefono-010' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'hace falta cita', 'necesito cita', 'reservar', 'turno', 'por internet', 'online', 'anular'],
      es: { h: 'La <b>cita previa</b> se pide en citaprevia.soria.es o llamando al 010.',
            l: ['Hay cita para Registro y para Estadística, entre otros servicios municipales.',
                'Al pedirla hay que elegir el servicio y el tipo de gestión.'],
            f: 'Desde la misma web se puede consultar una cita ya pedida.' },
      s: { t: 'Cita previa — Ayuntamiento de Soria', u: 'https://citaprevia.soria.es/citaprevia/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta', 'alta padron', 'baja', 'cambio de domicilio', 'modificacion', 'nuevo vecino', 'certificado', 'volante', 'documentacion', 'que necesito', 'que llevar', 'documentos'],
      es: { h: 'En <b>Estadística</b> se hacen las altas, las bajas, las modificaciones y los certificados del padrón.',
            l: ['Todo ello con cita previa, que se pide en citaprevia.soria.es o en el 010.'],
            f: 'La web no publica la documentación concreta de cada caso. Confírmela en el 010 antes de desplazarse.' },
      s: { t: 'Cita previa — Ayuntamiento de Soria', u: 'https://citaprevia.soria.es/citaprevia/' },
    },
    {
      k: ['sede electronica', 'internet', 'tramite', 'tramites', 'catalogo', 'certificado digital', 'identificarse', 'presentar'],
      es: { h: 'La <b>sede electrónica</b> está en soria.sedelectronica.es.',
            l: ['El Ayuntamiento publica además un catálogo general de servicios en soria.es.'],
            f: 'Es la vía para presentar solicitudes sin pedir cita.' },
      s: { t: 'Trámites — soria.es', u: 'https://www.soria.es/es/gobierno/tramites' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Soria?' },
    { lang: 'ES', t: '¿Dónde está la oficina de atención ciudadana?' },
    { lang: 'ES', t: '¿Cómo pido cita previa?' },
    { lang: 'ES', t: '¿Cuál es el teléfono?' },
    { lang: 'ES', t: '¿Puedo hacerlo por internet?' },
  ],
},

// ===========================================================================
{
  slug: 'santa-eularia-des-riu',
  nombre: 'Santa Eulària des Riu',
  articulo: 'de Santa Eulària des Riu',
  dominios: 'santaeulariadesriu.com',
  fecha: '10 de septiembre de 2026',
  oficina: { sigla: 'el Ayuntamiento', tel: '971 33 28 00', email: '' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'Ajuntament", nombre: 'catalán' },
  kb: [
    {
      k: ['oficina', 'ayuntamiento', 'donde', 'direccion', 'placa d espanya', 'plaza de espana', 'telefono', 'llamar', 'contacto', 'atencion ciudadana',
          'on es', 'adreca', 'telefon', 'ajuntament'],
      es: { h: 'El Ayuntamiento está en la <b>plaça d’Espanya, 1</b>, 07840 Santa Eulària des Riu.',
            l: ['Teléfono: 971 33 28 00.'],
            f: 'Hay además oficinas municipales en Jesús y en es Puig d’en Valls.' },
      ca: { h: "L'Ajuntament és a la <b>plaça d’Espanya, 1</b>, 07840 Santa Eulària des Riu.",
            l: ['Telèfon: 971 33 28 00.'],
            f: "Hi ha a més oficines municipals a Jesús i a es Puig d’en Valls." },
      s: { t: 'Cita previa — Ajuntament de Santa Eulària des Riu', u: 'https://santaeulariadesriu.com/index.php/es/ayuntamiento/cita-previa' },
    },
    {
      k: ['jesus', 'puig d en valls', 'es puig', 'otra oficina', 'oficinas', 'mas cerca', 'cercana', 'cual me toca', 'caja', 'transporte', 'tarjeta',
          'altra oficina', 'oficines', 'mes propera', 'transport', 'targeta'],
      es: { h: 'Hay <b>dos oficinas municipales</b> además de la del Ayuntamiento.',
            l: ['La de <b>Jesús</b> hace padrón, caja, registro y tarjeta de transporte público.',
                'La de <b>es Puig d’en Valls</b> hace padrón, caja y registro.'],
            f: 'En las dos se atiende con cita previa.' },
      ca: { h: "Hi ha <b>dues oficines municipals</b> a més de la de l'Ajuntament.",
            l: ['La de <b>Jesús</b> fa padró, caixa, registre i targeta de transport públic.',
                "La de <b>es Puig d’en Valls</b> fa padró, caixa i registre."],
            f: 'A totes dues s’atén amb cita prèvia.' },
      s: { t: 'Cita previa — Ajuntament de Santa Eulària des Riu', u: 'https://santaeulariadesriu.com/index.php/es/ayuntamiento/cita-previa' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'hace falta cita', 'necesito cita', 'reservar', 'turno', 'dni', 'pasaporte', 'catastro', 'urbanismo', 'que servicios',
          'cita previa', 'demanar cita', 'cal cita', 'passaport', 'quins serveis'],
      es: { h: 'Santa Eulària atiende <b>con cita previa</b>, y la pide por servicio.',
            l: ['Hay cita para <b>Padrón</b> y para <b>Registro de entrada</b>, que son los dos de atención ciudadana.',
                'Y también para DNI, pasaporte, catastro, urbanismo, caja y la tarjeta de transporte público.'],
            f: 'El listado completo está publicado en la web del Ayuntamiento.' },
      ca: { h: "Santa Eulària atén <b>amb cita prèvia</b>, i es demana per servei.",
            l: ['Hi ha cita per al <b>Padró</b> i per al <b>Registre d’entrada</b>, que són els dos d’atenció ciutadana.',
                'I també per a DNI, passaport, cadastre, urbanisme, caixa i la targeta de transport públic.'],
            f: "El llistat complet està publicat al web de l'Ajuntament." },
      s: { t: 'Cita previa — Ajuntament de Santa Eulària des Riu', u: 'https://santaeulariadesriu.com/index.php/es/ayuntamiento/cita-previa' },
    },
    {
      k: ['horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'tarde', 'por la tarde', 'verano', 'que dias',
          'horari', 'fins a quina hora', 'obren', 'tanquen', 'estiu'],
      es: { h: 'La página de cita previa <b>no publica el horario</b> de las oficinas, y no se lo voy a estimar.',
            l: ['Da la dirección y el teléfono, pero no las horas de atención.'],
            f: 'Confírmelo en el 971 33 28 00 antes de desplazarse.' },
      ca: { h: "La pàgina de cita prèvia <b>no publica l'horari</b> de les oficines, i no l'hi estimaré.",
            l: ['Dóna l’adreça i el telèfon, però no les hores d’atenció.'],
            f: 'Confirmeu-ho al 971 33 28 00 abans de desplaçar-vos.' },
      s: { t: 'Cita previa — Ajuntament de Santa Eulària des Riu', u: 'https://santaeulariadesriu.com/index.php/es/ayuntamiento/cita-previa' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'cambio de domicilio', 'nuevo vecino', 'certificado', 'volante', 'convivencia', 'residencia',
          'padro', 'empadronar-me', 'empadronament', 'canvi de domicili', 'certificat', 'convivencia'],
      es: { h: 'Los <b>certificados de residencia, empadronamiento y convivencia</b> se piden al servicio de Padrón, con cita previa.',
            l: ['El Padrón atiende en el Ayuntamiento y en las oficinas de Jesús y es Puig d’en Valls.'],
            f: 'Para la documentación concreta de cada caso, llame al 971 33 28 00.' },
      ca: { h: 'Els <b>certificats de residència, empadronament i convivència</b> es demanen al servei de Padró, amb cita prèvia.',
            l: ["El Padró atén a l'Ajuntament i a les oficines de Jesús i es Puig d’en Valls."],
            f: 'Per a la documentació concreta de cada cas, truqueu al 971 33 28 00.' },
      s: { t: 'Solicitud de certificados — Ajuntament de Santa Eulària des Riu', u: 'http://www.santaeulalia.net/index.php/es/padron-y-estadistica/solicitud-de-certificados-residencia-empadronamiento-convivencia' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Santa Eulària?' },
    { lang: 'ES', t: '¿Dónde pido el volante?' },
    { lang: 'CA', t: 'Cal demanar cita prèvia?' },
    { lang: 'ES', t: '¿Hay oficina en Jesús?' },
    { lang: 'ES', t: '¿Qué horario tienen?' },
  ],
},

// ===========================================================================
{
  slug: 'burjassot',
  nombre: 'Burjassot',
  articulo: 'de Burjassot',
  dominios: 'burjassot.org y sede.burjassot.org',
  fecha: '10 de septiembre de 2026',
  oficina: { sigla: 'el SAC', tel: '96 316 05 00', email: 'registro@burjassot.es' },
  idioma2: { cod: 'VA', clave: 'va', sigla: 'al SAC', nombre: 'valenciano' },
  kb: [
    {
      k: ['sac', 'oficina', 'donde', 'direccion', 'mariana pineda', 'casa de cultura', 'atencion ciudadana', 'ayuntamiento', 'telefono', 'llamar', 'contacto', 'correo',
          'on es', 'adreca', 'oficina', 'telefon', 'ajuntament'],
      es: { h: 'El <b>Servicio de Atención al Ciudadano (SAC)</b> está en la calle Mariana Pineda, 93-95, en la Casa de Cultura.',
            l: ['Teléfono: 96 316 05 00. Correo: registro@burjassot.es.'],
            f: 'Es la ventanilla de atención ciudadana y de registro del Ayuntamiento.' },
      va: { h: "El <b>Servei d'Atenció al Ciutadà (SAC)</b> està al carrer Mariana Pineda, 93-95, a la Casa de Cultura.",
            l: ['Telèfon: 96 316 05 00. Correu: registro@burjassot.es.'],
            f: "És la finestreta d'atenció ciutadana i de registre de l'Ajuntament." },
      s: { t: 'Servicio de Atención al Ciudadano SAC — burjassot.org', u: 'https://www.burjassot.org/servicio-de-atencion-al-ciudadano-sac/' },
    },
    {
      k: ['horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'tarde', 'por la tarde', 'martes', 'jueves', 'verano', 'julio', 'agosto', 'septiembre', 'que dias',
          'horari', 'fins a quina hora', 'obren', 'tanquen', 'vesprada', 'estiu', 'quins dies'],
      es: { h: 'El SAC abre <b>de lunes a viernes de 9:00 a 14:00</b>, y además <b>martes y jueves de 16:00 a 17:50</b>.',
            l: ['Del <b>15 de junio al 30 de septiembre</b> las tardes están cerradas: solo de 9:00 a 14:00.'],
            f: 'Dudas de horario: 96 316 05 00.' },
      va: { h: "El SAC obri <b>de dilluns a divendres de 9:00 a 14:00</b>, i a més <b>dimarts i dijous de 16:00 a 17:50</b>.",
            l: ['Del <b>15 de juny al 30 de setembre</b> les vesprades estan tancades: només de 9:00 a 14:00.'],
            f: "Dubtes d'horari: 96 316 05 00." },
      s: { t: 'Servicio de Atención al Ciudadano SAC — burjassot.org', u: 'https://www.burjassot.org/servicio-de-atencion-al-ciudadano-sac/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'hace falta cita', 'necesito cita', 'reservar', 'turno', 'por internet',
          'cita previa', 'demanar cita', 'cal cita', 'per internet'],
      es: { h: 'Para ir al SAC <b>hace falta cita previa</b>.',
            l: ['Se pide por internet, en citaprevia.burjassot.org.'],
            f: 'Si prefiere el teléfono, llame al 96 316 05 00.' },
      va: { h: 'Per anar al SAC <b>cal cita prèvia</b>.',
            l: ['Es demana per internet, a citaprevia.burjassot.org.'],
            f: 'Si preferiu el telèfon, truqueu al 96 316 05 00.' },
      s: { t: 'Cita previa — Ajuntament de Burjassot', u: 'https://www.burjassot.org/cita-previa/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'cambio de domicilio', 'nuevo vecino', 'certificado', 'volante', 'registro', 'presentar documentos', 'instancia', 'documentacion', 'que necesito', 'que llevar', 'documentos',
          'padro', 'empadronar-me', 'empadronament', 'canvi de domicili', 'certificat', 'volant', 'registre', 'que necessite'],
      es: { h: 'Los trámites de <b>padrón y de registro</b> se hacen en el SAC, con cita previa.',
            l: ['Está en la calle Mariana Pineda, 93-95.'],
            f: 'La web no publica la documentación concreta de cada caso. Confírmela en el 96 316 05 00 o en registro@burjassot.es.' },
      va: { h: 'Els tràmits de <b>padró i de registre</b> es fan al SAC, amb cita prèvia.',
            l: ['Està al carrer Mariana Pineda, 93-95.'],
            f: 'El web no publica la documentació concreta de cada cas. Confirmeu-la al 96 316 05 00 o a registro@burjassot.es.' },
      s: { t: 'Oficinas de asistencia de registro — sede.burjassot.org', u: 'https://sede.burjassot.org/sta/CarpetaPublic/doEvent?APP_CODE=STA&PAGE_CODE=PTS2_OFIASIREG' },
    },
    {
      k: ['sede electronica', 'carpeta', 'carpeta electronica', 'internet', 'por internet', 'online', 'tramite', 'tramites', 'certificado digital', 'expediente', 'mis datos',
          'seu electronica', 'carpeta electronica', 'tramit', 'tramits', 'per internet', 'expedient'],
      es: { h: 'La <b>sede electrónica</b> está en sede.burjassot.org.',
            l: ['Hay además una <b>carpeta electrónica</b>, en carpeta.burjassot.org, para consultar los expedientes propios.'],
            f: 'Es la vía para presentar solicitudes sin pedir cita.' },
      va: { h: 'La <b>seu electrònica</b> està a sede.burjassot.org.',
            l: ['Hi ha a més una <b>carpeta electrònica</b>, a carpeta.burjassot.org, per consultar els expedients propis.'],
            f: 'És la via per presentar sol·licituds sense demanar cita.' },
      s: { t: 'Sede electrónica — Ayuntamiento de Burjassot', u: 'https://sede.burjassot.org/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Burjassot?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'VA', t: 'Quin horari té el SAC?' },
    { lang: 'ES', t: '¿Hace falta cita previa?' },
    { lang: 'ES', t: '¿Dónde está el SAC?' },
  ],
},

// ===========================================================================
{
  slug: 'llucmajor',
  nombre: 'Llucmajor',
  articulo: 'de Llucmajor',
  dominios: 'llucmajor.org y seu.llucmajor.org',
  fecha: '10 de septiembre de 2026',
  oficina: { sigla: "l'OAC", tel: '971 66 16 23', email: '' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'oficinas', 'donde', 'direccion', 'constitucio', 'arenal', 'badies', 'badia gran', 'isaac peral', 'maria antonia salva', 'cual me toca', 'mas cerca', 'atencion ciudadana', 'telefono', 'llamar', 'contacto',
          'oficines', 'on es', 'adreca', 'mes propera', 'telefon'],
      es: { h: 'Llucmajor tiene <b>tres Oficinas de Atención al Ciudadano (OAC)</b>.',
            l: ['OAC Llucmajor, carrer Constitució, 1, 07260 · teléfono 971 66 16 23.',
                'OAC s’Arenal, carrer Mª Antònia Salvà, 50, 07600 · teléfono 971 44 10 71.',
                'OAC Badies, carrer Isaac Peral, 5B, 07609 Badia Gran · teléfono 971 74 82 37.'],
            f: 'Las tres son oficinas de asistencia en materia de registro.' },
      ca: { h: "Llucmajor té <b>tres Oficines d'Atenció al Ciutadà (OAC)</b>.",
            l: ['OAC Llucmajor, carrer Constitució, 1, 07260 · telèfon 971 66 16 23.',
                'OAC s’Arenal, carrer Mª Antònia Salvà, 50, 07600 · telèfon 971 44 10 71.',
                'OAC Badies, carrer Isaac Peral, 5B, 07609 Badia Gran · telèfon 971 74 82 37.'],
            f: "Totes tres són oficines d'assistència en matèria de registre." },
      s: { t: 'Oficines d’assistència de registre — seu.llucmajor.org', u: 'https://seu.llucmajor.org/sta/CarpetaPublic/doEvent?APP_CODE=STA&PAGE_CODE=PTS_OFIASIREG' },
    },
    {
      k: ['horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'tarde', 'por la tarde', 'verano', 'que dias',
          'horari', 'fins a quina hora', 'obren', 'tanquen', 'estiu', 'quins dies'],
      es: { h: 'Las OAC de <b>Llucmajor y s’Arenal</b> abren de lunes a viernes de <b>8:30 a 14:00</b>.',
            l: ['La OAC de <b>Badies</b> cierra media hora antes: de 8:30 a 13:30.'],
            f: 'La web no publica horario de tarde ni un horario distinto para el verano.' },
      ca: { h: "Les OAC de <b>Llucmajor i s’Arenal</b> obren de dilluns a divendres de <b>8:30 a 14:00</b>.",
            l: ["L'OAC de <b>Badies</b> tanca mitja hora abans: de 8:30 a 13:30."],
            f: "El web no publica horari de vesprada ni un horari diferent per a l'estiu." },
      s: { t: 'Oficines d’assistència de registre — seu.llucmajor.org', u: 'https://seu.llucmajor.org/sta/CarpetaPublic/doEvent?APP_CODE=STA&PAGE_CODE=PTS_OFIASIREG' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'hace falta cita', 'necesito cita', 'reservar', 'turno', 'por internet',
          'cita previa', 'demanar cita', 'cal cita', 'per internet'],
      es: { h: 'La <b>cita previa</b> se pide por internet, en citaprevia.llucmajor.org.',
            l: ['La centralita del Ayuntamiento es el 971 66 00 50.'],
            f: 'También se puede llamar directamente a la OAC que le venga mejor.' },
      ca: { h: 'La <b>cita prèvia</b> es demana per internet, a citaprevia.llucmajor.org.',
            l: ["La centraleta de l'Ajuntament és el 971 66 00 50."],
            f: 'També podeu trucar directament a l’OAC que us vagi millor.' },
      s: { t: 'Cita prèvia — Ajuntament de Llucmajor', u: 'https://citaprevia.llucmajor.org/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'cambio de domicilio', 'nuevo vecino', 'certificado', 'volante', 'registro', 'presentar documentos', 'instancia', 'sede electronica', 'internet', 'tramite', 'tramites', 'documentacion', 'que necesito', 'que llevar', 'documentos',
          'padro', 'empadronar-me', 'empadronament', 'canvi de domicili', 'certificat', 'volant', 'registre', 'seu electronica', 'tramit', 'tramits', 'que necessito'],
      es: { h: 'Los trámites de <b>padrón y de registro</b> se hacen en cualquiera de las tres OAC.',
            l: ['También por la sede electrónica, en seu.llucmajor.org.'],
            f: 'La web no publica la documentación concreta de cada caso. Confírmela en el 971 66 16 23 antes de desplazarse.' },
      ca: { h: 'Els tràmits de <b>padró i de registre</b> es fan a qualsevol de les tres OAC.',
            l: ['També per la seu electrònica, a seu.llucmajor.org.'],
            f: 'El web no publica la documentació concreta de cada cas. Confirmeu-la al 971 66 16 23 abans de desplaçar-vos.' },
      s: { t: 'Seu electrònica — Ajuntament de Llucmajor', u: 'https://seu.llucmajor.org/sta/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Llucmajor?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'CA', t: 'Quin horari tenen les OAC?' },
    { lang: 'ES', t: '¿Hay oficina en s’Arenal?' },
    { lang: 'ES', t: '¿Cómo pido cita previa?' },
  ],
},

// ===========================================================================
{
  slug: 'marratxi',
  nombre: 'Marratxí',
  articulo: 'de Marratxí',
  dominios: 'marratxi.es y seuelectronica.marratxi.es',
  fecha: '10 de septiembre de 2026',
  oficina: { sigla: "l'OAC", tel: '971 78 81 00', email: '' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'oficinas', 'donde', 'direccion', 'olesa', 'cabaneta', 'pont d inca', 'antoni maura', 'erica', 'cual me toca', 'mas cerca', 'atencion ciudadana', 'telefono', 'llamar', 'contacto',
          'oficines', 'on es', 'adreca', 'mes propera', 'telefon'],
      es: { h: 'Marratxí atiende en las <b>Oficinas de Atención a la Ciudadanía (OAC)</b>.',
            l: ['OAC Ajuntament, camí de n’Olesa, 66, Sa Cabaneta · teléfono 971 78 81 00.',
                'OAC es Pont d’Inca, avinguda Antoni Maura, 56, Edifici Erica, planta baja · teléfono 971 79 51 45.'],
            f: 'En las dos se hace lo mismo: no hay una que le corresponda por barrio.' },
      ca: { h: "Marratxí atén a les <b>Oficines d'Atenció a la Ciutadania (OAC)</b>.",
            l: ['OAC Ajuntament, camí de n’Olesa, 66, Sa Cabaneta · telèfon 971 78 81 00.',
                'OAC es Pont d’Inca, avinguda Antoni Maura, 56, Edifici Erica, planta baixa · telèfon 971 79 51 45.'],
            f: 'A totes dues es fa el mateix: no n’hi ha cap que us toqui per barri.' },
      s: { t: 'OAC — Ajuntament de Marratxí', u: 'https://www.marratxi.es/oac/' },
    },
    {
      k: ['horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'tarde', 'por la tarde', 'sabado', 'sabados', 'verano', 'que dias', 'horabaixa',
          'horari', 'fins a quina hora', 'obren', 'tanquen', 'dissabte', 'dissabtes', 'estiu', 'quins dies'],
      es: { h: 'Las dos OAC abren <b>de lunes a viernes de 8:15 a 14:00</b>.',
            l: ['La OAC del Ayuntamiento abre además los <b>sábados de 9:00 a 13:00</b>.',
                'La de es Pont d’Inca abre <b>martes y jueves por la tarde, de 15:15 a 19:00</b>.'],
            f: 'Para esos horarios de sábado y de tarde la cita previa es obligatoria.' },
      ca: { h: "Les dues OAC obren <b>de dilluns a divendres de 8:15 a 14:00</b>.",
            l: ["L'OAC de l'Ajuntament obre a més els <b>dissabtes de 9:00 a 13:00</b>.",
                "La d'es Pont d’Inca obre <b>dimarts i dijous a l'horabaixa, de 15:15 a 19:00</b>."],
            f: 'Per a aquests horaris de dissabte i de vesprada la cita prèvia és obligatòria.' },
      s: { t: 'OAC — Ajuntament de Marratxí', u: 'https://www.marratxi.es/oac/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'hace falta cita', 'necesito cita', 'obligatoria', 'reservar', 'turno',
          'cita previa', 'demanar cita', 'cal cita', 'obligatoria'],
      es: { h: 'El Ayuntamiento <b>ruega pedir cita previa</b> para cualquier trámite.',
            l: ['Y para los horarios extraordinarios —martes y jueves por la tarde, y sábado por la mañana— <b>es obligatoria</b>.'],
            f: 'En horario normal de mañana se atiende también sin cita.' },
      ca: { h: "L'Ajuntament <b>prega demanar cita prèvia</b> per a qualsevol tràmit.",
            l: ["I per als horaris extraordinaris —dimarts i dijous a l'horabaixa, i dissabte de matí— <b>és obligatòria</b>."],
            f: 'En horari normal de matí s’atén també sense cita.' },
      s: { t: 'OAC — Ajuntament de Marratxí', u: 'https://www.marratxi.es/oac/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'cambio de domicilio', 'nuevo vecino', 'certificado', 'volante', 'registro', 'presentar documentos', 'instancia', 'transporte', 'tarjeta', 'emt', 'tib', 'queja', 'sugerencia', 'documentacion', 'que necesito', 'que llevar', 'documentos',
          'padro', 'empadronar-me', 'empadronament', 'canvi de domicili', 'certificat', 'registre', 'transport', 'targeta', 'queixa', 'suggeriment', 'que necessito'],
      es: { h: 'En las OAC se hace el <b>registro de entrada</b> de documentos y las gestiones de <b>padrón de habitantes</b>.',
            l: ['También la tramitación de las tarjetas de transporte público, EMT y TIB.',
                'Y ahí se atienden las quejas y sugerencias sobre los servicios municipales.'],
            f: 'El registro vale para documentos dirigidos al Ayuntamiento y a otras administraciones.' },
      ca: { h: "A les OAC es fa el <b>registre d'entrada</b> de documents i les gestions de <b>padró d'habitants</b>.",
            l: ['També la tramitació de les targetes de transport públic, EMT i TIB.',
                "I s'hi atenen les queixes i suggeriments sobre els serveis municipals."],
            f: "El registre val per a documents dirigits a l'Ajuntament i a altres administracions." },
      s: { t: 'OAC — Ajuntament de Marratxí', u: 'https://www.marratxi.es/oac/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Marratxí?' },
    { lang: 'ES', t: '¿Puedo presentar un escrito en el registro?' },
    { lang: 'CA', t: 'Obren els dissabtes?' },
    { lang: 'ES', t: '¿Hace falta cita previa?' },
    { lang: 'ES', t: '¿Dónde están las OAC?' },
  ],
},

];
