// ---------------------------------------------------------------------------
//  LOS OCHO DEL CUARTO ENVIO — martes 15 de septiembre de 2026.
//  Comprobado en cada web municipal el 6 de septiembre de 2026.
//  Misma regla de siempre: lo que no se pudo verificar no se pone.
//
//  Catalan en Cornella, Sant Boi y Manresa; gallego en Pontevedra. Orihuela va
//  en castellano: esta en la Vega Baja, zona de predominio linguistico
//  castellano, igual que Torrevieja.
// ---------------------------------------------------------------------------

export const MUNICIPIOS_DIA04 = [

// ===========================================================================
{
  slug: 'arona',
  nombre: 'Arona',
  articulo: 'de Arona',
  dominios: 'arona.org y sede.arona.org',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'el SAC', tel: '010 o 922 761 600', email: 'portalweb@arona.org' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'oficinas', 'sac', 'atencion ciudadana', 'direccion', 'telefono', 'contacto', 'los cristianos', 'las galletas', 'arona casco'],
      es: { h: 'El <b>Servicio de Atención Ciudadana (SAC)</b> tiene <b>tres oficinas</b>, una en cada zona del municipio.',
            l: ['Arona Casco: calle Duque de la Torre, 33 — 38640 Arona.',
                'Los Cristianos: plaza del Pescador, Centro Cultural de Los Cristianos, 1 — 38650 Arona.',
                'Las Galletas: Centro Empresarial Rambla Dionisio González, 20 — 38632 Arona.',
                'Teléfono para las tres: el <b>010</b>, o el 922 761 600.'],
            f: 'Están repartidas así a propósito, para acercar la administración a las tres zonas.' },
      s: { t: 'Oficinas de Atención Presencial — arona.org', u: 'https://www.arona.org/Areas-Municipales/Atencion-Ciudadana/Oficinas-de-Atenci%C3%B3n-Presencial' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'sin cita', 'obligatoria', 'reservar', 'presencial'],
      es: { h: 'La <b>cita previa es obligatoria</b> para cualquier trámite, y también para pagar tasas o impuestos.',
            l: ['Sin cita no se atiende: no es una recomendación, es un requisito.',
                'Se pide en el 010 o en el 922 761 600.'],
            f: 'Antes de desplazarse a cualquiera de las tres oficinas, asegúrese de tener la cita.' },
      s: { t: 'Atención Ciudadana — arona.org', u: 'https://www.arona.org/Areas-Municipales/Atencion-Ciudadana' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'cambio de domicilio', 'mudarme'],
      es: { h: 'Los trámites de <b>padrón</b> se atienden en cualquiera de las tres oficinas del SAC, siempre con cita previa.',
            l: ['También hay atención telemática, sin desplazamiento.',
                'La sede electrónica está en sta.arona.org.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 010 antes de pedir la cita.' },
      s: { t: 'Atención Telemática — arona.org', u: 'https://www.arona.org/Areas-Municipales/Atencion-Ciudadana/Atencion-Telematica' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'telematica'],
      es: { h: 'La <b>atención telemática</b> permite resolver trámites sin ir a ninguna oficina.',
            l: ['Es la vía más rápida, porque no depende de que haya cita libre.'],
            f: 'Si se atasca, el 010 le orienta sobre qué trámite corresponde a su caso.' },
      s: { t: 'Oficinas de Atención Presencial — Sede Electrónica de Arona', u: 'https://sta.arona.org/sta/CarpetaPublic/Public?APP_CODE=STA&PAGE_CODE=OVC_OFICINAS' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Dónde están las oficinas del SAC?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'ES', t: '¿Hace falta cita previa?' },
    { lang: 'ES', t: '¿Puedo hacer trámites sin ir a la oficina?' },
  ],
},

// ===========================================================================
{
  slug: 'cornella-de-llobregat',
  nombre: 'Cornellà de Llobregat',
  articulo: 'de Cornellà de Llobregat',
  dominios: 'cornella.cat y tramits.cornella.cat',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'la OAC', tel: '93 377 02 12', email: 'oac@aj-cornella.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'telefono', 'contacto', 'iglesia', 'verano', 'tarde',
          'atencio ciutadana', 'adreca', 'horari', 'telefon', 'esglesia', 'estiu', 'tarda'],
      es: { h: 'La <b>Oficina d\'Atenció Ciutadana (OAC)</b> está en la plaça de l\'Església, 1 — 08940 Cornellà de Llobregat.',
            l: ['Teléfonos: 93 377 02 12 y 93 377 25 14.',
                'Mañanas, de lunes a viernes: de 8:30 a 14:30.',
                'Del 15 de junio al 15 de septiembre las mañanas son de 8:30 a 13:30.',
                'Tardes: de 16:30 a 19:30, <b>solo con cita previa</b>.'],
            f: 'Correo: oac@aj-cornella.cat. Hay además un servicio OAC 360º en el 93 595 50 93.' },
      ca: { h: 'L\'<b>Oficina d\'Atenció Ciutadana (OAC)</b> és a la plaça de l\'Església, 1 — 08940 Cornellà de Llobregat.',
            l: ['Telèfons: 93 377 02 12 i 93 377 25 14.',
                'Matins, de dilluns a divendres: de 8:30 a 14:30.',
                'Del 15 de juny al 15 de setembre els matins són de 8:30 a 13:30.',
                'Tardes: de 16:30 a 19:30, <b>només amb cita prèvia</b>.'],
            f: 'Correu: oac@aj-cornella.cat. Hi ha a més un servei OAC 360º al 93 595 50 93.' },
      s: { t: 'Oficina d\'Atenció Ciutadana — cornella.cat', u: 'https://www.cornella.cat/ca/contactar/oficina-datencio-ciutadana' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'antelacion', 'con cuanto', '12 horas',
          'demanar cita', 'antelacio', 'antelacion minima'],
      es: { h: 'La cita previa se pide eligiendo <b>horario (mañana o tarde) y trámite</b>.',
            l: ['Hay que pedirla con una <b>antelación mínima de 12 horas</b>.',
                'Para las tardes es obligatoria; para las mañanas, no.'],
            f: 'Se solicita en citaprevia.cornella.cat.' },
      ca: { h: 'La cita prèvia es demana escollint <b>horari (matí o tarda) i tràmit</b>.',
            l: ['Cal demanar-la amb una <b>antelació mínima de 12 hores</b>.',
                'Per a les tardes és obligatòria; per als matins, no.'],
            f: 'Es demana a citaprevia.cornella.cat.' },
      s: { t: 'Cita Prèvia — Ajuntament de Cornellà', u: 'https://citaprevia.cornella.cat/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'nacimiento', 'videollamada', 'certificado', 'cambio de domicilio',
          'padro', 'empadronar-me', 'empadronament', 'naixement', 'videotrucada', 'certificat', 'canvi de domicili'],
      es: { h: 'Parte de los trámites del <b>padró municipal d\'habitants</b> se pueden hacer por <b>videollamada</b>.',
            l: ['El alta al padrón por nacimiento está entre los disponibles en esa modalidad.',
                'El resto se gestiona en la OAC o en el catálogo de trámites en línea.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 93 377 02 12 antes de pedir la cita.' },
      ca: { h: 'Part dels tràmits del <b>padró municipal d\'habitants</b> es poden fer per <b>videotrucada</b>.',
            l: ['L\'alta al padró per naixement és un dels disponibles en aquesta modalitat.',
                'La resta es gestiona a l\'OAC o al catàleg de tràmits en línia.'],
            f: 'La documentació concreta depèn del seu cas. Confirmi-la al 93 377 02 12 abans de demanar la cita.' },
      s: { t: 'L\'OAC amplia els serveis virtuals — cornella.cat', u: 'https://www.cornella.cat/ca/actualitat/noticies/loficina-datencio-ciutadana-amplia-els-serveis-virtuals' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo',
          'seu electronica', 'tramit', 'tramits', 'cataleg', 'per internet'],
      es: { h: 'El <b>catálogo de trámites</b> en línea está en tramits.cornella.cat.',
            l: ['La sede electrónica es seuelectronica.cornella.cat.'],
            f: 'Dudas: 93 377 02 12 o oac@aj-cornella.cat.' },
      ca: { h: 'El <b>catàleg de tràmits</b> en línia és a tramits.cornella.cat.',
            l: ['La seu electrònica és seuelectronica.cornella.cat.'],
            f: 'Dubtes: 93 377 02 12 o oac@aj-cornella.cat.' },
      s: { t: 'Catàleg de Tràmits — Ajuntament de Cornellà', u: 'https://tramits.cornella.cat/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué horario tiene la OAC en verano?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'CA', t: 'Amb quanta antelació he de demanar cita?' },
    { lang: 'ES', t: '¿Puedo hacer el padrón por videollamada?' },
  ],
},

// ===========================================================================
{
  slug: 'orihuela',
  nombre: 'Orihuela',
  articulo: 'de Orihuela',
  dominios: 'orihuela.es',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'el Servicio de Estadística', tel: '966 340 347', email: 'estadistica@orihuela.es' },
  idioma2: null,
  kb: [
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'estadistica', 'poeta del pueblo', 'ruiz capdepon', 'horario', 'jueves'],
      es: { h: 'El <b>Padrón Municipal</b> está en el edificio <b>«Poeta del Pueblo»</b>, calle Ruiz Capdepón, 7 — 03300 Orihuela.',
            l: ['Teléfono: 966 340 347.',
                'Horario del padrón: de lunes a viernes de 9:00 a 13:30.',
                'Los <b>jueves</b> también por la tarde, de 16:00 a 18:00.',
                'Correo para certificados: estadistica@orihuela.es.'],
            f: 'La oficina general del edificio abre de lunes a viernes de 8:30 a 13:30.' },
      s: { t: 'Dependencias municipales — orihuela.es', u: 'https://www.orihuela.es/dependencias-municipales/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita', 'presencial'],
      es: { h: 'La <b>cita previa</b> del Servicio de Estadística y Padrón se pide por teléfono o por internet.',
            l: ['Oficinas de Orihuela: 966 340 347 o 672 217 838.',
                'Orihuela Costa: 966 076 150.',
                'Por internet: orihuela.governalia.es.'],
            f: 'Para pedir certificados de empadronamiento también sirve el correo estadistica@orihuela.es.' },
      s: { t: 'Servicio de solicitud de cita previa — orihuela.es', u: 'https://www.orihuela.es/el-ayuntamiento-pone-a-disposicion-de-la-ciudadania-un-servicio-de-solicitud-de-cita-previa/' },
    },
    {
      k: ['orihuela costa', 'costa', 'playa flamenca', 'oriol', 'otra oficina', 'segunda oficina'],
      es: { h: 'Hay una segunda oficina en <b>Orihuela Costa</b>.',
            l: ['Plaza del Oriol, 1 — Urbanización Playa Flamenca, 03189 Orihuela-Costa.',
                'Teléfono: 966 760 000.',
                'Para cita previa en esa oficina: 966 076 150.'],
            f: 'Es la referencia si vive en la costa y no quiere subir al casco.' },
      s: { t: 'Dependencias municipales — orihuela.es', u: 'https://www.orihuela.es/dependencias-municipales/' },
    },
    {
      k: ['certificado', 'volante', 'acreditar residencia', 'como consigo', 'solicitar certificado'],
      es: { h: 'Los <b>certificados de empadronamiento</b> se pueden solicitar por correo electrónico.',
            l: ['Dirección: estadistica@orihuela.es.',
                'O presencialmente en el edificio «Poeta del Pueblo», con cita previa.'],
            f: 'Teléfono del servicio: 966 340 347.' },
      s: { t: 'Servicios a la ciudadanía — orihuela.es', u: 'https://www.orihuela.es/servicios-a-la-ciudadania/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué horario tiene el padrón?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'ES', t: '¿Hay oficina en Orihuela Costa?' },
    { lang: 'ES', t: '¿Cómo pido un certificado de empadronamiento?' },
  ],
},

// ===========================================================================
{
  slug: 'pontevedra',
  nombre: 'Pontevedra',
  articulo: 'de Pontevedra',
  dominios: 'pontevedra.gal y sede.pontevedra.gal',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'el Registro General', tel: '986 804 300', email: 'contacto@pontevedra.gal' },
  idioma2: { cod: 'GL', clave: 'gl', sigla: 'no Rexistro Xeral', nombre: 'gallego' },
  kb: [
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'registro', 'michelena', 'oficina', 'direccion', 'telefono',
          'empadroarme', 'empadroamento', 'rexistro', 'enderezo'],
      es: { h: 'El <b>Padrón</b> y el <b>Registro General</b> están en la rúa Michelena, 30, planta baja.',
            l: ['Teléfono: 986 804 300.',
                'Horario: de lunes a viernes de 8:30 a 14:30.',
                'Del 16 de junio al 15 de septiembre y del 22 de diciembre al 6 de enero: de 8:30 a 13:45.'],
            f: 'Correo de contacto: contacto@pontevedra.gal.' },
      gl: { h: 'O <b>Padrón</b> e o <b>Rexistro Xeral</b> están na rúa Michelena, 30, baixo.',
            l: ['Teléfono: 986 804 300.',
                'Horario: de luns a venres de 8:30 a 14:30.',
                'Do 16 de xuño ao 15 de setembro e do 22 de decembro ao 6 de xaneiro: de 8:30 a 13:45.'],
            f: 'Correo de contacto: contacto@pontevedra.gal.' },
      s: { t: 'O Rexistro Xeral Municipal — pontevedra.gal', u: 'https://www.pontevedra.gal/areas/o-rexistro-xeral-municipal/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'sin cita', 'reservar', 'cola', 'numero', 'orden de llegada',
          'cita previa', 'sen cita', 'quenda', 'rolda'],
      es: { h: 'Se puede ir <b>con cita previa o sin ella</b>.',
            l: ['Sin cita: se atiende por orden de llegada, cogiendo número en la máquina dispensadora de las oficinas municipales.',
                'Con cita: en citaprevia.pontevedra.gal, o pidiéndola en el propio mostrador de atención.'],
            f: 'Es decir, no le van a echar por no traer cita.' },
      gl: { h: 'Pódese ir <b>con cita previa ou sen ela</b>.',
            l: ['Sen cita: atenderano por orde de chegada, collendo número na máquina dispensadora das oficinas municipais.',
                'Con cita: en citaprevia.pontevedra.gal, ou pedíndoa no propio mostrador de atención.'],
            f: 'É dicir, non o van botar por non levar cita.' },
      s: { t: 'Cita previa — sede.pontevedra.gal', u: 'https://sede.pontevedra.gal/public/dynamic/procedures/citaprevia.xhtml' },
    },
    {
      k: ['certificado', 'volante', 'acreditar residencia', 'solicitar certificado', 'como consigo',
          'certificado de empadroamento', 'solicitude'],
      es: { h: 'La <b>solicitud de certificados de empadronamiento</b> tiene su propio trámite en la sede electrónica.',
            l: ['Se puede presentar en línea, sin ir a la oficina.',
                'La sede es sede.pontevedra.gal.'],
            f: 'Si necesita ayuda con la sede electrónica, el teléfono es el 986 804 300.' },
      gl: { h: 'A <b>solicitude de certificados de empadroamento</b> ten o seu propio trámite na sede electrónica.',
            l: ['Pódese presentar en liña, sen ir á oficina.',
                'A sede é sede.pontevedra.gal.'],
            f: 'Se precisa axuda coa sede electrónica, o teléfono é o 986 804 300.' },
      s: { t: 'Solicitude de certificados de empadroamento — sede.pontevedra.gal', u: 'https://sede.pontevedra.gal/public/catalog-detail/1016147' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet',
          'sede electronica', 'tramite', 'tramites', 'en lina'],
      es: { h: 'La <b>sede electrónica</b> permite hacer trámites y presentar documentos sin desplazarse.',
            l: ['Dirección: sede.pontevedra.gal.'],
            f: 'Para dudas o ayuda con el acceso: 986 804 300.' },
      gl: { h: 'A <b>sede electrónica</b> permite facer trámites e presentar documentos sen desprazarse.',
            l: ['Enderezo: sede.pontevedra.gal.'],
            f: 'Para dúbidas ou axuda co acceso: 986 804 300.' },
      s: { t: 'Sede Electrónica — Concello de Pontevedra', u: 'https://sede.pontevedra.gal/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Puedo ir al padrón sin cita previa?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'GL', t: 'Onde está o Rexistro Xeral?' },
    { lang: 'GL', t: 'Que horario ten no verán?' },
  ],
},

// ===========================================================================
{
  slug: 'sant-boi-de-llobregat',
  nombre: 'Sant Boi de Llobregat',
  articulo: 'de Sant Boi de Llobregat',
  dominios: 'santboi.cat y seuelectronica.santboi.cat',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'el eMAP', tel: '93 654 12 00', email: 'santboi@santboi.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'eMAP", nombre: 'catalán' },
  kb: [
    {
      k: ['emap', 'oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'telefono', 'contacto', 'tarde', 'ayuntamiento',
          'atencio ciutadana', 'adreca', 'horari', 'telefon', 'tarda', 'ajuntament'],
      es: { h: 'El <b>Espai Municipal d\'Atenció a les Persones (eMAP)</b> está en la plaça de l\'Ajuntament, 1 — 08830 Sant Boi de Llobregat.',
            l: ['Teléfonos: 93 654 12 00 y 93 635 12 12.',
                'De lunes a jueves: de 9:00 a 14:00 y de 16:00 a 19:00.',
                'Viernes y vísperas de festivo: de 9:00 a 14:00.',
                'Del 1 de diciembre al 7 de enero el horario es de 8:30 a 14:00.'],
            f: 'Atiende de forma presencial, por teléfono y por internet.' },
      ca: { h: 'L\'<b>Espai Municipal d\'Atenció a les Persones (eMAP)</b> és a la plaça de l\'Ajuntament, 1 — 08830 Sant Boi de Llobregat.',
            l: ['Telèfons: 93 654 12 00 i 93 635 12 12.',
                'De dilluns a dijous: de 9:00 a 14:00 i de 16:00 a 19:00.',
                'Divendres i vigílies de festiu: de 9:00 a 14:00.',
                'De l\'1 de desembre al 7 de gener l\'horari és de 8:30 a 14:00.'],
            f: 'Atén de manera presencial, per telèfon i per internet.' },
      s: { t: 'Telèfons d\'atenció ciutadana — santboi.cat', u: 'https://www.santboi.cat/telefons-datencio-ciutadana' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita', 'presencial',
          'demanar cita', 'sense cita'],
      es: { h: 'La <b>cita previa</b> se pide por teléfono.',
            l: ['Números: 93 635 12 12 o 93 654 82 23.',
                'Por esos mismos teléfonos le ayudan con el trámite si se puede resolver sin ir.'],
            f: 'El eMAP abre tardes de lunes a jueves, que es cuando menos gente hay.' },
      ca: { h: 'La <b>cita prèvia</b> es demana per telèfon.',
            l: ['Números: 93 635 12 12 o 93 654 82 23.',
                'Per aquests mateixos telèfons l\'ajuden amb el tràmit si es pot resoldre sense anar-hi.'],
            f: 'L\'eMAP obre tardes de dilluns a dijous, que és quan hi ha menys gent.' },
      s: { t: 'Cita prèvia — seuelectronica.santboi.cat', u: 'https://seuelectronica.santboi.cat/PaginesW.nsf/Web/Planes/A76EE896547F51A6C12583AE00292720?OpenDocument=&Clau=citaprevia&Idioma=ca&Seu=S' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'cambio de domicilio', 'mudarme',
          'padro', 'empadronar-me', 'empadronament', 'certificat', 'volant', 'canvi de domicili'],
      es: { h: 'Los trámites del <b>padró municipal</b> se atienden en el eMAP.',
            l: ['Presencialmente en la plaça de l\'Ajuntament, 1.',
                'O por teléfono, en el 93 635 12 12.'],
            f: 'La documentación concreta depende de su caso. Confírmela por teléfono antes de desplazarse.' },
      ca: { h: 'Els tràmits del <b>padró municipal</b> s\'atenen a l\'eMAP.',
            l: ['Presencialment a la plaça de l\'Ajuntament, 1.',
                'O per telèfon, al 93 635 12 12.'],
            f: 'La documentació concreta depèn del seu cas. Confirmi-la per telèfon abans de desplaçar-se.' },
      s: { t: 'Tràmits — santboi.cat', u: 'https://www.santboi.cat/tramits' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet',
          'seu electronica', 'tramit', 'tramits', 'per internet'],
      es: { h: 'Los trámites en línea están en <b>santboi.cat/tramits</b> y en la seu electrònica.',
            l: ['La sede es seuelectronica.santboi.cat.'],
            f: 'Si prefiere que se lo expliquen: 93 635 12 12.' },
      ca: { h: 'Els tràmits en línia són a <b>santboi.cat/tramits</b> i a la seu electrònica.',
            l: ['La seu és seuelectronica.santboi.cat.'],
            f: 'Si prefereix que li ho expliquin: 93 635 12 12.' },
      s: { t: 'Tràmits — santboi.cat', u: 'https://www.santboi.cat/tramits' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿El eMAP abre por las tardes?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'CA', t: 'Quin horari té l\'eMAP els divendres?' },
    { lang: 'ES', t: '¿Cómo pido cita previa?' },
  ],
},

// ===========================================================================
{
  slug: 'manresa',
  nombre: 'Manresa',
  articulo: 'de Manresa',
  dominios: 'manresa.cat',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'la OAC', tel: '938 782 301 o 010', email: 'oac@ajmanresa.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'telefono', 'contacto', 'plaza mayor', 'lunes', 'verano', 'whatsapp',
          'atencio ciutadana', 'adreca', 'horari', 'telefon', 'placa major', 'dilluns', 'estiu'],
      es: { h: 'La <b>Oficina d\'Atenció Ciutadana (OAC)</b> está en la plaça Major, 1, bajos.',
            l: ['Teléfono: 938 782 301, o el 010 (con coste según operadora).',
                'Horario general, del 12 de septiembre al 21 de junio: lunes de 9:00 a 18:00; de martes a viernes de 9:00 a 15:00.',
                'Horario de verano, del 22 de junio al 10 de septiembre: de lunes a viernes de 9:00 a 14:00.',
                'Correo: oac@ajmanresa.cat.'],
            f: 'Hay también un WhatsApp municipal: 644 069 801.' },
      ca: { h: 'L\'<b>Oficina d\'Atenció Ciutadana (OAC)</b> és a la plaça Major, 1, baixos.',
            l: ['Telèfon: 938 782 301, o el 010 (amb cost segons operadora).',
                'Horari general, del 12 de setembre al 21 de juny: dilluns de 9:00 a 18:00; de dimarts a divendres de 9:00 a 15:00.',
                'Horari d\'estiu, del 22 de juny al 10 de setembre: de dilluns a divendres de 9:00 a 14:00.',
                'Correu: oac@ajmanresa.cat.'],
            f: 'Hi ha també un WhatsApp municipal: 644 069 801.' },
      s: { t: 'Adreces i telèfons municipals — manresa.cat', u: 'https://web.manresa.cat/web/menu/4116-adreces-i-telefons-municipals' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'cambio de domicilio', 'mudarme',
          'padro', 'empadronar-me', 'empadronament', 'certificat', 'volant', 'canvi de domicili'],
      es: { h: 'Los trámites del <b>padró municipal</b> se atienden en la OAC de la plaça Major.',
            l: ['El lunes es el día con horario más amplio: hasta las 18:00.',
                'También se puede consultar por el WhatsApp municipal, el 644 069 801.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 938 782 301 antes de ir.' },
      ca: { h: 'Els tràmits del <b>padró municipal</b> s\'atenen a l\'OAC de la plaça Major.',
            l: ['El dilluns és el dia amb horari més ampli: fins a les 18:00.',
                'També es pot consultar pel WhatsApp municipal, el 644 069 801.'],
            f: 'La documentació concreta depèn del seu cas. Confirmi-la al 938 782 301 abans d\'anar-hi.' },
      s: { t: 'Atenció a la ciutadania — manresa.cat', u: 'https://web.manresa.cat/web/menu/4115-atencio-a-la-ciutadania' },
    },
    {
      k: ['presencial', 'ir en persona', 'sin cita', 'cita', 'cita previa', 'registro',
          'presencialment', 'demanar cita', 'sense cita', 'registre'],
      es: { h: 'La atención <b>presencial</b> se hace en la OAC de la plaça Major, 1.',
            l: ['En verano y en Navidad los horarios de atención y de los registros municipales cambian.',
                'Conviene comprobarlo antes de ir si es en esas fechas.'],
            f: 'Teléfono: 938 782 301 o el 010.' },
      ca: { h: 'L\'atenció <b>presencial</b> es fa a l\'OAC de la plaça Major, 1.',
            l: ['A l\'estiu i per Nadal els horaris d\'atenció i dels registres municipals canvien.',
                'Convé comprovar-ho abans d\'anar-hi si és en aquestes dates.'],
            f: 'Telèfon: 938 782 301 o el 010.' },
      s: { t: 'Presencialment — manresa.cat', u: 'https://web.manresa.cat/web/menu/8237-presencialment' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet',
          'seu electronica', 'tramit', 'tramits', 'per internet'],
      es: { h: 'Además de la OAC, hay atención <b>por internet y por WhatsApp</b>.',
            l: ['WhatsApp municipal: 644 069 801.',
                'Correo: oac@ajmanresa.cat.'],
            f: 'Para muchas consultas, el WhatsApp evita el desplazamiento.' },
      ca: { h: 'A més de l\'OAC, hi ha atenció <b>per internet i per WhatsApp</b>.',
            l: ['WhatsApp municipal: 644 069 801.',
                'Correu: oac@ajmanresa.cat.'],
            f: 'Per a moltes consultes, el WhatsApp estalvia el desplaçament.' },
      s: { t: 'Atenció ciutadana — manresa.cat', u: 'https://web.manresa.cat/web/menu/10769-atencio-ciutadana' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué horario tiene la OAC los lunes?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'CA', t: 'Quin horari té l\'OAC a l\'estiu?' },
    { lang: 'ES', t: '¿Hay WhatsApp del ayuntamiento?' },
  ],
},

// ===========================================================================
{
  slug: 'coslada',
  nombre: 'Coslada',
  articulo: 'de Coslada',
  dominios: 'coslada.es y sede.ayto-coslada.es',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'la oficina de Registro, Padrón e Información', tel: '91 627 82 00', email: 'informacion@ayto-coslada.es' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'registro', 'padron', 'informacion', 'direccion', 'horario', 'telefono', 'contacto', 'constitucion'],
      es: { h: 'La oficina de <b>Registro, Padrón e Información</b> está en la avenida de la Constitución, 47, 1ª planta (planta calle) — 28821 Coslada.',
            l: ['Teléfono: 91 627 82 00, extensión 3000.',
                'Del 16 de septiembre al 9 de junio: de 8:30 a 14:00.',
                'Del 10 de junio al 15 de septiembre: de 8:30 a 13:00.',
                'Correo: informacion@ayto-coslada.es.'],
            f: 'La atención presencial es <b>con cita previa</b>.' },
      s: { t: 'Registro, Padrón e Información — coslada.es', u: 'https://coslada.es/alcaldia/secretaria-general/registro-padron-e-informacion/' },
    },
    {
      k: ['volante', 'certificado', 'empadronamiento', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'por telefono', 'por correo', 'sin ir'],
      es: { h: 'Los <b>volantes de empadronamiento</b> se pueden pedir <b>por teléfono y por correo electrónico</b>, sin ir a la oficina.',
            l: ['Teléfono: 91 627 82 00.',
                'Correo: registro@ayto-coslada.es.'],
            f: 'Es de las pocas gestiones que no exigen ni cita ni desplazamiento.' },
      s: { t: 'Registro, Padrón e Información — coslada.es', u: 'https://coslada.es/alcaldia/secretaria-general/registro-padron-e-informacion/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita', 'presencial'],
      es: { h: 'La atención presencial se hace <b>mediante cita previa</b>.',
            l: ['Se pide en el teléfono 91 627 82 00.',
                'También hay un portal de cita previa en citaprevia.ayto-coslada.es.'],
            f: 'Si solo necesita un volante de empadronamiento, no hace falta cita: se pide por teléfono o por correo.' },
      s: { t: 'Cita previa — Ayuntamiento de Coslada', u: 'https://citaprevia.ayto-coslada.es/citasWebCoslada/citas.php' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'impresos', 'administracion electronica'],
      es: { h: 'La <b>sede electrónica</b> permite resolver trámites sin desplazarse a las dependencias municipales.',
            l: ['Dirección: sede.ayto-coslada.es.',
                'Hay además una sección de impresos administrativos en coslada.es.'],
            f: 'Dudas: 91 627 82 00 o informacion@ayto-coslada.es.' },
      s: { t: 'Sede Electrónica — Ayuntamiento de Coslada', u: 'https://sede.ayto-coslada.es/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Puedo pedir el volante de empadronamiento por teléfono?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'ES', t: '¿Qué horario tiene la oficina en verano?' },
    { lang: 'ES', t: '¿Hace falta cita previa?' },
  ],
},

// ===========================================================================
{
  slug: 'estepona',
  nombre: 'Estepona',
  articulo: 'de Estepona',
  dominios: 'ayuntamiento.estepona.es',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'la Oficina de Atención al Ciudadano', tel: '952 80 90 00', email: 'registroayuntamiento@estepona.es' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'oficinas', 'atencion al ciudadano', 'direccion', 'horario', 'telefono', 'contacto', 'blas infante', 'puertosol', 'cancelada'],
      es: { h: 'La <b>Oficina de Atención al Ciudadano</b> principal está en el edificio del antiguo Ayuntamiento, plaza Blas Infante.',
            l: ['Hay otras dos: en el edificio Puertosol y en Cancelada.',
                'Horario de atención: de 9:00 a 14:00, mediante <b>cita previa</b>.',
                'Teléfono general: 952 80 90 00.'],
            f: 'En la del antiguo Ayuntamiento se tramitan los volantes de empadronamiento y los documentos de fe de vida.' },
      s: { t: 'Reapertura de las oficinas de Atención al Ciudadano — ayuntamiento.estepona.es', u: 'https://ayuntamiento.estepona.es/noticia/15638-el-ayuntamiento-reabre-las-oficinas-de-atencion-al-ciudadano-en-el-antiguo-ayuntamiento-y-en-cancelada' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita', 'aplicacion', 'app', 'movil'],
      es: { h: 'La <b>cita previa</b> se pide por internet, por teléfono o desde una aplicación móvil.',
            l: ['Web: citaprevia.estepona.es.',
                'Teléfono de cita previa: 952 80 81 50.',
                'Hay una app municipal para pedir cita en los distintos departamentos.'],
            f: 'La atención de 9:00 a 14:00 es siempre con cita.' },
      s: { t: 'Cita Previa y Gestión de Colas — citaprevia.estepona.es', u: 'https://citaprevia.estepona.es/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'fe de vida', 'inscripcion padronal'],
      es: { h: 'Con <b>certificado digital</b> se puede hacer la inscripción padronal y obtener los certificados de empadronamiento <b>en línea</b>.',
            l: ['Sin certificado digital: los volantes de empadronamiento y la fe de vida se tramitan en la oficina del antiguo Ayuntamiento, plaza Blas Infante.',
                'Hay un portal específico del padrón en padron.estepona.es.'],
            f: 'Para ir en persona hace falta cita previa: 952 80 81 50.' },
      s: { t: 'Padrón de habitantes — ayuntamiento.estepona.es', u: 'https://ayuntamiento.estepona.es/sede-electronica/plantillas-sede/padron-de-habitantes' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'certificado digital'],
      es: { h: 'La <b>sede electrónica</b> permite hacer trámites sin ir a las oficinas.',
            l: ['Con certificado digital se accede a la inscripción padronal y a los certificados.',
                'El portal del padrón es padron.estepona.es.'],
            f: 'Dudas: 952 80 90 00.' },
      s: { t: 'Padrón Municipal de Habitantes — padron.estepona.es', u: 'https://padron.estepona.es/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Dónde están las oficinas de atención al ciudadano?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'ES', t: '¿Puedo empadronarme por internet?' },
    { lang: 'ES', t: '¿Cómo pido cita previa?' },
  ],
},

];
