// ---------------------------------------------------------------------------
//  LOS OCHO DEL SEXTO ENVIO — jueves 17 de septiembre de 2026.
//  Comprobado en cada web municipal el 7 de septiembre de 2026.
//
//  Catalan en Cerdanyola y Manacor; gallego en Naron. Elda va en castellano:
//  Vinalopo Mitja, zona de predominio linguistico castellano.
//
//  NOTA: en esta tanda entra Mieres en lugar de Linares. La web de Linares
//  (aytolinares.es y linares.es) no responde, y sin poder verificar un solo
//  dato suyo la demo tendria que inventarselo todo. Linares se queda fuera
//  hasta que su web vuelva a estar en pie.
// ---------------------------------------------------------------------------

export const MUNICIPIOS_DIA06 = [

// ===========================================================================
{
  slug: 'cerdanyola-del-valles',
  nombre: 'Cerdanyola del Vallès',
  articulo: 'de Cerdanyola del Vallès',
  dominios: 'cerdanyola.cat y tramits.cerdanyola.cat',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'la OAC', tel: '93 580 88 88', email: 'oac@cerdanyola.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'francesc layret', 'verano', 'invierno',
          'atencio ciutadana', 'adreca', 'horari', 'telefon', 'estiu', 'hivern'],
      es: { h: 'La <b>Oficina d\'Atenció a la Ciutadania (OAC)</b> está en la plaça Francesc Layret, s/n.',
            l: ['Teléfono: 93 580 88 88.',
                'Del 1 de septiembre al 30 de junio: de lunes a viernes de 8:30 a 14:30.',
                'Del 1 de julio al 31 de agosto: de 8:30 a 14:00.'],
            f: 'La OAC atiende <b>solo con cita previa</b>.' },
      ca: { h: 'L\'<b>Oficina d\'Atenció a la Ciutadania (OAC)</b> és a la plaça Francesc Layret, s/n.',
            l: ['Telèfon: 93 580 88 88.',
                'De l\'1 de setembre al 30 de juny: de dilluns a divendres de 8:30 a 14:30.',
                'De l\'1 de juliol al 31 d\'agost: de 8:30 a 14:00.'],
            f: 'L\'OAC atén <b>només amb cita prèvia</b>.' },
      s: { t: 'Oficina d\'Atenció a la Ciutadania — cerdanyola.cat', u: 'https://www.cerdanyola.cat/oac' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'sin cita', 'obligatoria', 'reservar', 'presencial',
          'cita previa', 'demanar cita', 'sense cita', 'obligatoria'],
      es: { h: 'La OAC atiende <b>únicamente con cita previa</b>. Sin ella no se atiende.',
            l: ['La cita se pide en la web del Ayuntamiento.',
                'O por teléfono, en el 93 580 88 88.'],
            f: 'Hay una excepción: el empadronamiento de recién nacidos se puede hacer sin cita.' },
      ca: { h: 'L\'OAC atén <b>únicament amb cita prèvia</b>. Sense ella no s\'atén.',
            l: ['La cita es demana al web de l\'Ajuntament.',
                'O per telèfon, al 93 580 88 88.'],
            f: 'Hi ha una excepció: l\'empadronament de nadons es pot fer sense cita.' },
      s: { t: 'L\'OAC atén només amb cita prèvia — cerdanyola.cat', u: 'https://www.cerdanyola.cat/actualitat/loficina-datencio-ciutadana-aten-nomes-amb-cita-previa' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'bebe', 'recien nacido', 'nacimiento', 'certificado', 'cambio de domicilio',
          'padro', 'empadronar-me', 'empadronament', 'nadons', 'nadó', 'naixement', 'certificat', 'canvi de domicili'],
      es: { h: 'Los trámites del <b>padró municipal</b> se hacen en la OAC, con cita previa.',
            l: ['<b>Excepción:</b> los empadronamientos de recién nacidos se pueden hacer <b>sin cita previa</b>.',
                'Para el resto, la cita es obligatoria.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 93 580 88 88 antes de pedir la cita.' },
      ca: { h: 'Els tràmits del <b>padró municipal</b> es fan a l\'OAC, amb cita prèvia.',
            l: ['<b>Excepció:</b> els empadronaments de nadons es poden fer <b>sense cita prèvia</b>.',
                'Per a la resta, la cita és obligatòria.'],
            f: 'La documentació concreta depèn del seu cas. Confirmi-la al 93 580 88 88 abans de demanar la cita.' },
      s: { t: 'L\'OAC atén només amb cita prèvia — cerdanyola.cat', u: 'https://www.cerdanyola.cat/actualitat/loficina-datencio-ciutadana-aten-nomes-amb-cita-previa' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet',
          'seu electronica', 'tramit', 'tramits', 'per internet'],
      es: { h: 'Los <b>trámites y gestiones</b> en línea están en tramits.cerdanyola.cat.',
            l: ['La seu electrònica es cerdanyola.cat/seu-electronica.'],
            f: 'Si prefiere ir en persona, recuerde pedir cita: 93 580 88 88.' },
      ca: { h: 'Els <b>tràmits i gestions</b> en línia són a tramits.cerdanyola.cat.',
            l: ['La seu electrònica és cerdanyola.cat/seu-electronica.'],
            f: 'Si prefereix anar-hi en persona, recordi demanar cita: 93 580 88 88.' },
      s: { t: 'Tràmits i gestions — Ajuntament de Cerdanyola del Vallès', u: 'https://www.cerdanyola.cat/oficina-datencio-ciutadana-oac' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hace falta cita previa para ir a la OAC?' },
    { lang: 'CA', t: 'Puc empadronar un nadó sense cita?' },
    { lang: 'ES', t: '¿Cuál es el teléfono?' },
    { lang: 'ES', t: '¿Dónde está la oficina?' },
    { lang: 'ES', t: '¿Qué horario tiene la OAC en verano?' },
  ],
},

// ===========================================================================
{
  slug: 'mieres',
  nombre: 'Mieres',
  articulo: 'de Mieres',
  dominios: 'mieres.es y sedeelectronica.ayto-mieres.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el Registro General', tel: '985 46 61 11', email: 'info@ayto-mieres.es' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'registro', 'registro general', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'plaza de la constitucion'],
      es: { h: 'El <b>Registro General</b> está en la plaza de la Constitución, s/n — 33600 Mieres (Asturias).',
            l: ['Teléfonos: 985 46 61 11 y 985 46 62 62.',
                'Horario: de lunes a viernes de 9:00 a 14:00.'],
            f: '<b>No es necesario pedir cita previa.</b>' },
      s: { t: 'Registro General (presencial) — mieres.es', u: 'https://www.mieres.es/ayuntamiento/registro-general-presencial/' },
    },
    {
      k: ['cita', 'cita previa', 'sin cita', 'turno', 'ticket', 'letra', 'letra a', 'letra b', 'cola', 'colas'],
      es: { h: 'En el Registro <b>no hace falta cita previa</b>: el acceso se organiza con una máquina de turnos a la entrada.',
            l: ['Pida la <b>letra A</b> para presentar solicitudes.',
                'Pida la <b>letra B</b> para recoger instancias o informarse sobre un trámite.',
                'Conviene llevar la documentación preparada para digitalizar antes de que le toque el turno.'],
            f: 'Saber qué letra le corresponde ahorra una cola entera.' },
      s: { t: 'Registro General (presencial) — mieres.es', u: 'https://www.mieres.es/ayuntamiento/registro-general-presencial/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'volante', 'certificado', 'cambio de domicilio', 'alta'],
      es: { h: 'Los trámites del <b>padrón municipal</b> tienen su ficha en la sede electrónica.',
            l: ['Alta en padrón municipal.',
                'Cambio de domicilio en padrón municipal.',
                'Los volantes de empadronamiento se pueden obtener por la sede, sin ir a la oficina.'],
            f: 'Si prefiere ir en persona: plaza de la Constitución, s/n, de 9:00 a 14:00, sin cita.' },
      s: { t: 'Alta en padrón municipal — sedeelectronica.ayto-mieres.es', u: 'https://sedeelectronica.ayto-mieres.es/sta/CarpetaPublic/doEvent?APP_CODE=STA&PAGE_CODE=CATALOGO&DETALLE=6269001222877699999500' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'destacados'],
      es: { h: 'La <b>sede electrónica</b> está en sedeelectronica.ayto-mieres.es.',
            l: ['Tiene catálogo de procedimientos y una sección de trámites destacados.',
                'Ahí figuran también las oficinas de asistencia en materia de registro.'],
            f: 'Dudas: 985 46 61 11.' },
      s: { t: 'Sede electrónica — Ayuntamiento de Mieres', u: 'https://sedeelectronica.ayto-mieres.es/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hace falta cita previa en el registro?' },
    { lang: 'ES', t: '¿Puedo darme de alta en el padrón por internet?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'ES', t: '¿Qué letra tengo que coger en la máquina?' },
  ],
},

// ===========================================================================
{
  slug: 'elda',
  nombre: 'Elda',
  articulo: 'de Elda',
  dominios: 'elda.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'la OMAC', tel: '965 380 402', email: 'ayuntamiento@elda.es' },
  idioma2: null,
  kb: [
    {
      k: ['omac', 'oficina', 'atencion al ciudadano', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'plaza constitucion', 'verano', 'julio', 'agosto'],
      es: { h: 'La <b>Oficina Municipal de Atención al Ciudadano (OMAC)</b> está en la planta baja del Ayuntamiento, plaza Constitución, 1 — 03600 Elda (Alicante).',
            l: ['Teléfono: 965 380 402.',
                'Horario: de lunes a viernes de 9:00 a 14:00.',
                'Del 1 de julio al 31 de agosto: de 9:00 a 13:30.'],
            f: 'Gestiona certificados municipales, actualizaciones del padrón y otros asuntos administrativos.' },
      s: { t: 'Atención Ciudadana — elda.es', u: 'https://www.elda.es/atencion-ciudadana-y-brecha-digital/' },
    },
    {
      k: ['cita', 'cita previa', 'sin cita', 'pedir cita', 'obligatoria', 'necesaria', 'reservar'],
      es: { h: 'Para ir en persona a la OMAC <b>no hace falta cita previa</b>.',
            l: ['Se puede pedir igualmente, de forma opcional, llamando al 965 380 402.'],
            f: 'Es decir: si le viene bien pasarse sin más, puede.' },
      s: { t: 'Atención presencial con cita previa — elda.es', u: 'https://www.elda.es/el-ayuntamiento-de-elda-habilita-a-partir-del-proximo-lunes-la-atencion-presencial-con-cita-previa-en-varios-departamentos/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'cambio de domicilio', 'actualizacion'],
      es: { h: 'La OMAC gestiona las <b>actualizaciones del padrón</b> y la emisión de certificados municipales.',
            l: ['Presencialmente en la planta baja del Ayuntamiento, sin cita.',
                'O por la sede electrónica, identificándose.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 965 380 402 antes de ir.' },
      s: { t: 'Atención al Ciudadano — elda.es', u: 'https://www.elda.es/category/atencion-al-ciudadano/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'certificado digital', 'clave', 'dni electronico'],
      es: { h: 'Para los <b>servicios electrónicos</b> hace falta identificarse.',
            l: ['Sirve el certificado electrónico, el DNI electrónico o la Clave permanente.',
                'La oficina virtual está en eamic.elda.es.'],
            f: 'Si no tiene ninguno de los tres, la OMAC atiende presencialmente sin cita.' },
      s: { t: 'Sedes, administración electrónica y transparencia — elda.es', u: 'https://www.elda.es/sedes/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hace falta cita previa en la OMAC?' },
    { lang: 'ES', t: '¿Qué necesito para entrar en la sede electrónica?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'ES', t: '¿Qué horario tiene la OMAC en agosto?' },
  ],
},

// ===========================================================================
{
  slug: 'tres-cantos',
  nombre: 'Tres Cantos',
  articulo: 'de Tres Cantos',
  dominios: 'trescantos.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'Atención al Vecino', tel: '912 938 000', email: 'atencion.vecino@trescantos.es' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'atencion al vecino', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'plaza del ayuntamiento', 'tarde', 'verano'],
      es: { h: 'El Ayuntamiento está en la <b>plaza del Ayuntamiento, 1</b> — 28760 Tres Cantos (Madrid).',
            l: ['Teléfono: 912 938 000.',
                'Correo: atencion.vecino@trescantos.es.',
                'Horario: de lunes a viernes de <b>8:00 a 18:00</b>, salvo festivos locales y el 24 y el 31 de diciembre.',
                'Del 13 de julio al 31 de agosto no hay servicio de tarde.'],
            f: 'Diez horas seguidas al día es de los horarios más amplios de la Comunidad de Madrid.' },
      s: { t: 'Horarios y servicios de atención ciudadana — trescantos.es', u: 'https://web.trescantos.es/tramite/horarios-y-servicios-de-atencion-ciudadana/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'volante', 'alta', 'cambio de domicilio', 'renovacion', 'caducidad'],
      es: { h: 'El servicio de <b>padrón</b> cubre todos los movimientos del Padrón de Habitantes.',
            l: ['Empadronamientos y emisión de volantes.',
                'Altas y cambios de domicilio.',
                'Cambio de datos padronales.',
                'Renovación de la caducidad en la inscripción del padrón.'],
            f: 'Para el registro y el padrón <b>no hace falta cita previa</b>.' },
      s: { t: 'Horarios y servicios de atención ciudadana — trescantos.es', u: 'https://web.trescantos.es/tramite/horarios-y-servicios-de-atencion-ciudadana/' },
    },
    {
      k: ['cita', 'cita previa', 'sin cita', 'pedir cita', 'necesaria', 'obligatoria', 'reservar'],
      es: { h: 'Para acudir a la oficina de <b>registro o de padrón no es necesaria la cita previa</b>.',
            l: ['Otros servicios municipales sí tienen su propio sistema de citas.',
                'Las citas previas se gestionan desde la web municipal.'],
            f: 'Con el horario de 8:00 a 18:00, hay margen de sobra para pasarse sin cita.' },
      s: { t: 'Citas Previas — trescantos.es', u: 'https://web.trescantos.es/tramites/citas-previas/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'formularios', 'impresos'],
      es: { h: 'Los <b>trámites</b> municipales están agrupados por áreas en la web.',
            l: ['Hay un buscador de trámites y un fondo documental con los formularios.'],
            f: 'Dudas: 912 938 000 o atencion.vecino@trescantos.es.' },
      s: { t: 'Trámites — Ayuntamiento de Tres Cantos', u: 'https://web.trescantos.es/tramites/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hace falta cita previa para el padrón?' },
    { lang: 'ES', t: '¿Abren los sábados?' },
    { lang: 'ES', t: '¿Qué teléfono tienen?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'ES', t: '¿Qué trámites de padrón puedo hacer?' },
  ],
},

// ===========================================================================
{
  slug: 'rincon-de-la-victoria',
  nombre: 'Rincón de la Victoria',
  articulo: 'de Rincón de la Victoria',
  dominios: 'rincondelavictoria.es y sede.rincondelavictoria.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el Ayuntamiento', tel: '952 40 23 00', email: 'registro@rincondelavictoria.es' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'atencion al ciudadano', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'al andalus', 'ayuntamiento'],
      es: { h: 'El Ayuntamiento está en la <b>plaza Al-Ándalus, 1</b> — 29730 Rincón de la Victoria (Málaga).',
            l: ['Teléfono: 952 40 23 00.',
                'Horario de atención al público: de 8:30 a 14:00.'],
            f: 'El Padrón de Habitantes está en el mismo edificio, pero con teléfonos propios.' },
      s: { t: 'Contacta con el Ayuntamiento — rincondelavictoria.es', u: 'https://www.rincondelavictoria.es/contactar' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'poblacion', 'estadistica', 'certificado', 'volante'],
      es: { h: 'El <b>Padrón de Habitantes</b> tiene sus propios teléfonos y su propio correo.',
            l: ['Teléfonos: 951 500 320, 951 500 311 y 951 500 119.',
                'Correo: padron@rincondelavictoria.es.',
                'Horario de verano: de 8:30 a 13:30, de lunes a viernes.',
                'Dirección: plaza Al-Ándalus, 1.'],
            f: 'Llamar al teléfono del padrón, y no a la centralita, ahorra un traslado de llamada.' },
      s: { t: 'Contactar Padrón de habitantes — rincondelavictoria.es', u: 'https://www.rincondelavictoria.es/areas/regimen-interior/poblacion-y-estadistica/contactar' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'obligatoria', 'necesaria', 'presencial', 'alta', 'cambio'],
      es: { h: 'Para la atención presencial y para tramitar <b>altas o cambios en el Padrón</b> hay que <b>pedir cita previa</b>.',
            l: ['La cita se pide llamando al 952 40 23 00.'],
            f: 'También hay servicios electrónicos en sede.rincondelavictoria.es, que evitan el desplazamiento.' },
      s: { t: 'Cita previa — rincondelavictoria.es', u: 'https://rincondelavictoria.es/cita-previa' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'carpeta ciudadana', 'registro general'],
      es: { h: 'La <b>sede electrónica</b> está en sede.rincondelavictoria.es.',
            l: ['Incluye la Carpeta Ciudadana, para consultar el estado de sus gestiones municipales.',
                'El Registro General tiene su propia página en la web municipal.'],
            f: 'Dudas: 952 40 23 00.' },
      s: { t: 'Carpeta Ciudadana — rincondelavictoria.es', u: 'https://www.rincondelavictoria.es/noticias/el-ayuntamiento-de-rincon-de-la-victoria-facilita-el-acceso-la-informacion-sobre-gestiones-municipales-traves-de-la-carpeta-ciudadana' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué teléfono tiene el padrón?' },
    { lang: 'ES', t: '¿Qué horario tienen?' },
    { lang: 'ES', t: '¿Necesito certificado digital?' },
    { lang: 'ES', t: '¿Dónde está el ayuntamiento?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'ES', t: '¿Piden cita?' },
  ],
},

// ===========================================================================
{
  slug: 'manacor',
  nombre: 'Manacor',
  articulo: 'de Manacor',
  dominios: 'manacor.org',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'la OAC', tel: '971 849 100', email: 'ajuntament@manacor.org' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'convent', 'convento',
          'atencio ciutadana', 'adreca', 'horari', 'telefon'],
      es: { h: 'La <b>Oficina d\'Atenció Ciutadana (OAC)</b> está en la planta baja del edificio municipal del carrer Convent.',
            l: ['El Ajuntament está en la plaça Convent, 1 — 07500 Manacor.',
                'Teléfono: 971 849 100.',
                'Horario: de lunes a viernes de 8:30 a 14:00.',
                'El servicio de certificado digital atiende de 9:00 a 14:00.'],
            f: 'Hay además atención por WhatsApp en el 674 03 59 21.' },
      ca: { h: 'L\'<b>Oficina d\'Atenció Ciutadana (OAC)</b> és a la planta baixa de l\'edifici municipal del carrer Convent.',
            l: ['L\'Ajuntament és a la plaça Convent, 1 — 07500 Manacor.',
                'Telèfon: 971 849 100.',
                'Horari: de dilluns a divendres de 8:30 a 14:00.',
                'El servei de certificat digital atén de 9:00 a 14:00.'],
            f: 'Hi ha a més atenció per WhatsApp al 674 03 59 21.' },
      s: { t: 'L\'Ajuntament estrena l\'Oficina d\'Atenció Ciutadana — manacor.org', u: 'https://manacor.org/en/node/14579' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'poblacion', 'certificado', 'cambio de domicilio',
          'padro', 'empadronar-me', 'empadronament', 'poblacio', 'certificat', 'canvi de domicili'],
      es: { h: 'La OAC atiende directamente el <b>padró</b>, el registro y el certificado digital.',
            l: ['El departamento de Població tiene extensión propia: 971 84 91 00, extensión 1312.',
                'La OAC se creó precisamente para evitar colas en estos trámites.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 971 849 100 antes de ir.' },
      ca: { h: 'L\'OAC atén directament el <b>padró</b>, el registre i el certificat digital.',
            l: ['El departament de Població té extensió pròpia: 971 84 91 00, extensió 1312.',
                'L\'OAC es va crear precisament per evitar coes en aquests tràmits.'],
            f: 'La documentació concreta depèn del seu cas. Confirmi-la al 971 849 100 abans d\'anar-hi.' },
      s: { t: 'Adreces i telèfons — manacor.org', u: 'https://manacor.org/en/node/10953' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'cola', 'colas', 'espera',
          'cita previa', 'demanar cita', 'coes'],
      es: { h: 'La OAC funciona con un <b>sistema de cita previa</b> para evitar esperas innecesarias.',
            l: ['Teléfono: 971 849 100.',
                'También se puede consultar por WhatsApp: 674 03 59 21.'],
            f: 'La oficina se estrenó con ese objetivo: mejorar los servicios y quitar colas.' },
      ca: { h: 'L\'OAC funciona amb un <b>sistema de cita prèvia</b> per evitar esperes innecessàries.',
            l: ['Telèfon: 971 849 100.',
                'També es pot consultar per WhatsApp: 674 03 59 21.'],
            f: 'L\'oficina es va estrenar amb aquest objectiu: millorar els serveis i llevar coes.' },
      s: { t: 'L\'Ajuntament estrena l\'Oficina d\'Atenció Ciutadana — manacor.org', u: 'https://manacor.org/en/node/14579' },
    },
    {
      k: ['whatsapp', 'movil', 'mensaje', 'escribir', 'sin llamar',
          'whatsapp', 'missatge', 'escriure'],
      es: { h: 'El Ajuntament tiene un servicio de atención ciudadana <b>por WhatsApp</b>.',
            l: ['Número: 674 03 59 21.'],
            f: 'Para consultas rápidas evita la llamada y la cola.' },
      ca: { h: 'L\'Ajuntament té un servei d\'atenció ciutadana <b>per WhatsApp</b>.',
            l: ['Número: 674 03 59 21.'],
            f: 'Per a consultes ràpides evita la trucada i la coa.' },
      s: { t: 'Nou servei d\'atenció ciutadana a través de WhatsApp — manacor.org', u: 'https://manacor.org/en/node/12892' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Dónde está la OAC?' },
    { lang: 'ES', t: '¿Qué teléfono tienen?' },
    { lang: 'ES', t: '¿Cómo hago el cambio de domicilio?' },
    { lang: 'ES', t: '¿Qué horario tiene el registro?' },
    { lang: 'ES', t: '¿Piden cita?' },
    { lang: 'CA', t: 'Hi ha WhatsApp de l\'Ajuntament?' },
  ],
},

// ===========================================================================
{
  slug: 'alhaurin-de-la-torre',
  nombre: 'Alhaurín de la Torre',
  articulo: 'de Alhaurín de la Torre',
  dominios: 'alhaurindelatorre.es y sede.alhaurindelatorre.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el SAC', tel: '952 41 71 50', email: 'informacion@alhaurindelatorre.es' },
  idioma2: null,
  kb: [
    {
      k: ['sac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'casa consistorial', 'antonio vega', 'julio', 'agosto', 'whatsapp', 'telegram'],
      es: { h: 'El <b>Servicio de Atención Ciudadana (SAC)</b> está en la Casa Consistorial, plaza Alcalde Antonio Vega González, s/n — 29130 Alhaurín de la Torre (Málaga).',
            l: ['Teléfonos: 952 41 71 50 y 952 41 71 51.',
                'Horario: de 9:30 a 14:00. En julio y agosto, de 9:30 a 13:30.',
                'Correo: informacion@alhaurindelatorre.es.',
                'WhatsApp y Telegram: 637 326 401.'],
            f: 'Se puede consultar por mensaje sin necesidad de llamar.' },
      s: { t: 'Atención ciudadana — alhaurindelatorre.es', u: 'https://alhaurindelatorre.es/atencion-ciudadana/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta', 'baja', 'renovacion', 'confirmacion', 'cambio de domicilio', 'modificacion'],
      es: { h: 'El SAC gestiona todos los movimientos del <b>Padrón Municipal de Habitantes</b>.',
            l: ['Altas y bajas.',
                'Renovación y confirmación.',
                'Cambios de domicilio.',
                'Modificación de datos.'],
            f: 'Para la expedición de <b>certificados de empadronamiento no hace falta cita previa</b>.' },
      s: { t: '¿Qué trámites puedo realizar en el SAC? — alhaurindelatorre.es', u: 'https://alhaurindelatorre.es/que-tramites-puedo-realizar-en-el-servicio-de-atencion-ciudadana-sac/' },
    },
    {
      k: ['cita', 'cita previa', 'sin cita', 'pedir cita', 'reservar', 'urbanismo', 'urbanistico'],
      es: { h: 'Para los <b>certificados de empadronamiento no es necesario pedir cita previa</b>.',
            l: ['Sí hace falta para temas urbanísticos y para el registro de documentación urbanística.',
                'Esas citas se piden en el 952 41 71 57.'],
            f: 'Para el resto de gestiones del SAC: 952 41 71 50 y 952 41 71 51.' },
      s: { t: 'Cita Previa — alhaurindelatorre.es', u: 'https://alhaurindelatorre.es/cita-previa-d22/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'carpeta ciudadana'],
      es: { h: 'La <b>sede electrónica</b> está en sede.alhaurindelatorre.es.',
            l: ['Incluye una Carpeta Ciudadana para seguir sus expedientes.',
                'Los trámites están listados en alhaurindelatorre.es/tramites.'],
            f: 'Dudas: 952 41 71 50, o por WhatsApp en el 637 326 401.' },
      s: { t: 'Sede Electrónica — Ayuntamiento de Alhaurín de la Torre', u: 'https://sede.alhaurindelatorre.es/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hace falta cita para el certificado de empadronamiento?' },
    { lang: 'ES', t: '¿Tienen WhatsApp?' },
    { lang: 'ES', t: '¿Qué horario tiene el SAC en agosto?' },
    { lang: 'ES', t: '¿Dónde está la oficina?' },
    { lang: 'ES', t: '¿Cuál es el teléfono?' },
  ],
},

// ===========================================================================
{
  slug: 'naron',
  nombre: 'Narón',
  articulo: 'de Narón',
  dominios: 'naron.gal y sedeelectronica.naron.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el Registro', tel: '981 33 77 00', email: 'naron@naron.gal' },
  idioma2: { cod: 'GL', clave: 'gl', sigla: 'no Rexistro', nombre: 'gallego' },
  kb: [
    {
      k: ['oficina', 'concello', 'direccion', 'telefono', 'contacto', 'plaza de galicia', 'ayuntamiento',
          'enderezo', 'praza de galicia'],
      es: { h: 'El <b>Concello de Narón</b> está en la plaza de Galicia, s/n — 15570 Narón.',
            l: ['Teléfono: 981 33 77 00.',
                'Correo: naron@naron.gal.'],
            f: 'La centralita reparte por extensiones: la <b>3</b> es la de Registro, Estadística y Policía Local.' },
      gl: { h: 'O <b>Concello de Narón</b> está na praza de Galicia, s/n — 15570 Narón.',
            l: ['Teléfono: 981 33 77 00.',
                'Correo: naron@naron.gal.'],
            f: 'A centraliña reparte por extensións: a <b>3</b> é a de Rexistro, Estatística e Policía Local.' },
      s: { t: 'Directorio Telefónico — naron.gal', u: 'https://www.naron.gal/cat/gal/concello/ayuntamiento_directorio_telefonico' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita', 'telefono de cita',
          'cita previa', 'pedir cita'],
      es: { h: 'La <b>cita previa</b> tiene un teléfono propio: el <b>981 111 025</b>.',
            l: ['Se atiende de 8:30 a 13:30, por la mañana.'],
            f: 'No es el número de la centralita: para cita, llame directamente al 981 111 025.' },
      gl: { h: 'A <b>cita previa</b> ten un teléfono propio: o <b>981 111 025</b>.',
            l: ['Atenden de 8:30 a 13:30, pola mañá.'],
            f: 'Non é o número da centraliña: para cita, chame directamente ao 981 111 025.' },
      s: { t: 'Directorio Telefónico — naron.gal', u: 'https://www.naron.gal/cat/gal/concello/ayuntamiento_directorio_telefonico' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'estadistica', 'certificado', 'volante', 'lunes', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran',
          'empadroarme', 'empadroamento', 'estatistica', 'luns'],
      es: { h: 'El padrón lo lleva <b>Estadística</b>, que atiende al público los <b>lunes de 11:00 a 13:00</b>.',
            l: ['Por teléfono: 981 33 77 00, extensión 3.',
                'Esa extensión cubre Registro, Estadística y Policía Local.'],
            f: 'Si va en persona, tenga en cuenta esa franja: es estrecha.' },
      gl: { h: 'O padrón lévao <b>Estatística</b>, que atende ao público os <b>luns de 11:00 a 13:00</b>.',
            l: ['Por teléfono: 981 33 77 00, extensión 3.',
                'Esa extensión cobre Rexistro, Estatística e Policía Local.'],
            f: 'Se vai en persoa, teña en conta esa franxa: é estreita.' },
      s: { t: 'Directorio Telefónico — naron.gal', u: 'https://www.naron.gal/cat/gal/concello/ayuntamiento_directorio_telefonico' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet',
          'sede electronica', 'tramite', 'tramites'],
      es: { h: 'La <b>sede electrónica</b> del Concello está en sedeelectronica.naron.es.',
            l: ['Permite hacer gestiones sin acudir a las oficinas.'],
            f: 'Dudas: 981 33 77 00.' },
      gl: { h: 'A <b>sede electrónica</b> do Concello está en sedeelectronica.naron.es.',
            l: ['Permite facer xestións sen acudir ás oficinas.'],
            f: 'Dúbidas: 981 33 77 00.' },
      s: { t: 'Sede Electrónica do Concello de Narón', u: 'https://sedeelectronica.naron.es/siac/default.aspx' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué días atiende Estadística?' },
    { lang: 'ES', t: '¿Qué necesito para empadronar a un recién nacido?' },
    { lang: 'GL', t: 'Onde está o Concello?' },
    { lang: 'GL', t: 'Como podo pedir cita previa?' },
    { lang: 'ES', t: '¿Puedo hacerlo por internet?' },
  ],
},

];
