// ---------------------------------------------------------------------------
//  LOS OCHO DEL QUINTO ENVIO — miercoles 16 de septiembre de 2026.
//  Comprobado en cada web municipal el 6 de septiembre de 2026.
//
//  Catalan en Granollers. Valenciano en Sant Vicent del Raspeig: este si esta
//  en zona de predominio linguistico valenciano (l'Alacanti) —a diferencia de
//  Torrevieja y Orihuela, que van en castellano.
// ---------------------------------------------------------------------------

export const MUNICIPIOS_DIA05 = [

// ===========================================================================
{
  slug: 'molina-de-segura',
  nombre: 'Molina de Segura',
  articulo: 'de Molina de Segura',
  dominios: 'molinadesegura.es y sedeelectronica.molinadesegura.es',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'Atención al Ciudadano', tel: '968 388 500', email: 'ayuntamiento@molinadesegura.es' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'oficinas', 'atencion al ciudadano', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'compania', 'altorreal', 'sabado', 'sabados'],
      es: { h: 'La oficina de <b>Atención al Ciudadano</b> está en el Parque de la Compañía, s/n.',
            l: ['Teléfono: 968 388 500.',
                'Horario de verano: de lunes a viernes de 8:00 a 14:30, y sábados de 9:00 a 13:00.',
                'Hay otra oficina en Altorreal: avenida Reino de Murcia, 56.',
                'El Registro del Ayuntamiento está en la plaza de España, s/n.'],
            f: 'Son tres puntos distintos: conviene saber cuál le corresponde antes de salir de casa.' },
      s: { t: 'Atención al Ciudadano — molinadesegura.es', u: 'https://portal.molinadesegura.es/atencion-al-ciudadano/' },
    },
    {
      k: ['certificado', 'certificados de padron', 'historico', 'convivencia', 'descargar', 'clave', 'certificado digital'],
      es: { h: 'Los <b>certificados de padrón</b> se descargan de la sede electrónica identificándose.',
            l: ['Sirve el certificado digital o Cl@ve Permanente.',
                'Se pueden obtener individuales, individuales históricos y colectivos.'],
            f: 'Si no tiene certificado digital, se pueden pedir en la oficina de Atención al Ciudadano: 968 388 500.' },
      s: { t: 'Certificados de padrón — sedeelectronica.molinadesegura.es', u: 'https://sedeelectronica.molinadesegura.es/index.php?option=com_content&view=article&id=403:certificados-de-padron&catid=88&Itemid=289' },
    },
    {
      k: ['volante', 'volantes de padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'padron', 'cambio de domicilio', 'mudarme'],
      es: { h: 'Los <b>volantes de padrón</b> tienen su propio trámite en la sede electrónica.',
            l: ['Hay además un portal específico del padrón: padron.molinadesegura.es.',
                'Los formularios del padrón se descargan de la sede.'],
            f: 'Volante y certificado no valen para lo mismo: si le han pedido uno concreto, compruébelo antes.' },
      s: { t: 'Volantes de padrón — sedeelectronica.molinadesegura.es', u: 'https://sedeelectronica.molinadesegura.es/index.php?option=com_content&view=article&id=404:volantes-de-padron&catid=88&Itemid=289' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'formularios', 'impresos'],
      es: { h: 'La <b>sede electrónica</b> está en sedeelectronica.molinadesegura.es.',
            l: ['Ahí están los trámites y la descarga de formularios del padrón.',
                'Hay también una carpeta ciudadana en cciudadana.molinadesegura.es.'],
            f: 'Dudas: 968 388 500.' },
      s: { t: 'Sede Electrónica — Ayuntamiento de Molina de Segura', u: 'https://sedeelectronica.molinadesegura.es/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Dónde está la oficina de atención al ciudadano?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'ES', t: '¿Cómo descargo un certificado de padrón?' },
    { lang: 'ES', t: '¿Abren los sábados?' },
  ],
},

// ===========================================================================
{
  slug: 'alcala-de-guadaira',
  nombre: 'Alcalá de Guadaíra',
  articulo: 'de Alcalá de Guadaíra',
  dominios: 'ciudadalcala.org',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'la OAC', tel: '955 796 420', email: 'oac@alcalaguadaira.org' },
  idioma2: null,
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'santa lucia'],
      es: { h: 'La <b>Oficina de Atención Ciudadana (OAC)</b> está en la calle Santa Lucía, s/n — 41500 Alcalá de Guadaíra.',
            l: ['Teléfono: 955 796 420.',
                'Horario: de 9:00 a 13:00.'],
            f: 'Correo: oac@alcalaguadaira.org.' },
      s: { t: 'Oficina Municipal de Atención Ciudadana — ciudadalcala.org', u: 'https://ciudadalcala.org/ayuntamiento/servicios-municipales' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'vecino', 'nuevo vecino', 'vivir', 'cambio de domicilio', 'mudarme'],
      es: { h: 'Si viene a vivir a Alcalá de Guadaíra, tiene que <b>empadronarse</b> en las oficinas municipales.',
            l: ['Con el empadronamiento adquiere la condición de vecino, y con ella sus derechos y deberes.',
                'Se tramita en la OAC: calle Santa Lucía, s/n, de 9:00 a 13:00.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 955 796 420 antes de ir.' },
      s: { t: 'Servicios al ciudadano — ciudadalcala.org', u: 'https://ciudadalcala.org/servicios-al-ciudadano' },
    },
    {
      k: ['informacion', 'que hacen', 'para que sirve', 'orientacion', 'servicios municipales', 'tramites administrativos'],
      es: { h: 'La OAC <b>orienta e informa</b> sobre los servicios municipales y los recursos de la ciudad.',
            l: ['Atiende consultas sobre servicios y trámites administrativos.',
                'Y también sobre los recursos del municipio en general.'],
            f: 'Es el punto de entrada si no sabe a qué departamento le corresponde su gestión.' },
      s: { t: 'Atención al ciudadano — ciudadalcala.org', u: 'https://ciudadalcala.org/contacto' },
    },
    {
      k: ['omic', 'consumo', 'consumidor', 'reclamacion', 'cita', 'cita previa', 'rafael santos'],
      es: { h: 'La <b>Oficina de Información al Consumidor (OMIC)</b> funciona <b>con cita previa</b>.',
            l: ['Se atiende en la OAC, en el edificio de la calle Rafael Santos.'],
            f: 'Para el resto de gestiones de la OAC, el teléfono es el 955 796 420.' },
      s: { t: 'La OMIC de Alcalá atiende a más de un millar de personas al año — ciudadalcala.org', u: 'https://ciudadalcala.org/noticias/noticia/3362/la-oficina-de-informacion-al-consumidor-de-alcala-atiende-a-mas-de-un-millar-de-personas-al-ano-' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué horario tiene la OAC?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'ES', t: '¿Dónde me empadrono si me mudo aquí?' },
    { lang: 'ES', t: '¿La OMIC necesita cita previa?' },
  ],
},

// ===========================================================================
{
  slug: 'santa-lucia-de-tirajana',
  nombre: 'Santa Lucía de Tirajana',
  articulo: 'de Santa Lucía de Tirajana',
  dominios: 'santaluciagc.com',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'la OAC', tel: '928 727 200, 900 705 010 o 010', email: 'info@santaluciagc.com' },
  idioma2: null,
  kb: [
    {
      k: ['oac', 'oficina', 'atencion al ciudadano', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'tirajanas', 'martes', 'jueves', 'tarde', 'agosto'],
      es: { h: 'La <b>Oficina de Atención al Ciudadano (OAC)</b> está en la avenida de las Tirajanas, 151, Edificio Anexo.',
            l: ['Lunes, miércoles y viernes: de 9:00 a 14:00.',
                'Martes y jueves: de 9:00 a <b>19:00</b>.',
                'En agosto, Semana Santa y Navidad: de lunes a viernes de 9:00 a 14:00.'],
            f: 'Si necesita ir por la tarde, sus días son el martes y el jueves.' },
      s: { t: 'Oficina de Atención al Ciudadano (OAC) — santaluciagc.com', u: 'https://www.santaluciagc.com/areas/buen-gobierno-y-hacienda/oficina-de-atencion-al-ciudadano-oac/' },
    },
    {
      k: ['certificado', 'empadronamiento', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'padron', 'signos externos', 'inmediato', 'al momento'],
      es: { h: 'Los <b>certificados de empadronamiento</b> se obtienen en la OAC <b>con carácter inmediato</b>.',
            l: ['Lo mismo vale para los certificados de signos externos.',
                'No hay que volver otro día a recogerlos.'],
            f: 'La OAC está en la avenida de las Tirajanas, 151, Edificio Anexo.' },
      s: { t: 'Oficina de Atención Ciudadana (OAC) — santaluciagc.com', u: 'https://www2.santaluciagc.com/modules.php?mod=portal&file=ver_gen&id=TkRjMk5BPT0%3D' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita', 'telefono de cita'],
      es: { h: 'La <b>cita previa</b> se pide por teléfono.',
            l: ['928 727 200.',
                '900 705 010.',
                'O el <b>010</b>, si llama desde Santa Lucía.'],
            f: 'La OAC atiende de forma presencial, telemática y telefónica.' },
      s: { t: 'Oficina de Atención al Ciudadano (OAC) — santaluciagc.com', u: 'https://www.santaluciagc.com/areas/buen-gobierno-y-hacienda/oficina-de-atencion-al-ciudadano-oac/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'clave', 'certificado digital'],
      es: { h: 'Las gestiones de la <b>sede electrónica</b> se pueden hacer también con el sistema <b>Cl@ve</b>.',
            l: ['No hace falta certificado digital instalado para todo.',
                'Hay además una oficina virtual del ciudadano para lo tributario.'],
            f: 'Si se atasca, la OAC atiende por teléfono en el 928 727 200 o el 010.' },
      s: { t: 'Las gestiones en la sede electrónica también con Cl@ve — santaluciagc.com', u: 'https://www.santaluciagc.com/las-gestiones-en-la-sede-electronica-del-ayuntamiento-de-santa-lucia-tambien-se-pueden-hacer-a-traves-del-sistema-clave/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué días abre la OAC por la tarde?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'ES', t: '¿Me dan el certificado de empadronamiento en el momento?' },
    { lang: 'ES', t: '¿Cómo pido cita previa?' },
  ],
},

// ===========================================================================
{
  slug: 'sant-vicent-del-raspeig',
  nombre: 'Sant Vicent del Raspeig',
  articulo: 'de Sant Vicent del Raspeig',
  dominios: 'raspeig.es',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'la oficina CIVIC', tel: '010 o 965 67 50 65', email: 'civic@raspeig.es' },
  idioma2: { cod: 'VA', clave: 'va', sigla: "a l'oficina CIVIC", nombre: 'valenciano' },
  kb: [
    {
      k: ['civic', 'oficina', 'atencion al ciudadano', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'comunitat valenciana', 'invierno', 'verano',
          'atencio', 'adreca', 'horari', 'telefon', 'hivern', 'estiu'],
      es: { h: 'La oficina <b>CIVIC</b> está en la plaça de la Comunitat Valenciana, 1.',
            l: ['Teléfono: el <b>010</b> desde el término municipal, o el 965 67 50 65.',
                'Del 16 de octubre al 14 de mayo: de lunes a jueves de 9:00 a 16:30, y viernes de 9:00 a 14:00.',
                'Del 15 de mayo al 15 de octubre: de lunes a viernes de 8:30 a 14:00.'],
            f: 'Correo: civic@raspeig.es.' },
      va: { h: 'L\'oficina <b>CIVIC</b> està a la plaça de la Comunitat Valenciana, 1.',
            l: ['Telèfon: el <b>010</b> des del terme municipal, o el 965 67 50 65.',
                'Del 16 d\'octubre al 14 de maig: de dilluns a dijous de 9:00 a 16:30, i divendres de 9:00 a 14:00.',
                'Del 15 de maig al 15 d\'octubre: de dilluns a divendres de 8:30 a 14:00.'],
            f: 'Correu: civic@raspeig.es.' },
      s: { t: 'Horario Oficina CIVIC — raspeig.es', u: 'https://raspeig.es/seccion/horario-oficina-civic/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'justificante', 'sin cita', 'ticket', 'maquina',
          'padro', 'empadronar-me', 'empadronament', 'justificant', 'sense cita'],
      es: { h: 'Para los <b>justificantes del Padrón de Habitantes no hace falta cita previa</b>.',
            l: ['Solo hay que acudir con el documento de identidad original.',
                'Y sacar ticket en la máquina expendedora del hall.'],
            f: 'La oficina CIVIC gestiona además los movimientos en el Padrón de Habitantes.' },
      va: { h: 'Per als <b>justificants del Padró d\'Habitants no cal cita prèvia</b>.',
            l: ['Només cal acudir amb el document d\'identitat original.',
                'I traure tiquet a la màquina expenedora del hall.'],
            f: 'L\'oficina CIVIC gestiona a més els moviments al Padró d\'Habitants.' },
      s: { t: 'Padrón Municipal de Habitantes (PMH) — raspeig.es', u: 'https://raspeig.es/area/padron-municipal-de-habitantes-pmh/' },
    },
    {
      k: ['volante', 'certificado', 'certificado de empadronamiento', 'acreditar residencia',
          'volant', 'certificat', 'certificat d empadronament'],
      es: { h: 'El <b>volante o certificado de empadronamiento</b> tiene su propia ficha de trámite.',
            l: ['Se puede consultar en raspeig.es, en el apartado de trámites.'],
            f: 'Para el justificante no hace falta cita: documento de identidad y ticket en el hall.' },
      va: { h: 'El <b>volant o certificat d\'empadronament</b> té la seua pròpia fitxa de tràmit.',
            l: ['Es pot consultar a raspeig.es, a l\'apartat de tràmits.'],
            f: 'Per al justificant no cal cita: document d\'identitat i tiquet al hall.' },
      s: { t: 'Volante / Certificado de empadronamiento — raspeig.es', u: 'https://raspeig.es/tramites/volante-certificado-de-empadronamiento/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita',
          'cita previa', 'demanar cita'],
      es: { h: 'La <b>cita previa</b> se pide por la web, indicando el servicio para el que la necesita.',
            l: ['También por teléfono, en el 965 67 50 65.'],
            f: 'Recuerde que para los justificantes de padrón no hace falta.' },
      va: { h: 'La <b>cita prèvia</b> es demana per la web, indicant el servei per al qual la necessita.',
            l: ['També per telèfon, al 965 67 50 65.'],
            f: 'Recorde que per als justificants de padró no cal.' },
      s: { t: 'Atención al ciudadano — raspeig.es', u: 'https://raspeig.es/area/atencion-al-ciudadano/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hace falta cita para el justificante de padrón?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'VA', t: 'Quin horari té l\'oficina CIVIC a l\'estiu?' },
    { lang: 'ES', t: '¿Dónde está la oficina CIVIC?' },
  ],
},

// ===========================================================================
{
  slug: 'granollers',
  nombre: 'Granollers',
  articulo: 'de Granollers',
  dominios: 'granollers.cat y seuelectronica.granollers.cat',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'la OAC', tel: '010 o 93 842 66 10', email: 'oac@granollers.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'sant josep', 'sin cita', 'con cita', 'verano',
          'atencio ciutadana', 'adreca', 'horari', 'telefon', 'sense cita', 'amb cita', 'estiu'],
      es: { h: 'La <b>Oficina d\'Atenció a la Ciutadania (OAC)</b> está en el carrer de Sant Josep, 7 — 08401 Granollers.',
            l: ['Teléfono: el <b>010</b>, o el 93 842 66 10 desde fuera de Granollers.',
                '<b>Con cita previa</b>: de lunes a jueves de 8:30 a 19:00; viernes y vísperas de festivo de 9:00 a 14:00.',
                '<b>Sin cita previa</b>: de lunes a jueves de 8:30 a 15:00; viernes y vísperas de 9:00 a 14:00.',
                'Verano, del 1 de julio al 15 de septiembre: de lunes a jueves de 8:30 a 15:00, y viernes de 9:00 a 14:00.'],
            f: 'Con cita puede ir hasta las 19:00; sin cita, solo hasta las 15:00.' },
      ca: { h: 'L\'<b>Oficina d\'Atenció a la Ciutadania (OAC)</b> és al carrer de Sant Josep, 7 — 08401 Granollers.',
            l: ['Telèfon: el <b>010</b>, o el 93 842 66 10 des de fora de Granollers.',
                '<b>Amb cita prèvia</b>: de dilluns a dijous de 8:30 a 19:00; divendres i vigílies de festiu de 9:00 a 14:00.',
                '<b>Sense cita prèvia</b>: de dilluns a dijous de 8:30 a 15:00; divendres i vigílies de 9:00 a 14:00.',
                'Estiu, de l\'1 de juliol al 15 de setembre: de dilluns a dijous de 8:30 a 15:00, i divendres de 9:00 a 14:00.'],
            f: 'Amb cita pot anar-hi fins a les 19:00; sense cita, només fins a les 15:00.' },
      s: { t: 'Oficina d\'Atenció a la Ciutadania (OAC) — granollers.cat', u: 'https://www.granollers.cat/adreces/administratius/oficina-datencio-ciutadana-oac' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'cambio de domicilio', 'mudarme',
          'padro', 'empadronar-me', 'empadronament', 'certificat', 'volant', 'canvi de domicili'],
      es: { h: 'La OAC tramita el <b>empadronamiento</b>, entre otras muchas gestiones municipales.',
            l: ['También el censo de animales domésticos y el cementerio municipal.',
                'Las tarjetas de autobús para jubilados y los duplicados de recibos pagados.',
                'Las inscripciones a casales de verano, cursos y talleres.',
                'Y el cobro de diversas tasas y precios públicos.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 010 antes de ir.' },
      ca: { h: 'L\'OAC tramita l\'<b>empadronament</b>, entre moltes altres gestions municipals.',
            l: ['També el cens d\'animals domèstics i el cementiri municipal.',
                'Les targetes d\'autobús per a jubilats i els duplicats de rebuts pagats.',
                'Les inscripcions a casals d\'estiu, cursos i tallers.',
                'I el cobrament de diverses taxes i preus públics.'],
            f: 'La documentació concreta depèn del seu cas. Confirmi-la al 010 abans d\'anar-hi.' },
      s: { t: 'Oficina d\'Atenció a la Ciutadania (OAC) — granollers.cat', u: 'https://www.granollers.cat/adreces/administratius/oficina-datencio-ciutadana-oac' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita',
          'cita previa', 'demanar cita'],
      es: { h: 'La <b>cita previa</b> se pide desde la web municipal.',
            l: ['granollers.cat/citaprevia.',
                'También hay una vía específica en la seu electrònica.'],
            f: 'Con cita la OAC atiende hasta las 19:00 de lunes a jueves; sin ella, hasta las 15:00.' },
      ca: { h: 'La <b>cita prèvia</b> es demana des del web municipal.',
            l: ['granollers.cat/citaprevia.',
                'També hi ha una via específica a la seu electrònica.'],
            f: 'Amb cita l\'OAC atén fins a les 19:00 de dilluns a dijous; sense ella, fins a les 15:00.' },
      s: { t: 'Cita Prèvia — Ajuntament de Granollers', u: 'https://www.granollers.cat/citaprevia' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet',
          'seu electronica', 'tramit', 'tramits', 'per internet'],
      es: { h: 'La OAC atiende <b>por la seu electrònica, por teléfono y presencialmente</b>.',
            l: ['La sede es seuelectronica.granollers.cat.',
                'Correo: oac@granollers.cat.'],
            f: 'Por teléfono: el 010, o el 93 842 66 10 desde fuera.' },
      ca: { h: 'L\'OAC atén <b>per la seu electrònica, per telèfon i presencialment</b>.',
            l: ['La seu és seuelectronica.granollers.cat.',
                'Correu: oac@granollers.cat.'],
            f: 'Per telèfon: el 010, o el 93 842 66 10 des de fora.' },
      s: { t: 'Oficina d\'Atenció a la Ciutadania — Seu Electrònica de Granollers', u: 'https://seuelectronica.granollers.cat/portal/sede/se_contenedor1.jsp?seccion=s_floc_d4_v1.jsp&contenido=1103&tipo=1&nivel=1400&layout=se_contenedor1.jsp&language=ca' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hasta qué hora atienden sin cita previa?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'CA', t: 'Quin horari té l\'OAC a l\'estiu?' },
    { lang: 'ES', t: '¿Qué trámites hace la OAC?' },
  ],
},

// ===========================================================================
{
  slug: 'motril',
  nombre: 'Motril',
  articulo: 'de Motril',
  dominios: 'motril.es y sede.motril.es',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'el Registro', tel: '958 83 83 00', email: 'informacion@motril.es' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'registro', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'cardenal belluga'],
      es: { h: 'La oficina de <b>Registro y Atención Ciudadana</b> está en la calle Cardenal Belluga, 1 — 18600 Motril (Granada).',
            l: ['Teléfonos: 958 83 83 00, 958 83 83 02, 958 83 83 03 y 958 83 83 04.',
                'Horario: de lunes a viernes de 9:00 a 13:30.'],
            f: 'Hay además oficinas de distrito repartidas por el municipio.' },
      s: { t: 'Registro — Ayuntamiento de Motril', u: 'https://motril.es/registro/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'estadistica', 'certificado', 'volante', 'extranjeros', 'renovacion', 'cambio de domicilio'],
      es: { h: 'El servicio de <b>Estadística</b> lleva todos los movimientos del padrón.',
            l: ['Altas, bajas, cambios y modificaciones de datos del padrón.',
                'Renovaciones de extranjeros.',
                'Volantes y certificados de empadronamiento.',
                'Teléfonos específicos de padrón: 958 83 83 25 y 958 83 83 26.'],
            f: 'También atienden al contribuyente y el registro de documentación.' },
      s: { t: 'Nuevo sistema de cita previa online — motril.es', u: 'https://motril.es/el-ayuntamiento-de-motril-implanta-un-nuevo-sistema-de-cita-previa-online-para-mejorar-y-agilizar-la-atencion-al-ciudadano/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita', 'espera', 'colas'],
      es: { h: 'Hay un sistema de <b>cita previa online</b> para reducir los tiempos de espera.',
            l: ['Cubre los servicios de estadística —empadronamiento—, información y registro.',
                'Se accede desde la web municipal, motril.es.'],
            f: 'Si prefiere el teléfono: 958 83 83 25 o 958 83 83 26 para el padrón.' },
      s: { t: 'Nuevo sistema de cita previa online — motril.es', u: 'https://motril.es/el-ayuntamiento-de-motril-implanta-un-nuevo-sistema-de-cita-previa-online-para-mejorar-y-agilizar-la-atencion-al-ciudadano/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'telematica', 'oficinas de asistencia'],
      es: { h: 'La <b>sede electrónica</b> está en sede.motril.es.',
            l: ['Ahí figuran también las oficinas de asistencia en materia de registro.',
                'Hay atención telemática y telefónica además de la presencial.'],
            f: 'Dudas: 958 83 83 00.' },
      s: { t: 'Sede electrónica — Ayuntamiento de Motril', u: 'https://sede.motril.es/sta' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué teléfono tiene el padrón?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'ES', t: '¿Puedo pedir cita previa por internet?' },
    { lang: 'ES', t: '¿Qué horario tiene el registro?' },
  ],
},

// ===========================================================================
{
  slug: 'zamora',
  nombre: 'Zamora',
  articulo: 'de Zamora',
  dominios: 'zamora.es',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'el departamento de Padrón y Estadística', tel: '980 54 87 00', email: 'registro@zamora.es' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'padron', 'estadistica', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'santa ana', 'san torcuato'],
      es: { h: 'El departamento de <b>Padrón y Estadística</b> está en la calle Santa Ana, 5, esquina con la Ronda de San Torcuato, planta baja.',
            l: ['Teléfono: 980 54 87 00, extensiones 170, 171 y 173.',
                'Horario: de 9:00 a 13:30.'],
            f: 'Es la oficina que lleva todo lo relativo al Padrón Municipal de Habitantes.' },
      s: { t: 'Ubicación y contacto — zamora.es', u: 'https://www.zamora.es/contenidos.aspx?id=665' },
    },
    {
      k: ['empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta', 'inscripcion', 'nuevo vecino', 'mudarme'],
      es: { h: 'El <b>alta en el Padrón Municipal de Habitantes</b> tiene su propio trámite.',
            l: ['Se puede hacer telemáticamente rellenando la instancia que aparece en la sede electrónica.',
                'O presencialmente en Santa Ana, 5, de 9:00 a 13:30.'],
            f: 'Hay también trámites de baja y de modificación de datos, cada uno con su ficha.' },
      s: { t: 'Solicitud para la Inscripción en el Padrón Municipal (Alta) — zamora.es', u: 'https://www.zamora.es/contenidos.aspx?id=31745' },
    },
    {
      k: ['certificado', 'volante', 'convivencia', 'residencia', 'acreditar', 'como consigo'],
      es: { h: 'La <b>solicitud de certificado o volante de empadronamiento</b> es un trámite específico.',
            l: ['Sirve para acreditar la convivencia o la residencia.',
                'Se puede presentar telemáticamente desde la sede electrónica.'],
            f: 'Teléfono del departamento: 980 54 87 00, extensiones 170, 171 y 173.' },
      s: { t: 'Solicitud de Certificado o Volante de Empadronamiento — zamora.es', u: 'https://www.zamora.es/contenidos.aspx?id=31750' },
    },
    {
      k: ['modificar', 'modificacion', 'cambiar datos', 'corregir', 'error', 'baja', 'darme de baja'],
      es: { h: 'Para <b>modificar datos</b> del padrón o para darse de <b>baja</b> hay dos trámites distintos.',
            l: ['Modificación de los datos del Padrón Municipal de Habitantes.',
                'Baja en el Padrón Municipal de Habitantes.',
                'Ambos se pueden presentar telemáticamente con la instancia de la sede.'],
            f: 'Si no sabe cuál le corresponde, pregunte en el 980 54 87 00.' },
      s: { t: 'Solicitud de Modificación de los Datos del Padrón — zamora.es', u: 'https://www.zamora.es/contenidos.aspx?id=31748' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Dónde está la oficina del padrón?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'ES', t: '¿Cómo pido un certificado de empadronamiento?' },
    { lang: 'ES', t: '¿Puedo darme de alta en el padrón por internet?' },
  ],
},

// ===========================================================================
{
  slug: 'colmenar-viejo',
  nombre: 'Colmenar Viejo',
  articulo: 'de Colmenar Viejo',
  dominios: 'colmenarviejo.com',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: 'Atención al Ciudadano', tel: '91 845 00 53', email: 'registro@colmenarviejo.com' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'atencion al ciudadano', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'plaza del pueblo', 'lunes', 'tarde'],
      es: { h: 'La oficina de <b>Atención al Ciudadano</b> está en la plaza del Pueblo, 1.',
            l: ['Teléfono: 91 845 00 53.',
                'Horario: de lunes a viernes de 9:00 a 14:00.',
                'Los <b>lunes</b> también por la tarde, de 16:30 a 19:30.'],
            f: 'El lunes es el único día con horario de tarde.' },
      s: { t: 'Atención al Ciudadano — colmenarviejo.com', u: 'https://colmenarviejo.com/ayuntamiento/concejalias/educacion-sanidad-y-atencion-al-ciudadano/atencion-al-ciudadano' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'cambio de domicilio', 'mudarme', 'registro'],
      es: { h: 'Los trámites de <b>padrón</b> y el registro municipal se atienden en la oficina de la plaza del Pueblo, 1.',
            l: ['De lunes a viernes de 9:00 a 14:00, y los lunes también de 16:30 a 19:30.',
                'Correo del registro: registro@colmenarviejo.com.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 91 845 00 53 antes de ir.' },
      s: { t: 'Contactar — Ayuntamiento de Colmenar Viejo', u: 'https://colmenarviejo.com/contactar' },
    },
    {
      k: ['departamentos', 'secretaria', 'tesoreria', 'a quien pregunto', 'que departamento', 'donde me dirijo'],
      es: { h: 'El Ayuntamiento publica su <b>directorio de departamentos</b> en la web.',
            l: ['Ahí figuran Secretaría General, Tesorería Municipal y el resto de áreas.',
                'También el listado de centros municipales.'],
            f: 'Si no sabe a qué departamento le corresponde su gestión, empiece por Atención al Ciudadano: 91 845 00 53.' },
      s: { t: 'Departamentos — Ayuntamiento de Colmenar Viejo', u: 'https://colmenarviejo.com/ayuntamiento/administracion/departamentos' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué días abren por la tarde?' },
    { lang: 'ES', t: '¿Cuánto cuesta exactamente el IBI?' },
    { lang: 'ES', t: '¿Dónde está la oficina de atención al ciudadano?' },
    { lang: 'ES', t: '¿Dónde tramito el padrón?' },
  ],
},

];
