// ---------------------------------------------------------------------------
//  LOS OCHO DEL SEGUNDO ENVIO. Todo lo de aqui esta comprobado en la web
//  municipal el 6 de septiembre de 2026. Si un dato no se pudo verificar, NO
//  esta puesto: la demo prefiere decir "no lo se" y dar el telefono antes que
//  inventarse un numero de impreso. Un ayuntamiento detecta un tramite mal
//  citado en diez segundos, y ahi se acaba la venta.
//
//  Badalona y Terrassa tienen fichas mas largas porque sus sedes publican el
//  detalle de cada tramite (impresos, plazos, tasas). Las otras seis publican
//  la oficina y poco mas, asi que su base de conocimiento es mas corta a
//  proposito.
// ---------------------------------------------------------------------------

export const MUNICIPIOS = [

// ===========================================================================
{
  slug: 'badalona',
  nombre: 'Badalona',
  articulo: 'de Badalona',
  dominios: 'badalona.cat y seu.badalona.cat',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: "el SAC", largo: 'Servei d\'Atenció al Ciutadà', tel: '93 483 26 00', email: 'sac@badalona.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "al SAC", nombre: 'catalán', sufijo: 'ca', oficinaLargo: 'Servei d\'Atenció al Ciutadà' },
  kb: [
    {
      k: ['empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'darme de alta', 'cambio de domicilio', 'mudarme', 'nuevo vecino',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me', 'donar-me d alta'],
      es: { h: 'El alta y el cambio de domicilio en el <b>padró municipal d\'habitants</b> se tramitan en el SAC o en la sede electrónica.',
            l: ['Hay que acreditar la titularidad de la vivienda. Si no se puede, se presenta una solicitud de comprobación de residencia.',
                'En vivienda de alquiler: contrato a nombre de quien se empadrona, más un recibo que acredite el pago de un suministro (agua, luz, gas, teléfono), del alquiler o de la fianza.',
                'Esos recibos tienen que tener <b>menos de 3 meses</b>.',
                'Si autoriza a otra persona: impreso <b>F0212</b>, original del documento de identidad de la persona autorizada y fotocopia del de quien autoriza.'],
            f: 'Cita previa en el 93 483 29 25 o en badalona.cat > cita previa.' },
    ca: { h: 'L\'alta i el canvi de domicili al <b>padró municipal d\'habitants</b> es tramiten al SAC o a la seu electrònica.',
            l: ['Cal acreditar la titularitat de l\'habitatge. Si no es pot, es presenta una sol·licitud de comprovació de residència.',
                'En habitatge de lloguer: contracte a nom de qui s\'empadrona, més un rebut que acrediti el pagament d\'un subministrament (aigua, llum, gas, telèfon), del lloguer o de la fiança.',
                'Aquests rebuts han de tenir <b>menys de 3 mesos</b>.',
                'Si autoritza una altra persona: imprès <b>F0212</b>, original del document d\'identitat de la persona autoritzada i fotocòpia del de qui autoritza.'],
            f: 'Cita prèvia al 93 483 29 25 o a badalona.cat > cita prèvia.' },
      s: { t: 'Alta o canvi de domicili al padró municipal d\'habitants — seu.badalona.cat',
           u: 'https://seu.badalona.cat/sta/CarpetaPublic/doEvent?APP_CODE=STA&PAGE_CODE=PTS_CATSERV&DETALLE=6269000171155610099500' },
    },
    {
      k: ['certificado', 'certificado de empadronamiento', 'certificado padron', 'volante', 'acreditar residencia', 'historico',
          'certificat', 'certificat d empadronament', 'volant', 'acreditar residencia', 'historic'],
      es: { h: 'El <b>certificat del padró municipal d\'habitants</b> acredita que una persona está o estuvo empadronada. Lo hay individual, individual histórico, colectivo y colectivo histórico.',
            l: ['Individual: impreso <b>F0210</b> o <b>F0211</b>, más documento de identidad en vigor.',
                'Colectivo: impreso de autorización <b>F0206</b> o <b>F0207</b>, original del documento de la persona autorizada y fotocopia del de todas las que autorizan.',
                'Para autorizar a un tercero: impreso <b>F0205</b>.',
                'Los mayores de 16 años solo pueden pedir el suyo individual o individual histórico. De los menores de 16 lo pide el padre, la madre o el tutor.',
                '<b>Gratuito</b>, excepto los certificados anteriores al 01/03/1991.'],
            f: 'Plazo: inmediato si se saca por internet con certificado digital o idCAT Mòbil; de 10 a 15 días hábiles si se pide presencialmente.' },
      ca: { h: 'El <b>certificat del padró municipal d\'habitants</b> acredita que una persona està o va estar empadronada. N\'hi ha d\'individual, individual històric, col·lectiu i col·lectiu històric.',
            l: ['Individual: imprès <b>F0210</b> o <b>F0211</b>, més document d\'identitat en vigor.',
                'Col·lectiu: imprès d\'autorització <b>F0206</b> o <b>F0207</b>, original del document de la persona autoritzada i fotocòpia del de totes les que autoritzen.',
                'Per autoritzar una tercera persona: imprès <b>F0205</b>.',
                'Els majors de 16 anys només poden demanar el seu individual o individual històric. Dels menors de 16 el demana el pare, la mare o el tutor.',
                '<b>Gratuït</b>, excepte els certificats anteriors a l\'01/03/1991.'],
            f: 'Termini: immediat si es treu per internet amb certificat digital o idCAT Mòbil; de 10 a 15 dies hàbils si es demana presencialment.' },
      s: { t: 'Certificat del Padró Municipal d\'Habitants — seu.badalona.cat',
           u: 'https://seu.badalona.cat/sta/CarpetaPublic/doEvent?APP_CODE=STA&PAGE_CODE=PTS_CATSERV&DETALLE=6269000171155618099500&lang=ca' },
    },
    {
      k: ['sac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'cita previa', 'cita', 'telefono', 'contacto',
          'atencio ciutadana', 'adreca', 'horari', 'cita previa', 'telefon'],
      es: { h: 'El <b>Servei d\'Atenció al Ciutadà (SAC)</b> es la oficina de atención presencial del Ayuntamiento.',
            l: ['Edificio El Viver, plaza de la Assemblea de Catalunya, 9-12, planta baja — 08911 Badalona.',
                'Centralita: 93 483 26 00. Cita previa del SAC: 93 483 29 25.',
                'Correo: sac@badalona.cat.',
                'Horario: de lunes a viernes de 8:30 a 13:30. Los jueves también de 16:00 a 18:00.',
                'Las tardes de jueves están cerradas todo agosto y algunos días sueltos del año.'],
            f: 'La cita previa se pide preferentemente en badalona.cat > cita previa.' },
      ca: { h: 'El <b>Servei d\'Atenció al Ciutadà (SAC)</b> és l\'oficina d\'atenció presencial de l\'Ajuntament.',
            l: ['Edifici El Viver, plaça de l\'Assemblea de Catalunya, 9-12, planta baixa — 08911 Badalona.',
                'Centraleta: 93 483 26 00. Cita prèvia del SAC: 93 483 29 25.',
                'Correu: sac@badalona.cat.',
                'Horari: de dilluns a divendres de 8:30 a 13:30. Els dijous també de 16:00 a 18:00.',
                'Les tardes de dijous estan tancades tot l\'agost i alguns dies solts de l\'any.'],
            f: 'La cita prèvia es demana preferentment a badalona.cat > cita prèvia.' },
      s: { t: 'Què és el Servei d\'Atenció al Ciutadà — badalona.cat',
           u: 'https://www.badalona.cat/ca/ajuntament/atencio-a-la-ciutadania/que-es-el-servei-dantencio-al-ciutada' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'catalogo', 'por internet',
          'seu electronica', 'tramit', 'tramits', 'cataleg', 'per internet'],
      es: { h: 'Los trámites municipales se gestionan en la <b>seu electrònica</b>, donde está el catálogo completo de procedimientos.',
            l: ['Se accede con certificado digital o idCAT Mòbil.', 'Desde ahí se puede sacar el certificado de padrón al momento.'],
            f: 'Si lo prefiere presencialmente, pida cita en el SAC: 93 483 29 25.' },
      ca: { h: 'Els tràmits municipals es gestionen a la <b>seu electrònica</b>, on hi ha el catàleg complet de procediments.',
            l: ['S\'hi accedeix amb certificat digital o idCAT Mòbil.', 'Des d\'allà es pot treure el certificat de padró a l\'instant.'],
            f: 'Si ho prefereix presencialment, demani cita al SAC: 93 483 29 25.' },
      s: { t: 'Seu electrònica — seu.badalona.cat', u: 'https://seu.badalona.cat/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Badalona?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'CA', t: 'Què necessito per empadronar-me a Badalona?' },
    { lang: 'ES', t: '¿Dónde está el SAC y cómo pido cita?' },
  ],
},

// ===========================================================================
{
  slug: 'terrassa',
  nombre: 'Terrassa',
  articulo: 'de Terrassa',
  dominios: 'terrassa.cat y aoberta.terrassa.cat',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: "la OAC", largo: 'Oficina d\'Atenció Ciutadana', tel: '937 397 000', email: 'padro.habitants@terrassa.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán', sufijo: 'ca', oficinaLargo: 'Oficina d\'Atenció Ciutadana' },
  kb: [
    {
      k: ['volante', 'volante de empadronamiento', 'acreditar residencia', 'convivencia',
          'volant', 'volant d empadronament', 'convivencia'],
      es: { h: 'El <b>volant del padró municipal d\'habitants</b> acredita el empadronamiento según los datos vigentes del padrón.',
            l: ['Individual, o de residencia: acredita el empadronamiento de quien lo pide.',
                'Colectivo, o de convivencia: acredita el de todas las personas empadronadas en ese domicilio.',
                'Por internet se genera <b>al momento</b> con certificado digital o idCAT Mòbil.'],
            f: 'Oficina del Padró: Ca de la Unió, 36, 1r piso — 08221 Terrassa. Teléfono 937 397 000.' },
      ca: { h: 'El <b>volant del padró municipal d\'habitants</b> acredita l\'empadronament segons les dades vigents del padró.',
            l: ['Individual, o de residència: acredita l\'empadronament de qui el demana.',
                'Col·lectiu, o de convivència: acredita el de totes les persones empadronades en aquell domicili.',
                'Per internet es genera <b>a l\'instant</b> amb certificat digital o idCAT Mòbil.'],
            f: 'Oficina del Padró: Ca de la Unió, 36, 1r pis — 08221 Terrassa. Telèfon 937 397 000.' },
      s: { t: 'Volant del Padró Municipal d\'Habitants — aoberta.terrassa.cat', u: 'https://aoberta.terrassa.cat/tramits/fitxa.jsp?id=841' },
    },
    {
      k: ['certificado', 'certificado de empadronamiento', 'certificado padron', 'juicio', 'judicial',
          'certificat', 'certificat d empadronament', 'judicial'],
      es: { h: 'El <b>certificat del padró</b> es el documento que hace prueba en un procedimiento administrativo o judicial. El volante, no.',
            l: ['Acredita la residencia individual o colectiva de una persona.',
                'Según el tipo, y en todos los anteriores a 1996, se aplica la tasa correspondiente.'],
            f: 'Consultas del padrón: padro.habitants@terrassa.cat o 937 397 000.' },
      ca: { h: 'El <b>certificat del padró</b> és el document que fa prova en un procediment administratiu o judicial. El volant, no.',
            l: ['Acredita la residència individual o col·lectiva d\'una persona.',
                'Segons el tipus, i en tots els anteriors a 1996, s\'aplica la taxa corresponent.'],
            f: 'Consultes del padró: padro.habitants@terrassa.cat o 937 397 000.' },
      s: { t: 'Certificat del Padró Municipal d\'Habitants — aoberta.terrassa.cat', u: 'https://aoberta.terrassa.cat/tramits/fitxa.jsp?id=801' },
    },
    {
      k: ['empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'alta padron', 'darme de alta', 'cambio de domicilio', 'mudarme',
          'empadronar-me', 'alta padro', 'canvi de domicili', 'donar-me d alta'],
      es: { h: 'El <b>alta al padró</b> y el <b>canvi de domicili</b> son dos trámites distintos, cada uno con su ficha en la sede.',
            l: ['Alta: para quien se empadrona en Terrassa por primera vez.',
                'Cambio de domicilio: para quien ya está empadronado y se muda dentro del municipio.',
                'Ambos se pueden gestionar en cualquiera de las siete OAC, con cita previa.'],
            f: 'La documentación exacta de cada caso está en su ficha. Si prefiere confirmarlo por teléfono: 937 397 000.' },
      ca: { h: 'L\'<b>alta al padró</b> i el <b>canvi de domicili</b> són dos tràmits diferents, cadascun amb la seva fitxa a la seu.',
            l: ['Alta: per a qui s\'empadrona a Terrassa per primera vegada.',
                'Canvi de domicili: per a qui ja hi està empadronat i es muda dins del municipi.',
                'Tots dos es poden gestionar a qualsevol de les set OAC, amb cita prèvia.'],
            f: 'La documentació exacta de cada cas és a la seva fitxa. Si ho vol confirmar per telèfon: 937 397 000.' },
      s: { t: 'Alta al Padró Municipal d\'Habitants — aoberta.terrassa.cat', u: 'https://aoberta.terrassa.cat/tramits/fitxa.jsp?id=141' },
    },
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'cita previa', 'cita', 'telefono', 'contacto',
          'atencio ciutadana', 'adreca', 'horari', 'telefon'],
      es: { h: 'Terrassa tiene <b>siete OAC</b> repartidas por la ciudad. Teléfono único: <b>937 397 000</b>.',
            l: ['Plaça Didó, 5 — abre también tardes: lunes y miércoles de 16:00 a 18:00.',
                'Districte 2: avinguda de Barcelona, 180. Districte 3: plaça de Can Palet, 1.',
                'Districte 4: avinguda d\'Àngel Sallent, 55. Districte 5: plaça de la Cultura, 5.',
                'Districte 6: rambla de Francesc Macià, 189. Districte 7: carrer d\'Amèrica, 33.',
                'Horario de las OAC de distrito: de lunes a jueves de 9:00 a 15:00, y viernes y vísperas de festivo de 9:00 a 14:30.'],
            f: 'La OAC de Plaça Didó abre de 8:30 a 15:00 de lunes a jueves, y hasta las 14:30 los viernes.' },
      ca: { h: 'Terrassa té <b>set OAC</b> repartides per la ciutat. Telèfon únic: <b>937 397 000</b>.',
            l: ['Plaça Didó, 5 — obre també tardes: dilluns i dimecres de 16:00 a 18:00.',
                'Districte 2: avinguda de Barcelona, 180. Districte 3: plaça de Can Palet, 1.',
                'Districte 4: avinguda d\'Àngel Sallent, 55. Districte 5: plaça de la Cultura, 5.',
                'Districte 6: rambla de Francesc Macià, 189. Districte 7: carrer d\'Amèrica, 33.',
                'Horari de les OAC de districte: de dilluns a dijous de 9:00 a 15:00, i divendres i vigílies de festiu de 9:00 a 14:30.'],
            f: 'L\'OAC de Plaça Didó obre de 8:30 a 15:00 de dilluns a dijous, i fins a les 14:30 els divendres.' },
      s: { t: 'Oficines i serveis municipals — aoberta.terrassa.cat', u: 'https://aoberta.terrassa.cat/oficines' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué diferencia hay entre volante y certificado de padrón?' },
    { lang: 'ES', t: '¿Puedo pedir cita por internet?' },
    { lang: 'CA', t: 'On és l\'OAC més propera i quin horari té?' },
    { lang: 'ES', t: '¿Para qué sirve el volante de empadronamiento?' },
  ],
},

// ===========================================================================
{
  slug: 'jerez-de-la-frontera',
  nombre: 'Jerez de la Frontera',
  articulo: 'de Jerez de la Frontera',
  dominios: 'jerez.es y sedeelectronica.jerez.es',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: "la OAC", largo: 'Oficina de Atención a la Ciudadanía', tel: '956 149 370 o 010', email: 'oac@aytojerez.es' },
  idioma2: null,
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'consistorio'],
      es: { h: 'La <b>Oficina de Atención a la Ciudadanía (OAC)</b> es el canal presencial del Ayuntamiento.',
            l: ['Sede central: calle Consistorio, 15.',
                'Horario: de 9:00 a 14:00 de lunes a viernes, y de 17:00 a 18:30 de lunes a jueves.',
                'OAC Distrito Este: Centro Social Blas Infante, avenida de Nazaret, s/n. De 9:30 a 13:30, de lunes a jueves. Teléfono 956 14 97 60.',
                'Correo: oac@aytojerez.es.'],
            f: 'Teléfono para citas: 956 149 370 o el 010.' },
      s: { t: 'Oficina de Atención a la Ciudadanía — jerez.es', u: 'https://www.jerez.es/ciudad/informacion-util/otros/oac' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita', 'sin cita'],
      es: { h: '<b>Todos los trámites de la OAC requieren cita previa.</b> No se atiende sin ella.',
            l: ['Se puede pedir por la sede electrónica.', 'O por teléfono, en el 956 149 370 o en el 010.'],
            f: 'Para los trámites de padrón, el Ayuntamiento recomienda usar directamente la sede electrónica y ahorrarse el desplazamiento.' },
      s: { t: 'Cita Previa OAC — jerez.es', u: 'https://www.jerez.es/webs-municipales/participacion/atencion-a-la-ciudadania/cita-previa-oac' },
    },
    {
      k: ['empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'padron', 'certificado', 'volante', 'cambio de domicilio', 'mudarme'],
      es: { h: 'La OAC gestiona todo lo relativo al <b>Padrón Municipal de Habitantes</b>.',
            l: ['Certificados de empadronamiento y volantes de empadronamiento.',
                'Movimientos en el padrón: altas, bajas y modificaciones.'],
            f: 'Para cualquier trámite de padrón el Ayuntamiento recomienda la sede electrónica. La documentación concreta de su caso está en la ficha del trámite; si prefiere confirmarla antes, llame al 956 149 370 o al 010.' },
      s: { t: 'Trámites de ciudadanía — sedeelectronica.jerez.es',
           u: 'https://www.sedeelectronica.jerez.es/tramites?tema=Ciudadan%C3%ADa&tx_tramiteskey_tramitesfrontendkey%5Baction%5D=listtema&tx_tramiteskey_tramitesfrontendkey%5Bcontroller%5D=Tramite' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo'],
      es: { h: 'Los trámites municipales se gestionan en la <b>sede electrónica</b>, disponible las 24 horas.',
            l: ['Ahí está el catálogo de trámites por temas.', 'Es la vía recomendada por el propio Ayuntamiento para el padrón.'],
            f: 'Si prefiere hacerlo presencialmente, recuerde que hace falta cita previa: 956 149 370 o 010.' },
      s: { t: 'Sede Electrónica de Jerez de la Frontera', u: 'https://www.sedeelectronica.jerez.es/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Jerez?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'ES', t: '¿Dónde está la OAC y qué horario tiene?' },
    { lang: 'ES', t: '¿Hace falta cita previa para ir a la OAC?' },
  ],
},

// ===========================================================================
{
  slug: 'leganes',
  nombre: 'Leganés',
  articulo: 'de Leganés',
  dominios: 'leganes.org',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: "el SAC", largo: 'Servicio de Atención al Ciudadano', tel: '010 o 912 489 010', email: '010@leganes.org' },
  idioma2: null,
  kb: [
    {
      k: ['sac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'casa del reloj', '010'],
      es: { h: 'El <b>Servicio de Atención al Ciudadano (010)</b> es el canal de atención del Ayuntamiento, presencial y telefónico.',
            l: ['Casa del Reloj: avenida de Gibraltar, 2.',
                'Horario presencial: de lunes a viernes de 8:30 a 14:30 y de 17:00 a 19:00; sábados de 9:00 a 13:00.',
                'En julio y agosto: de 8:30 a 14:30, y sábados de 9:00 a 13:00.',
                'Teléfono: el <b>010</b> desde Leganés, o el 912 489 010 desde fuera.'],
            f: 'La atención telefónica es más amplia que la presencial: de lunes a viernes de 8:00 a 21:30, y sábados, domingos y festivos de 10:00 a 20:00.' },
      s: { t: 'Servicio de Atención al Ciudadano - 010 — leganes.org', u: 'https://www.leganes.org/w/servicio-de-atencion-al-ciudadano-010' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita', 'sin cita', 'presencial'],
      es: { h: 'Para la atención presencial es <b>imprescindible pedir cita previa</b>.',
            l: ['La cita se pide en la página web municipal, www.leganes.org.'],
            f: 'Si su consulta se puede resolver por teléfono, el 010 atiende de 8:00 a 21:30 entre semana y también fines de semana y festivos, sin cita.' },
      s: { t: 'Atención a la Ciudadanía — leganes.org', u: 'https://www.leganes.org/atencion-a-la-ciudadania' },
    },
    {
      k: ['empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'padron', 'certificado', 'volante', 'cambio de domicilio', 'mudarme'],
      es: { h: 'Los trámites del <b>Padrón Municipal de Habitantes</b> —altas, cambios de domicilio, volantes y certificados— se atienden en el SAC.',
            l: ['Presencialmente en la Casa del Reloj, con cita previa.',
                'Por teléfono en el 010 para consultar los requisitos de su caso antes de desplazarse.'],
            f: 'La documentación exacta depende de su situación (vivienda propia, alquiler, autorización de un tercero). Confírmela en el 010 antes de pedir la cita: se ahorra un viaje.' },
      s: { t: 'Atención a la Ciudadanía — leganes.org', u: 'https://www.leganes.org/atencion-a-la-ciudadania' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo'],
      es: { h: 'El Ayuntamiento tiene <b>sede electrónica</b> para presentar solicitudes sin ir a la oficina.',
            l: ['Se accede desde www.leganes.org.', 'Desde ahí también se pide la cita previa para lo presencial.'],
            f: 'Si no encuentra el trámite, el 010 le dice si existe versión electrónica antes de que se desplace.' },
      s: { t: 'Ayuntamiento de Leganés', u: 'https://www.leganes.org/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué horario tiene la Casa del Reloj?' },
    { lang: 'ES', t: '¿Piden cita?' },
    { lang: 'ES', t: '¿Puedo hacerlo por internet?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'ES', t: '¿Qué diferencia hay entre volante y certificado?' },
  ],
},

// ===========================================================================
{
  slug: 'santander',
  nombre: 'Santander',
  articulo: 'de Santander',
  dominios: 'santander.es y sede.santander.es',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: "el Servicio de Estadística", largo: 'Servicio de Estadística', tel: '942 200 613', email: 'estadistica@ayto-santander.es' },
  idioma2: null,
  kb: [
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'estadistica', 'modificacion', 'cambio de domicilio', 'mudarme'],
      es: { h: 'El <b>Padrón de Habitantes</b> lo lleva el <b>Servicio de Estadística</b> del Ayuntamiento.',
            l: ['Calle Los Escalantes, 3, 2ª planta.',
                'Horario de atención al público: de lunes a viernes de 8:30 a 13:00.',
                'Teléfono: 942 200 613, extensiones 277, 334 o 269.',
                'Correo: estadistica@ayto-santander.es.'],
            f: 'Altas, bajas y modificaciones de datos se tramitan ahí o en la sede electrónica del padrón.' },
      s: { t: 'Estadística y Población — sede.santander.es',
           u: 'https://sede.santander.es/tramites/tramites-procedimientos/areas-sede/para-las-personas/estadistica-y-poblacion' },
    },
    {
      k: ['certificado', 'certificado de empadronamiento', 'volante', 'acreditar residencia', 'justificante'],
      es: { h: 'El <b>certificado de empadronamiento</b> se solicita en la sede electrónica o en el Servicio de Estadística.',
            l: ['Santander tiene una sede específica para el padrón: sedepadron.santander.es.',
                'Ahí está el catálogo de trámites del padrón y se pueden obtener certificados y volantes.'],
            f: 'Si necesita confirmar qué tipo de documento le piden —volante o certificado no valen para lo mismo—, llame al 942 200 613.' },
      s: { t: 'Solicitud de Certificado de Empadronamiento — sede.santander.es',
           u: 'https://sede.santander.es/tramites/solicitud-certificado-empadronamiento' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita', 'presencial', 'oficina', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran'],
      es: { h: 'Para ser atendido presencialmente en las oficinas municipales hay que <b>pedir cita previa</b>.',
            l: ['El sistema de cita previa está en citaprevia.santander.es.',
                'Permite elegir día y hora concretos en el centro municipal correspondiente.'],
            f: 'El Servicio de Estadística atiende de lunes a viernes de 8:30 a 13:00, en calle Los Escalantes, 3, 2ª planta.' },
      s: { t: 'Cita previa — Ayuntamiento de Santander', u: 'https://citaprevia.santander.es/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'registro'],
      es: { h: 'La <b>sede electrónica</b> permite registrar documentos y hacer trámites sin ir a la oficina.',
            l: ['Sede general: sede.santander.es.', 'Sede específica del padrón: sedepadron.santander.es.'],
            f: 'Información general del Ayuntamiento: el <b>010</b>.' },
      s: { t: 'Sede Electrónica del Ayuntamiento de Santander', u: 'https://sede.santander.es/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Dónde se tramita el padrón en Santander?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'ES', t: '¿Cómo pido cita previa?' },
    { lang: 'ES', t: '¿Cómo consigo un certificado de empadronamiento?' },
  ],
},

// ===========================================================================
{
  slug: 'dos-hermanas',
  nombre: 'Dos Hermanas',
  articulo: 'de Dos Hermanas',
  dominios: 'doshermanas.es y sede.doshermanas.es',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: "la Oficina de Atención al Ciudadano", largo: 'Oficina de Atención al Ciudadano', tel: '954 91 95 00', email: 'sede@doshermanas.es' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'atencion ciudadana', 'sac', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', 'ayuntamiento'],
      es: { h: 'La <b>Oficina de Atención al Ciudadano</b> es el canal presencial del Ayuntamiento.',
            l: ['Plaza de la Constitución, 1 — 41701 Dos Hermanas (Sevilla).',
                'Teléfono: 954 91 95 00.',
                'Horario: de lunes a viernes de 9:00 a 14:00.',
                'Correo: sede@doshermanas.es.'],
            f: '' },
      s: { t: 'Oficinas del Ayuntamiento de Dos Hermanas — sede.doshermanas.es',
           u: 'https://sede.doshermanas.es/portal/sede/se_contenedor1.jsp?seccion=s_floc_d4_v1.jsp&contenido=75&tipo=1&nivel=1400&codResi=1&language=es&codMenu=27&codMenuPN=6' },
    },
    {
      k: ['empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'padron', 'certificado', 'volante', 'cambio de domicilio', 'mudarme'],
      es: { h: 'Los trámites del <b>padrón municipal</b> se pueden hacer por internet en la sede electrónica o presencialmente en la Oficina de Atención al Ciudadano.',
            l: ['Empadronamiento, certificados y solicitud de cita previa están disponibles de forma electrónica.',
                'Presencialmente: plaza de la Constitución, 1, de lunes a viernes de 9:00 a 14:00.'],
            f: 'La documentación exacta depende de su caso. Confírmela en el 954 91 95 00 antes de desplazarse.' },
      s: { t: 'Sede electrónica del Ayuntamiento de Dos Hermanas', u: 'https://sede.doshermanas.es/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'registro'],
      es: { h: 'La <b>sede electrónica</b> es la ventanilla del Ayuntamiento en internet, abierta las 24 horas.',
            l: ['Ahí está el catálogo de trámites y las oficinas de asistencia en materia de registro.',
                'Desde ella se piden también las citas previas.'],
            f: 'Dudas sobre la sede: sede@doshermanas.es o 954 91 95 00.' },
      s: { t: 'Sede electrónica del Ayuntamiento de Dos Hermanas', u: 'https://sede.doshermanas.es/' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita', 'presencial'],
      es: { h: 'La <b>cita previa</b> se solicita a través de la sede electrónica.',
            l: ['También se puede pedir llamando al 954 91 95 00.'],
            f: 'Oficina de Atención al Ciudadano: plaza de la Constitución, 1, de lunes a viernes de 9:00 a 14:00.' },
      s: { t: 'Sede electrónica del Ayuntamiento de Dos Hermanas', u: 'https://sede.doshermanas.es/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué horario tiene la oficina de atención al ciudadano?' },
    { lang: 'ES', t: '¿Puedo empadronarme por internet?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'ES', t: '¿Cómo pido cita previa?' },
    { lang: 'ES', t: '¿Cuál es el teléfono?' },
  ],
},

// ===========================================================================
{
  slug: 'parla',
  nombre: 'Parla',
  articulo: 'de Parla',
  dominios: 'ayuntamientoparla.es y sede.ayuntamientoparla.es',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: "el SAC", largo: 'Servicio de Atención al Ciudadano', tel: '010', email: 'sac@ayuntamientoparla.es' },
  idioma2: null,
  kb: [
    {
      k: ['sac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'a que hora cierran', 'abren', 'cierran', 'telefono', 'contacto', '010', 'dulce chacon', 'parla este'],
      es: { h: 'El <b>Servicio de Atención al Ciudadano (SAC)</b> funciona por tres vías: presencial, telefónica e internet.',
            l: ['Bajos del Ayuntamiento.',
                'Centro cultural Dulce Chacón.',
                'Caseta del Parque Universo, en Parla Este.',
                'Teléfono: el <b>010</b>.'],
            f: 'Horario: de lunes a viernes de 8:30 a 19:30, y sábados de 9:00 a 13:00.' },
      s: { t: 'Servicio de Atención al Ciudadano (SAC) — ayuntamientoparla.es',
           u: 'https://www.ayuntamientoparla.es/callejero/servicio-de-atencion-al-ciudadano-sac' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita', 'presencial', 'sin cita'],
      es: { h: 'Los trámites presenciales del SAC se atienden <b>con cita previa</b>.',
            l: ['La cita se pide en la web municipal o llamando al 010.',
                'La oficina de Parla Este atiende con cita previa a quienes tienen que acreditar su identidad presencialmente para obtener el certificado digital.'],
            f: 'El horario del SAC es amplio —de 8:30 a 19:30 entre semana y sábados por la mañana—, pero eso no sustituye a la cita.' },
      s: { t: 'Atención a la ciudadanía con cita previa — ayuntamientoparla.es',
           u: 'https://www.ayuntamientoparla.es/noticias/el-servicio-de-atencion-a-la-ciudadania-de-parla-vuelve-a-realizar-tramites-presenciales-solo-con-cita-previa-desde-el-8-de-junio' },
    },
    {
      k: ['empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'padron', 'certificado', 'volante', 'cambio de domicilio', 'mudarme', 'censo'],
      es: { h: 'El SAC gestiona los trámites de <b>padrón</b>, además del censo electoral, los certificados digitales y la firma electrónica.',
            l: ['Presencialmente en cualquiera de las tres oficinas, con cita previa.',
                'Por teléfono en el 010 para consultar requisitos antes de ir.'],
            f: 'La documentación depende de su situación concreta. Confírmela en el 010 antes de pedir la cita.' },
      s: { t: 'Servicio de Atención al Ciudadano (SAC) — ayuntamientoparla.es',
           u: 'https://www.ayuntamientoparla.es/callejero/servicio-de-atencion-al-ciudadano-sac' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'certificado digital', 'firma'],
      es: { h: 'La <b>sede electrónica</b> permite hacer trámites sin desplazarse.',
            l: ['Se accede desde www.ayuntamientoparla.es.',
                'El SAC también tramita certificados digitales y firma electrónica, que es lo que hace falta para operar en la sede.'],
            f: 'Para acreditar la identidad presencialmente hace falta cita en la oficina de Parla Este.' },
      s: { t: 'Sede Electrónica del Ayuntamiento de Parla', u: 'https://sede.ayuntamientoparla.es/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Dónde están las oficinas del SAC?' },
    { lang: 'ES', t: '¿Dónde pido el volante?' },
    { lang: 'ES', t: '¿Cuál es el teléfono?' },
    { lang: 'ES', t: '¿Cómo consigo el certificado digital?' },
    { lang: 'ES', t: '¿Piden cita?' },
    { lang: 'ES', t: '¿El SAC abre los sábados?' },
  ],
},

// ===========================================================================
{
  slug: 'tarragona',
  nombre: 'Tarragona',
  articulo: 'de Tarragona',
  dominios: 'tarragona.cat y tramits.tarragona.cat',
  fecha: '6 de septiembre de 2026',
  oficina: { sigla: "la OMAC", largo: 'Oficina Municipal d\'Atenció Ciutadana', tel: '977 296 258', email: 'omac@tarragona.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OMAC", nombre: 'catalán', sufijo: 'ca', oficinaLargo: 'Oficina Municipal d\'Atenció Ciutadana' },
  kb: [
    {
      k: ['omac', 'oficina', 'atencion ciudadana', 'direccion', 'telefono', 'contacto', 'rambla',
          'atencio ciutadana', 'adreca', 'telefon'],
      es: { h: 'La <b>Oficina Municipal d\'Atenció Ciutadana (OMAC)</b> es el canal presencial del Ayuntamiento.',
            l: ['OMAC: Rambla Nova, 59 — Tarragona.',
                'Teléfono: 977 296 258.',
                'Correo: omac@tarragona.cat.',
                'Trámites por internet: tramits.tarragona.cat.'],
            f: 'La OMAC informa sobre población, licencias de obra, aperturas, fiestas, dominio público, medio ambiente, limpieza, enseñanza, contratación, cultura, deportes, juventud y servicios sociales.' },
      ca: { h: 'L\'<b>Oficina Municipal d\'Atenció Ciutadana (OMAC)</b> és el canal presencial de l\'Ajuntament.',
            l: ['OMAC: Rambla Nova, 59 — Tarragona.',
                'Telèfon: 977 296 258.',
                'Correu: omac@tarragona.cat.',
                'Tràmits per internet: tramits.tarragona.cat.'],
            f: 'L\'OMAC informa sobre població, llicències d\'obra, obertures, festes, domini públic, medi ambient, neteja, ensenyament, contractació, cultura, esports, joventut i serveis socials.' },
      s: { t: 'OMAC — Oficina Municipal d\'Atenció Ciutadana', u: 'https://www.tarragona.cat/lajuntament/atencio-ciutadana/omac' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita', 'sin cita', 'plusvalia',
          'cita previa', 'demanar cita', 'plusvalua'],
      es: { h: 'La <b>cita previa es obligatoria solo para el trámite de plusvalía</b>. Para el resto de trámites de la OMAC no lo es.',
            l: ['Para los demás trámites la cita es la vía preferente, pero no obligatoria: sirve para evitar esperas.',
                'Se pide en citaprevia.tarragona.cat.'],
            f: 'Si su gestión no es la plusvalía, puede acudir sin cita — aunque con ella espera menos.' },
      ca: { h: 'La <b>cita prèvia és obligatòria només per al tràmit de plusvàlua</b>. Per a la resta de tràmits de l\'OMAC no ho és.',
            l: ['Per als altres tràmits la cita és la via preferent, però no obligatòria: serveix per evitar esperes.',
                'Es demana a citaprevia.tarragona.cat.'],
            f: 'Si la seva gestió no és la plusvàlua, pot venir sense cita — encara que amb cita esperarà menys.' },
      s: { t: 'Cita prèvia — Ajuntament de Tarragona', u: 'https://citaprevia.tarragona.cat/' },
    },
    {
      k: ['empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'padron', 'poblacion', 'certificado', 'volante', 'cambio de domicilio',
          'empadronar-me', 'empadronament', 'padro', 'poblacio', 'certificat', 'volant', 'canvi de domicili'],
      es: { h: 'Los trámites de <b>población</b> —el padrón— son una de las materias que atiende la OMAC.',
            l: ['Presencialmente en Rambla Nova, 59, con cita preferente pero no obligatoria.',
                'Por internet en tramits.tarragona.cat.'],
            f: 'La documentación concreta de su caso está en la ficha del trámite. Si prefiere confirmarla antes: 977 296 258 o omac@tarragona.cat.' },
      ca: { h: 'Els tràmits de <b>població</b> —el padró— són una de les matèries que atén l\'OMAC.',
            l: ['Presencialment a la Rambla Nova, 59, amb cita preferent però no obligatòria.',
                'Per internet a tramits.tarragona.cat.'],
            f: 'La documentació concreta del seu cas és a la fitxa del tràmit. Si ho vol confirmar abans: 977 296 258 o omac@tarragona.cat.' },
      s: { t: 'Atenció ciutadana — Ajuntament de Tarragona', u: 'https://www.tarragona.cat/lajuntament/atencio-ciutadana' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo',
          'seu electronica', 'tramit', 'tramits', 'cataleg', 'per internet'],
      es: { h: 'Los trámites municipales por internet están en <b>tramits.tarragona.cat</b>.',
            l: ['Disponible las 24 horas, sin desplazamiento ni cita.'],
            f: 'Si no encuentra su trámite, la OMAC lo aclara en el 977 296 258.' },
      ca: { h: 'Els tràmits municipals per internet són a <b>tramits.tarragona.cat</b>.',
            l: ['Disponible les 24 hores, sense desplaçament ni cita.'],
            f: 'Si no troba el seu tràmit, l\'OMAC ho aclareix al 977 296 258.' },
      s: { t: 'OMAC — Oficina Municipal d\'Atenció Ciutadana', u: 'https://www.tarragona.cat/lajuntament/atencio-ciutadana/omac' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hace falta cita previa para ir a la OMAC?' },
    { lang: 'ES', t: '¿Puedo hacer trámites de padrón por internet?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'CA', t: 'On és l\'OMAC i quin telèfon té?' },
  ],
},

];
