// ---------------------------------------------------------------------------
//  LOS OCHO DEL ONCEAVO ENVIO — martes 6 de octubre de 2026.
//  Comprobado en cada web municipal el 7 de septiembre de 2026.
//
//  Estos ocho tambien estaban parados por falta de correo de contacto. Se
//  localizo con _envios/buscar-correo.mjs y se confirmo a mano uno por uno.
//
//  Dos cosas que salieron de la comprobacion y conviene no perder:
//
//  - La Vila Joiosa estaba en esta lista y se ha caido: su web ya monta un
//    chatbot (el plugin AI Engine Pro de WordPress). No es un lead de "no
//    tienen asistente", asi que se queda fuera hasta que se le escriba otra
//    cosa. En su sitio entra Mislata.
//  - La OAC de Mislata NO esta en el ayuntamiento: esta provisionalmente en
//    el Centre Jove del Mercat, c/ Major 36. Es justo el tipo de dato que un
//    asistente mal hecho da mal, asi que la demo lo dice.
//
//  Valenciano en Denia, Alcoi y Mislata; catalan en Ripollet, Figueres e
//  Igualada. Lucena y Tudela, solo castellano.
//
//  Horarios: los que no estan es porque el ayuntamiento no los publica en su
//  web. En esos casos la demo dice que no tiene fuente y da el telefono; no
//  se inventa ninguno.
// ---------------------------------------------------------------------------

export const MUNICIPIOS_DIA11 = [

// ===========================================================================
{
  slug: 'denia',
  nombre: 'Dénia',
  articulo: 'de Dénia',
  dominios: 'denia.es, oac.denia.es y sede.denia.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'la OAC', tel: '96 646 70 09', email: 'oac@ayto-denia.es' },
  idioma2: { cod: 'VA', clave: 'va', sigla: 'a la OAC', nombre: 'valenciano', sufijo: 'va' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'constitucion',
          'atencio ciutadana', 'adreca', 'horari', 'a quina hora obrin', 'telefon'],
      es: { h: 'La <b>Oficina de Atención Ciudadana (OAC)</b> está en la plaza de la Constitución, 10.',
            l: ['Teléfono: 96 646 70 09. Correo: oac@ayto-denia.es.',
                'Atención <b>con cita previa</b>: lunes, miércoles y viernes de 9:00 a 14:00.',
                'Las personas <b>mayores de 65 años</b> pueden hacer sus trámites personales por la mañana <b>sin cita</b>.'],
            f: 'La cita se pide en la oficina virtual, oac.denia.es.' },
      va: { h: "L'<b>Oficina d'Atenció Ciutadana (OAC)</b> està a la plaça de la Constitució, 10.",
            l: ['Telèfon: 96 646 70 09. Correu: oac@ayto-denia.es.',
                'Atenció <b>amb cita prèvia</b>: dilluns, dimecres i divendres de 9:00 a 14:00.',
                'Les persones <b>majors de 65 anys</b> poden fer els seus tràmits personals al matí <b>sense cita</b>.'],
            f: "La cita es demana a l'oficina virtual, oac.denia.es." },
      s: { t: 'Oficina de Atención Ciudadana — denia.es', u: 'https://www.denia.es/es/info/atencio_ciutadana/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'renovacion padronal', 'confirmacion de residencia',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me'],
      es: { h: 'La OAC gestiona el <b>padrón municipal</b>: altas, cambios de domicilio, bajas de oficio, confirmación de residencia y renovación padronal de personas extranjeras.',
            l: ['Estos trámites se atienden <b>con cita previa</b>, lunes, miércoles y viernes de 9:00 a 14:00.',
                'La cita se pide en oac.denia.es.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 96 646 70 09 o en oac@ayto-denia.es.' },
      va: { h: "L'OAC gestiona el <b>padró municipal</b>: altes, canvis de domicili, baixes d'ofici, confirmació de residència i renovació padronal de persones estrangeres.",
            l: ['Aquests tràmits s\'atenen <b>amb cita prèvia</b>, dilluns, dimecres i divendres de 9:00 a 14:00.',
                'La cita es demana a oac.denia.es.'],
            f: 'La documentació concreta depèn del seu cas. Confirme-la al 96 646 70 09 o a oac@ayto-denia.es.' },
      s: { t: 'Oficina de Atención Ciudadana — denia.es', u: 'https://www.denia.es/es/info/atencio_ciutadana/' },
    },
    {
      k: ['certificado', 'certificado de empadronamiento', 'certificado padron', 'volante', 'acreditar residencia',
          'certificat', "certificat d empadronament", 'volant'],
      es: { h: 'Los <b>certificados del padrón</b> solicitados en la OAC se tramitan <b>sin cita previa</b>.',
            l: ['Es la excepción: el resto de trámites de padrón sí requieren cita.'],
            f: 'Plaza de la Constitución, 10. Teléfono 96 646 70 09.' },
      va: { h: 'Els <b>certificats del padró</b> sol·licitats a l\'OAC es tramiten <b>sense cita prèvia</b>.',
            l: ["És l'excepció: la resta de tràmits de padró sí que requereixen cita."],
            f: 'Plaça de la Constitució, 10. Telèfon 96 646 70 09.' },
      s: { t: 'Oficina de Atención Ciudadana — denia.es', u: 'https://www.denia.es/es/info/atencio_ciutadana/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'oficina virtual', 'cita', 'cita previa', 'pedir cita', 'registro',
          'seu electronica', 'tramit', 'tramits', 'per internet', 'cita previa', 'demanar cita'],
      es: { h: 'Hay dos direcciones y no hacen lo mismo: la <b>oficina virtual</b> está en oac.denia.es y la <b>sede electrónica</b> en sede.denia.es.',
            l: ['La cita previa se pide en <b>oac.denia.es</b>.',
                'El registro y las oficinas de asistencia en materia de registro están en <b>sede.denia.es</b>.'],
            f: 'Si no tiene claro cuál le toca, llame al 96 646 70 09 y se lo dicen.' },
      va: { h: "Hi ha dues adreces i no fan el mateix: l'<b>oficina virtual</b> està a oac.denia.es i la <b>seu electrònica</b> a sede.denia.es.",
            l: ['La cita prèvia es demana a <b>oac.denia.es</b>.',
                "El registre i les oficines d'assistència en matèria de registre estan a <b>sede.denia.es</b>."],
            f: 'Si no té clar quina li toca, telefone al 96 646 70 09 i li ho diran.' },
      s: { t: 'OAC Dénia — Oficina Virtual', u: 'https://oac.denia.es/es/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Dénia?' },
    { lang: 'ES', t: '¿Cómo pido el certificado de empadronamiento?' },
    { lang: 'VA', t: 'On està la OAC i quin horari té?' },
    { lang: 'ES', t: '¿Cómo pido cita previa?' },
  ],
},

// ===========================================================================
{
  slug: 'lucena',
  nombre: 'Lucena',
  articulo: 'de Lucena',
  dominios: 'lucena.es y sede.eprinsa.es/lucena',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el SIAC', tel: '957 500 410', email: 'siac@aytolucena.es' },
  idioma2: null,
  kb: [
    {
      k: ['siac', 'oficina', 'atencion al ciudadano', 'atencion ciudadana', 'direccion', 'telefono', 'contacto', 'plaza nueva', 'ayuntamiento'],
      es: { h: 'El <b>Servicio Integral de Atención al Ciudadano (SIAC)</b> está en la plaza Nueva, 1, 14900 Lucena (Córdoba).',
            l: ['Teléfono: 957 500 410.',
                'Correo: siac@aytolucena.es.'],
            f: 'El Ayuntamiento no publica el horario del SIAC en su web. Confírmelo en el 957 500 410.' },
      s: { t: 'Contactar — lucena.es', u: 'https://www.lucena.es/contactar' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'certificado', 'volante'],
      es: { h: 'Los trámites de <b>padrón</b> se atienden en el SIAC, en la plaza Nueva, 1.',
            l: ['También se pueden presentar por la sede electrónica, en sede.eprinsa.es/lucena.'],
            f: 'La documentación depende de su caso. Confírmela en el 957 500 410 o en siac@aytolucena.es antes de desplazarse.' },
      s: { t: 'Sede electrónica — Ayuntamiento de Lucena', u: 'https://sede.eprinsa.es/lucena' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'sin cita', 'turno'],
      es: { h: 'La <b>cita previa</b> se pide en lucena.cxmflow.com/oabs/.',
            l: [],
            f: 'Si el sistema no le da hueco, llame al 957 500 410.' },
      s: { t: 'Cita previa — Ayuntamiento de Lucena', u: 'https://lucena.cxmflow.com/oabs/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'registro'],
      es: { h: 'La <b>sede electrónica</b> del Ayuntamiento de Lucena está en sede.eprinsa.es/lucena.',
            l: ['Desde ahí se presentan solicitudes y se consulta el estado de los expedientes.'],
            f: 'Dudas: 957 500 410 o siac@aytolucena.es.' },
      s: { t: 'Sede electrónica — Ayuntamiento de Lucena', u: 'https://sede.eprinsa.es/lucena' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Lucena?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'ES', t: '¿Dónde está el SIAC y qué horario tiene?' },
    { lang: 'ES', t: '¿Cómo pido cita previa?' },
  ],
},

// ===========================================================================
{
  slug: 'ripollet',
  nombre: 'Ripollet',
  articulo: 'de Ripollet',
  dominios: 'ripollet.cat y citaprevia.ripollet.cat',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: "l'OAC", tel: '935 04 60 00', email: 'oac@ripollet.cat' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'telefono', 'contacto', 'balmes',
          'atencio ciutadana', 'adreca', 'telefon'],
      es: { h: "L'<b>Oficina d'Atenció Ciutadana (OAC)</b> está en el carrer de Balmes, 2, 08291 Ripollet.",
            l: ['Teléfono: 935 04 60 00.',
                'Correo: oac@ripollet.cat.'],
            f: 'El Ayuntamiento no publica el horario de la OAC en su web. Confírmelo en el 935 04 60 00.' },
      ca: { h: "L'<b>Oficina d'Atenció Ciutadana (OAC)</b> és al carrer de Balmes, 2, 08291 Ripollet.",
            l: ['Telèfon: 935 04 60 00.',
                'Correu: oac@ripollet.cat.'],
            f: "L'Ajuntament no publica l'horari de l'OAC al seu web. Confirmeu-lo al 935 04 60 00." },
      s: { t: "Oficina d'Atenció Ciutadana — ripollet.cat", u: 'https://www.ripollet.cat/' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'certificado', 'volante',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me', 'certificat', 'volant'],
      es: { h: 'Los trámites de <b>padrón</b> se hacen en la OAC, carrer de Balmes, 2, o por la seu electrònica.',
            l: ['Para ir presencialmente hay que pedir <b>cita previa</b> en citaprevia.ripollet.cat.'],
            f: 'La documentación depende de su caso. Confírmela en el 935 04 60 00 o en oac@ripollet.cat.' },
      ca: { h: 'Els tràmits de <b>padró</b> es fan a l\'OAC, carrer de Balmes, 2, o per la seu electrònica.',
            l: ['Per anar-hi presencialment cal demanar <b>cita prèvia</b> a citaprevia.ripollet.cat.'],
            f: 'La documentació depèn del seu cas. Confirmeu-la al 935 04 60 00 o a oac@ripollet.cat.' },
      s: { t: 'Seu electrònica — ripollet.cat', u: 'https://www.ripollet.cat/seu-electronica' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'turno',
          'cita previa', 'demanar cita', 'hora'],
      es: { h: 'La <b>cita previa</b> se pide en citaprevia.ripollet.cat.',
            l: [],
            f: 'Si el sistema no le da hueco, llame al 935 04 60 00.' },
      ca: { h: 'La <b>cita prèvia</b> es demana a citaprevia.ripollet.cat.',
            l: [],
            f: 'Si el sistema no us dona hora, telefoneu al 935 04 60 00.' },
      s: { t: 'Cita prèvia — Ajuntament de Ripollet', u: 'https://citaprevia.ripollet.cat/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'multas', 'notificaciones', 'autoliquidacion',
          'seu electronica', 'tramit', 'tramits', 'per internet', 'cataleg', 'multes', 'notificacions'],
      es: { h: 'La <b>seu electrònica</b> está en ripollet.cat/seu-electronica.',
            l: ['Desde ahí: catálogo de trámites, autoliquidaciones, «el meu espai», representaciones, notificaciones, cita previa y multas y sanciones.',
                'También se consultan los acuerdos del Pleno, el tablón de edictos y la contratación pública.'],
            f: 'Dudas: 935 04 60 00 o oac@ripollet.cat.' },
      ca: { h: 'La <b>seu electrònica</b> és a ripollet.cat/seu-electronica.',
            l: ["Des d'allà: catàleg de tràmits, autoliquidacions, «el meu espai», representacions, notificacions, cita prèvia i multes i sancions.",
                'També s\'hi consulten els acords del Ple, el tauler d\'edictes i la contractació pública.'],
            f: 'Dubtes: 935 04 60 00 o oac@ripollet.cat.' },
      s: { t: 'Seu electrònica — ripollet.cat', u: 'https://www.ripollet.cat/seu-electronica' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Ripollet?' },
    { lang: 'ES', t: '¿Dónde está la oficina de atención ciudadana?' },
    { lang: 'CA', t: "Què puc fer a la seu electrònica sense haver d'anar-hi?" },
    { lang: 'ES', t: '¿Cómo pido cita previa?' },
  ],
},

// ===========================================================================
{
  slug: 'figueres',
  nombre: 'Figueres',
  articulo: 'de Figueres',
  dominios: 'figueres.cat y citaprevia.figueres.cat',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: "l'OMAC", tel: '972 03 22 00', email: 'omac@figueres.org' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OMAC", nombre: 'catalán' },
  kb: [
    {
      k: ['omac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'salvador dali',
          'atencio ciutadana', 'adreca', 'horari', 'a quina hora obren', 'telefon'],
      es: { h: "L'<b>Oficina Municipal d'Atenció Ciutadana (OMAC)</b> está en la avenida Salvador Dalí, 107, planta baja, 17600 Figueres.",
            l: ['Teléfono: 972 03 22 00. Correo: omac@figueres.org.',
                'Mañanas de lunes a viernes de 8:30 a 14:00, <b>con cita previa</b>.',
                '<b>Sin cita</b>: de 8:30 a 13:00, o hasta agotar los tiques del día.',
                'Tardes de lunes a jueves de 16:00 a 18:00, <b>solo con cita previa</b>.',
                'En Navidad, Santa Creu, Semana Santa y del 24 de junio al 11 de septiembre: <b>solo por la mañana</b>.'],
            f: 'La cita se pide en citaprevia.figueres.cat.' },
      ca: { h: "L'<b>Oficina Municipal d'Atenció Ciutadana (OMAC)</b> és a l'avinguda Salvador Dalí, 107, planta baixa, 17600 Figueres.",
            l: ['Telèfon: 972 03 22 00. Correu: omac@figueres.org.',
                'Matins de dilluns a divendres de 8:30 a 14:00, <b>amb cita prèvia</b>.',
                '<b>Sense cita</b>: de 8:30 a 13:00, o fins a exhaurir els tiquets del dia.',
                'Tardes de dilluns a dijous de 16:00 a 18:00, <b>només amb cita prèvia</b>.',
                'Per Nadal, Santa Creu, Setmana Santa i del 24 de juny a l\'11 de setembre: <b>només matins</b>.'],
            f: 'La cita es demana a citaprevia.figueres.cat.' },
      s: { t: "OMAC — Ajuntament de Figueres", u: 'https://www.figueres.cat/ajuntament/atencio-ciutadana/omac' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'certificado', 'volante',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me', 'certificat', 'volant'],
      es: { h: 'Los trámites de <b>padrón</b> se hacen en la OMAC, avenida Salvador Dalí, 107.',
            l: ['Se puede ir <b>sin cita</b> de 8:30 a 13:00, mientras queden tiques.',
                'Con cita, hasta las 14:00 y las tardes de lunes a jueves.'],
            f: 'La documentación depende de su caso. Confírmela en el 972 03 22 00 o en omac@figueres.org antes de desplazarse.' },
      ca: { h: "Els tràmits de <b>padró</b> es fan a l'OMAC, avinguda Salvador Dalí, 107.",
            l: ['Es pot anar-hi <b>sense cita</b> de 8:30 a 13:00, mentre quedin tiquets.',
                'Amb cita, fins a les 14:00 i les tardes de dilluns a dijous.'],
            f: 'La documentació depèn del seu cas. Confirmeu-la al 972 03 22 00 o a omac@figueres.org abans de desplaçar-vos.' },
      s: { t: 'OMAC — Ajuntament de Figueres', u: 'https://www.figueres.cat/ajuntament/atencio-ciutadana/omac' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'sin cita', 'turno', 'tique', 'tiquet',
          'cita previa', 'demanar cita', 'sense cita', 'tiquets'],
      es: { h: 'La <b>cita previa</b> se pide en citaprevia.figueres.cat.',
            l: ['No siempre hace falta: de 8:30 a 13:00 se atiende sin cita, hasta agotar los tiques del día.',
                'Por la tarde, de lunes a jueves de 16:00 a 18:00, <b>la cita es obligatoria</b>.'],
            f: 'Si el sistema no le da hueco, llame al 972 03 22 00.' },
      ca: { h: 'La <b>cita prèvia</b> es demana a citaprevia.figueres.cat.',
            l: ["No sempre cal: de 8:30 a 13:00 s'atén sense cita, fins a exhaurir els tiquets del dia.",
                'A la tarda, de dilluns a dijous de 16:00 a 18:00, <b>la cita és obligatòria</b>.'],
            f: 'Si el sistema no us dona hora, telefoneu al 972 03 22 00.' },
      s: { t: 'Cita prèvia — Ajuntament de Figueres', u: 'https://citaprevia.figueres.cat/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'registro',
          'seu electronica', 'tramit', 'tramits', 'per internet', 'cataleg'],
      es: { h: 'Los trámites en línea se hacen desde figueres.cat, en el apartado de atención ciudadana.',
            l: [],
            f: 'El Ayuntamiento no publica una dirección propia de seu electrònica separada. Para asegurarse, pregunte en el 972 03 22 00 o en omac@figueres.org.' },
      ca: { h: "Els tràmits en línia es fan des de figueres.cat, a l'apartat d'atenció ciutadana.",
            l: [],
            f: "L'Ajuntament no publica una adreça pròpia de seu electrònica separada. Per assegurar-vos, pregunteu al 972 03 22 00 o a omac@figueres.org." },
      s: { t: 'Atenció ciutadana — Ajuntament de Figueres', u: 'https://www.figueres.cat/ajuntament/atencio-ciutadana/omac' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Figueres?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'CA', t: "On és l'OMAC i quin horari té?" },
    { lang: 'ES', t: '¿Puedo ir sin cita previa?' },
  ],
},

// ===========================================================================
{
  slug: 'igualada',
  nombre: 'Igualada',
  articulo: "d'Igualada",
  dominios: 'igualada.cat y tramits.igualada.cat',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: "l'OAC", tel: '93 803 19 50', email: 'atencio.ciutadana@aj-igualada.net' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: "a l'OAC", nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'plaza del ayuntamiento',
          'atencio ciutadana', 'adreca', 'horari', 'a quina hora obren', 'telefon'],
      es: { h: "L'<b>Oficina d'Atenció Ciutadana (OAC)</b> está en la plaça de l'Ajuntament, 1, bajos, 08700 Igualada.",
            l: ['Teléfono: 93 803 19 50. Correo: atencio.ciutadana@aj-igualada.net.',
                'Horario de invierno: de lunes a jueves de 8:00 a 18:00; viernes y vísperas de festivo de 8:00 a 14:00.',
                'Del <b>25 de junio al 15 de septiembre</b>, y en Semana Santa y Navidad: de lunes a viernes de 8:00 a 14:00.'],
            f: 'La cita previa se pide en el 93 803 19 50.' },
      ca: { h: "L'<b>Oficina d'Atenció Ciutadana (OAC)</b> és a la plaça de l'Ajuntament, 1, baixos, 08700 Igualada.",
            l: ['Telèfon: 93 803 19 50. Correu: atencio.ciutadana@aj-igualada.net.',
                "Horari d'hivern: de dilluns a dijous de 8:00 a 18:00; divendres i vigílies de festiu de 8:00 a 14:00.",
                'Del <b>25 de juny al 15 de setembre</b>, i per Setmana Santa i Nadal: de dilluns a divendres de 8:00 a 14:00.'],
            f: 'La cita prèvia es demana al 93 803 19 50.' },
      s: { t: "Oficina d'Atenció Ciutadana — igualada.cat", u: 'https://www.igualada.cat/ca/regidories/promocio-de-la-ciutat-i-coordinacio/oficina-datencio-ciutadana' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'que documentos',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me', 'quins documents'],
      es: { h: "El alta en el <b>padró municipal d'habitants</b> es un trámite de <b>resolución inmediata</b>.",
            l: ['Siempre: <b>original del documento de identidad</b> (DNI, tarjeta de identidad de un estado de la UE, pasaporte o NIE).',
                'Si es <b>propietario</b>: escrituras de la vivienda y última factura (de los dos últimos meses) de luz, agua o gas.',
                'Si está de <b>alquiler</b>: contrato de alquiler vigente y último recibo del alquiler.',
                'En <b>fonda u hotel</b>: documento original con el sello del centro.',
                'Ciudadanos de la <b>UE</b>: certificado de inscripción en el Registro Central de Extranjeros.',
                '<b>Menores</b>: libro de familia o certificado de nacimiento de los progenitores. Con un solo progenitor, autorización firmada del otro y copia compulsada de su documento.',
                'Si se empadronan varios mayores de edad que no son propietarios ni arrendatarios, hace falta autorización del propietario de la vivienda.'],
            f: 'Se tramita en la OAC, plaça de l\'Ajuntament, 1, o en tramits.igualada.cat.' },
      ca: { h: "L'alta al <b>padró municipal d'habitants</b> és un tràmit de <b>resolució immediata</b>.",
            l: ["Sempre: <b>original del document d'identitat</b> (DNI, targeta d'identitat d'un estat de la UE, passaport o NIE).",
                'Si sou <b>propietari</b>: escriptures de l\'habitatge i última factura (dels dos darrers mesos) de llum, aigua o gas.',
                'Si esteu de <b>lloguer</b>: contracte de lloguer vigent i darrer rebut de lloguer.',
                "En <b>fonda o hotel</b>: document original amb el segell del centre.",
                'Ciutadans de la <b>UE</b>: certificat d\'inscripció al Registre Central d\'Estrangers.',
                '<b>Menors</b>: llibre de família o certificat de naixement dels progenitors. Amb un sol progenitor, autorització signada de l\'altre i còpia compulsada del seu document.',
                "Si s'empadronen diversos majors d'edat que no són propietaris ni arrendataris, cal autorització del propietari de l'habitatge."],
            f: "Es tramita a l'OAC, plaça de l'Ajuntament, 1, o a tramits.igualada.cat." },
      s: { t: "Alta en el padró municipal d'habitants — e-Tràmits Igualada", u: 'https://tramits.igualada.cat/ciutadania/DetallTramit.aspx?IdTramit=2' },
    },
    {
      k: ['certificado', 'certificado de empadronamiento', 'certificado padron', 'volante', 'acreditar residencia', 'historico',
          'certificat', "certificat d empadronament", 'volant', 'historic'],
      es: { h: 'El <b>certificat d\'empadronament</b> acredita los periodos en que una persona ha estado empadronada en Igualada.',
            l: ['Se pide en la OAC o en tramits.igualada.cat.'],
            f: 'Dudas: 93 803 19 50 o atencio.ciutadana@aj-igualada.net.' },
      ca: { h: "El <b>certificat d'empadronament</b> acredita els períodes en què una persona ha estat empadronada a Igualada.",
            l: ["Es demana a l'OAC o a tramits.igualada.cat."],
            f: 'Dubtes: 93 803 19 50 o atencio.ciutadana@aj-igualada.net.' },
      s: { t: "Certificat d'empadronament — e-Tràmits Igualada", u: 'https://tramits.igualada.cat/ciutadania/DetallTramit.aspx?IdTramit=36' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'e-tramits',
          'seu electronica', 'tramit', 'tramits', 'per internet', 'cataleg'],
      es: { h: 'Los trámites en línea se hacen en <b>tramits.igualada.cat</b>; la seu electrònica está en seu-e.cat/ca/web/igualada.',
            l: ['Desde e-Tràmits se tramitan el alta en el padrón y los certificados de empadronamiento.'],
            f: 'Dudas: 93 803 19 50 o atencio.ciutadana@aj-igualada.net.' },
      ca: { h: 'Els tràmits en línia es fan a <b>tramits.igualada.cat</b>; la seu electrònica és a seu-e.cat/ca/web/igualada.',
            l: ["Des d'e-Tràmits es tramiten l'alta al padró i els certificats d'empadronament."],
            f: 'Dubtes: 93 803 19 50 o atencio.ciutadana@aj-igualada.net.' },
      s: { t: 'Seu electrònica — Ajuntament d\'Igualada', u: 'https://www.seu-e.cat/ca/web/igualada/seu-electronica' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Igualada?' },
    { lang: 'ES', t: '¿Cómo pido el certificado de empadronamiento?' },
    { lang: 'CA', t: "Què necessito per empadronar-me a Igualada?" },
    { lang: 'ES', t: '¿Dónde está la OAC y qué horario tiene?' },
  ],
},

// ===========================================================================
{
  slug: 'tudela',
  nombre: 'Tudela',
  articulo: 'de Tudela',
  dominios: 'tudela.es y sede.tudela.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el SAC', tel: '948 417 100', email: 'sac010@tudela.es' },
  idioma2: null,
  kb: [
    {
      k: ['sac', '010', 'oficina', 'atencion ciudadana', 'direccion', 'telefono', 'contacto', 'plaza vieja', 'ventanilla', 'ventanilla municipal'],
      es: { h: 'El <b>Servicio de Atención Ciudadana (SAC)</b> es la ventanilla única del Ayuntamiento: informa, tramita y presta los servicios más pedidos.',
            l: ['Plaza Vieja, 1, 31500 Tudela (Navarra).',
                'Teléfono: 948 417 100. Correo: sac010@tudela.es.',
                'Se puede resolver por internet, por teléfono o presencialmente.'],
            f: 'El Ayuntamiento no publica un horario general del SAC en su web. Confírmelo en el 948 417 100.' },
      s: { t: 'SAC — Ayuntamiento de Tudela', u: 'http://www.tudela.es/tu-ayuntamiento/organizacion-administrativa/organizacion-calidad-participacion-ciudadana/sac' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'primera vez', 'cambio de domicilio', 'mudarme', 'nuevo vecino'],
      es: { h: 'Para el <b>alta en el padrón por primera vez</b> el horario funciona en dos tramos y no es lo mismo uno que otro.',
            l: ['De <b>8:00 a 10:00</b>: <b>sin cita previa</b>, por orden de llegada.',
                'De <b>10:00 a 14:30</b>: <b>cita previa necesaria</b>.'],
            f: 'La cita se pide en el 948 417 100 o en sac010@tudela.es.' },
      s: { t: 'ALTA PADRÓN por primera vez — Ayuntamiento de Tudela', u: 'https://www.tudela.es/anuncio/alta-padron-por-primera-vez-cita-previa-necesaria-entre-las-1000-y-las-1430' },
    },
    {
      k: ['certificado', 'certificado de empadronamiento', 'certificado padron', 'volante', 'acreditar residencia', 'historico', 'antes de 1996'],
      es: { h: 'Los <b>certificados y volantes de padrón</b> los gestiona Servicios Generales, incluidos los de registros <b>anteriores a 1996</b>.',
            l: ['Se piden a través del SAC.'],
            f: 'Teléfono 948 417 100 o sac010@tudela.es.' },
      s: { t: 'Servicios Generales — Ayuntamiento de Tudela', u: 'https://tudela.es/tu-ayuntamiento/organizacion-administrativa/organizacion-calidad-participacion-ciudadana/servicios-generales' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'carpeta ciudadana', 'ventanilla municipal', 'registro'],
      es: { h: 'La <b>sede electrónica</b> está en sede.tudela.es.',
            l: ['La <b>carpeta ciudadana</b> y la ventanilla municipal están en tudela.es/ventanilla-municipal.'],
            f: 'Dudas: 948 417 100 o sac010@tudela.es.' },
      s: { t: 'Sede electrónica — Ayuntamiento de Tudela', u: 'https://sede.tudela.es/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Tudela?' },
    { lang: 'ES', t: '¿Cómo pido el certificado de empadronamiento?' },
    { lang: 'ES', t: '¿Puedo empadronarme sin cita previa?' },
    { lang: 'ES', t: '¿Dónde está el SAC?' },
  ],
},

// ===========================================================================
{
  slug: 'alcoi',
  nombre: 'Alcoi',
  articulo: "d'Alcoi",
  dominios: 'alcoi.org y sedeelectronica.alcoi.org',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el SIAC', tel: '96 553 71 00', email: 'bustiaciutadana@alcoi.org' },
  idioma2: { cod: 'VA', clave: 'va', sigla: 'al SIAC', nombre: 'valenciano', sufijo: 'va' },
  kb: [
    {
      k: ['siac', 'oficina', 'atencion ciudadana', 'informacion', 'direccion', 'contacto', 'sant llorenc', 'san lorenzo',
          'atencio ciutadana', 'informacio', 'adreca'],
      es: { h: "El <b>Servei d'Informació i Atenció al Ciutadà (SIAC)</b> está en el carrer de Sant Llorenç, 4.",
            l: ['El <b>padrón</b> se atiende en el número <b>6</b> de la misma calle, y ahí sí hace falta <b>cita previa</b>.',
                'Correo: bustiaciutadana@alcoi.org.'],
            f: 'El Ayuntamiento no publica el horario del SIAC en su web. Confírmelo antes de ir.' },
      va: { h: "El <b>Servei d'Informació i Atenció al Ciutadà (SIAC)</b> està al carrer de Sant Llorenç, 4.",
            l: ['El <b>padró</b> s\'atén al número <b>6</b> del mateix carrer, i allà sí que cal <b>cita prèvia</b>.',
                'Correu: bustiaciutadana@alcoi.org.'],
            f: "L'Ajuntament no publica l'horari del SIAC al seu web. Confirmeu-lo abans d'anar-hi." },
      s: { t: 'Canals de comunicació — alcoi.org', u: 'https://www.alcoi.org/ca/areas/participacion_ciudadana/canales_comunicacion.html' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me'],
      es: { h: 'Los trámites de <b>padrón</b> se atienden en el carrer de Sant Llorenç, <b>6</b>, y requieren <b>cita previa</b>.',
            l: ['La cita se pide en citaprevia.alcoi.org.'],
            f: 'La documentación depende de su caso. Confírmela antes de desplazarse, en bustiaciutadana@alcoi.org.' },
      va: { h: "Els tràmits de <b>padró</b> s'atenen al carrer de Sant Llorenç, <b>6</b>, i requereixen <b>cita prèvia</b>.",
            l: ['La cita es demana a citaprevia.alcoi.org.'],
            f: 'La documentació depèn del seu cas. Confirme-la abans de desplaçar-se, a bustiaciutadana@alcoi.org.' },
      s: { t: "Informe o certificat d'empadronament — Seu electrònica d'Alcoi", u: 'https://sedeelectronica.alcoi.org/sta/CarpetaPublic/doEvent?APP_CODE=STA&PAGE_CODE=CATALOGO&DETALLE=6269000018049195707711&lang=CA' },
    },
    {
      k: ['certificado', 'certificado de empadronamiento', 'certificado padron', 'informe', 'volante', 'individual', 'colectivo', 'plazo',
          'certificat', "certificat d empadronament", 'informe', 'volant', 'col lectiu', 'termini'],
      es: { h: 'El <b>informe o certificado de empadronamiento</b> (individual o colectivo) acredita el domicilio en el que una persona consta empadronada.',
            l: ['Lo pueden pedir <b>personas físicas</b>, presentando una instancia.',
                'Se tramita por la <b>seu electrònica</b> o presencialmente en el carrer de Sant Llorenç, 6, con cita previa.',
                'Plazo de resolución: <b>tres meses</b>.',
                'Está sujeto a la tasa por expedición de documentación administrativa.'],
            f: 'El importe exacto de esa tasa no se lo puedo dar: consúltelo en bustiaciutadana@alcoi.org.' },
      va: { h: "L'<b>informe o certificat d'empadronament</b> (individual o col·lectiu) acredita el domicili en què una persona consta empadronada.",
            l: ['El poden demanar <b>persones físiques</b>, presentant una instància.',
                "Es tramita per la <b>seu electrònica</b> o presencialment al carrer de Sant Llorenç, 6, amb cita prèvia.",
                'Termini de resolució: <b>tres mesos</b>.',
                "Està subjecte a la taxa per expedició de documentació administrativa."],
            f: "L'import exacte d'eixa taxa no li'l puc donar: consulte'l a bustiaciutadana@alcoi.org." },
      s: { t: "Informe o certificat d'empadronament — Seu electrònica d'Alcoi", u: 'https://sedeelectronica.alcoi.org/sta/CarpetaPublic/doEvent?APP_CODE=STA&PAGE_CODE=CATALOGO&DETALLE=6269000018049195707711&lang=CA' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo', 'cita', 'cita previa', 'pedir cita', 'registro',
          'seu electronica', 'tramit', 'tramits', 'per internet', 'cataleg', 'cita previa', 'demanar cita'],
      es: { h: 'La <b>seu electrònica</b> está en sedeelectronica.alcoi.org y la <b>cita previa</b> en citaprevia.alcoi.org.',
            l: ['En la seu electrònica están el catálogo de trámites y las oficinas de asistencia en materia de registro.'],
            f: 'Dudas: bustiaciutadana@alcoi.org.' },
      va: { h: 'La <b>seu electrònica</b> està a sedeelectronica.alcoi.org i la <b>cita prèvia</b> a citaprevia.alcoi.org.',
            l: ["A la seu electrònica hi ha el catàleg de tràmits i les oficines d'assistència en matèria de registre."],
            f: 'Dubtes: bustiaciutadana@alcoi.org.' },
      s: { t: "Seu electrònica — Ajuntament d'Alcoi", u: 'https://sedeelectronica.alcoi.org/sta/CarpetaPublic/doEvent?APP_CODE=STA&PAGE_CODE=PTS_HOME&lang=ca' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Alcoi?' },
    { lang: 'ES', t: '¿Cómo pido el certificado de empadronamiento?' },
    { lang: 'VA', t: "Com demane cita prèvia?" },
    { lang: 'ES', t: '¿Dónde se hacen los trámites de padrón?' },
  ],
},

// ===========================================================================
{
  slug: 'mislata',
  nombre: 'Mislata',
  articulo: 'de Mislata',
  dominios: 'mislata.es y mislata.sedipualba.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'la OAC', tel: '96 399 11 01', email: 'correuciutada@mislata.es' },
  idioma2: { cod: 'VA', clave: 'va', sigla: 'a la OAC', nombre: 'valenciano', sufijo: 'va' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'centre jove', 'mercat', 'donde esta la oficina',
          'atencio ciutadana', 'adreca', 'horari', 'a quina hora obrin', 'telefon'],
      es: { h: 'Atención: la <b>OAC está provisionalmente en el Centre Jove del Mercat</b>, carrer Major, 36 — <b>no</b> en la Casa de la Vila.',
            l: ['La dirección oficial del Ayuntamiento es plaça de la Constitució, 8, 46920 Mislata.',
                'Horario: de lunes a viernes de 8:00 a 14:00. En verano, hasta el 15 de octubre, de 8:00 a 13:30.',
                'Teléfonos: 96 399 11 01 (general) y 96 399 11 65 (padrón).',
                'Correo: correuciutada@mislata.es.'],
            f: 'Antes de ir, confirme que sigue en el Centre Jove: es un traslado provisional.' },
      va: { h: 'Atenció: l\'<b>OAC està provisionalment al Centre Jove del Mercat</b>, carrer Major, 36 — <b>no</b> a la Casa de la Vila.',
            l: ["L'adreça oficial de l'Ajuntament és plaça de la Constitució, 8, 46920 Mislata.",
                'Horari: de dilluns a divendres de 8:00 a 14:00. A l\'estiu, fins al 15 d\'octubre, de 8:00 a 13:30.',
                'Telèfons: 96 399 11 01 (general) i 96 399 11 65 (padró).',
                'Correu: correuciutada@mislata.es.'],
            f: "Abans d'anar-hi, confirme que continua al Centre Jove: és un trasllat provisional." },
      s: { t: 'Oficina de Atención a la Ciudadanía (OAC) — mislata.es', u: 'https://www.mislata.es/es/informate/tablon-de-anuncios/oficina-de-atencion-la-ciudadania-oac' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta padron', 'cambio de domicilio', 'mudarme', 'nuevo vecino', 'confirmacion de residencia', 'modificar datos',
          'empadronar-me', 'empadronament', 'alta padro', 'canvi de domicili', 'mudar-me'],
      es: { h: 'La OAC gestiona el <b>padrón de habitantes</b>: altas, confirmaciones de residencia de personas extranjeras, modificaciones de datos y cambios de domicilio.',
            l: ['También emite certificados de empadronamiento: históricos, individuales y colectivos.',
                'Teléfono directo de padrón: <b>96 399 11 65</b>.'],
            f: 'La documentación depende de su caso. Confírmela en el 96 399 11 65 antes de desplazarse.' },
      va: { h: "L'OAC gestiona el <b>padró d'habitants</b>: altes, confirmacions de residència de persones estrangeres, modificacions de dades i canvis de domicili.",
            l: ["També emet certificats d'empadronament: històrics, individuals i col·lectius.",
                'Telèfon directe de padró: <b>96 399 11 65</b>.'],
            f: 'La documentació depèn del seu cas. Confirme-la al 96 399 11 65 abans de desplaçar-se.' },
      s: { t: 'Oficina de Atención al Ciudadano (OAC) — mislata.es', u: 'https://www.mislata.es/es/transparencia/organizacion-administrativa/estructura-organizativa/cartas-de-servicios/oficina-de-atencion-al-ciudano-oac' },
    },
    {
      k: ['certificado', 'certificado de empadronamiento', 'certificado padron', 'volante', 'acreditar residencia', 'historico', 'colectivo', 'individual', 'gratis', 'gratuito',
          'certificat', "certificat d empadronament", 'volant', 'historic', 'col lectiu', 'gratuit'],
      es: { h: 'El <b>certificado de empadronamiento</b> acredita el domicilio y los demás hechos relativos al empadronamiento en Mislata.',
            l: ['Presencialmente: <b>documento de identidad original</b>. Por internet: <b>certificado digital</b>.',
                'Si va un representante: autorización expresa y copia del DNI de la persona representada.',
                'De un <b>menor</b>: lo piden sus representantes legales con el libro de familia o el certificado de nacimiento.',
                'Los certificados <b>ordinarios y colectivos están exentos de tasa</b>. Los históricos sí tienen tasa.',
                'Los ordinarios se emiten automáticamente en mislata.sedipualba.es/certificadoempadronamiento/.'],
            f: 'El importe de la tasa de los históricos no se lo puedo dar: pregúntelo en el 96 399 11 65. Los certificados de circunstancias especiales se piden por escrito en el Registro o en la sede electrónica.' },
      va: { h: "El <b>certificat d'empadronament</b> acredita el domicili i els altres fets relatius a l'empadronament a Mislata.",
            l: ["Presencialment: <b>document d'identitat original</b>. Per internet: <b>certificat digital</b>.",
                'Si hi va un representant: autorització expressa i còpia del DNI de la persona representada.',
                "D'un <b>menor</b>: el demanen els seus representants legals amb el llibre de família o el certificat de naixement.",
                'Els certificats <b>ordinaris i col·lectius estan exempts de taxa</b>. Els històrics sí que en tenen.',
                'Els ordinaris s\'emeten automàticament a mislata.sedipualba.es/certificadoempadronamiento/.'],
            f: "L'import de la taxa dels històrics no li'l puc donar: pregunte'l al 96 399 11 65. Els certificats de circumstàncies especials es demanen per escrit al Registre o a la seu electrònica." },
      s: { t: 'Certificado de empadronamiento — mislata.es', u: 'https://www.mislata.es/es/administracion/oficina-virtual/padron-de-habitantes/certificado-de-empadronamiento' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'oficina virtual', 'registro', 'instancia', 'sedipualba',
          'seu electronica', 'tramit', 'tramits', 'per internet', 'instancia', 'registre'],
      es: { h: 'La <b>sede electrónica</b> está en mislata.sedipualba.es y se accede con <b>certificado digital</b>.',
            l: ['La OAC registra documentos de entrada y salida, y también atiende tesorería (domiciliaciones, duplicados de recibos, certificados de pago) y las sanciones de tráfico de la Mancomunitat de l\'Horta Sud.'],
            f: 'Dudas: 96 399 11 01 o correuciutada@mislata.es.' },
      va: { h: 'La <b>seu electrònica</b> està a mislata.sedipualba.es i s\'hi accedeix amb <b>certificat digital</b>.',
            l: ["L'OAC registra documents d'entrada i eixida, i també atén tresoreria (domiciliacions, duplicats de rebuts, certificats de pagament) i les sancions de trànsit de la Mancomunitat de l'Horta Sud."],
            f: 'Dubtes: 96 399 11 01 o correuciutada@mislata.es.' },
      s: { t: 'Oficina Virtual — mislata.es', u: 'https://www.mislata.es/es/administracion/oficina-virtual' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Qué necesito para empadronarme en Mislata?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'ES', t: '¿Dónde está la OAC ahora mismo?' },
    { lang: 'VA', t: "Com aconseguisc un certificat d'empadronament?" },
  ],
},

];
