// ---------------------------------------------------------------------------
//  LOS OCHO DEL OCTAVO ENVIO — miercoles 23 de septiembre de 2026.
//  Comprobado en cada web municipal el 7 de septiembre de 2026.
//
//  Estos ocho estaban marcados "revisar" en SEGUIMIENTO.csv porque no se habia
//  comprobado si ya tenian chatbot. Se comprobo con _envios/detectar-chatbot.mjs
//  el 7/9/2026: ninguno tiene widget de chatbot en su portada. Es una
//  comprobacion de portada, no una auditoria del sitio entero.
//
//  Catalan en Palma; valenciano en Gandia (la Safor, zona de predominio
//  linguistico valenciano).
// ---------------------------------------------------------------------------

export const MUNICIPIOS_DIA08 = [

// ===========================================================================
{
  slug: 'palma',
  nombre: 'Palma',
  articulo: 'de Palma',
  dominios: 'palma.cat y seuelectronica.palma.cat',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'las OAC', tel: '971 22 59 00', email: 'ajuntament@palma.es' },
  idioma2: { cod: 'CA', clave: 'ca', sigla: 'a les OAC', nombre: 'catalán' },
  kb: [
    {
      k: ['oac', 'oficina', 'oficinas', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'escorxador', 'avingudes', 'son ferriol', 'pere garau',
          'atencio ciutadana', 'adreca', 'horari', 'telefon'],
      es: { h: 'Palma tiene <b>varias Oficinas d\'Atenció a la Ciutadania (OAC)</b>, todas con el mismo teléfono: <b>971 22 59 00</b>.',
            l: ['OAC S\'Escorxador: carrer de l\'Emperadriu Eugènia, 6 — 07010 Palma.',
                'OAC Avingudes: avinguda de Gabriel Alomar, 18 — 07006 Palma.',
                'OAC Son Ferriol: carrer del Cid, 8 — 07198 Palma.',
                'OAC Pere Garau: carrer de Pere Llobera, 9 — 07007 Palma.',
                'Horario general: de 8:30 a 14:00, de lunes a viernes.'],
            f: 'La OAC Avingudes amplía horario de octubre a mayo: de lunes a jueves hasta las 17:00.' },
      ca: { h: 'Palma té <b>diverses Oficines d\'Atenció a la Ciutadania (OAC)</b>, totes amb el mateix telèfon: <b>971 22 59 00</b>.',
            l: ['OAC S\'Escorxador: carrer de l\'Emperadriu Eugènia, 6 — 07010 Palma.',
                'OAC Avingudes: avinguda de Gabriel Alomar, 18 — 07006 Palma.',
                'OAC Son Ferriol: carrer del Cid, 8 — 07198 Palma.',
                'OAC Pere Garau: carrer de Pere Llobera, 9 — 07007 Palma.',
                'Horari general: de 8:30 a 14:00, de dilluns a divendres.'],
            f: 'L\'OAC Avingudes amplia horari d\'octubre a maig: de dilluns a dijous fins a les 17:00.' },
      s: { t: 'Oficines d\'atenció a la ciutadania (OAC) — seuelectronica.palma.cat', u: 'https://seuelectronica.palma.cat/ca/-/oficines-d-atenci%C3%B3-a-la-ciutadania-oac-' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta', 'cambio de domicilio', 'extranjeros', 'renovacion',
          'padro', 'empadronar-me', 'empadronament', 'canvi de domicili', 'estrangers'],
      es: { h: 'Las altas y los cambios de domicilio en el padrón se hacen <b>con cita previa</b>.',
            l: ['También se tramitan las bajas.',
                'Y la renovación periódica de las inscripciones de extranjeros no comunitarios.',
                'La cita para trámites padronales se solicita en el 971 22 59 00.'],
            f: 'Los <b>mayores de 65 años</b> pueden ir directamente a la OAC de Son Moix <b>sin cita</b>, de 8:30 a 13:30, para altas o cambios de domicilio.' },
      ca: { h: 'Les altes i els canvis de domicili al padró es fan <b>amb cita prèvia</b>.',
            l: ['També es tramiten les baixes.',
                'I la renovació periòdica de les inscripcions dels estrangers no comunitaris.',
                'La cita per a tràmits padronals es demana al 971 22 59 00.'],
            f: 'Els <b>majors de 65 anys</b> poden anar directament a l\'OAC de Son Moix <b>sense cita</b>, de 8:30 a 13:30, per a altes o canvis de domicili.' },
      s: { t: 'Oficines d\'atenció a la ciutadania (OAC) — seuelectronica.palma.cat', u: 'https://seuelectronica.palma.cat/ca/-/oficines-d-atenci%C3%B3-a-la-ciutadania-oac-' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'sin cita', 'reservar', 'mayores', '65', 'son moix',
          'cita previa', 'demanar cita', 'sense cita', 'majors'],
      es: { h: 'Para los trámites del padrón hace falta <b>cita previa</b>, con una excepción importante.',
            l: ['La cita se pide en el 971 22 59 00.',
                'Excepción: los mayores de 65 años pueden acudir sin cita a la OAC de Son Moix, de 8:30 a 13:30.'],
            f: 'Esa excepción vale para altas y cambios de domicilio en el padrón municipal.' },
      ca: { h: 'Per als tràmits del padró cal <b>cita prèvia</b>, amb una excepció important.',
            l: ['La cita es demana al 971 22 59 00.',
                'Excepció: els majors de 65 anys poden anar sense cita a l\'OAC de Son Moix, de 8:30 a 13:30.'],
            f: 'Aquesta excepció val per a altes i canvis de domicili al padró municipal.' },
      s: { t: 'Atenció presencial — Oficines d\'atenció a la ciutadania', u: 'https://palma.es/atencion-presencial-oficinas-de-atencion-a-la-ciudadania' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet',
          'seu electronica', 'tramit', 'tramits', 'per internet'],
      es: { h: 'La <b>seu electrònica</b> está en seuelectronica.palma.cat.',
            l: ['Permite hacer trámites sin pasar por la OAC.'],
            f: 'Dudas: 971 22 59 00.' },
      ca: { h: 'La <b>seu electrònica</b> és a seuelectronica.palma.cat.',
            l: ['Permet fer tràmits sense passar per l\'OAC.'],
            f: 'Dubtes: 971 22 59 00.' },
      s: { t: 'Seu Electrònica — Ajuntament de Palma', u: 'https://seuelectronica.palma.cat/' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Dónde están las OAC?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'ES', t: '¿Hasta qué hora abren?' },
    { lang: 'CA', t: 'Els majors de 65 anys necessiten cita?' },
    { lang: 'ES', t: '¿Hace falta cita para empadronarse?' },
  ],
},

// ===========================================================================
{
  slug: 'oviedo',
  nombre: 'Oviedo',
  articulo: 'de Oviedo',
  dominios: 'oviedo.es y sede.oviedo.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'Estadística y Padrón', tel: '984 083 800', email: 'ayuntamiento@oviedo.es' },
  idioma2: null,
  kb: [
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'estadistica', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'rosal', 'numero', 'turno'],
      es: { h: 'El <b>Padrón Municipal de Habitantes</b> está en la calle Rosal, 23.',
            l: ['Teléfono: 984 083 800, extensiones 2600 y 2601.',
                'Atención al público de 9:00 a 14:00 en días laborables.',
                'Ojo con los turnos: en Estadística los <b>números se sacan de 9:00 a 12:00</b>.',
                'Para volantes y certificados, el horario es de 9:00 a 14:00.'],
            f: 'Si llega después de las 12:00 puede quedarse sin número aunque la oficina siga abierta.' },
      s: { t: 'Estadística y Padrón de habitantes — oviedo.es', u: 'https://www.oviedo.es/-/padron-y-estadistica' },
    },
    {
      k: ['correo', 'email', 'por correo', 'sin ir', 'a distancia', 'remoto', 'estadistica@oviedo.es'],
      es: { h: 'La mayoría de los trámites del padrón se pueden hacer <b>por correo electrónico</b>, sin ir a la oficina.',
            l: ['Dirección: estadistica@oviedo.es.',
                'Solo algunos casos concretos exigen presencia física.'],
            f: 'Antes de pedir cita, pregunte por correo si su caso se puede resolver así.' },
      s: { t: 'Estadística y Padrón de habitantes — oviedo.es', u: 'https://www.oviedo.es/-/padron-y-estadistica' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita', 'registro', 'registro general'],
      es: { h: 'La <b>cita previa</b> se pide por internet o por teléfono.',
            l: ['Web: oviedo.es/citaprevia.',
                'Teléfono: 984 083 800, extensiones 2600 y 2601.',
                'El Registro General tiene su propia página de cita previa.'],
            f: 'Recuerde que muchos trámites de padrón se resuelven por correo y se ahorra la cita.' },
      s: { t: 'Cita previa Estadística y Padrón municipal — oviedo.es', u: 'https://www.oviedo.es/estadistica/cita-previa-estadistica-y-padron-municipal-de-habitantes' },
    },
    {
      k: ['recaudacion', 'tesoreria', 'plaza de la constitucion', 'oficina de recaudacion', 'donde pago'],
      es: { h: 'La <b>Oficina de Recaudación</b> está en la plaza de la Constitución, 1.',
            l: ['Teléfono: 985 953 270.'],
            f: 'No es la misma oficina que el Padrón, que está en la calle Rosal, 23.' },
      s: { t: 'Atención Ciudadana — Ayuntamiento de Oviedo', u: 'https://www.oviedo.es/atencionciudadana' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hasta qué hora dan números en el padrón?' },
    { lang: 'ES', t: '¿Puedo hacer el padrón por correo?' },
    { lang: 'ES', t: '¿Hace falta cita previa?' },
    { lang: 'ES', t: '¿Dónde está la oficina del padrón?' },
    { lang: 'ES', t: '¿Y el horario de verano?' },
  ],
},

// ===========================================================================
{
  slug: 'getafe',
  nombre: 'Getafe',
  articulo: 'de Getafe',
  dominios: 'getafe.es y sede.getafe.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'el SAV', tel: '912 027 900', email: 'puntoinformacion@ayto-getafe.org' },
  idioma2: null,
  kb: [
    {
      k: ['sav', 'oficina', 'oficinas', 'atencion al vecino', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'buenos aires', 'chico mendes'],
      es: { h: 'El <b>Servicio de Atención al Vecino (SAV)</b> tiene su sede principal en la plaza de la Constitución, 1 — 28901 Getafe (Madrid).',
            l: ['Teléfono principal: 912 027 900.',
                'Avenida de Buenos Aires, 2 — teléfonos 912 027 993 y 912 027 900, extensión 53606.',
                'Avenida de Francisco Chico Mendes, s/n — teléfonos 912 027 994 y 912 027 900, extensión 53701.',
                'Horario: de lunes a viernes de 9:30 a 14:00.'],
            f: 'Correo: puntoinformacion@ayto-getafe.org.' },
      s: { t: 'Oficinas de atención a la ciudadanía — sede.getafe.es', u: 'https://sede.getafe.es/sta/CarpetaPublic/doEvent?APP_CODE=STA&PAGE_CODE=CONTACTO_PERS' },
    },
    {
      k: ['cita', 'cita previa', 'sin cita', 'pedir cita', 'reservar', 'necesaria', 'obligatoria', 'antelacion'],
      es: { h: 'Hace falta <b>cita previa</b> para casi todo, con <b>dos excepciones</b>.',
            l: ['No hace falta cita para el <b>certificado de empadronamiento</b>.',
                'Tampoco para registrar documentación dirigida al Ayuntamiento.',
                'Las citas de Padrón se abren con 30 días de antelación; las de Registro, con 14.',
                'En los centros cívicos, con 14 días.'],
            f: 'Si solo necesita el certificado de empadronamiento, puede ir directamente.' },
      s: { t: 'Contacte con el Servicio de Atención al Vecino — sede.getafe.es', u: 'https://sede.getafe.es/sta/CarpetaPublic/doEvent?APP_CODE=STA&PAGE_CODE=CONTACTO' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'cambio de domicilio'],
      es: { h: 'El SAV gestiona el <b>padrón</b> y la expedición de certificados.',
            l: ['El certificado de empadronamiento se obtiene <b>sin cita previa</b>.',
                'Para altas y cambios de domicilio sí hace falta cita, que se abre con 30 días de antelación.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 912 027 900 antes de ir.' },
      s: { t: 'Servicio de atención al vecino (SAV) — getafe.es', u: 'https://getafe.es/delegaciones/area-social/servicio-de-atencion-al-vecino-sav/' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'telefonos de interes'],
      es: { h: 'La <b>sede electrónica</b> está en sede.getafe.es.',
            l: ['Hay también un listado de teléfonos de interés en getafe.es.'],
            f: 'Atención telefónica general: 912 027 900.' },
      s: { t: 'Sede Electrónica — Ayuntamiento de Getafe', u: 'https://sede.getafe.es/portalGetafe/sede/se_principal1.jsp?codResi=1' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hace falta cita para el certificado de empadronamiento?' },
    { lang: 'ES', t: '¿Dónde están las oficinas del SAV?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'ES', t: '¿Con cuánta antelación se piden las citas?' },
  ],
},

// ===========================================================================
{
  slug: 'fuenlabrada',
  nombre: 'Fuenlabrada',
  articulo: 'de Fuenlabrada',
  dominios: 'ayto-fuenlabrada.es y sede.ayto-fuenlabrada.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'Atención Ciudadana', tel: '010 o 91 649 70 10', email: 'atciu@ayto-fuenlabrada.es' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'plaza de la constitucion', 'verano', 'navidad', 'semana santa', '010'],
      es: { h: 'El <b>Servicio de Atención Ciudadana</b> está en la plaza de la Constitución, 1.',
            l: ['Teléfonos: 91 649 70 00; el <b>010</b> desde dentro de Fuenlabrada; el 91 649 70 10 desde fuera.',
                'Horario: de lunes a viernes de <b>8:30 a 19:00</b>.',
                'En Semana Santa, verano (del 1 de julio al 11 de septiembre de 2026) y Navidad: de 8:30 a 14:00.',
                'Correo: atciu@ayto-fuenlabrada.es.'],
            f: 'Fuera de esos periodos son más de diez horas seguidas al día.' },
      s: { t: 'Directorios y teléfonos de contacto — ayto-fuenlabrada.es', u: 'https://www.ayto-fuenlabrada.es/directorios-telefonos-contacto' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'alta', 'nuevo vecino', 'certificado', 'volante', 'cambio de domicilio'],
      es: { h: 'El Servicio de Atención Ciudadana inscribe en el <b>Padrón de Habitantes</b> a los nuevos vecinos.',
            l: ['Se hace una vez verificada la identidad del solicitante.',
                'La gestión padronal es uno de los trámites que van con cita previa.'],
            f: 'El alta en el padrón tiene su propia ficha en ayto-fuenlabrada.es.' },
      s: { t: 'Alta en el padrón de habitantes — ayto-fuenlabrada.es', u: 'https://www.ayto-fuenlabrada.es/web/portal/w/alta-en-el-padron-de-habitantes' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'reservar', 'como pido cita', 'ventanilla unica', 'registro'],
      es: { h: 'Hay <b>cita previa</b> para registro, Ventanilla Única y gestión padronal.',
            l: ['Información sobre citas en el <b>010</b> desde el municipio, o en el 91 649 70 10 desde fuera.',
                'Ese teléfono atiende de 8:30 a 14:30.',
                'También se pide en citaprevia.ayto-fuenlabrada.es.'],
            f: 'El teléfono de citas tiene horario más corto que la oficina: hasta las 14:30.' },
      s: { t: 'Cita Previa — ayto-fuenlabrada.es', u: 'https://www.ayto-fuenlabrada.es/cita-previa' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'certificados personales'],
      es: { h: 'La <b>sede electrónica</b> está en sede.ayto-fuenlabrada.es.',
            l: ['Los trámites y certificados personales están agrupados en ayto-fuenlabrada.es/tramites.'],
            f: 'Dudas: el 010, o el 91 649 70 10 desde fuera del municipio.' },
      s: { t: 'Trámites y certificados personales — ayto-fuenlabrada.es', u: 'https://www.ayto-fuenlabrada.es/tramites/asuntos-personales' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hasta qué hora abren?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'ES', t: '¿Dónde pido el volante?' },
    { lang: 'ES', t: '¿Qué horario tienen en verano?' },
    { lang: 'ES', t: '¿Cómo pido cita para el padrón?' },
    { lang: 'ES', t: '¿Cuál es el teléfono?' },
  ],
},

// ===========================================================================
{
  slug: 'albacete',
  nombre: 'Albacete',
  articulo: 'de Albacete',
  dominios: 'albacete.es y sede.albacete.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'la OMACi', tel: '967 59 61 00', email: 'att.ciudadana@albacete.es' },
  idioma2: null,
  kb: [
    {
      k: ['omaci', 'oficina', 'atencion ciudadania', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'plaza de la catedral'],
      es: { h: 'La <b>Oficina Municipal de Atención a la Ciudadanía (OMACi)</b> está en la plaza de la Catedral, s/n — 02071 Albacete.',
            l: ['Teléfono: 967 59 61 00.',
                'Atención telefónica: de lunes a viernes de 9:00 a 14:00, excepto festivos.',
                'Correo: sac@ayto-albacete.es.'],
            f: 'Es la oficina que lleva el padrón municipal y los certificados.' },
      s: { t: 'Oficina Municipal de Atención a la Ciudadanía (OMACi) — albacete.es', u: 'https://www.albacete.es/es/directorio/oficina-municipal-atencion-ciudadania-omaci' },
    },
    {
      k: ['cita', 'cita previa', 'sin cita', 'pedir cita', 'necesaria', 'obligatoria', 'reservar'],
      es: { h: '<b>No hace falta cita previa</b>, salvo para un caso concreto.',
            l: ['La excepción: el alta o el cambio de domicilio en el Padrón Municipal de Habitantes, cuando se hace presencialmente.',
                'Para todo lo demás se puede acudir directamente.'],
            f: 'Los volantes y certificados de empadronamiento no exigen cita.' },
      s: { t: 'Padrón de Habitantes y Atención Ciudadana — albacete.es', u: 'https://www.albacete.es/es/tu-ayuntamiento/padron-habitantes-atencion-ciudadana' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'volante', 'certificado', 'cambio de domicilio'],
      es: { h: 'La OMACi lleva el <b>padrón municipal de habitantes</b> y expide volantes y certificados de empadronamiento.',
            l: ['Los volantes y certificados no necesitan cita previa.',
                'El alta y el cambio de domicilio presenciales, sí.'],
            f: 'La documentación concreta depende de su caso. Confírmela en el 967 59 61 00 antes de ir.' },
      s: { t: 'Padrón de Habitantes y Atención Ciudadana — albacete.es', u: 'https://www.albacete.es/es/tu-ayuntamiento/padron-habitantes-atencion-ciudadana' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'carpeta ciudadana', 'registro electronico'],
      es: { h: 'Los documentos se pueden registrar presencialmente o por la <b>Carpeta Ciudadana</b>.',
            l: ['La Carpeta Ciudadana es el registro electrónico municipal.'],
            f: 'Dudas: 967 59 61 00.' },
      s: { t: 'Atención Ciudadana — Ayuntamiento de Albacete', u: 'http://www.albacete.es/es/servicio_de_atencion_ciudadana' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hace falta cita previa en la OMACi?' },
    { lang: 'ES', t: '¿Dónde está la OMACi?' },
    { lang: 'ES', t: '¿Hasta qué hora abren?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'ES', t: '¿Necesito cita para un volante de empadronamiento?' },
  ],
},

// ===========================================================================
{
  slug: 'marbella',
  nombre: 'Marbella',
  articulo: 'de Marbella',
  dominios: 'marbella.es y ayuntamiento.marbella.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'la OAC', tel: '952 76 11 00', email: 'oac@marbella.es' },
  idioma2: null,
  kb: [
    {
      k: ['oac', 'oficina', 'oficinas', 'atencion al ciudadano', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'naranjos', 'san pedro', 'nueva andalucia'],
      es: { h: 'Marbella tiene <b>tres Oficinas de Atención al Ciudadano (OAC)</b>.',
            l: ['Marbella: plaza de los Naranjos, 1.',
                'San Pedro Alcántara: plaza de la Iglesia, 1.',
                'Distrito de Nueva Andalucía: avenida Miguel de Cervantes, 15.',
                'Horario: de lunes a viernes de 9:00 a 14:00.'],
            f: 'Teléfono de cita previa: 952 76 11 00. Correo: oac@marbella.es.' },
      s: { t: 'Oficina de Atención al Ciudadano — marbella.es', u: 'https://www.marbella.es/ayto/localizaciones-municipales/directorio-municipal/servicios/oficina-de-atencion-al-ciudadano-marbella.html' },
    },
    {
      k: ['cita', 'cita previa', 'pedir cita', 'sin cita', 'obligatoria', 'necesaria', 'reservar'],
      es: { h: '<b>Todos</b> los trámites de las OAC requieren <b>cita previa</b>.',
            l: ['Se pide en citaprevia.marbella.es.',
                'O por teléfono, en el 952 76 11 00.'],
            f: 'Sin cita no se atiende: no es una recomendación.' },
      s: { t: 'Cita previa para las Oficinas de Atención al Ciudadano', u: 'https://ayuntamiento.marbella.es/gobierno-abierto/oficina-de-atencion-al-ciudadano-oac/2591-cita-previa-para-las-oficinas-de-atencion-al-ciudadano-en-marbella-y-san-pedro-alcantara.html' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'cambio de domicilio', 'modificacion'],
      es: { h: 'La OAC gestiona <b>altas, cambios y modificaciones</b> en el Padrón de Habitantes.',
            l: ['También la obtención de certificados y volantes de empadronamiento.',
                'Todo con cita previa: citaprevia.marbella.es o 952 76 11 00.'],
            f: 'La documentación concreta depende de su caso. Confírmela antes de reservar la cita.' },
      s: { t: 'OAC — Ayuntamiento de Marbella', u: 'https://ayuntamiento.marbella.es/gobierno-abierto/oficina-de-atencion-al-ciudadano-oac.html' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'a distancia'],
      es: { h: 'La <b>sede electrónica</b> permite hacer más de 150 trámites a distancia.',
            l: ['Es la vía para evitar la cita previa, que en las OAC es obligatoria.'],
            f: 'Dudas: oac@marbella.es o 952 76 11 00.' },
      s: { t: 'Sede electrónica con más de 150 trámites a distancia — marbella.es', u: 'https://www.marbella.es/actualidad/noticias/el-ayuntamiento-pone-en-marcha-una-sede-electronica-que-ya-permite-realizar-mas-de-150-tramites-a-distancia.html' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hace falta cita previa en la OAC?' },
    { lang: 'ES', t: '¿Puedo hacer trámites sin ir?' },
    { lang: 'ES', t: '¿Qué horario tienen?' },
    { lang: 'ES', t: '¿Qué necesito para empadronarme?' },
    { lang: 'ES', t: '¿Dónde están las oficinas?' },
    { lang: 'ES', t: '¿Cuál es el teléfono?' },
  ],
},

// ===========================================================================
{
  slug: 'valdemoro',
  nombre: 'Valdemoro',
  articulo: 'de Valdemoro',
  dominios: 'valdemoro.es y sede.valdemoro.es',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'Atención Ciudadana', tel: '91 809 98 90', email: 'ciudadano@valdemoro.es' },
  idioma2: null,
  kb: [
    {
      k: ['oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'plaza de la constitucion'],
      es: { h: 'La oficina de <b>Atención Ciudadana</b> está en la plaza de la Constitución, 11 — 28341 Valdemoro.',
            l: ['Teléfono: 91 809 98 90.',
                'Horario: de 8:30 a 14:00.'],
            f: 'Correo: ciudadano@valdemoro.es.' },
      s: { t: 'Contacto — Ayuntamiento de Valdemoro', u: 'https://www.valdemoro.es/contacto' },
    },
    {
      k: ['cita', 'cita previa', 'sin cita', 'pedir cita', 'necesaria', 'obligatoria', 'reservar'],
      es: { h: 'Desde el 1 de abril de 2022 <b>no hace falta cita previa</b> para Atención Ciudadana.',
            l: ['Aun así hay citas disponibles cada 15 minutos, con dos huecos simultáneos.',
                'Se piden en sede.valdemoro.es.'],
            f: 'Es decir: puede ir directamente, pero con cita espera menos.' },
      s: { t: 'El Ayuntamiento amplía la cita previa al Servicio de Atención Ciudadana — valdemoro.es', u: 'https://www.valdemoro.es/temas/-/asset_publisher/qJiOaInH705S/content/el-ayuntamiento-amplia-la-cita-previa-al-servicio-de-atencion-ciudadana/maximized' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'volante', 'certificado', 'cambio de domicilio', 'renovacion', 'baja'],
      es: { h: 'El <b>volante de empadronamiento</b> se expide solo presencialmente y <b>sin cita previa</b>.',
            l: ['Para los demás trámites del padrón sí se puede pedir cita: altas, cambios, certificados, renovación, confirmación de domicilio o baja por inscripción indebida.'],
            f: 'Si solo necesita el volante, vaya directamente: plaza de la Constitución, 11, de 8:30 a 14:00.' },
      s: { t: 'Atención Ciudadana — sede.valdemoro.es', u: 'https://sede.valdemoro.es/tramites-atencionciudadana' },
    },
    {
      k: ['sede electronica', 'tramite', 'tramites', 'online', 'internet', 'por internet', 'catalogo'],
      es: { h: 'La <b>sede electrónica</b> está en sede.valdemoro.es.',
            l: ['Tiene un catálogo de los servicios que admiten cita previa.'],
            f: 'Dudas: 91 809 98 90.' },
      s: { t: 'Sede Electrónica — Ayuntamiento de Valdemoro', u: 'https://sede.valdemoro.es/sede' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hace falta cita previa?' },
    { lang: 'ES', t: '¿Hasta qué hora abren?' },
    { lang: 'ES', t: '¿Dónde está la oficina?' },
    { lang: 'ES', t: '¿Puedo hacer los trámites por internet?' },
    { lang: 'ES', t: '¿Cómo consigo un volante de empadronamiento?' },
  ],
},

// ===========================================================================
{
  slug: 'gandia',
  nombre: 'Gandia',
  articulo: 'de Gandia',
  dominios: 'gandia.es y gandia.org',
  fecha: '7 de septiembre de 2026',
  oficina: { sigla: 'la OAC', tel: '010 o 962 959 400', email: 'informacio@gandia.org' },
  idioma2: { cod: 'VA', clave: 'va', sigla: "a l'OAC", nombre: 'valenciano' },
  kb: [
    {
      k: ['oac', 'oficina', 'atencion ciudadana', 'direccion', 'horario', 'hasta que hora', 'a que hora abren', 'abren', 'cierran', 'telefono', 'contacto', 'lunes', 'tarde', 'grau',
          'atencio ciutadana', 'horari', 'telefon', 'dilluns', 'vesprada'],
      es: { h: 'La <b>Oficina d\'Atenció a la Ciutadania (OAC)</b> abre de lunes a viernes de 8:30 a 14:30.',
            l: ['Los <b>lunes</b> también por la tarde, de 16:00 a 18:00.',
                'Teléfonos: el <b>010</b>, el 962 959 400 (Gandia) y el 962 959 498 (Grau).',
                'Correo para citas: citaprevia@gandia.org.'],
            f: 'El lunes es el único día con horario de tarde.' },
      va: { h: 'L\'<b>Oficina d\'Atenció a la Ciutadania (OAC)</b> obri de dilluns a divendres de 8:30 a 14:30.',
            l: ['Els <b>dilluns</b> també de vesprada, de 16:00 a 18:00.',
                'Telèfons: el <b>010</b>, el 962 959 400 (Gandia) i el 962 959 498 (Grau).',
                'Correu per a cites: citaprevia@gandia.org.'],
            f: 'El dilluns és l\'únic dia amb horari de vesprada.' },
      s: { t: 'Oficina d\'Atenció a la Ciutadania — gandia.es', u: 'https://gandia.es/atg/web_php/index.php?contenido=descripcion&id_boto=143&lang=10' },
    },
    {
      k: ['cita', 'cita previa', 'sin cita', 'pedir cita', 'prioritaria', 'reservar',
          'cita previa', 'sense cita', 'prioritaria', 'demanar cita'],
      es: { h: 'Se puede acudir a la OAC <b>en cualquier momento, sin cita previa</b>.',
            l: ['Si prefiere ser atendido a una hora concreta, existe la <b>cita previa prioritaria</b>.',
                'Se pide en el 010, en el 962 959 400 o en citaprevia@gandia.org.'],
            f: 'La cita es una comodidad, no un requisito.' },
      va: { h: 'Es pot acudir a l\'OAC <b>en qualsevol moment, sense cita prèvia</b>.',
            l: ['Si preferixes ser atés a una hora concreta, hi ha la <b>cita prèvia prioritària</b>.',
                'Es demana al 010, al 962 959 400 o a citaprevia@gandia.org.'],
            f: 'La cita és una comoditat, no un requisit.' },
      s: { t: 'Cita prèvia — Ajuntament de Gandia', u: 'https://www.gandia.es/atg/Web_php/index.php?contenido=subapartados_woden&id_boto=725&lang=10' },
    },
    {
      k: ['padron', 'empadronar', 'empadronarme', 'empadrono', 'me mudo', 'me empadrono', 'empadronamiento', 'certificado', 'volante', 'alta', 'baja', 'modificacion',
          'padro', 'empadronar-me', 'empadronament', 'certificat', 'volant'],
      es: { h: 'La OAC gestiona el <b>Padró d\'habitants</b> completo.',
            l: ['Obtención de certificados y volantes de empadronamiento.',
                'Altas, bajas y modificaciones en el padrón.',
                'También asistencia con registros, presentación de documentación dirigida a otras administraciones, certificados electrónicos e información catastral.'],
            f: 'Para todo esto se puede ir sin cita previa.' },
      va: { h: 'L\'OAC gestiona el <b>Padró d\'habitants</b> complet.',
            l: ['Obtenció de certificats i volants d\'empadronament.',
                'Altes, baixes i modificacions al padró.',
                'També assistència amb registres, presentació de documentació dirigida a altres administracions, certificats electrònics i informació cadastral.'],
            f: 'Per a tot això es pot anar sense cita prèvia.' },
      s: { t: 'Padró — Ajuntament de Gandia', u: 'https://www.gandia.es/atg/web_php/index.php?contenido=subapartados_woden&id_boto=14&lang=10' },
    },
    {
      k: ['certificado electronico', 'certificados y volantes', 'catastro', 'catastral', 'otras administraciones', 'registro',
          'certificat electronic', 'cadastral', 'registre'],
      es: { h: 'La OAC hace además de <b>oficina de asistencia en materia de registro</b>.',
            l: ['Obtención de certificados electrónicos.',
                'Información catastral.',
                'Presentación de documentación dirigida a otras administraciones públicas.'],
            f: 'Teléfonos: 010, 962 959 400 (Gandia) o 962 959 498 (Grau).' },
      va: { h: 'L\'OAC fa a més d\'<b>oficina d\'assistència en matèria de registre</b>.',
            l: ['Obtenció de certificats electrònics.',
                'Informació cadastral.',
                'Presentació de documentació dirigida a altres administracions públiques.'],
            f: 'Telèfons: 010, 962 959 400 (Gandia) o 962 959 498 (Grau).' },
      s: { t: 'Oficines d\'Assistència en matèria de registre — gandia.es', u: 'https://www.gandia.es/aytg/Web_php/index.php?contenido=subapartados_woden&id_boto=143&lang=10' },
    },
  ],
  sugerencias: [
    { lang: 'ES', t: '¿Hace falta cita previa?' },
    { lang: 'VA', t: 'Quin horari té l\'OAC els dilluns?' },
    { lang: 'ES', t: '¿Dónde está la oficina?' },
    { lang: 'ES', t: '¿Puedo presentar un escrito en el registro?' },
    { lang: 'ES', t: '¿Qué trámites de padrón puedo hacer?' },
  ],
},

];
